import { personById } from "./core/store.js";
import { escapeHtml, showToast, updateIsland } from "./core/ui.js";
import { sendToModel } from "./integrations/ai-client.js";
import { addMemoryEntry } from "./memory-engine.js";

let generating=false;

export function createAnonymousBoxRenderer({store,navigate}){
  return function render(container){
    const state=store.getState(),items=[...(state.anonymousQuestions||[])].sort((a,b)=>b.createdAt-a.createdAt),config={proactive:true,...(state.anonymousBoxConfig||{})};
    container.className="app-view anonymous-box-view";
    container.innerHTML=`<section class="anonymous-hero"><span>ASK ME ANYTHING</span><h2>匿名提问箱</h2><p>每封信都有自己的往来记录。身份始终隐藏，但口吻、记忆和关系会保持连续。</p><button class="anonymous-generate" data-generate ${generating?"disabled":""}>${generating?"正在收集来信…":"一键生成匿名来信"}</button></section><label class="anonymous-switch"><span><strong>允许主动匿名来信</strong><small>CHAR 与 NPC 会结合关系和近况偶尔投递</small></span><input class="switch" type="checkbox" data-proactive ${config.proactive?"checked":""}></label><section class="anonymous-list">${items.map(questionCard).join("")||'<div class="empty"><strong>信箱还是空的</strong><span>点一次生成，看看谁正在偷偷写信。</span></div>'}</section>`;
    container.querySelector("[data-generate]").onclick=()=>generateQuestions(store,()=>render(container),3);
    container.querySelector("[data-proactive]").onchange=e=>store.update(s=>s.anonymousBoxConfig={...(s.anonymousBoxConfig||{}),proactive:e.target.checked});
    container.querySelectorAll("[data-open-letter]").forEach(card=>card.onclick=e=>{if(e.target.closest("[data-delete-question]"))return;navigate("anonymous-letter",{id:card.dataset.openLetter})});
    container.querySelectorAll("[data-delete-question]").forEach(button=>button.onclick=e=>{e.stopPropagation();store.update(s=>s.anonymousQuestions=s.anonymousQuestions.filter(x=>x.id!==button.dataset.deleteQuestion));render(container)});
  }
}

export function createAnonymousLetterRenderer({store,navigate}){
  return function render(container,params={}){
    const state=store.getState(),item=state.anonymousQuestions.find(x=>x.id===params.id);if(!item)return navigate("anonymous-box");
    const thread=letterThread(item);container.className="app-view anonymous-letter-view";
    container.innerHTML=`<section class="letter-desk"><div class="letter-paper"><header><span>ANONYMOUS LETTER</span><time>${new Date(item.createdAt).toLocaleDateString("zh-CN")}</time></header><div class="letter-opening"><i>?</i><p>${escapeHtml(item.text)}</p></div><div class="letter-thread">${thread.map((x,index)=>letterMessage(x,index)).join("")}</div><footer><span>FROM SOMEONE</span><b>BB</b></footer></div></section><form class="letter-composer" data-letter-form><textarea name="reply" rows="3" maxlength="500" placeholder="写下回信……"></textarea><button ${item.sending?"disabled":""} aria-label="寄出回信">${item.sending?"···":"寄出"}</button></form>`;
    container.querySelector("[data-letter-form]").onsubmit=e=>{e.preventDefault();const text=e.currentTarget.elements.reply.value.trim();if(!text)return showToast("先写下回信");sendLetterReply(store,item.id,text,()=>render(container,params))};
    requestAnimationFrame(()=>{container.scrollTop=container.scrollHeight});
  }
}

export function setupAnonymousQuestions({store}){setInterval(async()=>{const state=store.getState(),config={proactive:true,...(state.anonymousBoxConfig||{})},now=Date.now();if(!config.lastGeneratedAt){store.update(s=>s.anonymousBoxConfig={...(s.anonymousBoxConfig||{}),lastGeneratedAt:now});return}if(document.hidden||!config.proactive||generating||now-Number(config.lastGeneratedAt)<2*60*60*1000)return;await generateQuestions(store,()=>{},1,true)},60000)}

async function generateQuestions(store,done,count=3,quiet=false){if(generating)return;generating=true;if(!quiet)updateIsland("正在收集匿名来信…",true);try{const state=store.getState(),model=activeModel(state),user=personById(state,state.currentUserId),people=state.people.filter(x=>x.type==="char"||x.type==="npc");if(!people.length)throw Error("请先创建 CHAR 或 NPC");const roster=people.map(x=>`${x.id}｜${x.name}｜${x.type}｜${x.personality||x.persona||x.note||""}`).join("\n"),recent=state.conversations.flatMap(c=>(state.messages[c.id]||[]).slice(-3).map(m=>`${c.personId}:${m.role}:${m.text||m.type}`)).slice(-16).join("\n"),prompt=`这是 USER ${user.name} 的匿名信箱。候选写信人：\n${roster}\n最近互动：\n${recent}\n请生成 ${count} 封匿名来信。可以认真深入了解 USER，也可以按人设试探、调侃或逗 USER；必须像真实的人临时提笔，不要机械复述资料。每封信明显符合写信者的人设和关系，但不能暴露身份。严格只返回 JSON：{"questions":[{"sourceId":"候选人的真实ID","text":"自然的匿名来信，120字以内","intent":"简短内心动机"}]}。`;const result=parseJson(await sendToModel(model,[{role:"user",text:prompt}],"")),valid=new Set(people.map(x=>x.id)),rows=(result?.questions||[]).filter(x=>valid.has(x.sourceId)&&x.text).slice(0,count);if(!rows.length)throw Error("没有生成有效来信");store.update(s=>{s.anonymousQuestions=s.anonymousQuestions||[];s.anonymousQuestions.unshift(...rows.map(x=>({id:crypto.randomUUID(),sourcePersonId:x.sourceId,text:String(x.text).slice(0,180),intent:String(x.intent||""),createdAt:Date.now(),status:"unanswered",thread:[],answer:"",reply:""})));s.anonymousBoxConfig={...(s.anonymousBoxConfig||{}),lastGeneratedAt:Date.now(),proactive:s.anonymousBoxConfig?.proactive!==false}});if(!quiet)showToast(`收到 ${rows.length} 封匿名来信`)}catch(error){if(!quiet)showToast(error.message)}finally{generating=false;updateIsland("bunny 正在陪你",false);done()}}

async function sendLetterReply(store,id,text,done){const snapshot=store.getState(),item=snapshot.anonymousQuestions.find(x=>x.id===id),source=personById(snapshot,item?.sourcePersonId),user=personById(snapshot,snapshot.currentUserId);if(!item||!source)return;const previous=letterThread(item),userLetter={id:crypto.randomUUID(),role:"user",text,createdAt:Date.now()};store.update(s=>{const target=s.anonymousQuestions.find(x=>x.id===id);target.thread=[...previous,userLetter];target.status="answered";target.sending=true});done();updateIsland("匿名写信人正在回信…",true);try{const history=[...previous,userLetter].map(x=>`${x.role==="user"?"USER":"匿名写信人"}：${x.text}`).join("\n"),prompt=`你是匿名写信人 ${source.name}，但绝不能在正文中泄露名字或直接承认身份。人物设定：${source.personality||source.persona||source.note||""}。USER 是 ${user.name}。最初的信：${item.text}\n书信往来：\n${history}\n请继续以高度符合人设、像真实存在的人一样回信。保持与前文的情绪和信息连续，可以深入交流、回避、害羞、逗弄或反问；不写舞台动作，不解释系统。只输出本次信件正文，100字以内。`,reply=String(await sendToModel(activeModel(snapshot),[{role:"user",text:prompt}],"")).trim();store.update(s=>{const target=s.anonymousQuestions.find(x=>x.id===id);target.thread.push({id:crypto.randomUUID(),role:"anonymous",text:reply,createdAt:Date.now()});target.sending=false;target.answer=target.answer||text;target.reply=reply;target.answeredAt=Date.now()});await addMemoryEntry(source.id,{kind:"memory",category:"relationship",layer:"retrieval",text:`匿名书信往来：${text} / ${reply}`,date:new Date().toISOString().slice(0,10),importance:3,emotionalWeight:3})}catch(error){store.update(s=>{const target=s.anonymousQuestions.find(x=>x.id===id);target.sending=false});showToast(`回信暂未送达：${error.message}`)}finally{updateIsland("bunny 正在陪你",false);done()}}

function letterThread(item){if(Array.isArray(item.thread)&&item.thread.length)return item.thread.map(x=>({...x}));const rows=[];if(item.answer)rows.push({id:`legacy-user-${item.id}`,role:"user",text:item.answer,createdAt:item.answeredAt||item.createdAt});if(item.reply)rows.push({id:`legacy-anon-${item.id}`,role:"anonymous",text:item.reply,createdAt:item.answeredAt||item.createdAt});return rows}
function questionCard(item){const count=letterThread(item).length;return`<article class="anonymous-card ${item.status}" data-open-letter="${item.id}" role="button" tabindex="0"><header><span class="anonymous-seal">?</span><div><strong>匿名来信</strong><small>${new Date(item.createdAt).toLocaleString("zh-CN")}</small></div><button data-delete-question="${item.id}" aria-label="删除">×</button></header><p>${escapeHtml(item.text)}</p><footer><span>${count?`${count} 封往来`:"等待你的回信"}</span><b>打开信件 ›</b></footer></article>`}
function letterMessage(item,index){return`<article class="letter-message ${item.role}"><span>${item.role==="user"?"YOUR LETTER":"ANONYMOUS REPLY"} · ${index+1}</span><p>${escapeHtml(item.text)}</p><time>${new Date(item.createdAt||Date.now()).toLocaleString("zh-CN",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"})}</time></article>`}
function activeModel(state){const model=state.modelProfiles.find(x=>x.id===state.activeModelProfileId);if(!model?.apiKey||!model.model)throw Error("请先在“模型与 API”中启用一个文本模型");return model}
function parseJson(text){try{const match=String(text||"").match(/\{[\s\S]*\}/);return match?JSON.parse(match[0]):null}catch{return null}}
