import { personById } from "./core/store.js";
import { escapeHtml, initialsAvatar, showToast, openSheet, closeSheet, updateIsland } from "./core/ui.js";
import { sendToModel } from "./integrations/ai-client.js";
import { addMemoryEntry } from "./memory-engine.js";

let generating=false;
export function createAnonymousBoxRenderer({store}){return function render(container){const state=store.getState(),items=[...(state.anonymousQuestions||[])].sort((a,b)=>b.createdAt-a.createdAt),config={proactive:true,...(state.anonymousBoxConfig||{})};container.className="app-view anonymous-box-view";container.innerHTML=`<section class="anonymous-hero"><span>ASK ME ANYTHING</span><h2>匿名提问箱</h2><p>问题可能来自 CHAR、NPC，或者某个只是想逗逗你的人。</p><button class="anonymous-generate" data-generate ${generating?"disabled":""}>${generating?"正在收集问题…":"一键生成匿名问题"}</button></section><label class="anonymous-switch"><span><strong>允许主动匿名提问</strong><small>网页打开期间，角色会结合关系和近况偶尔投递问题</small></span><input class="switch" type="checkbox" data-proactive ${config.proactive?"checked":""}></label><section class="anonymous-list">${items.map(x=>questionCard(x)).join("")||'<div class="empty"><strong>提问箱还是空的</strong><span>点一次生成，看看谁正在偷偷好奇。</span></div>'}</section>`;container.querySelector("[data-generate]").onclick=()=>generateQuestions(store,()=>render(container),3);container.querySelector("[data-proactive]").onchange=e=>store.update(s=>s.anonymousBoxConfig={...(s.anonymousBoxConfig||{}),proactive:e.target.checked});container.querySelectorAll("[data-answer]").forEach(button=>button.onclick=()=>answerQuestion(store,button.dataset.answer,()=>render(container)));container.querySelectorAll("[data-delete-question]").forEach(button=>button.onclick=()=>{store.update(s=>s.anonymousQuestions=s.anonymousQuestions.filter(x=>x.id!==button.dataset.deleteQuestion));render(container)})}}

export function setupAnonymousQuestions({store}){setInterval(async()=>{const state=store.getState(),config={proactive:true,...(state.anonymousBoxConfig||{})},now=Date.now();if(!config.lastGeneratedAt){store.update(s=>s.anonymousBoxConfig={...(s.anonymousBoxConfig||{}),lastGeneratedAt:now});return}if(document.hidden||!config.proactive||generating||now-Number(config.lastGeneratedAt)<2*60*60*1000)return;await generateQuestions(store,()=>{},1,true)},60000)}

async function generateQuestions(store,done,count=3,quiet=false){if(generating)return;generating=true;if(!quiet)updateIsland("正在收集匿名问题…",true);try{const state=store.getState(),model=activeModel(state),user=personById(state,state.currentUserId),people=state.people.filter(x=>x.type==="char"||x.type==="npc");if(!people.length)throw Error("请先创建 CHAR 或 NPC");const roster=people.map(x=>`${x.id}｜${x.name}｜${x.type}｜${x.personality||x.persona||x.note||""}`).join("\n"),recent=state.conversations.flatMap(c=>(state.messages[c.id]||[]).slice(-3).map(m=>`${c.personId}:${m.role}:${m.text||m.type}`)).slice(-16).join("\n"),prompt=`这是 USER ${user.name} 的匿名提问箱。候选提问者：\n${roster}\n最近互动：\n${recent}\n请生成 ${count} 个匿名问题。提问者可以认真深入了解 USER，也可以按自己的人设调侃、试探或逗 USER，但不能机械重复资料。每个问题必须明显符合真实提问者的人设和与 USER 的关系，界面不会公开身份。严格只返回 JSON：{"questions":[{"sourceId":"候选人的真实ID","text":"自然的匿名问题，80字以内","intent":"简短内心动机"}]}。`;const result=parseJson(await sendToModel(model,[{role:"user",text:prompt}],"")),valid=new Set(people.map(x=>x.id)),rows=(result?.questions||[]).filter(x=>valid.has(x.sourceId)&&x.text).slice(0,count);if(!rows.length)throw Error("没有生成有效问题");store.update(s=>{s.anonymousQuestions=s.anonymousQuestions||[];s.anonymousQuestions.unshift(...rows.map(x=>({id:crypto.randomUUID(),sourcePersonId:x.sourceId,text:String(x.text).slice(0,120),intent:String(x.intent||""),createdAt:Date.now(),status:"unanswered",answer:"",reply:""})));s.anonymousBoxConfig={...(s.anonymousBoxConfig||{}),lastGeneratedAt:Date.now(),proactive:s.anonymousBoxConfig?.proactive!==false}});if(!quiet)showToast(`收到 ${rows.length} 个匿名问题`)}catch(error){if(!quiet)showToast(error.message)}finally{generating=false;updateIsland("bunny 正在陪你",false);done()}}

function answerQuestion(store,id,done){const item=store.getState().anonymousQuestions.find(x=>x.id===id);if(!item)return;openSheet(`<div class="anonymous-answer-sheet"><div class="sheet-title"><div><small>ANONYMOUS QUESTION</small><h3>${escapeHtml(item.text)}</h3></div><button class="button ghost" data-sheet-close>取消</button></div><textarea rows="6" data-answer-text placeholder="认真回答，或者也逗回去…">${escapeHtml(item.answer||"")}</textarea><button class="button" data-send-answer>匿名回复</button></div>`,{onReady(sheet){sheet.querySelector("[data-send-answer]").onclick=async()=>{const answer=sheet.querySelector("[data-answer-text]").value.trim();if(!answer)return showToast("先写下你的回答");const state=store.getState(),source=personById(state,item.sourcePersonId),user=personById(state,state.currentUserId);closeSheet();updateIsland("匿名提问者正在看你的回答…",true);try{const prompt=`你是匿名提问者 ${source.name}，但绝不能在回复中暴露名字或直接承认身份。你的人设：${source.personality||source.persona||source.note||""}。你匿名问 USER：${item.text}\nUSER 回答：${answer}\n以符合人设的真人口吻给一句匿名反馈，40字以内；可以深入追问、害羞、调侃或装作不在意。禁止动作描写。只输出反馈正文。`,reply=await sendToModel(activeModel(state),[{role:"user",text:prompt}],"");store.update(s=>{const target=s.anonymousQuestions.find(x=>x.id===id);Object.assign(target,{answer,reply:String(reply).trim(),status:"answered",answeredAt:Date.now()})});await addMemoryEntry(source.id,{kind:"episodic",event:`在匿名提问箱中问了“${item.text}”，USER 回答“${answer}”`,text:`匿名提问互动：${item.text} / ${answer}`,date:new Date().toISOString().slice(0,10),emotionalWeight:3,isAnniversary:false});showToast("回答已送达") }catch(error){store.update(s=>{const target=s.anonymousQuestions.find(x=>x.id===id);Object.assign(target,{answer,status:"answered",answeredAt:Date.now()})});showToast(`回答已保存；匿名反馈暂未生成：${error.message}`)}finally{updateIsland("bunny 正在陪你",false);done()}}}})}

function questionCard(item){return`<article class="anonymous-card ${item.status}"><header><span class="anonymous-seal">?</span><div><strong>匿名提问</strong><small>${new Date(item.createdAt).toLocaleString("zh-CN")}</small></div><button data-delete-question="${item.id}" aria-label="删除">×</button></header><p>${escapeHtml(item.text)}</p>${item.answer?`<blockquote><span>你的回答</span>${escapeHtml(item.answer)}</blockquote>`:""}${item.reply?`<div class="anonymous-reply"><span>对方的匿名回应</span><p>${escapeHtml(item.reply)}</p></div>`:""}${item.status!=="answered"?`<button class="anonymous-answer" data-answer="${item.id}">回答这个问题</button>`:""}</article>`}
function activeModel(state){const model=state.modelProfiles.find(x=>x.id===state.activeModelProfileId);if(!model?.apiKey||!model.model)throw Error("请先在“模型与 API”中启用一个文本模型");return model}
function parseJson(text){try{const match=String(text||"").match(/\{[\s\S]*\}/);return match?JSON.parse(match[0]):null}catch{return null}}
