import { createStore } from "./core/store.js";
import { registerRoute, navigate } from "./core/router.js";
import { createDesktopRenderer } from "./apps/desktop-v2.js";
import { createChatRenderers } from "./apps/chat-v2.js";
import { createConversationV3Renderer } from "./chat-v3.js";
import { createWalletRenderer } from "./wallet-v2.js";
import { createCallRenderer, setupChatVoiceSettings, setupProactiveCalls } from "./call-v3.js";
import { createContactsRenderer, createCharacterEditorRenderer, createUserProfileRenderer, createAddFriendRenderer } from "./apps/contacts.js";
import { createFriendRequestsRenderer } from "./apps/friend-requests.js";
import { createPhoneSettingsRenderer, applyAppIdentity } from "./apps/phone-settings-v2.js";
import { createChatSettingsRenderer, applyChatAppearance } from "./apps/chat-settings-v2.js";
import { createDataSettingsRenderer } from "./apps/data-settings.js";
import { createWorldbookRenderer, createPresetsRenderer } from "./apps/prompt-library.js";
import { createApiSettingsRenderer } from "./apps/api-settings.js";
import { createPlaceholderRenderer, placeholderRoutes } from "./apps/placeholders.js";
import { createTogetherRenderer, createFocusRenderer, createWorldRenderer } from "./apps/companions.js";
import { createBridgeRenderer } from "./integrations/reality-bridge.js";
import { createMcpRenderer } from "./integrations/mcp-client.js";
import { registerBunnyTools } from "./webmcp.js";
import { showToast, setPhoneAppearance } from "./core/ui.js";
import { playLaunchAnimation } from "./splash.js";
import { registerPwa } from "./pwa.js";
import { setupIosRefinement } from "./ios-refinement.js";

const store = createStore();
playLaunchAnimation();
registerPwa();
const context = { store, navigate };
const chats = createChatRenderers(context);

registerRoute("desktop", createDesktopRenderer(context));
registerRoute("chat", chats.list);
registerRoute("conversation", createConversationV3Renderer(context));
registerRoute("call", createCallRenderer(context));
registerRoute("contacts", createContactsRenderer(context));
registerRoute("character-edit", createCharacterEditorRenderer(context));
registerRoute("user-profile", createUserProfileRenderer(context));
registerRoute("add-friend", createAddFriendRenderer(context));
registerRoute("friend-requests", createFriendRequestsRenderer(context));
registerRoute("phone-settings", createPhoneSettingsRenderer(context));
registerRoute("chat-settings", createChatSettingsRenderer(context));
registerRoute("api", createApiSettingsRenderer(context));
registerRoute("data-settings", createDataSettingsRenderer(context));
registerRoute("worldbook", createWorldbookRenderer(context));
registerRoute("presets", createPresetsRenderer(context));
registerRoute("moments", chats.moments);
registerRoute("chat-me", chats.me);
registerRoute("bridge", createBridgeRenderer(context));
registerRoute("mcp", createMcpRenderer(context));
registerRoute("together", createTogetherRenderer(context));
registerRoute("focus", createFocusRenderer(context));
registerRoute("world", createWorldRenderer(context));
placeholderRoutes.filter(route => !["worldbook","presets","wallet"].includes(route)).forEach(route => registerRoute(route, createPlaceholderRenderer(route)));
registerRoute("wallet", createWalletRenderer(context));
registerRoute("placeholder", container => { container.innerHTML = `<div class="empty"><strong>这个模块还在路上</strong><span>当前版本不会伪装成已经接入。</span></div>`; });

document.querySelector("#home-button").addEventListener("click", () => navigate("desktop"));
document.querySelector("#app-view").addEventListener("scroll", event => document.querySelector("#app-header").classList.toggle("scrolled", event.target.scrollTop > 8));

const initialHash = location.hash.slice(1);
setPhoneAppearance(store.getState().appearance);
applyAppIdentity(store.getState().appearance);
applyChatAppearance(store.getState().chatAppearance);
navigate(["chat", "contacts", "character-edit", "user-profile", "add-friend", "friend-requests", "phone-settings", "chat-settings", "api", "data-settings", "worldbook", "presets", "moments", "chat-me", "bridge", "mcp", "together", "focus", "world", ...placeholderRoutes].includes(initialHash) ? initialHash : "desktop");
setupIosRefinement(context);
setupChatVoiceSettings(context);
setupProactiveCalls(context);
if (registerBunnyTools(context)) showToast("已启用页面级 MCP 工具");
