import { conversationById, personById } from "./core/store.js";
import { escapeHtml, initialsAvatar, showToast, openSheet, closeSheet } from "./core/ui.js";
import { sendToModel } from "./integrations/ai-client.js";
import { startBrowserRecognition, speakText } from "./voice-client.js";
import { resolveTtsConfig } from "./tts-providers.js";
import { memoryProfile } from "./memory-engine.js";

const sessions=new Map();
export function createCallRenderer({store,navigate}){
  return function render(container,params={}){
    const state=store.getState(),conv=conversationById(state,params.id||"conv-jun");if(!conv)return navigate("chat");
    const person=personById(state,conv.personId),user=personById(state,state.currentUserId),profile=state.chatProfiles[person.id]||{},kind=params.mode==="video"?"视频":"语音",key=`${conv.id}:${params.mode||"voice"}:${params.direction||"outgoing"}`;
    let session=sessions.get(key);if(!session){session={status:params.direction==="incoming"?"incoming":"calling",lines:[],startedAt:Date.now(),connectedAt:0,direction:params.direction||"outgoing",ended:false};sessions.set(key,session);queueMicrotask(()=>begin(session,key,conv,person,user,profile,kind,container,params))}
    document.querySelector("#header-title").textContent=`${kind}通话`;document.querySelector("#header-kicker").textContent=person.name;
    const back=document.querySelector("#back-button");back.classList.remove("hidden");back.textContent="‹";back.onclick=()=>finish(session,key,conv,person,kind,params,navigate);
    const video=params.mode==="video",background=profile.videoBackground||profile.avatarUrl||person.avatarUrl||"",portrait=profile.userVideoPortrait||user.avatarUrl||"";
    container.className=`app-view call-screen ${video?"video-call":"voice-call"}`;
    container.innerHTML=`<section class="call-stage" ${video&&background?`style="--video-bg:url('${escapeHtml(background)}')"`:""}><div class="call-aurora"></div><div class="call-status"><span>${statusText(session,person)}</span><time data-call-time>${duration(session)}</time></div>${video?`${!background?`<div class="video-char-fallback">${initialsAvatar(person,profile)}<strong>${escapeHtml(person.name)}</strong></div>`:""}<div class="video-user-portrait">${portrait?`<img src="${escapeHtml(portrait)}" alt="USER 肖像">`:initialsAvatar(user,{avatarUrl:""})}</div>`:`<div class="call-portraits">${avatar(person,profile,"char")}<span class="call-heart">♥</span>${avatar(user,{avatarUrl:user.avatarUrl||""},"user")}</div>`}<div class="call-dialogue" data-call-dialogue>${dialogue(session,video)}</div><nav class="call-controls"><button class="call-control glass" data-voice-input>${micIcon()}<span>说话</span></button><button class="call-control hangup" data-hangup>${phoneIcon()}<span>挂断</span></button><button class="call-control glass" data-text-input>${textIcon()}<span>文字</span></button></nav></section>`;
    container.querySelector("[data-hangup]").onclick=()=>finish(session,key,conv,person,kind,params,navigate);
    container.querySelector("[data-voice-input]").onclick=()=>voiceInput(session,key,conv,person,user,profile,kind,container,params);
    container.querySelector("[data-text-input]").onclick=()=>textInput(session,key,conv,person,user,profile,kind,container,params);
    container.querySelectorAll("[data-call-line]").forEach(el=>bindLongPress(el,()=>favoriteLine(session,Number(el.dataset.callLine),conv,person)));
    if(session.status==="incoming"&&!session.incomingShown)incoming(session,key,conv,person,user,profile,kind,container,params);
    const timer=setInterval(()=>{const el=container.querySelector("[data-call-time]");if(!el||!document.body.contains(el))return clearInterval(timer);el.textContent=duration(session)},1000);
  }

  async function begin(session,key,conv,person,user,profile,kind,container,params){if(params.direction==="incoming")return;session.status="loading";rerender(container,params);try{const state=store.getState(),reply=await sendToModel(activeModel(state),[{role:"user",text:decisionPrompt(person,user,profile,kind,memoryProfile(state,person.id))}],""),result=parse(reply,{answer:"accept",opening:reply});if(result.answer==="reject"){session.status="rejected";session.error=result.reason||"对方现在不方便接听";rerender(container,params);setTimeout(()=>finish(session,key,conv,person,kind,params,navigate,"char"),1500);return}session.status="connected";session.connectedAt=Date.now();rerender(container,params);if(result.opening){const line=normalizeCallLine({role:"char",action:result.openingAction,text:result.opening,translation:result.translation});await streamLine(session,line,container,params,resolveTtsConfig(state,profile))}}catch(error){session.status="error";session.error=error.message;rerender(container,params)}}
  function incoming(session,key,conv,person,user,profile,kind,container,params){session.incomingShown=true;openSheet(`<div class="incoming-call-card">${initialsAvatar(person,profile)}<span>${escapeHtml(person.name)}</span><h3>邀请你进行${kind}通话</h3><div class="incoming-actions"><button class="decline" data-decline>${phoneIcon()}<span>拒绝</span></button><button class="accept" data-accept>${phoneIcon()}<span>接听</span></button></div></div>`,{onReady(sheet){sheet.querySelector("[data-decline]").onclick=()=>{closeSheet();finish(session,key,conv,person,kind,params,navigate,"user")};sheet.querySelector("[data-accept]").onclick=async()=>{closeSheet();session.status="connected";session.connectedAt=Date.now();rerender(container,params);const line=normalizeCallLine({role:"char",action:params.openingAction||"声音靠近听筒",text:params.opening||"喂，突然有点想听听你的声音。",translation:params.openingTranslation||""});await streamLine(session,line,container,params,resolveTtsConfig(store.getState(),profile))}}})}
  function textInput(session,key,conv,person,user,profile,kind,container,params){openSheet(`<div class="call-input-sheet"><div class="sheet-title"><h3>文字输入</h3></div><textarea rows="5" data-call-text placeholder="输入想对 ${escapeHtml(person.name)} 说的话…"></textarea><div class="row"><button class="button secondary" data-sheet-close>取消</button><button class="button" data-send-call-text>发送</button></div></div>`,{onReady(sheet){sheet.querySelector("[data-send-call-text]").onclick=()=>{const text=sheet.querySelector("[data-call-text]").value.trim();if(!text)return showToast("请输入内容");closeSheet();respond(session,key,conv,person,user,profile,kind,text,container,params)}}})}
  function voiceInput(session,key,conv,person,user,profile,kind,container,params){let live=null;openSheet(`<div class="call-input-sheet"><div class="sheet-title"><h3>语音转文字</h3><span class="pill">浏览器免 Key</span></div><textarea rows="5" data-stt-text placeholder="识别结果可手动修改，也可以直接输入"></textarea><div class="voice-sheet-actions"><button data-cancel-voice>取消</button><button class="voice-record" data-record>${micIcon()}</button><button data-confirm-voice>确认</button></div><small data-stt-state>点击中间话筒开始识别</small></div>`,{onReady(sheet){const text=sheet.querySelector("[data-stt-text]"),status=sheet.querySelector("[data-stt-state]"),record=sheet.querySelector("[data-record]");record.onclick=()=>{try{live=startBrowserRecognition({language:recognitionLanguage(profile.language),onText:v=>text.value=v,onState:v=>status.textContent=v==="listening"?"正在聆听…":"识别结束",onError:e=>status.textContent=`识别失败：${e}`});record.classList.add("active")}catch(error){status.textContent=error.message}};sheet.querySelector("[data-cancel-voice]").onclick=()=>{live?.abort();closeSheet()};sheet.querySelector("[data-confirm-voice]").onclick=()=>{const value=text.value.trim();if(!value)return showToast("没有可发送的内容");live?.stop();closeSheet();respond(session,key,conv,person,user,profile,kind,value,container,params)}}})}
  async function respond(session,key,conv,person,user,profile,kind,input,container,params){session.lines.push({role:"user",action:"",text:input,translation:""});session.status="loading";rerender(container,params);try{const state=store.getState(),mem=memoryProfile(state,person.id),history=session.lines.slice(-10).map(x=>`${x.role}:${x.action?`（${x.action}）`:""}${x.text}`).join("\n"),foreign=profile.translationEnabled?"角色台词可以使用设定语言；只要台词不是简体中文，translation 必须给出准确简体中文翻译。":"translation 留空。",prompt=`你是 ${person.name}，人物设定：${person.personality||person.persona||person.note||""}。USER 是 ${user.name}。核心共同记忆：${mem.coreMemory}。当前关系与内在状态：${JSON.stringify(mem.dynamicState)}。你们正在进行${kind}通话。最近通话：\n${history}\n${foreign}\n必须非常贴合角色年龄、性格、关系、口癖和表达习惯，像真实存在的人通话；自然代入记忆，不要复述档案。action 必须是简短中文动作/声音状态，不含括号；text 只能是实际说出口的台词，外语角色可用外文；translation 只翻译外文台词，不翻译动作。你可根据人设与情境自主挂断。严格只返回 JSON：{"action":"中文动作描述","text":"实际说出口的原文","translation":"外文台词的中文翻译或空字符串","hangup":true或false}。字段不得遗漏，不得在 text 中混入动作。`;const result=parse(await sendToModel(activeModel(state),[{role:"user",text:prompt}],""),null);if(!result?.text)throw Error("通话模型没有返回有效格式");session.status="connected";await streamLine(session,normalizeCallLine({role:"char",...result}),container,params,resolveTtsConfig(state,profile));if(result.hangup)setTimeout(()=>finish(session,key,conv,person,kind,params,navigate,"char"),900)}catch(error){session.status="connected";session.error=error.message;rerender(container,params)}}
  async function streamLine(session,line,container,params,tts){const target={...line,text:"",translation:""};session.lines.push(target);for(const char of [...line.text]){target.text+=char;paintDialogue(container,session,params.mode==="video");await delay(28)}if(line.translation){await delay(180);for(const char of [...line.translation]){target.translation+=char;paintDialogue(container,session,params.mode==="video");await delay(18)}}rerender(container,params);speakText(tts,line.text,{tone:line.tone||""}).catch(error=>showToast(`语音朗读失败：${error.message}`))}
  function favoriteLine(session,index,conv,person){const line=session.lines[index];if(!line)return;store.update(s=>{s.favorites=s.favorites||[];s.favorites.unshift({id:crypto.randomUUID(),messageId:`call-${session.startedAt}-${index}`,conversationId:conv.id,personId:person.id,createdAt:Date.now(),role:line.role,type:"text",text:line.text,translation:line.translation||"",source:"call"})});showToast("通话片段已收藏")}
  function finish(session,key,conv,person,kind,params,navigate,endedBy="user"){if(session.ended)return;session.ended=true;const seconds=session.connectedAt?Math.max(1,Math.floor((Date.now()-session.connectedAt)/1000)):0,recordId=crypto.randomUUID(),time=timeNow(),role=session.direction==="incoming"?"char":"user",type=kind==="视频"?"video-call":"voice-call";store.update(s=>{s.callRecords=s.callRecords||[];s.callRecords.unshift({id:recordId,conversationId:conv.id,personId:person.id,kind,direction:session.direction,startedAt:session.startedAt,connectedAt:session.connectedAt,endedAt:Date.now(),endedBy,duration:seconds,lines:session.lines.map(x=>({...x}))});const list=s.messages[conv.id]||(s.messages[conv.id]=[]);list.push({id:crypto.randomUUID(),role,type,text:`${kind}通话 ${formatDuration(seconds)}`,duration:seconds,callRecordId:recordId,time});const target=s.conversations.find(x=>x.id===conv.id);if(target){target.preview=`[${kind}通话]`;target.time=time}});sessions.delete(key);window.speechSynthesis?.cancel?.();navigate("conversation",{id:conv.id})}
  function rerender(container,params){createCallRenderer({store,navigate})(container,params)}
}

export function setupChatVoiceSettings({store,navigate}){const observer=new MutationObserver(()=>{if(document.querySelector("#app-screen")?.dataset.app!=="chat-settings")return;const form=document.querySelector("#app-view [data-form]");if(!form||form.querySelector("[data-call-settings-addon]"))return;const personId=history.state?.params?.personId||"char-jun",profile=store.getState().chatProfiles[personId]||{},submit=form.querySelector('button[type="submit"]');submit?.insertAdjacentHTML("beforebegin",`<section class="card stack" data-call-settings-addon><div class="section-title"><h3>主动通话</h3><span>当前 CHAR</span></div><label class="setting-row"><div><span class="label">允许 CHAR 主动打电话</span><small>依据人设、日程与最近聊天判断</small></div><input class="switch" type="checkbox" data-proactive-call ${profile.proactiveCall?"checked":""}></label><button type="button" class="button secondary" data-test-incoming>测试来电界面</button></section>`);form.querySelector("[data-proactive-call]").onchange=e=>store.update(s=>s.chatProfiles[personId].proactiveCall=e.target.checked);form.querySelector("[data-test-incoming]").onclick=()=>{const conv=store.getState().conversations.find(x=>x.personId===personId);if(conv)navigate("call",{id:conv.id,mode:"voice",direction:"incoming"})}});observer.observe(document.querySelector("#app-screen"),{childList:true,subtree:true})}
export function setupProactiveCalls({store,navigate}){let busy=false;setInterval(async()=>{const state=store.getState();if(busy||document.hidden||state.callRuntime?.active)return;const now=Date.now();if(now-Number(state.callRuntime?.lastCallCheck||0)<15*60*1000)return;store.update(s=>s.callRuntime={...(s.callRuntime||{}),lastCallCheck:now});busy=true;try{for(const [personId,p] of Object.entries(state.chatProfiles)){if(!p.proactiveCall||Math.random()>.12)continue;const conv=state.conversations.find(x=>x.personId===personId),person=personById(state,personId),user=personById(state,state.currentUserId);if(!conv||!person)continue;const recent=(state.messages[conv.id]||[]).slice(-6).map(x=>`${x.role}:${x.text||x.type}`).join("\n"),prompt=`你是${person.name}，人物设定：${person.personality||person.persona||person.note||""}。判断现在是否会主动给${user.name}打语音电话。当前时间：${new Date().toLocaleString("zh-CN")}；安静时段：${p.quietHours||"无"}；最近聊天：\n${recent}\n严格只返回 JSON：{"call":true或false,"opening":"接通后的自然开场白","reason":"原因"}。`;try{const result=parse(await sendToModel(activeModel(state),[{role:"user",text:prompt}],""),null);if(result?.call)navigate("call",{id:conv.id,mode:"voice",direction:"incoming",opening:result.opening||"突然有点想听听你的声音。"})}catch{}break}}finally{busy=false}},60000)}
function decisionPrompt(person,user,profile,kind,memory){return`你是${person.name}，人物设定：${person.personality||person.persona||person.note||""}。核心共同记忆：${memory.coreMemory}。当前关系与内在状态：${JSON.stringify(memory.dynamicState)}。${user.name} 正在发起${kind}通话。当前时间 ${new Date().toLocaleString("zh-CN")}，安静时段 ${profile.quietHours||"无"}。必须高度服从人物设定，以真人方式自然代入记忆；严格按人设判断是否接听。openingAction 是不带括号的简短中文动作/声音状态；opening 是实际说出口的台词，可按角色语言使用外文；外文时 translation 必须是中文翻译。只返回 JSON：{"answer":"accept或reject","reason":"拒接原因","openingAction":"中文动作","opening":"接通原文","translation":"中文翻译或空"}。字段不得遗漏。`}
function paintDialogue(container,session,video){const target=container.querySelector("[data-call-dialogue]");if(target){target.innerHTML=dialogue(session,video);target.scrollTop=target.scrollHeight}}
function dialogue(session,video){if(session.status==="loading")return'<div class="call-loading"><i></i><i></i><i></i></div>';if(session.error)return`<p class="call-error">${escapeHtml(session.error)}</p>`;if(!session.lines.length)return'<p class="call-wait">等待接通…</p>';return session.lines.slice(-8).map((x,i)=>`<article class="call-line ${x.role} ${video?"bubble":""}" data-call-line="${Math.max(0,session.lines.length-8+i)}"><p>${x.action?`<em>（${escapeHtml(x.action)}）</em>`:""}${escapeHtml(x.text)}</p>${x.translation?`<strong>${escapeHtml(x.translation)}</strong>`:""}</article>`).join("")}
function normalizeCallLine(value={}){let text=String(value.text||""),action=String(value.action||"").replace(/[（）()]/g,"").trim(),match=text.match(/[（(]([^）)]+)[）)]/);if(match&&!action)action=match[1].trim();text=text.replace(/[（(][^）)]*[）)]/g,"").trim();return{role:value.role||"char",action,text,translation:String(value.translation||"").replace(/[（(][^）)]*[）)]/g,"").trim(),tone:value.tone||""}}
function activeModel(state){const model=state.modelProfiles.find(x=>x.id===state.activeModelProfileId);if(!model?.apiKey||!model.model)throw Error("请先在“模型与 API”启用一个可用模型预设");return model}
function parse(text,fallback){try{const match=String(text||"").match(/\{[\s\S]*\}/);return match?JSON.parse(match[0]):fallback}catch{return fallback}}
function avatar(person,profile,kind){return`<div class="call-avatar ${kind}">${initialsAvatar(person,profile)}<span>${escapeHtml(person.name)}</span></div>`}
function statusText(session,person){return({incoming:"来电",calling:"正在呼叫…",loading:"等待 AI 响应…",connected:`正在与 ${person.name} 通话`,rejected:"对方暂时无法接听",error:"连接失败"})[session.status]||"通话"}
function duration(session){return session.connectedAt?formatDuration((Date.now()-session.connectedAt)/1000):""}
function formatDuration(value){const total=Math.max(0,Math.floor(Number(value)||0));return`${String(Math.floor(total/60)).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`}
function recognitionLanguage(value){return({"粤语":"yue-Hant-HK",English:"en-US","日本語":"ja-JP",Français:"fr-FR","한국어":"ko-KR",Deutsch:"de-DE",Español:"es-ES"})[value]||"zh-CN"}
function bindLongPress(el,fn){let timer;el.onpointerdown=()=>timer=setTimeout(fn,480);el.onpointerup=el.onpointercancel=()=>clearTimeout(timer)}
function delay(ms){return new Promise(r=>setTimeout(r,ms))}
function timeNow(){return new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit",hour12:false})}
function micIcon(){return'<svg viewBox="0 0 24 24"><rect x="9" y="3" width="6" height="11" rx="3"/><path d="M6 11a6 6 0 0 0 12 0M12 17v4m-4 0h8"/></svg>'}
function phoneIcon(){return'<svg viewBox="0 0 24 24"><path d="M5 15c4-3 10-3 14 0l-2 4-4-2v-2h-2v2l-4 2-2-4Z"/></svg>'}
function textIcon(){return'<svg viewBox="0 0 24 24"><path d="M4 5h16v12H9l-5 4V5Z"/><path d="M8 9h8m-8 4h5"/></svg>'}
