import { sendToModel } from './integrations/ai-client.js';
import { escapeHtml, showToast } from './core/ui.js';
import { addMemoryEntry } from './memory-engine.js';
import { ensureDailySchedule, scheduleClock } from './schedule-engine.js';
import { ensureWorldEngine, entityWorld, knownWorldEvents, relationEdge } from './world-engine.js';

const running=new Set();
export function diaryDay(state,personId,now=new Date()) {const clock=scheduleClock(state,personId,now);return clock.minute>=21*60?clock.day:scheduleClock(state,personId,new Date(now.getTime()-24*3600_000)).day}
export function diaryUnlocked(state,personId,accountId=state.currentUserId) {return relationEdge(state,personId,accountId,entityWorld(state,personId)).affinity>=48 || Number(state.memoryProfiles?.[personId]?.dynamicState?.charImpressionOfUser?.affectionLevel||0)>=55}

export async function writeCharacterDiary(store,personId,accountId=store.getState().currentUserId,now=new Date()) {
  const state=ensureWorldEngine(store.getState()),person=state.people.find(row=>row.id===personId),conv=state.conversations.find(row=>row.personId===personId&&row.userAccountId===accountId),model=state.modelProfiles.find(row=>row.id===state.activeModelProfileId);
  if(!person||person.type!=='char'||!conv)throw Error('这位角色还没有与你建立聊天');
  if(!model?.apiKey||!model?.model)throw Error('先在「模型与 API」配置文本模型');
  const date=diaryDay(state,personId,now),worldId=entityWorld(state,personId),key=`${worldId}:${accountId}:${personId}:${date}`;
  if(state.diaryEntries.some(row=>row.key===key))return state.diaryEntries.find(row=>row.key===key);
  if(running.has(key))return null;running.add(key);
  try {const diaryTime=new Date(`${date}T12:00:00Z`),schedule=ensureDailySchedule(store,personId,diaryTime),events=knownWorldEvents(store.getState(),personId,worldId,18).filter(row=>scheduleClock(state,personId,new Date(row.occurredAt)).day===date).map(row=>row.payload.summary||row.payload.text).filter(Boolean),messages=(state.messages[conv.id]||[]).filter(row=>scheduleClock(state,personId,new Date(row.createdAt||0)).day===date&&!row.recalled).slice(-18).map(row=>({speaker:row.role==='user'?'USER':person.name,text:row.text||row.description||''}));
    const context={person:{name:person.name,personality:person.personality||person.persona||'',occupation:person.occupation||'',note:person.note||''},date,schedule:schedule?.blocks.map(row=>({time:`${row.start}-${row.end}`,title:row.title,mood:row.mood})),events,messages};
    const system='你为一位虚构人物写当天睡前的私人日记。用第一人称，标题不超过 18 字，正文 120—280 字。只写已给出的事实以及人物对事实的主观感受：今天没发生的事不能写成发生过。记住 USER 的一句具体话、没回完的消息、日程里的小事或与朋友的细节；可以嘴硬、跑题、嫌自己多心，也可以整天平淡。语言贴近人物，句长有变化，不写“今日总结”“成长”“珍惜眼前人”等模板结尾，不给读者讲道理。对 USER 的看法可与嘴上说的不同，但不要凭空升级亲密关系。只返回 JSON：{"title":"标题","body":"日记"}。';
    const raw=await sendToModel(model,[{role:'user',text:JSON.stringify(context)}],system),data=JSON.parse(String(raw).match(/\{[\s\S]*\}/)?.[0]||'{}');if(typeof data.title!=='string'||typeof data.body!=='string'||data.body.trim().length<30)throw Error('日记内容格式不完整');
    const row={id:crypto.randomUUID(),key,worldId,accountId,personId,date,title:data.title.trim().slice(0,24),body:data.body.trim().slice(0,900),createdAt:Date.now(),sourceMessageIds:(state.messages[conv.id]||[]).slice(-18).map(item=>item.id)};
    store.update(s=>{ensureWorldEngine(s);if(!s.diaryEntries.some(item=>item.key===key))s.diaryEntries.unshift(row)});
    await addMemoryEntry(`${worldId}::${personId}::${accountId}`,{kind:'episodic',category:'self_awareness',layer:'retrieval',text:`${date} 日记：${row.body}`,importance:3,confidence:.8,visibility:'self',sourceIds:row.sourceMessageIds,date,source:'diary'});
    return row;
  } finally {running.delete(key)}
}

export function setupDiaryAutomation({store}) {const check=async()=>{if(document.hidden)return;const state=store.getState();if(!state.modelProfiles.some(row=>row.id===state.activeModelProfileId&&row.apiKey&&row.model))return;for(const conv of state.conversations.filter(row=>row.userAccountId===state.currentUserId)){const person=state.people.find(row=>row.id===conv.personId);if(person?.type!=='char')continue;const date=diaryDay(state,person.id),key=`${entityWorld(state,person.id)}:${state.currentUserId}:${person.id}:${date}`;if(!(state.diaryEntries||[]).some(row=>row.key===key))await writeCharacterDiary(store,person.id).catch(()=>{})}};setTimeout(check,9000);setInterval(check,10*60_000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)void check()})}

export function createDiaryRenderer({store,navigate}) {return function render(container,params={}){const state=ensureWorldEngine(store.getState()),person=state.people.find(row=>row.id===(params.personId||state.people.find(item=>item.type==='char')?.id)),accountId=state.currentUserId;if(!person)return navigate('contacts');const unlocked=diaryUnlocked(state,person.id,accountId),rows=state.diaryEntries.filter(row=>row.personId===person.id&&row.accountId===accountId&&row.worldId===entityWorld(state,person.id));container.className='app-view character-diary-view';container.innerHTML=`<section class="diary-hero"><span>PRIVATE PAGES</span><h2>${escapeHtml(person.name)} 的日记</h2><p>${unlocked?'这些是他从未发出的文字。':'关系更亲近后，日记才会慢慢打开。'}</p><button type="button" data-diary-write>看看最近有没有新的一页</button></section><div class="diary-list">${rows.map(row=>`<button type="button" class="diary-card ${unlocked?'':'locked'}" data-diary-id="${escapeHtml(row.id)}"><small>${escapeHtml(row.date)}</small><strong>${unlocked?escapeHtml(row.title):'未解锁的一页'}</strong><span>${unlocked?escapeHtml(row.body.slice(0,48))+'…':'这页暂时只属于他自己。'}</span></button>`).join('')||'<div class="empty">这里还没有日记。每天夜里，CHAR 会整理当天发生的事。</div>'}</div>`;container.querySelector('[data-diary-write]').onclick=async()=>{const button=container.querySelector('[data-diary-write]');button.disabled=true;button.textContent='正在等他落笔…';try{const row=await writeCharacterDiary(store,person.id,accountId);showToast(row?'新的一页已写好':'正在写这一页');render(container,params)}catch(error){showToast(error.message);button.disabled=false;button.textContent='再试一次'}};container.querySelectorAll('[data-diary-id]').forEach(button=>button.onclick=()=>{if(!unlocked)return showToast('继续相处，等彼此更熟悉后再读');const row=rows.find(item=>item.id===button.dataset.diaryId);if(!row)return;container.querySelector('.diary-list').innerHTML=`<article class="diary-page"><button type="button" data-diary-back>‹ 返回目录</button><small>${escapeHtml(row.date)}</small><h3>${escapeHtml(row.title)}</h3><p>${escapeHtml(row.body)}</p></article>`;container.querySelector('[data-diary-back]').onclick=()=>render(container,params)})};}
