import {openSheet,closeSheet,escapeHtml as esc,showToast} from './core/ui.js';
export const chatSkins=[['imessage','iMessage'],['wechat','微信'],['kakaotalk','KakaoTalk'],['line','LINE'],['cloud','Bunny Cloud']];
export const normalizeSkin=value=>value==='pop'?'wechat':chatSkins.some(([id])=>id===value)||value==='custom'?value:'cloud';
// A CSSOM parser scopes custom rules to their own surface. Bubble CSS is appended last.
export function scopedCss(source,scope){if(!source)return '';let sheet;try{sheet=new CSSStyleSheet();sheet.replaceSync(String(source||'').replace(/\.bubble(?![\w-])/g,'.bubble-v3').replace(/\.chat-layout(?![\w-])/g,'.chat-layout-v3').replace(/\.chat-stream(?![\w-])/g,'.chat-stream-v3').replace(/\.chat-person(?![\w-])/g,'.chat-contact-bar'));}catch{return ''}
 const walk=rules=>[...rules].map(rule=>{if(rule.type===1){const selectors=`${scope} :is(${rule.selectorText})`;const body=[...rule.style].map(p=>`${p}:${rule.style.getPropertyValue(p)}!important`).join(';');return `${selectors}{${body}}`}if(rule.cssRules&&rule.conditionText)return `${rule.cssText.slice(0,rule.cssText.indexOf('{'))}{${walk(rule.cssRules)}}`;return ''}).join('\n');return walk(sheet.cssRules)}
function putStyle(id,css){let el=document.getElementById(id);if(!el){el=document.createElement('style');el.id=id;document.head.append(el)}el.textContent=css}
export function applyConversationSkin(a){const skin=normalizeSkin(a.bubblePreset);let css='';const scale=Math.max(.75,Math.min(1.4,Number(a.bubbleScale)||1));css+=`#phone-root #app-view .chat-layout-v3{--bubble-scale:${scale}}`;const size=Math.max(10,Math.min(26,Number(a.fontSize)||14));css+=`#phone-root #app-view .chat-layout-v3 .bubble-v3{font-size:${size}px!important}`;
 if(a.bubbleColor&&a.bubbleColor!=='#111'&&a.bubbleColor!=='#111111')css+=`#phone-root #app-view .chat-layout-v3 .message.user{--skin-bubble:${a.bubbleColor}}`;
 if(/^https?:\/\//i.test(a.fontUrl||''))css+=`@font-face{font-family:BunnyConversation;src:url(${JSON.stringify(a.fontUrl)});font-display:swap}#phone-root #app-view .chat-layout-v3{font-family:BunnyConversation,sans-serif!important}`;
 css+=scopedCss(a.interfaceCss,'#phone-root .screen[data-app=conversation] #app-view')+'\n'+scopedCss(a.bubbleCss,'#phone-root#phone-root .screen[data-app=conversation] #app-view');
 // Repeating an ID increases specificity without requiring nested elements.
 css=css.replaceAll('#phone-root #phone-root','#phone-root#phone-root');putStyle('bunny-conversation-user-css',css);return skin;
}
export function applyListSkin(container,state){const a=state.chatListAppearance||{};container.dataset.listSkin=normalizeSkin(a.skin||'cloud');putStyle('bunny-list-user-css',scopedCss(a.css,'#phone-root #app-view[data-list-skin]'))}
export function bindListSkinPicker(container,store,render){const open=()=>openListSkinPicker(store,render);const logo=container.querySelector('[data-list-style]');if(logo)logo.onclick=open;container.querySelectorAll('[data-chat-tab="chat"],[data-list-style]').forEach(button=>{let timer=0,x=0,y=0,suppress=0;button.addEventListener('pointerdown',e=>{x=e.clientX;y=e.clientY;timer=setTimeout(()=>{suppress=Date.now()+1000;open()},480)});button.addEventListener('pointermove',e=>{if(Math.hypot(e.clientX-x,e.clientY-y)>9)clearTimeout(timer)});for(const event of ['pointerup','pointercancel','pointerleave'])button.addEventListener(event,()=>clearTimeout(timer));button.addEventListener('click',e=>{if(Date.now()<suppress){e.preventDefault();e.stopImmediatePropagation()}},true);button.oncontextmenu=e=>{e.preventDefault();open()}})}
function openListSkinPicker(store,render){const current=store.getState().chatListAppearance||{skin:'cloud',css:''};let selected=normalizeSkin(current.skin);openSheet(`<form class="list-skin-editor"><div class="sheet-title"><h3>聊天列表外观</h3><button type="button" class="button ghost" data-sheet-close>取消</button></div><div class="list-skin-options">${chatSkins.map(([id,name])=>`<button type="button" data-list-choice="${id}" aria-pressed="${id===selected}" class="list-skin-preview preview-${id}"><div class="skin-mini-head"><i></i><b>•••</b></div>${[1,2,3].map(()=>'<div class="skin-mini-row"><i></i><span><b></b><em></em></span><small></small></div>').join('')}<strong>${name}</strong></button>`).join('')}</div><label class="field"><span>自定义列表 CSS</span><textarea name="css" rows="7" spellcheck="false" placeholder=".conversation { border-radius: 20px; }\n.chat-group-chip { font-size: 12px; }">${esc(current.css||'')}</textarea></label><small>仅作用于聊天列表。长按底部聊天图标可再次打开。</small><div class="sheet-split-actions"><button type="button" class="button secondary" data-reset-css>清除代码</button><button class="button">保存外观</button></div></form>`,{onReady(sheet){sheet.querySelectorAll('[data-list-choice]').forEach(b=>b.onclick=()=>{selected=b.dataset.listChoice;sheet.querySelectorAll('[data-list-choice]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});sheet.querySelector('[data-reset-css]').onclick=()=>sheet.querySelector('textarea').value='';sheet.querySelector('form').onsubmit=e=>{e.preventDefault();store.update(s=>s.chatListAppearance={skin:selected,css:e.target.elements.css.value});closeSheet();render();showToast('聊天列表外观已保存')}}})}
