import { bindPhotoEditor } from "./photo-editor.js";
import { alignBubbleShapes } from "./bubble-shape.js";
import { generateInnerVoice, savedInnerVoices, innerVoiceActivityDue } from './inner-voice.js';
import { worldContextPrompt } from "./world-context.js";
import { applyConversationSkin } from "./chat-skins.js";
import { conversationById, personById } from "./core/store.js";
import { escapeHtml, initialsAvatar, showToast, updateIsland, openSheet, closeSheet } from "./core/ui.js";
import { sendToModel } from "./integrations/ai-client.js";
import { walletDebit, walletCredit, ensureWallet, insufficientSheet } from "./wallet-v2.js";
import { ensureTtsState, resolveTtsConfig, synthesizeSpeech } from "./tts-providers.js";
import { buildInternalChatPrompt, parseChatResponse } from "./chat-protocol.js";
import { goBack } from "./core/router.js";
import { recordAudio, startBrowserRecognition, prepareCallAudio } from "./voice-client.js";
import { saveMediaBlob } from "./media-store.js";
import { retrieveMemoryContext, scheduleMemoryMaintenance, savePromptDebug } from "./memory-engine.js";
import { ensureAccountState, accountContext } from "./account-system.js";
import { generateImage } from "./image-client.js";
import { ensureTimeProfile, buildTimeContext, timeSummary, localDateValue, localTimeValue } from "./time-context.js";
import { compileWorldbook, compilePreset } from "./apps/prompt-library.js";
import { currentSchedule, nextReplyAt, ensureDailySchedule, enrichDailySchedule, publicScheduleStatus, recordScheduleCommitment, schedulePrompt } from './schedule-engine.js';
import { appendWorldEvent, changeRelationship, entityWorld, knownWorldEvents } from './world-engine.js';

const DEFAULT_REACTIONS = ["❤️", "👍", "👎", "😂", "‼️", "❓"];
const EMOJI_GROUPS = {
  "新表情": ["🫩","🫆","🫜","🫟","🪉","🪏","🫧","🪷","🪻","🪽","🪼","🫎","🫏","🐦‍🔥","🍋‍🟩","🍄‍🟫","⛓️‍💥","🙂‍↔️","🙂‍↕️","🩷","🩵","🩶"],
  "常用": ["😀","😃","😄","😁","😆","🥹","😂","🤣","😊","🥰","😍","😘","😋","😎","🤩","🥳","🙂","🙃","🥲","🥺","😭","😤","😡","🤯","😳","🥶","🫠"],
  "手势": ["👍","👎","👌","✌️","🤞","🫶","👏","🙌","🙏","🤝","💪","👀","💅","👉","👈","☝️","✋","🤚","🖐️","👋"],
  "爱心": ["❤️","🩷","🧡","💛","💚","🩵","💙","💜","🖤","🩶","🤍","🤎","💔","❤️‍🔥","❤️‍🩹","💕","💞","💓","💗","💖","💘","💝"],
  "动物": ["🐰","🐱","🐶","🐻","🐼","🐨","🦊","🐯","🦁","🐸","🐵","🐧","🐦","🦋","🐝","🐬","🐳","🦭","🦦","🦔"],
  "食物": ["🍎","🍓","🍒","🍑","🍋","🥐","🍞","🍰","🧁","🍫","🍬","🍭","☕️","🧋","🍵","🍺","🍷","🍜","🍣","🍙"],
  "符号": ["✨","⭐️","🌙","☀️","☁️","🌧️","🔥","💫","🎀","🎵","🎧","📍","💌","💬","✅","❌","⭕️","‼️","⁉️","❓"]
};
const TYPE_META = {
  text:["文字","Aa"], image:["图片","▧"], transfer:["转账","¥"], redpacket:["红包","礼"],
  location:["位置","⌖"], voice:["语音","◖"], sticker:["表情包","☺"], file:["文件","□"], "text-image":["图片","文"], "voice-call":["语音通话","☎"], "video-call":["视频通话","▣"]
};

export function createConversationV3Renderer({ store, navigate }) {
  const ui = { conversationId:"", quoteId: "", selectMode: false, selected: new Set(), attachmentsOpen:false, sending:false, echoNext:false, voiceGenerating:false, error:"" };

  function conversation(container, params = {}) {
    const state = store.getState();
    const conv = conversationById(state, params.id || "conv-jun");
    if (!conv || (conv.userAccountId && conv.userAccountId !== state.currentUserId)) return navigate("chat");
    if(conv.hiddenFromList)store.update(s=>{const row=conversationById(s,conv.id);if(row)row.hiddenFromList=false});
    if(ui.conversationId!==conv.id){ui.conversationId=conv.id;ui.quoteId="";ui.selectMode=false;ui.selected.clear();ui.attachmentsOpen=false;ui.echoNext=false}
    const person = personById(state, conv.personId);
    const user = personById(state, state.currentUserId);
    const profile = ensureTimeProfile(state.chatProfiles[person.id]||(state.chatProfiles[person.id]={}));
    const newThought=savedInnerVoices(state,conv).find(row=>row.activity&&!row.seenAt);
    const appearance = state.chatAppearance;
    const skin = applyConversationSkin(appearance);
    ensureDailySchedule(store,person.id);void enrichDailySchedule(store,person.id);
    if(conv.unread||state.messages[conv.id]?.some(x=>x.role==="char"&&!x.readAt))store.update(s=>{const target=conversationById(s,conv.id);if(target)target.unread=0;if(profile.readReceipts!==false)for(const message of s.messages[conv.id]||[])if(message.role==="char"&&!message.readAt)message.readAt=Date.now()});
    configureHeader();
    const messages = state.messages[conv.id] || [];
    const quoted = messages.find(message => message.id === ui.quoteId);
    container.className = `app-view conversation-v3 ${ui.selectMode ? "select-mode" : ""}`;
    container.innerHTML = `<section class="chat-layout-v3" data-chat-skin="${skin}" style="${backgroundStyle(appearance.background,appearance.backgroundOpacity)}">
      <header class="chat-contact-bar">
        <button class="chat-contact-avatar" data-profile-card aria-label="查看 ${escapeHtml(person.name)} 的资料">${initialsAvatar(person, profile)}</button>${newThought?'<button type="button" class="inner-voice-alert" data-voice-activity aria-label="查看新的心声">•••</button>':''}
        <div><strong>${escapeHtml(profile.remark || person.name)}</strong><span>${escapeHtml(publicScheduleStatus(store,person.id))}</span></div>
        <div class="chat-contact-actions"><button class="chat-time ${profile.timeAwarenessEnabled!==false?"active":"manual"}" data-time-awareness aria-label="时间感知：${escapeHtml(timeSummary(profile))}" title="${escapeHtml(timeSummary(profile))}">${clockIcon()}</button><button data-start-call="voice" aria-label="语音通话">${callIcon(false)}</button><button data-start-call="video" aria-label="视频通话">${callIcon(true)}</button><button class="chat-more" data-chat-settings aria-label="聊天设置">•••</button></div>
      </header>
      <div class="chat-stream-v3" data-stream>${messages.map((message,index,list)=>messageView(message,index>0&&list[index-1].role===message.role,person,user,profile,appearance,messages,ui,!list[index+1]||list[index+1].role!==message.role||list[index+1].recalled)).join("")}${ui.sending?typingView(person,profile):""}</div>
      ${ui.selectMode ? selectionBar(ui.selected.size) : composerView(quoted,ui.attachmentsOpen,ui.sending,ui.error,ui.echoNext)}
    </section>`;
    // Resolve the end of each visible sender run after recalled/system rows are
    // omitted. The shape and timestamp must agree about the same last bubble.
    const visibleRows=[...container.querySelectorAll('.chat-stream-v3 > .message')];
    visibleRows.forEach((row,index)=>row.classList.toggle('group-end',!visibleRows[index+1]?.classList.contains('continuation')));
    bind(container, params, conv, person, user, profile, messages);
    alignBubbleShapes(container.querySelector('[data-chat-skin]'));
    requestAnimationFrame(() => { const stream=container.querySelector("[data-stream]"); if(stream)stream.scrollTop=stream.scrollHeight; });

    function configureHeader() {
      const back=document.querySelector("#back-button");
      document.querySelector("#header-title").textContent=profile.remark || person.name;
      document.querySelector("#header-kicker").textContent="BUNNY CHAT";
      back.classList.remove("hidden");
      back.classList.toggle("selection-cancel",ui.selectMode);
      back.textContent=ui.selectMode ? "取消" : "‹";
      back.setAttribute("aria-label",ui.selectMode ? "取消多选" : "返回聊天列表");
      back.onclick=()=>{if(ui.selectMode){ui.selectMode=false;ui.selected.clear();conversation(container,params)}else goBack()};
    }
  };

  function bind(container, params, conv, person, user, profile, messages) {
    container.querySelector("[data-chat-settings]").onclick=()=>navigate("chat-settings",{personId:person.id,conversationId:conv.id});
    container.querySelector("[data-time-awareness]").onclick=()=>openTimeAwareness(profile,person,container,params);
    container.querySelectorAll("[data-start-call]").forEach(button=>button.onclick=()=>{unlockCallAudio();navigate("call",{id:conv.id,mode:button.dataset.startCall})});
    container.querySelectorAll(".money-card").forEach(card=>card.onclick=()=>{const message=messages.find(item=>item.id===card.closest(".message")?.dataset.messageId);if(message)openMoneyReceipt(message,person)});
    const topAvatar=container.querySelector("[data-profile-card]");
    let singleTimer;
    topAvatar.onclick=()=>{if(topAvatar.__bunnyDoubleTappedUntil>Date.now())return;clearTimeout(singleTimer);singleTimer=setTimeout(()=>showProfile(person,profile),280)};
    bindDoubleTap(topAvatar,()=>{clearTimeout(singleTimer);pat(person,profile,conv,container,params)});
    container.querySelector('[data-voice-activity]')?.addEventListener('click',()=>openInnerVoiceSheet(conv,person));
    container.querySelectorAll("[data-pat-avatar]").forEach(avatar=>bindDoubleTap(avatar,()=>pat(person,profile,conv,container,params)));
    container.querySelectorAll(".message.char .bubble-v3").forEach(bubble=>bindLongPress(bubble,()=>openMessageMenu(bubble.closest(".message").dataset.messageId,conv,person,container,params)));
    container.querySelectorAll(".message.user .bubble-v3").forEach(bubble=>bindLongPress(bubble,()=>openUserMessageMenu(bubble.closest(".message").dataset.messageId,conv,person,container,params)));
    container.querySelectorAll("[data-recalled-message]").forEach(button=>button.onclick=()=>showRecalled(messages.find(x=>x.id===button.dataset.recalledMessage),person));
    container.querySelectorAll("[data-play-voice]").forEach(button=>button.onclick=()=>playVoiceMessage(messages.find(x=>x.id===button.dataset.playVoice),profile,button.closest(".voice-message-wrap")?.querySelector(".voice-message")||button));
    container.querySelectorAll("[data-voice-transcript-toggle]").forEach(button=>button.onclick=event=>{event.stopPropagation();button.closest(".voice-message-wrap")?.classList.toggle("transcript-open")});
    container.querySelectorAll("[data-polaroid]").forEach(button=>button.onclick=()=>button.classList.toggle("flipped"));
    container.querySelectorAll("[data-real-photo]").forEach(button=>button.onclick=()=>openPhotoViewer(button.dataset.realPhoto,conv,person,profile,container,params));
    container.querySelectorAll('[data-echo-replay]').forEach(button=>button.onclick=()=>playEcho(button.closest('.message')));
    container.querySelector("[data-open-api]")?.addEventListener("click",()=>navigate("api",{section:"text"}));
    container.querySelectorAll("[data-select-message]").forEach(button=>button.onclick=()=>{const id=button.dataset.selectMessage;if(ui.selected.has(id))ui.selected.delete(id);else ui.selected.add(id);renderAgain(container,params)});
    container.querySelector("[data-selection-delete]")?.addEventListener("click",()=>deleteSelected(conv,container,params));
    container.querySelector("[data-selection-forward]")?.addEventListener("click",()=>forwardSelected(conv,person,container,params));
    const form=container.querySelector("[data-composer]");
    if(form){
      form.onsubmit=e=>{e.preventDefault();submitMessage(true,form,conv,person,profile,container,params)};
      form.querySelector("[data-send-ai]").onclick=event=>{event.preventDefault();submitMessage(true,form,conv,person,profile,container,params)};
      form.querySelector("[data-send-only]").onclick=()=>submitMessage(false,form,conv,person,profile,container,params);
      form.querySelector("[data-plus]").onclick=()=>{ui.attachmentsOpen=!ui.attachmentsOpen;activeRender(container,params)};
      container.querySelectorAll("[data-fold-action]").forEach(button=>button.onclick=()=>{if(button.dataset.foldAction==='echo'){ui.echoNext=!ui.echoNext;button.setAttribute('aria-pressed',String(ui.echoNext));form.elements.message.placeholder=ui.echoNext?'回声效果已开启 · 输入文字':'发送消息…';showToast(ui.echoNext?'下一条文字将以回声效果发送':'已关闭回声效果');return}handleFoldAction(button.dataset.foldAction,conv,person,container,params)});
      form.querySelector("[data-cancel-quote]")?.addEventListener("click",()=>{ui.quoteId="";renderAgain(container,params)});
    }
  }

  function openTimeAwareness(profile,person,container,params){
    ensureTimeProfile(profile);const today=new Date();
    openSheet(`<form class="time-awareness-sheet"><div class="sheet-title"><div><small>TIME AWARENESS</small><h3>${escapeHtml(person.name)} 的时间感知</h3></div><button type="button" class="button ghost" data-sheet-close>取消</button></div><label class="setting-row time-awareness-switch"><div><span class="label">跟随现实时间</span><small>开启后会感知日期、时段、间隔与作息</small></div><input class="switch" type="checkbox" name="enabled" ${profile.timeAwarenessEnabled!==false?"checked":""}></label><div class="time-manual-fields" data-manual-time><label class="field"><span>当前年月日</span><input type="date" name="manualDate" value="${escapeHtml(profile.manualDate||localDateValue(today))}"></label><label class="field"><span>当前时刻</span><input type="time" name="manualTime" value="${escapeHtml(profile.manualTime||localTimeValue(today))}"></label><p>关闭现实时间后，AI 会把这里设定的日期与时刻当作当前世界的真实现在。</p></div><button class="button" type="submit">保存时间设置</button></form>`,{onReady(sheet){const form=sheet.querySelector("form"),toggle=form.elements.enabled,manual=sheet.querySelector("[data-manual-time]");const sync=()=>{manual.classList.toggle("disabled",toggle.checked);manual.querySelectorAll("input").forEach(input=>input.disabled=toggle.checked)};toggle.onchange=sync;sync();form.onsubmit=event=>{event.preventDefault();const data=new FormData(form);store.update(s=>{const target=ensureTimeProfile(s.chatProfiles[person.id]);target.timeAwarenessEnabled=toggle.checked;target.manualDate=String(data.get("manualDate")||profile.manualDate||localDateValue(today));target.manualTime=String(data.get("manualTime")||profile.manualTime||localTimeValue(today))});closeSheet();activeRender(container,params);showToast(toggle.checked?"已跟随现实时间":"已切换到自定义时间")}}});
  }

  function renderAgain(container,params){createConversationV3RendererRenderHack(container,params)}
  let activeRender=null;
  function createConversationV3RendererRenderHack(container,params){activeRender?.(container,params)}

  async function submitMessage(sendAi,form,conv,person,profile,container,params){
    if(sendAi&&ui.sending)return showToast("正在等待 AI 回复");
    const input=form.elements.message,text=input.value.trim();
    if(text){const replyTo=ui.quoteId||"",now=timeNow(),effect=ui.echoNext?'echo':'',messageId=id();store.update(s=>{s.messages[conv.id].push({id:messageId,role:"user",type:"text",text,time:now,createdAt:Date.now(),replyTo,effect});const c=conversationById(s,conv.id);c.preview=text;c.time=now});ui.quoteId="";ui.error="";ui.echoNext=false;input.value="";if(effect==='echo')requestAnimationFrame(()=>playEcho(container.querySelector(`[data-message-id="${messageId}"]`)))}
    else if(!sendAi)return showToast("请输入消息内容");
    if(!sendAi){activeRender(container,params);return}
    ui.sending=true;activeRender(container,params);
    await requestAiReply(conv,person,profile,container,params);
  }

  async function requestAiReply(conv,person,profile,container,params,options={}){
    if(!ui.sending){ui.sending=true;ui.error="";activeRender(container,params)}
    const current=store.getState(),model=current.modelProfiles.find(x=>x.id===current.activeModelProfileId);
    updateIsland(`${person.name} 正在回复…`,true);
    try{
      if(!model?.apiKey||!model?.model)throw Error("没有可用的文本模型：请到“模型与 API”拉取模型、测试连接并保存启用")
      const block=currentSchedule(store,person.id);
      if(block?.canReply===false){
        const dueAt=nextReplyAt(store,person.id).getTime();
        store.update(s=>{s.callRuntime=s.callRuntime||{};s.callRuntime.pendingReplies=s.callRuntime.pendingReplies||{};s.callRuntime.pendingReplies[conv.id]={personId:person.id,dueAt,createdAt:Date.now(),reason:block.status,source:'schedule'}});
        showToast(`${person.name}现在${block.status}，有空后再回`);
        return;
      }
      const p=current.presets.find(x=>x.id===profile.presetId)||current.presets.find(x=>x.name===profile.preset);
      const books=current.worldbooks.filter(x=>(profile.worldbookIds||[]).includes(x.id)||x.name===profile.worldbook);
      const commonStickers=(current.stickerLibraries?.global||[]).map(x=>({...x,scope:"CHAR 通用"})),exclusiveStickers=(current.stickerLibraries?.characters?.[person.id]||[]).map(x=>({...x,scope:"角色专属"})),charStickers=[...exclusiveStickers,...commonStickers];
      const stickerGuide=charStickers.length?`当前 CHAR 可用表情包（只能按描述选择）：\n${charStickers.map((x,i)=>`${i+1}. [${x.scope}] ${x.name||"表情"}｜${x.description||(x.tags||[]).join("、")||"无描述"}`).join("\n")}`:"当前 CHAR 没有可用表情包，不要输出 sticker；仍可在开启偷表情时收藏 USER 发来的表情。";
      ensureTtsState(current);
      ensureAccountState(current);const user=personById(current,current.currentUserId),identity=accountContext(current,person.id,user.id),boundChar=person.boundCharId?personById(current,person.boundCharId):null,boundIdentities=[...new Set([...(person.boundIdentityIds||[]),...(person.boundCharId?[person.boundCharId]:[])])].map(id=>personById(current,id)).filter(Boolean),history=current.messages[conv.id]||[],lastUser=[...history].reverse().find(x=>x.role==="user"&&!x.recalled),lastMessage=[...history].reverse().find(x=>x.createdAt),memory=await retrieveMemoryContext(current,identity.memoryOwnerId,lastUser?.text||lastUser?.description||""),worldId=entityWorld(current,person.id),world=current.worlds.find(x=>x.id===worldId),knownEvents=knownWorldEvents(current,person.id,worldId,6).map(row=>row.payload.summary||row.payload.text).filter(Boolean);
      const imageEnabled=Boolean(current.mediaApis?.image?.enabled&&current.mediaApis.image.channels?.chat!==false&&profile.imageGenerationEnabled),timeContext=buildTimeContext(profile,{timezone:world?.timezone,lastMessageAt:lastMessage?.createdAt}),worldbookPrompts=books.map(book=>compileWorldbook(book,lastUser?.text||lastUser?.description||"")).filter(Boolean),preset=compilePreset(p),prompt=[preset.systemPrompt,worldContextPrompt(current,person.id),knownEvents.length?`【你亲历或公开可知的近期世界事件】\n${knownEvents.join('\n')}`:'',...worldbookPrompts,buildInternalChatPrompt({person,user,boundChar,boundIdentities,profile,translationEnabled:profile.translationEnabled,toneEnabled:profile.llmTone!==false,stickerGuide,imageGenerationEnabled:imageEnabled}),timeContext,schedulePrompt(store,person.id),`【当前账号身份规则】\n${identity.prompt}`,memory.promptBlock,options.instruction].filter(Boolean).join("\n\n"),promptBundle={system:prompt,prefixMessages:preset.prefixMessages};
      const avatarContext=profile.visionEnabled&&user.avatarUrl?[{id:"user-current-avatar",role:"user",type:"image",src:user.avatarUrl,text:"USER 当前头像",description:"这是 USER 当前正在使用的头像。你可以识别它，但不要机械复述。"}]:[];
      store.update(s=>{for(const message of s.messages[conv.id]||[])if(message.role==="user"&&!message.charReadAt)message.charReadAt=Date.now()});
      const modelMessages=[...avatarContext,...current.messages[conv.id].map(m=>profile.visionEnabled?m:{...m,src:""})];
      savePromptDebug(store,identity.memoryOwnerId,{systemPrompt:prompt,prefixMessages:preset.prefixMessages,messages:modelMessages,retrieval:{query:lastUser?.text||lastUser?.description||"",selected:memory.selected.map(x=>({id:x.id,kind:x.kind,text:x.text||x.event})),semantic:memory.semantic}});
      const raw=await sendToModel(model,modelMessages,promptBundle),parsed=await enforceChatFormat(raw,model,profile),responseBatchId=id();
      for(const row of parsed.messages)recordScheduleCommitment(store,person.id,row.text);
      for(let index=0;index<parsed.messages.length;index++){const reply=parsed.messages[index],pause=460+Math.min(1450,Math.max(0,reply.text.length-2)*24),messageId=id();await sleep(pause);store.update(s=>{s.messages[conv.id].push({id:messageId,responseBatchId,role:"char",type:"text",text:reply.text,translation:reply.translation,tone:reply.tone,effect:reply.effect,time:timeNow(),createdAt:Date.now(),arrivedWithPause:true});const target=s.conversations.find(x=>x.id===conv.id);if(target){target.preview=reply.text;target.time=timeNow()}});activeRender(container,params);if(reply.effect==='echo')requestAnimationFrame(()=>playEcho(container.querySelector(`[data-message-id="${messageId}"]`)))}
      for(const action of parsed.actions){
        if(action.kind==="sticker"){const query=action.query.toLowerCase(),item=charStickers.find(x=>[x.name,x.description,...(x.tags||[])].filter(Boolean).some(v=>String(v).toLowerCase().includes(query)||query.includes(String(v).toLowerCase())))||charStickers[0];if(item)store.update(s=>s.messages[conv.id].push({id:id(),responseBatchId,role:"char",type:"sticker",text:item.name||"表情包",src:item.url,description:item.description||(item.tags||[]).join("、")||"CHAR 发送的表情包",time:timeNow()}));continue}
        if(action.kind==="steal_sticker"){const source=current.messages[conv.id].find(x=>x.id===action.target&&x.role==="user"&&x.type==="sticker"&&x.src);if(source&&profile.stickerSteal){store.update(s=>{const library=s.stickerLibraries.characters[person.id]||(s.stickerLibraries.characters[person.id]=[]);if(!library.some(x=>x.url===source.src))library.push({name:source.text||"收藏的表情",url:source.src,description:source.description||source.text||"从 USER 收藏的表情",tags:["偷来的"]})});showToast(`${person.name} 收藏了这张表情`)}continue}
        if(action.kind==="image"){const description=action.description||"一张刚拍下的日常照片",messageId=id(),generating=Boolean(imageEnabled);store.update(s=>s.messages[conv.id].push({id:messageId,responseBatchId,role:"char",type:generating?"image":"text-image",text:description,src:generating?"":makeTextImageDataUrl(description),description,imagePrompt:action.prompt||"",generating,time:timeNow(),createdAt:Date.now()}));activeRender(container,params);if(!generating)continue;try{let src=await generateCharacterImage(current.mediaApis?.image,profile,action.prompt||description),mediaId="";if(!src)throw Error("生图 API 没有返回图片");try{const response=await fetch(src);if(response.ok){const media=await saveMediaBlob(await response.blob());src=media.src;mediaId=media.mediaId}}catch{}store.update(s=>{const target=s.messages[conv.id].find(x=>x.id===messageId);if(target)Object.assign(target,{src,mediaId,generating:false,type:"image"})})}catch(error){store.update(s=>{const target=s.messages[conv.id].find(x=>x.id===messageId);if(target)Object.assign(target,{src:makeTextImageDataUrl(description),generating:false,type:"text-image",generationError:error.message})});showToast(`生图暂不可用，已改用文字图：${error.message}`)}activeRender(container,params);continue}
        if(action.kind==="avatar"){const chosen=current.messages[conv.id].find(x=>x.id===action.target&&x.role==="user"&&x.src);if(chosen){store.update(s=>{const target=s.chatProfiles[person.id];target.previousAvatarUrl=target.avatarUrl||"";target.avatarUrl=chosen.src;target.avatarBatchId=responseBatchId});showToast(`${person.name} 换上了自己选的头像`)}continue}
        if(action.kind==="signature"){store.update(s=>{const target=personById(s,person.id);if(target){target.previousSignature=target.signature||"";target.signature=action.text;target.signatureBatchId=responseBatchId}});showToast(`${person.name} 更新了个性签名`);continue}
        if(action.kind==="voice"){store.update(s=>s.messages[conv.id].push({id:id(),responseBatchId,role:"char",type:"voice",text:action.text,translation:action.translation,tone:action.tone,duration:estimateVoiceDuration(action.text),time:timeNow()}));continue}
        if(action.kind==="reaction"){store.update(s=>{const target=findActionTarget(s.messages[conv.id],action.target,"user");if(target){target.reaction=action.emoji;target.reactionBy="char";target.reactionBatchId=responseBatchId}});continue}
        if(action.kind==="pat"){store.update(s=>s.messages[conv.id].push({id:id(),responseBatchId,role:"system",type:"pat",text:profile.patUserText||`${person.name}拍了拍你`,time:timeNow(),createdAt:Date.now()}));continue}
        if(action.kind==="defer"){store.update(s=>{s.callRuntime=s.callRuntime||{};s.callRuntime.pendingReplies=s.callRuntime.pendingReplies||{};s.callRuntime.pendingReplies[conv.id]={personId:person.id,dueAt:Date.now()+action.minutes*60000,createdAt:Date.now(),reason:"busy"}});continue}
        if(action.kind==="recall"){store.update(s=>{const target=findActionTarget(s.messages[conv.id],action.target,"char");if(target&&!target.recalled){target.recalled=true;target.recalledText=target.text;target.recalledAt=Date.now();target.recalledByBatchId=responseBatchId}});continue}
        const kind=action.kind==="redpacket"&&action.amount>520?"transfer":action.kind,messageId=id();store.update(s=>s.messages[conv.id].push({id:messageId,responseBatchId,role:"char",type:kind,text:action.note||(kind==="redpacket"?"大吉大利":"转账给你"),amount:action.amount,time:timeNow()}));walletCredit(store,{amount:action.amount,kind,title:`收到 ${person.name} 的${kind==="redpacket"?"红包":"转账"}`,conversationId:conv.id,messageId,note:action.note})
      }
      activeRender(container,params);
      if(parsed.messages.length){const event=appendWorldEvent(store,{id:`chat-batch:${responseBatchId}`,worldId,actorIds:[user.id,person.id],witnessIds:[user.id,person.id],kind:'private-chat',payload:{summary:`${person.name} 与 ${user.name} 聊到：${(lastUser?.text||'').slice(0,80)}`,public:false},source:'chat'});changeRelationship(store,{a:user.id,b:person.id,worldId,deltaAffinity:1,reasonEventId:event.id})}
      scheduleMemoryMaintenance({store,personId:person.id,ownerId:identity.memoryOwnerId,conversationId:conv.id,accountId:user.id,model,messages:store.getState().messages[conv.id]||[]});
      if(!ui.voiceGenerating&&innerVoiceActivityDue(store.getState(),conv)){
        ui.voiceGenerating=true;
        void generateInnerVoice(store,conv,person,{activity:true}).then(()=>{if(ui.conversationId===conv.id&&container.isConnected)activeRender(container,params)}).catch(error=>console.warn('Bunny inner voice activity skipped',error)).finally(()=>{ui.voiceGenerating=false});
      }
      if(profile.voiceGenerationMode==="auto"){const voices=(store.getState().messages[conv.id]||[]).filter(x=>x.responseBatchId===responseBatchId&&x.type==="voice"&&!x.audioMediaId);for(const message of voices)await cacheVoiceMessage(message,profile).catch(error=>showToast(error.message))}
      if(profile.autoPlayVoice&&parsed.messages.length){const spoken=parsed.messages.map(x=>x.text).join("。"),tone=parsed.messages.find(x=>x.tone)?.tone||"";synthesizeSpeech(resolveTtsConfig(store.getState(),profile),spoken,{tone}).catch(error=>showToast(error.message))}
    }catch(error){ui.error=readableAiError(error);showToast(ui.error)}finally{ui.sending=false;updateIsland("bunny 正在陪你",false);activeRender(container,params)}
  }

  function openMessageMenu(messageId,conv,person,container,params){
    const state=store.getState(),message=state.messages[conv.id].find(x=>x.id===messageId);
    const recent=(state.chatAppearance.recentReactions||DEFAULT_REACTIONS).slice(0,6);
    openSheet(`<div class="message-action-menu"><div class="tapback-row">${recent.map(emoji=>`<button data-reaction="${emoji}" aria-label="${emoji}">${emoji}</button>`).join("")}<button class="tapback-more" data-more-emoji aria-label="更多表情">＋</button></div>
      <div class="message-menu-preview">${escapeHtml(message.text)}</div>
      <div class="message-action-list">
        <button data-quote>${menuIcon("quote")}<span><strong>引用回复</strong><small>在输入框上方显示这条消息</small></span></button>
        ${message.type==='text'||!message.type?'<button data-echo-message><span class="echo-menu-symbol">◎</span><span><strong>回声</strong><small>让这条消息的文字跃满屏幕</small></span></button>':''}
        <button data-edit>${menuIcon("edit")}<span><strong>编辑</strong><small>修改文字或消息类型</small></span></button>
        <button data-favorite>${menuIcon("favorite")}<span><strong>收藏</strong><small>保存到“我的收藏”</small></span></button>
        <button data-multi>${menuIcon("multi")}<span><strong>多选</strong><small>删除或合并转发消息</small></span></button>
      </div></div>`,{onReady(sheet){
        sheet.querySelectorAll("[data-reaction]").forEach(b=>b.onclick=()=>applyReaction(b.dataset.reaction,messageId,conv,container,params));
        sheet.querySelector("[data-more-emoji]").onclick=()=>openEmojiPicker(emoji=>applyReaction(emoji,messageId,conv,container,params));
        sheet.querySelector("[data-quote]").onclick=()=>{ui.quoteId=messageId;closeSheet();activeRender(container,params);requestAnimationFrame(()=>container.querySelector("textarea")?.focus())};
        sheet.querySelector('[data-echo-message]')?.addEventListener('click',()=>markMessageEcho(messageId,conv,container,params));
        sheet.querySelector("[data-edit]").onclick=()=>openEditor(messageId,conv,container,params);
        sheet.querySelector("[data-favorite]").onclick=()=>favoriteMessage(messageId,conv);
        sheet.querySelector("[data-multi]").onclick=()=>{ui.selectMode=true;ui.selected=new Set([messageId]);closeSheet();activeRender(container,params)};
      }});
  }

  function applyReaction(emoji,messageId,conv,container,params){store.update(s=>{const m=s.messages[conv.id].find(x=>x.id===messageId);m.reaction=m.reaction===emoji?"":emoji;m.reactionBy="user";s.chatAppearance.recentReactions=[emoji,...(s.chatAppearance.recentReactions||DEFAULT_REACTIONS).filter(x=>x!==emoji)].slice(0,6)});closeSheet();activeRender(container,params);const state=store.getState(),person=personById(state,conv.personId);requestAiReply(conv,person,state.chatProfiles[person.id],container,params)}
  function openEmojiPicker(select){const names=Object.keys(EMOJI_GROUPS);openSheet(`<div class="emoji-picker"><div class="sheet-title"><h3>选择表情</h3><button class="button ghost" data-sheet-close>关闭</button></div><div class="emoji-tabs">${names.map((x,i)=>`<button class="${i===0?"active":""}" data-emoji-tab="${x}">${x}</button>`).join("")}</div><div class="emoji-grid" data-emoji-grid>${EMOJI_GROUPS[names[0]].map(x=>`<button data-emoji="${x}">${x}</button>`).join("")}</div></div>`,{onReady(sheet){const grid=sheet.querySelector("[data-emoji-grid]");const bind=()=>grid.querySelectorAll("[data-emoji]").forEach(b=>b.onclick=()=>select(b.dataset.emoji));bind();sheet.querySelectorAll("[data-emoji-tab]").forEach(tab=>tab.onclick=()=>{sheet.querySelectorAll("[data-emoji-tab]").forEach(x=>x.classList.toggle("active",x===tab));grid.innerHTML=EMOJI_GROUPS[tab.dataset.emojiTab].map(x=>`<button data-emoji="${x}">${x}</button>`).join("");bind()})}})}

  function openUserMessageMenu(messageId,conv,person,container,params){const message=store.getState().messages[conv.id].find(x=>x.id===messageId);if(!message||message.recalled)return;openSheet(`<div class="message-action-menu user-action-menu"><div class="message-menu-preview">${escapeHtml(message.text)}</div><div class="message-action-list">${message.type==='text'||!message.type?'<button data-echo-message><span class="echo-menu-symbol">◎</span><span><strong>回声</strong><small>让这条消息的文字跃满屏幕</small></span></button>':''}<button data-recall>${menuIcon("recall")}<span><strong>撤回</strong><small>CHAR 会知道你撤回了这条消息</small></span></button><button data-edit>${menuIcon("edit")}<span><strong>编辑</strong><small>修改消息类型和内容</small></span></button><button data-favorite>${menuIcon("favorite")}<span><strong>收藏</strong><small>保存文字、图片或语音</small></span></button><button data-delete-one>${menuIcon("delete")}<span><strong>删除</strong><small>仅从当前聊天记录删除</small></span></button><button data-multi>${menuIcon("multi")}<span><strong>多选</strong><small>批量删除或合并转发</small></span></button></div></div>`,{onReady(sheet){sheet.querySelector('[data-echo-message]')?.addEventListener('click',()=>markMessageEcho(messageId,conv,container,params));sheet.querySelector("[data-recall]").onclick=()=>recallUserMessage(messageId,conv,person,container,params);sheet.querySelector("[data-edit]").onclick=()=>openEditor(messageId,conv,container,params,"USER");sheet.querySelector("[data-favorite]").onclick=()=>favoriteMessage(messageId,conv);sheet.querySelector("[data-delete-one]").onclick=()=>confirmDialog("删除消息","确定删除这条消息吗？删除后不会通知 CHAR。","删除",()=>{store.update(s=>s.messages[conv.id]=s.messages[conv.id].filter(x=>x.id!==messageId));activeRender(container,params)});sheet.querySelector("[data-multi]").onclick=()=>{ui.selectMode=true;ui.selected=new Set([messageId]);closeSheet();activeRender(container,params)}}})}

  function markMessageEcho(messageId,conv,container,params){store.update(s=>{const target=s.messages[conv.id]?.find(row=>row.id===messageId);if(target)target.effect='echo'});closeSheet();activeRender(container,params);requestAnimationFrame(()=>playEcho(container.querySelector(`[data-message-id="${messageId}"]`)))}

  function favoriteMessage(messageId,conv){const state=store.getState(),message=state.messages[conv.id]?.find(x=>x.id===messageId);if(!message)return;store.update(s=>{s.favorites=s.favorites||[];if(!s.favorites.some(x=>x.messageId===messageId))s.favorites.unshift({id:id(),messageId,conversationId:conv.id,personId:conv.personId,createdAt:Date.now(),...message})});closeSheet();showToast("已添加到收藏")}

  function recallUserMessage(messageId,conv,person,container,params){store.update(s=>{const m=s.messages[conv.id].find(x=>x.id===messageId);if(m&&!m.recalled){m.recalled=true;m.recalledText=m.text;m.recalledAt=Date.now()}});closeSheet();activeRender(container,params);const state=store.getState();requestAiReply(conv,person,state.chatProfiles[person.id],container,params)}

  function openEditor(messageId,conv,container,params,owner="CHAR"){const m=store.getState().messages[conv.id].find(x=>x.id===messageId);let type=m.type||"text";openSheet(`<div class="message-editor"><div class="sheet-title"><h3>编辑 ${owner} 消息</h3><button class="button ghost" data-sheet-close>取消</button></div><div class="message-type-row">${Object.entries(TYPE_META).map(([key,val])=>`<button class="${type===key?"active":""}" data-message-type="${key}"><span>${val[1]}</span>${val[0]}</button>`).join("")}</div><label class="field"><span>消息内容</span><textarea data-edit-text rows="5">${escapeHtml(m.text)}</textarea></label><button class="button" data-save-edit>保存修改</button></div>`,{onReady(sheet){sheet.querySelectorAll("[data-message-type]").forEach(b=>b.onclick=()=>{type=b.dataset.messageType;sheet.querySelectorAll("[data-message-type]").forEach(x=>x.classList.toggle("active",x===b))});sheet.querySelector("[data-save-edit]").onclick=()=>{const text=sheet.querySelector("[data-edit-text]").value.trim();if(!text)return showToast("消息内容不能为空");store.update(s=>Object.assign(s.messages[conv.id].find(x=>x.id===messageId),{text,type,edited:true}));closeSheet();activeRender(container,params);showToast("消息已编辑")}}})}

  function deleteSelected(conv,container,params){if(!ui.selected.size)return;confirmDialog("删除消息",`确定删除选中的 ${ui.selected.size} 条消息吗？此操作无法撤销。`,"删除",()=>{store.update(s=>s.messages[conv.id]=s.messages[conv.id].filter(x=>!ui.selected.has(x.id)));ui.selected.clear();ui.selectMode=false;activeRender(container,params);showToast("消息已删除")})}
  function forwardSelected(conv,person,container,params){if(!ui.selected.size)return;const state=store.getState(),targets=state.conversations.filter(x=>x.id!==conv.id);openSheet(`<div class="forward-confirm"><div class="sheet-title"><h3>合并转发</h3><button class="button ghost" data-sheet-close>取消</button></div><p class="callout">将 ${ui.selected.size} 条消息合并成一份聊天记录。请选择接收人，确认后发送。</p><div class="forward-targets">${targets.map(c=>{const p=personById(state,c.personId);return`<label><input type="radio" name="forwardTarget" value="${c.id}">${initialsAvatar(p,state.chatProfiles[p.id]||{})}<span>${escapeHtml(p.name)}</span></label>`}).join("")||"<p>暂无其他联系人</p>"}</div><button class="button" data-confirm-forward>确认转发</button></div>`,{onReady(sheet){sheet.querySelector("[data-confirm-forward]").onclick=()=>{const target=sheet.querySelector('input[name="forwardTarget"]:checked');if(!target)return showToast("请选择接收人");const bundle=store.getState().messages[conv.id].filter(x=>ui.selected.has(x.id)).map(x=>({role:x.role,text:x.text,type:x.type||"text",time:x.time}));store.update(s=>s.messages[target.value].push({id:id(),role:"user",type:"chat-record",text:`与${person.name}的聊天记录`,time:timeNow(),bundle}));closeSheet();ui.selected.clear();ui.selectMode=false;activeRender(container,params);showToast("聊天记录已合并转发")}}})}

  function confirmDialog(title,text,action,done){openSheet(`<div class="confirm-dialog"><div class="confirm-symbol">!</div><h3>${title}</h3><p>${text}</p><div class="row"><button class="button secondary" data-sheet-close>取消</button><button class="button danger-button" data-confirm>${action}</button></div></div>`,{onReady(sheet){sheet.querySelector("[data-confirm]").onclick=()=>{closeSheet();done()}}})}
  function pat(person,profile,conv,container,params){const text=profile.patText||`你拍了拍${person.name}`;store.update(s=>s.messages[conv.id].push({id:id(),role:"system",type:"pat",text,time:timeNow()}));navigator.vibrate?.(18);showToast(text);activeRender(container,params)}
  function showProfile(person,profile){openSheet(`<section class="chat-profile-card-v2"><div class="profile-card-orbit"></div><header>${initialsAvatar(person,profile)}<span>BUNNY CONTACT</span><h2>${escapeHtml(profile.remark||person.name)}</h2><p>${escapeHtml(person.name)} · ${escapeHtml(person.occupation||person.note||"CHAR")}</p></header><blockquote>${escapeHtml(person.signature||"还没有留下个性签名")}</blockquote><div class="profile-card-facts"><span><small>所在地</small><strong>${escapeHtml(person.city||person.location||"未设置")}</strong></span><span><small>关系</small><strong>${escapeHtml(profile.relationship||"好友")}</strong></span></div><nav><button data-card-profile aria-label="角色档案">${photoToolIcon("prompt")}</button><button data-card-settings aria-label="聊天设置">${clockIcon()}</button><button data-sheet-close aria-label="关闭">${photoToolIcon("undo")}</button></nav></section>`,{onReady(sheet){sheet.querySelector("[data-card-profile]").onclick=()=>{closeSheet();navigate("character-edit",{id:person.id,type:person.type})};sheet.querySelector("[data-card-settings]").onclick=()=>{closeSheet();navigate("chat-settings",{personId:person.id})}}})}
  function handleFoldAction(action,conv,person,container,params){
    if(action==='inner-voice')return openInnerVoiceSheet(conv,person);
    if(action==="reroll")return rerollLastReply(conv,person,container,params);
    if(action==="call"||action==="video")return navigate("call",{id:conv.id,mode:action==="video"?"video":"voice"});
    if(action==="album"||action==="camera"){const input=document.createElement("input");input.type="file";input.accept="image/*";input.multiple=action==="album";if(action==="camera")input.capture="environment";input.onchange=async()=>{const files=[...(input.files||[])].slice(0,12);if(!files.length)return;try{showToast(`正在保存 ${files.length} 张照片…`);const rows=[];for(const file of files){const blob=await readImageBlobOptimized(file),media=await saveMediaBlob(blob);rows.push({type:"image",text:file.name,src:media.src,mediaId:media.mediaId,description:`USER 发送的真实照片：${file.name}`})}sendRichBatch(conv,rows,container,params);showToast(`已发送 ${rows.length} 张照片`)}catch(error){showToast(error.message)}};input.click();return}
    if(action==="text-image")return openTextImage(conv,container,params);
    if(action==="voice")return openVoiceRecorder(conv,person,container,params);
    if(action==="redpacket"||action==="transfer")return openMoney(action,conv,person,container,params);
    if(action==="sticker")return openUserStickers(conv,container,params);
  }
  function openInnerVoiceSheet(conv,person){
    const recent=savedInnerVoices(store.getState(),conv),latest=recent[0];
    if(latest&&!latest.seenAt){store.update(s=>{const row=(s.innerVoiceRecords||[]).find(x=>x.id===latest.id);if(row)row.seenAt=Date.now()});document.querySelector('[data-voice-activity]')?.remove()}
    openSheet(`<section class="inner-voice-sheet"><div class="sheet-title"><div><small>UNSENT WORDS</small><h3>${escapeHtml(person.name)} 的心声</h3></div><button type="button" class="button ghost" data-sheet-close>关闭</button></div><p class="inner-voice-note">一段只给你看的虚构内心独白。聊天几轮后偶尔出现，也可手动看看此刻。</p><div class="inner-voice-cloud ${latest?'has-thought':''}"><p data-inner-voice-text>${escapeHtml(latest?.thought||'那些没说出口的话，会在这里慢慢浮现。')}</p></div><small class="inner-voice-date" data-inner-voice-date>${latest?new Date(latest.createdAt).toLocaleString('zh-CN'):''}</small><button type="button" class="button inner-voice-generate" data-generate-inner-voice>${latest?'看看此刻有没有新心声':'生成此刻心声'}</button><p class="inner-voice-status" data-inner-voice-status role="status"></p></section>`,{onReady(sheet){const button=sheet.querySelector('[data-generate-inner-voice]'),status=sheet.querySelector('[data-inner-voice-status]');button.onclick=async()=>{button.disabled=true;button.textContent='正在捕捉心声…';status.textContent='';try{const row=await generateInnerVoice(store,conv,person);if(!sheet.isConnected)return;sheet.querySelector('[data-inner-voice-text]').textContent=row.thought;sheet.querySelector('.inner-voice-cloud').classList.add('has-thought');sheet.querySelector('[data-inner-voice-date]').textContent=new Date(row.createdAt).toLocaleString('zh-CN');button.textContent='心声已保存';status.textContent='这段心声只属于当前账号与这段聊天。'}catch(error){if(!sheet.isConnected)return;status.textContent=error.message;button.textContent='重试生成';button.disabled=false}}}});
  }
  function sendRich(conv,data,container,params,askAi=false){sendRichBatch(conv,[data],container,params,askAi)}
  function sendRichBatch(conv,rows,container,params,askAi=false){store.update(s=>{for(const data of rows)s.messages[conv.id].push({id:id(),role:"user",time:timeNow(),createdAt:Date.now(),...data});const target=s.conversations.find(item=>item.id===conv.id),last=rows.at(-1);if(target){target.preview=previewFor(last);target.time=timeNow()}});ui.attachmentsOpen=false;ui.error="";if(askAi)ui.sending=true;activeRender(container,params);if(askAi){const state=store.getState(),person=personById(state,conv.personId);requestAiReply(conv,person,state.chatProfiles[person.id],container,params)}}
  function rerollLastReply(conv,person,container,params){
    if(ui.sending)return showToast("正在等待 AI 回复");
    const messages=store.getState().messages[conv.id]||[],last=[...messages].reverse().find(x=>x.role==="char"&&!x.recalled);
    if(!last)return showToast("还没有可以重新生成的 CHAR 回复");
    confirmDialog("重新生成回复","会移除上一轮 CHAR 回复并基于此前聊天重新生成。原回复不会继续进入模型记忆。","重新生成",()=>{
      const batchId=last.responseBatchId,removedIds=new Set();
      store.update(s=>{const list=s.messages[conv.id]||[];if(batchId){list.filter(x=>x.responseBatchId===batchId).forEach(x=>removedIds.add(x.id));s.messages[conv.id]=list.filter(x=>x.responseBatchId!==batchId);for(const x of s.messages[conv.id]){if(x.reactionBatchId===batchId){x.reaction="";x.reactionBy="";delete x.reactionBatchId}if(x.recalledByBatchId===batchId){x.recalled=false;delete x.recalledAt;delete x.recalledByBatchId}}const profile=s.chatProfiles[person.id];if(profile?.avatarBatchId===batchId){profile.avatarUrl=profile.previousAvatarUrl||"";delete profile.previousAvatarUrl;delete profile.avatarBatchId}const target=personById(s,person.id);if(target?.signatureBatchId===batchId){target.signature=target.previousSignature||"";delete target.previousSignature;delete target.signatureBatchId}}else{let cut=list.length;while(cut>0&&list[cut-1].role==="char"){removedIds.add(list[cut-1].id);cut--}s.messages[conv.id]=list.slice(0,cut)}rollbackWalletMessages(s,removedIds);refreshConversationPreview(s,conv.id)});
      ui.attachmentsOpen=false;ui.sending=true;activeRender(container,params);requestAiReply(conv,person,store.getState().chatProfiles[person.id],container,params,{instruction:"【本次触发】USER 点击了重新生成。请替换刚才那一轮回答，保持上下文连贯，但不要复述或提及被移除的旧回答。"});
    })
  }
  function openVoiceRecorder(conv,person,container,params){let recorder=null,recognition=null,blob=null,started=0,ticker=null,duration=0;openSheet(`<div class="voice-recorder-sheet"><div class="sheet-title"><div><span class="eyebrow">VOICE MESSAGE</span><h3>发送语音给 ${escapeHtml(person.name)}</h3></div><button class="button ghost" type="button" data-cancel-voice>取消</button></div><div class="voice-record-orb" data-record-state><i></i><strong data-record-time>00:00</strong><span>点击开始录音，也可以直接输入</span></div><label class="field"><span>语音文字（识别后可修改，也可直接手动填写）</span><textarea data-voice-transcript rows="3" placeholder="直接输入这条语音要说的内容"></textarea></label><div class="voice-record-actions"><button type="button" data-record-toggle>${micIcon()}<span>开始</span></button><button type="button" data-send-recording>${sendIcon()}<span>发送</span></button></div></div>`,{onReady(sheet){const toggle=sheet.querySelector("[data-record-toggle]"),send=sheet.querySelector("[data-send-recording]"),orb=sheet.querySelector("[data-record-state]"),clock=sheet.querySelector("[data-record-time]"),transcriptInput=sheet.querySelector("[data-voice-transcript]");const stop=async()=>{if(!recorder)return;const active=recorder;recorder=null;clearInterval(ticker);blob=await active.stop();try{recognition?.stop()}catch{}recognition=null;duration=Math.max(1,Math.round((Date.now()-started)/1000));orb.classList.remove("recording");orb.classList.add("recorded");orb.querySelector("span").textContent="录音完成，可以发送";toggle.querySelector("span").textContent="重录"};toggle.onclick=async()=>{try{if(recorder)return stop();if(blob){blob=null;duration=0;clock.textContent="00:00"}recorder=await recordAudio();try{recognition=startBrowserRecognition({language:"zh-CN",onText:text=>transcriptInput.value=text,onError:()=>{}})}catch{}started=Date.now();orb.classList.add("recording");orb.classList.remove("recorded");orb.querySelector("span").textContent="正在录音，再点一次停止";toggle.querySelector("span").textContent="停止";ticker=setInterval(()=>{duration=Math.min(60,Math.floor((Date.now()-started)/1000));clock.textContent=formatDuration(duration);if(duration>=60)stop()},250)}catch(error){showToast(error.message)}};send.onclick=async()=>{if(recorder)await stop();const transcript=transcriptInput.value.trim();if(!blob&&!transcript)return showToast("请录音或直接输入语音文字");const audioUrl=blob?await readBlobAsDataUrl(blob):"",text=transcript||`语音消息 ${formatDuration(duration)}`,seconds=duration||estimateVoiceDuration(text);closeSheet();sendRich(conv,{type:"voice",text,transcript:text,audioUrl,duration:seconds,manualVoice:!blob,description:`USER 发送语音，语音中说：${text}`},container,params,true)};sheet.querySelector("[data-cancel-voice]").onclick=()=>{clearInterval(ticker);try{recognition?.abort()}catch{}recorder?.cancel();closeSheet()}}})}
  function openTextImage(conv,container,params){openSheet(`<div class="sheet-title"><h3>制作 1:1 文字图</h3><button class="button ghost" data-sheet-close>取消</button></div><label class="field"><span>图片中的完整文字</span><textarea data-text-image rows="6" maxlength="280" placeholder="这段文字会作为图片内容发送，CHAR 会把它当成图片读取"></textarea></label><button class="button" data-create-text-image>生成并发送</button>`,{onReady(sheet){sheet.querySelector("[data-create-text-image]").onclick=()=>{const text=sheet.querySelector("[data-text-image]").value.trim();if(!text)return showToast("请输入文字");const src=makeTextImageDataUrl(text);closeSheet();sendRich(conv,{type:"text-image",text,src,description:text},container,params)}}})}
  function openMoney(kind,conv,person,container,params){const wallet=ensureWallet(store.getState()),red=kind==="redpacket";openSheet(`<div class="money-form-head"><span>钱包余额 ¥${wallet.balance.toFixed(2)}</span><strong>${red?"发红包":"转账给"+escapeHtml(person.name)}</strong></div><label class="field"><span>金额${red?"（最高 ¥520）":""}</span><div class="money-input"><span>¥</span><input data-money type="number" min="0.01" step="0.01" ${red?'max="520"':""} inputmode="decimal" placeholder="0.00"></div></label><label class="field"><span>${red?"红包备注":"转账说明"}</span><input data-money-note maxlength="30" placeholder="${red?"大吉大利":"转账给你"}"></label><button class="button" data-send-money>确认发送</button>`,{onReady(sheet){sheet.querySelector("[data-send-money]").onclick=()=>{const amount=Math.round(Number(sheet.querySelector("[data-money]").value)*100)/100,note=sheet.querySelector("[data-money-note]").value.trim()||(red?"大吉大利":"转账给你");if(!amount||amount<=0)return showToast("请输入有效金额");if(red&&amount>520){closeSheet();openSheet(`<div class="confirm-dialog"><div class="confirm-symbol">¥</div><h3>红包限额 ¥520</h3><p>超过 ¥520 的金额只能使用转账发送。</p><div class="row"><button class="button secondary" data-sheet-close>取消</button><button class="button" data-switch-transfer>改为转账</button></div></div>`,{onReady(s){s.querySelector("[data-switch-transfer]").onclick=()=>{closeSheet();openMoney("transfer",conv,person,container,params)}}});return}const messageId=id();if(!walletDebit(store,{amount,kind,title:`发给 ${person.name} 的${red?"红包":"转账"}`,conversationId:conv.id,messageId,note})){insufficientSheet();return}store.update(s=>{s.messages[conv.id].push({id:messageId,role:"user",type:kind,text:note,amount,time:timeNow()});const target=s.conversations.find(item=>item.id===conv.id);if(target){target.preview=red?"[红包]":"[转账]";target.time=timeNow()}});closeSheet();ui.attachmentsOpen=false;activeRender(container,params);showToast(red?"红包已发送":"转账已发送")}}})}
  function openMoneyReceipt(message,person){const red=message.type==="redpacket";openSheet(`<section class="money-receipt ${message.type}"><div class="receipt-mark">${red?"礼":"¥"}</div><span>${red?"BUNNY RED PACKET":"BUNNY TRANSFER"}</span><h3>${escapeHtml(message.text||(red?"大吉大利":"转账给你"))}</h3><strong>¥${Number(message.amount||0).toFixed(2)}</strong><p>${message.role==="char"?`来自 ${escapeHtml(person.name)}`:`发给 ${escapeHtml(person.name)}`}</p><small>${escapeHtml(message.time||"")} · 已计入钱包明细</small><button class="button" data-sheet-close>完成</button></section>`)}
  function openUserStickers(conv,container,params){const state=store.getState();if(!state.stickerLibraries.user)store.update(s=>s.stickerLibraries.user=[]);const items=store.getState().stickerLibraries.user;openSheet(`<div class="sheet-title"><h3>我的表情包</h3><button class="button ghost" data-manage-user-stickers>管理</button></div><div class="sticker-library">${items.map((x,i)=>`<button class="sticker-tile" data-user-sticker="${i}"><img src="${escapeHtml(x.url)}" alt=""><span>${escapeHtml(x.description||x.name||"表情")}</span></button>`).join("")||'<p class="callout">先上传自己的表情包；它不会与 CHAR 表情库混用。</p>'}</div>`,{onReady(sheet){sheet.querySelector("[data-manage-user-stickers]").onclick=()=>openStickerImporter(conv,container,params);sheet.querySelectorAll("[data-user-sticker]").forEach(b=>b.onclick=()=>{const x=items[Number(b.dataset.userSticker)];closeSheet();sendRich(conv,{type:"sticker",text:x.name||"表情包",src:x.url,description:x.description||"用户发送的表情包"},container,params)})}})}
  function openStickerImporter(conv,container,params){openSheet(`<div class="sheet-title"><h3>导入 USER 表情包</h3><button class="button ghost" data-sheet-close>关闭</button></div><p class="callout">USER 表情库与 CHAR 表情库完全独立。</p><div class="sticker-import-actions"><label class="button secondary file-button">相册批量选择<input type="file" accept="image/*" multiple data-local-stickers hidden></label><label class="button secondary file-button">导入 DOCX<input type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" data-sticker-docx hidden></label></div><label class="field"><span>图床批量导入</span><textarea data-sticker-urls rows="7" placeholder="每行一个：表情包文字描述 https://example.com/image.png"></textarea></label><button class="button" data-import-sticker-urls>导入图床表情</button>`,{onReady(sheet){const saveRows=rows=>{if(!rows.length)return showToast("没有识别到“描述 空格 URL”格式");store.update(s=>{s.stickerLibraries.user=s.stickerLibraries.user||[];mergeStickers(s.stickerLibraries.user,rows)});closeSheet();openUserStickers(conv,container,params)};sheet.querySelector("[data-local-stickers]").onchange=async e=>{try{const files=[...e.target.files].slice(0,60),rows=await Promise.all(files.map(async file=>({name:file.name,url:await readImageOptimized(file,640,.76),description:file.name.replace(/\.[^.]+$/,"")})));openStickerDescriptions(rows,conv,container,params)}catch(error){showToast(error.message)}};sheet.querySelector("[data-sticker-docx]").onchange=async e=>{try{const text=await readDocxText(e.target.files?.[0]);saveRows(parseStickerLines(text))}catch(error){showToast(error.message)}};sheet.querySelector("[data-import-sticker-urls]").onclick=()=>saveRows(parseStickerLines(sheet.querySelector("[data-sticker-urls]").value))}})}
  function openStickerDescriptions(rows,conv,container,params){openSheet(`<div class="sheet-title"><h3>补充表情描述</h3><span>${rows.length} 张</span></div><div class="stack sticker-description-list">${rows.map((x,i)=>`<label class="field"><span>${escapeHtml(x.name)}</span><input data-sticker-desc="${i}" value="${escapeHtml(x.description)}" placeholder="例如：开心地挥手"></label>`).join("")}</div><button class="button" data-save-local-stickers>保存到 USER 表情库</button>`,{onReady(sheet){sheet.querySelector("[data-save-local-stickers]").onclick=()=>{rows.forEach((x,i)=>x.description=sheet.querySelector(`[data-sticker-desc="${i}"]`).value.trim()||"用户上传的表情包");store.update(s=>{s.stickerLibraries.user=s.stickerLibraries.user||[];s.stickerLibraries.user.push(...rows)});closeSheet();openUserStickers(conv,container,params)}}})}
  function openAttachmentMenu(conv,container,params){
    openSheet(`<div class="attachment-grid">${[["image","▧","图片"],["camera","◉","拍摄"],["voice","◖","语音"],["location","⌖","位置"],["redpacket","礼","红包"],["transfer","¥","转账"],["file","□","文件"]].map(x=>`<button data-attachment="${x[0]}"><span>${x[1]}</span>${x[2]}</button>`).join("")}</div>`,{onReady(sheet){sheet.querySelectorAll("[data-attachment]").forEach(b=>b.onclick=()=>handleAttachment(b.dataset.attachment))}});
    const add=(type,text)=>{store.update(s=>s.messages[conv.id].push({id:id(),role:"user",type,text,time:timeNow()}));closeSheet();activeRender(container,params)};
    function handleAttachment(type){
      if(["image","camera","file"].includes(type)){const input=document.createElement("input");input.type="file";input.accept=type==="file"?"*/*":"image/*";if(type==="camera")input.capture="environment";input.onchange=()=>{const file=input.files?.[0];if(file)add(type==="file"?"text":"image",`[${type==="file"?"文件":"图片"}] ${file.name}`)};input.click();return}
      if(type==="voice"){navigator.mediaDevices?.getUserMedia({audio:true}).then(stream=>{stream.getTracks().forEach(t=>t.stop());add("voice","[语音] 00:03")}).catch(()=>showToast("未获得麦克风权限"));return}
      if(type==="location"){if(!navigator.geolocation)return showToast("当前浏览器不支持定位");navigator.geolocation.getCurrentPosition(pos=>add("location",`[位置] ${pos.coords.latitude.toFixed(4)}, ${pos.coords.longitude.toFixed(4)}`),()=>showToast("未获得定位权限"));return}
      if(type==="redpacket"||type==="transfer"){const amount=prompt(`${TYPE_META[type][0]}金额`,"52.00");if(amount)add(type,`[${TYPE_META[type][0]}] ¥${amount}`)}
    }
  }

  function showRecalled(message,person){if(!message)return;openSheet(`<div class="recalled-content-sheet"><span class="eyebrow">RECALLED MESSAGE</span><h3>${message.role==="user"?"你":escapeHtml(person.name)}撤回的内容</h3><p>${escapeHtml(message.recalledText||message.text||"无文字内容")}</p><button class="button" data-sheet-close>完成</button></div>`)}
  function openPhotoViewer(messageId,conv,person,profile,container,params){const message=(store.getState().messages[conv.id]||[]).find(x=>x.id===messageId);if(!message?.src)return;openSheet(`<div class="photo-studio"><div class="photo-canvas-stage"><canvas data-photo-canvas></canvas></div><nav class="photo-tool-dock"><button data-photo-reroll aria-label="重新生成">${photoToolIcon("reroll")}</button><button data-photo-edit aria-label="涂鸦编辑">${photoToolIcon("edit")}</button><button data-photo-prompt aria-label="查看提示词">${photoToolIcon("prompt")}</button><button data-photo-save aria-label="保存图片">${photoToolIcon("save")}</button></nav><section class="photo-edit-panel" data-photo-edit-panel><div class="photo-color-row"><input type="color" value="#111111" data-brush-color><button data-clear-drawing aria-label="重置涂鸦">${photoToolIcon("undo")}</button><label aria-label="上传贴纸">${photoToolIcon("sticker")}<input hidden type="file" accept="image/*" data-photo-sticker></label><button data-send-doodle aria-label="完成并发送">${photoToolIcon("send")}</button></div><div class="photo-emoji-tray">${["❤️","🩷","✨","🎀","🐰","🌙","⭐️","🫧","🥺","😂","😽","🪽","🍓","☁️","🌷","🪷"].map(emoji=>`<button data-photo-emoji="${emoji}">${emoji}</button>`).join("")}</div></section></div>`,{onReady(sheet){const editor=bindPhotoEditor(sheet,message.src,showToast);sheet.querySelector("[data-photo-save]").onclick=async()=>{try{downloadBlob(await editor.exportBlob(),`${person.name||"bunny"}-${Date.now()}.png`)}catch(error){showToast(error.message)}};sheet.querySelector("[data-send-doodle]").onclick=async()=>{try{const blob=await editor.exportBlob(),media=await saveMediaBlob(blob);store.update(s=>{s.messages[conv.id].push({id:id(),role:"user",type:"image",src:media.src,mediaId:media.mediaId,text:"涂鸦后的照片",description:"USER 在照片上添加了涂鸦、emoji 或贴纸",time:timeNow(),createdAt:Date.now()});const target=s.conversations.find(x=>x.id===conv.id);if(target){target.preview="[图片]";target.time=timeNow()}});closeSheet();activeRender(container,params);await requestAiReply(conv,person,profile,container,params,{instruction:"USER 将这张照片重新涂鸦后发回来了。若识图已开启，请结合实际画面自然点评；不要逐项罗列画面。"})}catch(error){showToast(error.message)}};sheet.querySelector("[data-photo-reroll]").onclick=()=>{closeSheet();regeneratePhoto(message,conv,person,profile,container,params)};sheet.querySelector("[data-photo-prompt]").onclick=()=>openImagePrompt(message,conv,person,profile,container,params)}})}
  function openImagePrompt(message,conv,person,profile,container,params){openSheet(`<form class="image-prompt-editor"><div class="sheet-title"><div><small>HIDDEN IMAGE PROMPT</small><h3>图片提示词</h3></div><button type="button" class="button ghost" data-sheet-close>取消</button></div><textarea name="prompt" rows="10">${escapeHtml(message.imagePrompt||message.description||"")}</textarea><div class="sheet-split-actions"><button type="button" class="button secondary" data-save-prompt>保存</button><button class="button">保存并重新生成</button></div></form>`,{onReady(sheet){const form=sheet.querySelector("form"),save=()=>{const value=form.elements.prompt.value.trim();store.update(s=>{const target=s.messages[conv.id].find(x=>x.id===message.id);if(target)target.imagePrompt=value});message.imagePrompt=value;return value};sheet.querySelector("[data-save-prompt]").onclick=()=>{save();closeSheet();showToast("提示词已保存")};form.onsubmit=event=>{event.preventDefault();save();closeSheet();regeneratePhoto(message,conv,person,profile,container,params)}}})}
  async function regeneratePhoto(message,conv,person,profile,container,params){if(!store.getState().mediaApis?.image?.enabled)return showToast("请先在生图 API 设置中启用并测试连接");store.update(s=>{const target=s.messages[conv.id].find(x=>x.id===message.id);if(target)target.generating=true});activeRender(container,params);try{let src=await generateCharacterImage(store.getState().mediaApis.image,profile,message.imagePrompt||message.description),mediaId="";if(!src)throw Error("生图 API 没有返回图片");try{const response=await fetch(src);if(response.ok){const media=await saveMediaBlob(await response.blob());src=media.src;mediaId=media.mediaId}}catch{}store.update(s=>{const target=s.messages[conv.id].find(x=>x.id===message.id);if(target)Object.assign(target,{src,mediaId,type:"image",generating:false})});showToast("图片已重新生成")}catch(error){store.update(s=>{const target=s.messages[conv.id].find(x=>x.id===message.id);if(target)target.generating=false});showToast(error.message)}activeRender(container,params)}
  async function playVoiceMessage(message,profile,button){if(!message||button.classList.contains("playing"))return;const total=Math.max(1,Number(message.duration)||estimateVoiceDuration(message.text)),clock=button.querySelector("[data-voice-clock]");let timer=null,start=Date.now();const update=value=>{const elapsed=Math.min(total,Math.max(0,value));button.style.setProperty("--voice-progress",`${elapsed/total*100}%`);if(clock)clock.textContent=formatDuration(elapsed)};button.classList.add("playing");update(0);try{if(!message.audioUrl&&message.role==="char")await cacheVoiceMessage(message,profile);if(message.audioUrl){const audio=new Audio(message.audioUrl);audio.ontimeupdate=()=>update(audio.currentTime);await audio.play();await new Promise((resolve,reject)=>{audio.onended=resolve;audio.onerror=()=>reject(Error("语音文件无法播放"))})}else{timer=setInterval(()=>update((Date.now()-start)/1000),120);const config=message.role==="user"?{provider:"browser",lang:"zh-CN",speed:1,pitch:1,volume:1}:resolveTtsConfig(store.getState(),profile);await Promise.all([synthesizeSpeech(config,message.text,{tone:message.tone||""}),new Promise(resolve=>setTimeout(resolve,total*1000))])}}catch(error){showToast(error.message)}finally{clearInterval(timer);update(total);setTimeout(()=>{button.classList.remove("playing");update(0)},260)}}
  async function cacheVoiceMessage(message,profile){if(message.audioUrl)return message.audioUrl;const config=resolveTtsConfig(store.getState(),profile),blob=await synthesizeSpeech(config,message.text,{tone:message.tone||"",play:false});if(!blob)return"";const media=await saveMediaBlob(blob);store.update(s=>{for(const list of Object.values(s.messages||{})){const target=list.find(x=>x.id===message.id);if(target){target.audioMediaId=media.mediaId;target.audioUrl=media.src;break}}});message.audioMediaId=media.mediaId;message.audioUrl=media.src;return media.src}

  activeRender=conversation;
  return conversation;
}

function messageView(message,continuation,person,user,profile,appearance,messages,ui,groupEnd=true){
  if(message.role==="system")return `<article class="system-message-v3">${escapeHtml(message.text)}</article>`;
  if(message.recalled){const who=message.role==="user"?"你":escapeHtml(person.name),fresh=Date.now()-Number(message.recalledAt||0)<1600;return`<article class="recall-notice ${message.role} ${fresh?"recall-animate":""}"><button data-recalled-message="${message.id}">${who}撤回了一条信息</button></article>`}
  const isUser=message.role==="user",owner=isUser?user:person,avatarProfile=isUser?{avatarUrl:user.avatarUrl||""}:profile,hide=isUser&&appearance.hideUserAvatar;
  const quote=message.replyTo?messages.find(x=>x.id===message.replyTo):null;
  const select=ui.selectMode?`<button class="select-circle ${ui.selected.has(message.id)?"checked":""}" data-select-message="${message.id}" aria-label="选择消息"></button>`:"";
  const avatar=hide?"":`<div class="message-avatar-v3 ${continuation?"invisible":""}" ${isUser?"":"data-pat-avatar"}>${initialsAvatar(owner,avatarProfile)}</div>`;
  const special=message.type&&message.type!=="text"?"special-message":"",arriving=message.role==="char"&&message.arrivedWithPause&&Date.now()-Number(message.createdAt||0)<1800?"arriving":"";
  return `<article class="message ${message.role} ${continuation?"continuation":""} ${special} ${arriving} ${groupEnd?"group-end":""} ${message.reaction?"has-reaction":""}" data-message-id="${message.id}">${select}${avatar}<div class="message-body-v3">${!isUser&&!continuation?`<span class="message-sender-v3">${escapeHtml(profile.remark||person.name)}</span>`:""}<div class="bubble-v3">${quote?`<div class="inline-quote"><strong>${quote.role==="user"?escapeHtml(user.name):escapeHtml(person.name)}</strong><span>${escapeHtml(quote.text)}</span></div>`:""}${messageContent(message)}</div>${message.effect==='echo'?`<button type="button" class="echo-replay" data-echo-replay aria-label="重播回声效果">回声 · ↻</button>`:''}${message.translation&&message.type!=="voice"?`<div class="message-translation">${escapeHtml(message.translation)}</div>`:""}${message.reaction?`<button class="message-reaction-v3">${escapeHtml(message.reaction)}</button>`:""}<time>${message.time}${message.edited?" · 已编辑":""}${message.readAt||message.charReadAt?'<em class="message-read">已读</em>':""}</time></div></article>`;
}
function messageContent(message){
  if(message.type==="chat-record")return`<div class="chat-record-card"><strong>💬 ${escapeHtml(message.text)}</strong><span>${message.bundle?.length||0} 条消息</span><small>${(message.bundle||[]).slice(0,3).map(x=>escapeHtml(x.text)).join(" · ")}</small></div>`;
  if(message.type==="image"&&message.generating)return`<div class="image-generation-card"><span>${bunnyStamp()}</span><div><i></i><i></i><i></i></div><small>正在显影</small></div>`;
  if(message.type==="image"){const description=message.description||message.text||"一张照片";return`<button class="real-photo-message" data-real-photo="${message.id}" type="button" aria-label="查看真实照片"><img src="${escapeHtml(message.src||"")}" alt="${escapeHtml(description)}" loading="lazy"></button>`}
  if(message.type==="text-image"){const description=message.description||message.text||"图片内容";return`<button class="polaroid-message text-polaroid" data-polaroid type="button" aria-label="翻转查看图片内容"><span class="polaroid-inner"><span class="polaroid-front word-photo-front"><span class="word-photo-logo">${bunnyStamp()}</span><span class="word-photo-turn">↻</span></span><span class="polaroid-back word-photo-back"><i>${bunnyStamp()}</i><strong>${escapeHtml(description)}</strong><span>轻点翻回正面</span></span></span></button>`}
  if(message.type==="redpacket"||message.type==="transfer")return`<article class="money-card ${message.type}"><header><span class="money-symbol">${message.type==="redpacket"?"礼":"¥"}</span><div><strong>${escapeHtml(message.text|| (message.type==="redpacket"?"大吉大利":"转账给你"))}</strong><small>${message.role==="char"?"来自 CHAR":"发给 CHAR"}</small></div></header><div class="amount">¥${Number(message.amount||0).toFixed(2)}</div><footer>${message.type==="redpacket"?"Bunny 红包":"Bunny 转账"}</footer></article>`;
  if(message.type==="sticker")return`<div class="sticker-message"><img src="${escapeHtml(message.src||"")}" alt="${escapeHtml(message.text||"表情包")}"></div>`;
  if(message.type==="voice"){const transcript=message.transcript||message.text||"语音消息",translation=message.translation?`（${message.translation}）`:"";return`<div class="voice-message-wrap"><button class="voice-play-hit" data-play-voice="${message.id}" type="button" aria-label="播放语音"></button><button class="voice-message" data-voice-transcript-toggle type="button" aria-label="展开完整语音文字"><span class="voice-progress"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></span><strong data-voice-clock>${formatDuration(message.duration||estimateVoiceDuration(message.text))}</strong></button><div class="voice-transcript"><span>${escapeHtml(transcript)}</span>${translation?`<strong>${escapeHtml(translation)}</strong>`:""}</div></div>`}
  if(message.type==="location")return`<div class="location-message"><strong>${escapeHtml(message.text||"共享位置")}</strong><div class="location-map"></div></div>`;
  if(message.type==="file")return`<div class="file-message"><span>DOC</span><strong>${escapeHtml(message.text||"文件")}</strong></div>`;
  if(message.type==="voice-call"||message.type==="video-call")return`<div class="call-summary-message"><span>${message.type==="video-call"?"▣":"☎"}</span><strong>${message.type==="video-call"?"视频通话":"语音通话"} <time>${formatDuration(message.duration||0)}</time></strong></div>`;
  if(message.type&&message.type!=="text")return`<div class="typed-message"><span>${TYPE_META[message.type]?.[1]||"□"}</span><div><small>${TYPE_META[message.type]?.[0]||"消息"}</small><strong>${escapeHtml(message.text)}</strong></div></div>`;
  return escapeHtml(message.text)
}
function composerView(quote,open,sending,error,echoNext=false){const actions=[["camera","camera","拍摄"],["album","image","照片"],["voice","mic","语音"],["text-image","text","文字图"],["echo","echo","回声"],["inner-voice","thought","心声"],["redpacket","gift","红包"],["transfer","money","转账"],["sticker","smile","表情包"],["reroll","reroll","重 roll"],["call","phone","语音通话"],["video","video","视频通话"]];return `<div class="composer-shell-v3 ${open?"attachments-open":""}">${error?`<div class="composer-error"><span>${escapeHtml(error)}</span><button type="button" data-open-api>去配置模型</button></div>`:""}${quote?`<div class="composer-quote"><div><strong>回复</strong><span>${escapeHtml(quote.text)}</span></div><button data-cancel-quote aria-label="取消引用">×</button></div>`:""}<div class="folded-attachments"><div>${actions.map(x=>`<button type="button" data-fold-action="${x[0]}" ${x[0]==="echo"?`aria-pressed="${echoNext}"`:""}>${foldIcon(x[1])}<span>${x[2]}</span></button>`).join("")}</div></div><form class="composer-v3" data-composer><button type="button" data-plus aria-label="展开更多功能">${open?"×":"＋"}</button><textarea name="message" rows="1" placeholder="${echoNext?"回声效果已开启 · 输入文字":"发送消息…"}" aria-label="消息"></textarea><button type="button" class="send-icon" data-send-only aria-label="仅发送">${sendIcon()}</button><button type="button" class="ai-send-v3 ${sending?"sending":""}" data-send-ai aria-label="让 AI 回复当前聊天" ${sending?"disabled":""}>${sending?'<i></i>':sparkIcon()}</button></form></div>`}
function selectionBar(count){return`<nav class="selection-toolbar"><button data-selection-delete ${count?"":"disabled"}>⌫<span>删除</span></button><strong>${count?`已选择 ${count} 条`:"选择消息"}</strong><button data-selection-forward ${count?"":"disabled"}>↗<span>转发</span></button></nav>`}
function typingView(person,profile){return`<article class="message char ai-typing-message"><div class="message-avatar-v3">${initialsAvatar(person,profile)}</div><div class="message-body-v3"><div class="bubble-v3 ai-typing-bubble"><i></i><i></i><i></i></div><time>正在回复</time></div></article>`}
function backgroundStyle(url,opacity=1){const veil=1-Math.max(0,Math.min(1,opacity));return url?`background-image:linear-gradient(rgba(246,246,244,${veil}),rgba(246,246,244,${veil})),url('${escapeHtml(url)}');background-size:cover;background-position:center`:""}
function bindLongPress(element,callback){let timer,x=0,y=0;element.onpointerdown=e=>{x=e.clientX;y=e.clientY;timer=setTimeout(()=>{navigator.vibrate?.(12);callback()},460)};element.onpointermove=e=>{if(Math.abs(e.clientX-x)>8||Math.abs(e.clientY-y)>8)clearTimeout(timer)};element.onpointerup=element.onpointercancel=()=>clearTimeout(timer)}
function bindDoubleTap(element,callback){let previous=0;element.addEventListener("pointerup",event=>{const now=Date.now();if(now-previous<340){event.preventDefault();element.__bunnyDoubleTappedUntil=now+420;previous=0;callback()}else previous=now})}
function menuIcon(type){const d={quote:'M7 11h11a5 5 0 0 1 5 5v3M7 11l4-4m-4 4 4 4',edit:'M5 21l4-.8L21 6.2 17.8 3 4 16.2 5 21Z',favorite:'m13 4 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.9-5.4 2.9 1-6.1-4.4-4.3 6.1-.9L13 4Z',multi:'M8 7h14v14H8zM3 3h14v4M3 3v14h5',recall:'M8 8 4 12l4 4M5 12h10a6 6 0 0 1 6 6v2',delete:'M6 8h14M10 8V5h6v3m-8 0 1 14h8l1-14'}[type]||"M5 13h16";return`<svg viewBox="0 0 26 26" aria-hidden="true"><path d="${d}"/></svg>`}
function foldIcon(type){const d={thought:'<path d="M6 17c-2.2-1.2-3.2-3.1-2.7-5.1.5-1.7 1.7-2.8 3.5-3.2.4-2.5 2.3-4.1 4.6-4.1 1.9 0 3.4 1 4.2 2.5 2.4-.2 4.4 1.6 4.4 4 1.6.8 2.4 2.1 2.1 3.8-.3 2.1-2 3.3-4.6 3.3H8"/><circle cx="6" cy="20" r="1"/><circle cx="3" cy="22" r=".5"/>',echo:'<path d="M4 9a8 8 0 0 1 16 0M7 12a5 5 0 0 1 10 0M10 15a2 2 0 0 1 4 0"/><circle cx="12" cy="19" r="1"/>',camera:'<path d="M4 8h4l2-3h4l2 3h4v11H4z"/><circle cx="12" cy="13" r="3"/>',image:'<rect x="3" y="5" width="18" height="15" rx="2"/><path d="m5 18 5-5 3 3 3-3 4 4"/>',mic:'<rect x="9" y="3" width="6" height="12" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3M8 21h8"/>',text:'<path d="M5 6h14M12 6v13M8 19h8"/>',gift:'<rect x="4" y="9" width="16" height="11" rx="2"/><path d="M12 9v11M3 9h18v-3H3zM12 6c-4 0-5-4-2-4 2 0 2 4 2 4Zm0 0c4 0 5-4 2-4-2 0-2 4-2 4Z"/>',money:'<circle cx="12" cy="12" r="9"/><path d="M8 9h8m-4-3v12m-4-3h8"/>',smile:'<circle cx="12" cy="12" r="9"/><circle cx="9" cy="10" r="1"/><circle cx="15" cy="10" r="1"/><path d="M8 15c2 2 6 2 8 0"/>',reroll:'<path d="M19 8V3l-2 2a8 8 0 1 0 2.2 8"/><path d="M19 3h-5"/>',phone:'<path d="M7 4 4 6c1 8 6 13 14 14l2-3-5-3-2 2c-2-1-4-3-5-5l2-2-3-5Z"/>',video:'<rect x="3" y="6" width="13" height="12" rx="2"/><path d="m16 10 5-3v10l-5-3"/>'}[type]||"";return`<svg viewBox="0 0 24 24">${d}</svg>`}
export function playEcho(message){
  if(!message||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  const screen=message.closest('.chat-layout-v3'),bubble=message.querySelector('.bubble-v3');if(!screen||!bubble)return;
  screen.querySelector('.echo-scene')?.remove();
  const scene=document.createElement('div');scene.className='echo-scene';scene.setAttribute('aria-hidden','true');screen.append(scene);
  const base=bubble.getBoundingClientRect(),surface=screen.getBoundingClientRect(),w=surface.width,h=surface.height;
  const x=base.left-surface.left,y=base.top-surface.top,words=bubble.textContent.trim().slice(0,110);
  const sent=message.classList.contains('user'),style=getComputedStyle(bubble);
  const sourceFill=bubble.querySelector('.bubble-outline path');
  scene.style.setProperty('--echo-accent',sourceFill?getComputedStyle(sourceFill).fill:style.backgroundColor);
  scene.style.setProperty('--echo-font',style.fontFamily);
  const ghostWidth=base.width;
  let seed=[...String(message.dataset.messageId||words)].reduce((n,char)=>((n*33)^char.charCodeAt(0))>>>0,0x9e3779b9);
  const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};
  const anchors=[[.08,.08],[.52,.11],[.86,.2],[.23,.31],[.7,.39],[.14,.53],[.8,.58],[.43,.73],[.88,.86],[.18,.9]];
  const sizes=[.24,.34,.47,.62,.82,1.08,1.42,1.78,2.18];
  for(let i=0;i<38;i++){
    const ghost=document.createElement('article');ghost.className=`echo-sprite message ${sent?'user':'char'} group-end`;
    const body=document.createElement('div');body.className='message-body-v3';
    const copy=bubble.cloneNode(true);copy.removeAttribute('id');
    for(const key of ['color','border-radius','font-family','font-size','font-weight','letter-spacing','line-height','padding','box-shadow','text-shadow'])copy.style.setProperty(key,style.getPropertyValue(key));
    const copyPath=copy.querySelector('.bubble-outline path');if(sourceFill&&copyPath)copyPath.style.fill=getComputedStyle(sourceFill).fill;
    body.append(copy);ghost.append(body);
    const anchor=anchors[i%anchors.length],scale=sizes[(i*5+Math.floor(random()*3))%sizes.length];
    const desiredX=(anchor[0]+(random()-.5)*.35)*w-ghostWidth*scale/2;
    const desiredY=(anchor[1]+(random()-.5)*.19)*h-base.height*scale/2;
    const targetX=Math.max(-ghostWidth*scale*.58,Math.min(w-ghostWidth*scale*.42,desiredX))-x;
    const targetY=Math.max(-base.height*scale*.58,Math.min(h-base.height*scale*.42,desiredY))-y;
    ghost.style.setProperty('--echo-x',`${x}px`);ghost.style.setProperty('--echo-y',`${y}px`);
    ghost.style.setProperty('--echo-w',`${ghostWidth}px`);ghost.style.setProperty('--echo-dx',`${targetX}px`);
    ghost.style.setProperty('--echo-dy',`${targetY}px`);ghost.style.setProperty('--echo-scale',scale);
    ghost.style.setProperty('--echo-delay',`${Math.floor(random()*310)}ms`);ghost.style.zIndex=String(Math.round(scale*10));scene.append(ghost);
  }
  const letters=globalThis.Intl?.Segmenter?[...new Intl.Segmenter(undefined,{granularity:'grapheme'}).segment(words)].map(x=>x.segment):Array.from(words);
  letters.filter(x=>x.trim()).slice(0,12).forEach((letter,i)=>{
    const glyph=document.createElement('span');glyph.className='echo-glyph';glyph.textContent=letter;
    glyph.style.setProperty('--echo-x',`${x+base.width/2}px`);glyph.style.setProperty('--echo-y',`${y+base.height/2}px`);
    glyph.style.setProperty('--echo-dx',`${((i*73)%97)/97*w-x-base.width/2}px`);
    glyph.style.setProperty('--echo-dy',`${((i*41+19)%89)/89*h-y-base.height/2}px`);
    glyph.style.setProperty('--echo-delay',`${i*26}ms`);glyph.style.setProperty('--echo-turn',`${(i%2?-1:1)*(16+i%5*9)}deg`);scene.append(glyph);
  });
  window.setTimeout(()=>scene.remove(),3200);
}
function bunnyStamp(){return'<svg viewBox="0 0 64 64"><path d="M24 27C15 13 18 5 23 5c5 0 7 12 8 18 2-8 5-18 10-17 6 1 4 13-2 22 6 3 10 9 10 16 0 10-8 15-17 15S15 54 15 44c0-8 3-13 9-17Z"/><circle cx="26" cy="42" r="2"/><circle cx="39" cy="42" r="2"/><path d="M29 49c2 2 5 2 7 0"/><path d="M11 35c4 1 7 3 9 6M53 35c-4 1-7 3-9 6"/></svg>'}
function sendIcon(){return'<svg viewBox="0 0 24 24"><path d="m5 12 14-7-4 14-3-5-7-2Z"/><path d="m12 14 7-9"/></svg>'}
function sparkIcon(){return'<svg viewBox="0 0 24 24"><path d="M12 3c.7 4.3 2.7 6.3 7 7-4.3.7-6.3 2.7-7 7-.7-4.3-2.7-6.3-7-7 4.3-.7 6.3-2.7 7-7Z"/><path d="M18 16c.3 1.7 1.3 2.7 3 3-1.7.3-2.7 1.3-3 3-.3-1.7-1.3-2.7-3-3 1.7-.3 2.7-1.3 3-3Z"/></svg>'}
function micIcon(){return foldIcon("mic")}
function callIcon(video){return video?foldIcon("video"):foldIcon("phone")}
function clockIcon(){return'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/></svg>'}
function photoToolIcon(type){const d={reroll:'M19 8V3l-2 2a8 8 0 1 0 2.2 8M19 3h-5',edit:'M4 20l4-.8L20 5l-3-3L3 16l1 4Z',prompt:'M5 6h14M5 11h14M5 16h9',save:'M5 4h12l2 2v14H5V4Zm3 0v6h8V4m-8 16v-6h8v6',undo:'M9 7 4 12l5 5M5 12h8a6 6 0 0 1 6 6',sticker:'M5 4h14v10l-6 6H5V4Zm8 16v-6h6',send:'m4 12 16-8-5 16-3-6-8-2Zm8 2 8-10'}[type]||'';return`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${d}"/></svg>`}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function readAsDataUrl(file){return new Promise((resolve,reject)=>{if(file.size>5*1024*1024)return reject(Error("请选择 5MB 以内文件"));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error("文件读取失败"));r.readAsDataURL(file)})}
function readBlobAsDataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error("录音保存失败"));r.readAsDataURL(blob)})}
async function readImageOptimized(file,max=1280,quality=.82){if(!file.type.startsWith("image/"))throw Error("请选择图片文件");if(file.size>18*1024*1024)throw Error("请选择 18MB 以内图片");const src=await readAsDataUrl(new File([file],file.name,{type:file.type})).catch(async()=>{const r=new FileReader();return await new Promise((resolve,reject)=>{r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})});const image=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error("图片无法读取"));img.src=src});const scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL("image/webp",quality)}
async function readImageBlobOptimized(file,max=1600,quality=.84){if(!file.type.startsWith("image/"))throw Error(`${file.name} 不是图片`);if(file.size>24*1024*1024)throw Error(`${file.name} 超过 24MB`);const src=URL.createObjectURL(file);try{const image=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error(`${file.name} 无法读取`));img.src=src});const scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);return await new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(Error("照片压缩失败")),"image/webp",quality))}finally{URL.revokeObjectURL(src)}}
function wrapCanvas(ctx,text,x,y,maxWidth,lineHeight){const chars=[...text];let line="",lines=[];for(const char of chars){if(ctx.measureText(line+char).width>maxWidth){lines.push(line);line=char}else line+=char}if(line)lines.push(line);const start=y-(lines.length-1)*lineHeight/2;lines.slice(0,6).forEach((value,i)=>ctx.fillText(value,x,start+i*lineHeight))}
function makeTextImageDataUrl(text){const canvas=document.createElement("canvas");canvas.width=canvas.height=900;const ctx=canvas.getContext("2d"),glass=document.querySelector("#phone-root")?.dataset.theme==="glass",grad=ctx.createLinearGradient(0,0,900,900);grad.addColorStop(0,glass?"#edf5f7":"#fafaf6");grad.addColorStop(1,glass?"#b8c9d0":"#dfded8");ctx.fillStyle=grad;ctx.fillRect(0,0,900,900);ctx.strokeStyle="rgba(17,17,17,.11)";ctx.lineWidth=2;ctx.strokeRect(48,48,804,804);ctx.save();ctx.translate(450,430);ctx.strokeStyle="rgba(17,17,17,.075)";ctx.lineWidth=14;ctx.lineCap="round";ctx.beginPath();ctx.ellipse(-85,-185,55,145,-.2,0,Math.PI*2);ctx.ellipse(85,-185,55,145,.2,0,Math.PI*2);ctx.ellipse(0,35,230,250,0,0,Math.PI*2);ctx.stroke();ctx.restore();ctx.fillStyle="rgba(17,17,17,.38)";ctx.font='700 21px -apple-system,"PingFang SC",sans-serif';ctx.textAlign="center";ctx.fillText("BUNNY BUNNY",450,805);return canvas.toDataURL("image/jpeg",.9)}
function wrapCanvasFull(ctx,text,x,y,maxWidth,lineHeight,maxLines){const paragraphs=String(text).split(/\n/),lines=[];for(const paragraph of paragraphs){let line="";for(const char of [...paragraph]){if(ctx.measureText(line+char).width>maxWidth&&line){lines.push(line);line=char}else line+=char}lines.push(line||" ")}const shown=lines.slice(0,maxLines);if(lines.length>maxLines)shown[maxLines-1]=shown[maxLines-1].slice(0,-1)+"…";const start=y-(shown.length-1)*lineHeight/2;shown.forEach((value,i)=>ctx.fillText(value,x,start+i*lineHeight))}
async function generateCharacterImage(config,profile,prompt){if(!config?.enabled||!profile?.imageGenerationEnabled)return"";return generateImage(config,{prompt,negativePrompt:profile.imageNegativePrompt||"",referenceImage:profile.imageReferenceFace||""})}
function parseStickerLines(text){const normalized=String(text||"").replace(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/gi,"$2");return normalized.split(/(?:\r?\n|[|,，])+/).map(row=>{const value=row.trim(),match=value.match(/^(.*?)\s*(?:[:：]\s*|\s+)(https?:\/\/\S+)\s*$/i);if(!match)return null;const description=match[1].replace(/^[-—]+|[-—]+$/g,"").trim()||"表情包",url=match[2].replace(/^\[|\]$/g,"");return{name:description.slice(0,28),description,url,tags:[description]}}).filter(Boolean)}
function mergeStickers(target,rows){for(const row of rows)if(!target.some(x=>x.url===row.url))target.push(row)}
async function readDocxText(file){if(!file)throw Error("请选择 DOCX 文件");const bytes=new Uint8Array(await file.arrayBuffer()),view=new DataView(bytes.buffer);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(view.getUint32(i,true)===0x06054b50){eocd=i;break}if(eocd<0)throw Error("DOCX 文件结构无效");const entries=view.getUint16(eocd+10,true),central=view.getUint32(eocd+16,true),decoder=new TextDecoder();let offset=central,target=null;for(let i=0;i<entries;i++){if(view.getUint32(offset,true)!==0x02014b50)break;const method=view.getUint16(offset+10,true),size=view.getUint32(offset+20,true),nameLen=view.getUint16(offset+28,true),extraLen=view.getUint16(offset+30,true),commentLen=view.getUint16(offset+32,true),local=view.getUint32(offset+42,true),name=decoder.decode(bytes.slice(offset+46,offset+46+nameLen));if(name==="word/document.xml")target={method,size,local};offset+=46+nameLen+extraLen+commentLen}if(!target)throw Error("DOCX 中没有可读取的正文");const nameLen=view.getUint16(target.local+26,true),extraLen=view.getUint16(target.local+28,true),start=target.local+30+nameLen+extraLen,compressed=bytes.slice(start,start+target.size);let raw=compressed;if(target.method===8){if(typeof DecompressionStream==="undefined")throw Error("当前浏览器不支持直接解析 DOCX");raw=new Uint8Array(await new Response(new Blob([compressed]).stream().pipeThrough(new DecompressionStream("deflate-raw"))).arrayBuffer())}else if(target.method!==0)throw Error("不支持该 DOCX 压缩格式");const xml=new DOMParser().parseFromString(decoder.decode(raw),"application/xml");return[...xml.getElementsByTagNameNS("*","p")].map(p=>[...p.getElementsByTagNameNS("*","t")].map(x=>x.textContent).join("")).join("\n")}
function timeNow(){return new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit",hour12:false})}
function id(){return crypto.randomUUID?.()||`m-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms))}

async function enforceChatFormat(raw,model,profile){
  if(validChatEnvelope(raw,profile))return parseChatResponse(raw);
  const repair=`把下面的模型输出修复成聊天协议 JSON。不得改写人物原意，不得添加解释或 Markdown。顶层必须只有 messages 与 actions 两个数组；messages 每项必须有字符串 text、translation、tone；actions 每项必须有 type，并保持原操作。${profile.translationEnabled?"外语 text/voice 必须填写简体中文 translation；中文原文 translation 为空。":"所有 translation 必须是空字符串。"}\n严格输出：{\"messages\":[{\"text\":\"原文\",\"translation\":\"译文或空字符串\",\"tone\":\"语气或空字符串\"}],\"actions\":[]}\n待修复内容：\n${String(raw||"").slice(0,12000)}`;
  const fixed=await sendToModel(model,[{role:"user",text:repair}],"");
  if(!validChatEnvelope(fixed,profile))throw Error("AI 回复格式连续两次不符合聊天协议，已停止写入，避免出现错误气泡")
  return parseChatResponse(fixed);
}
function validChatEnvelope(raw,profile){try{const source=String(raw||"").trim(),types=new Set(["voice","reaction","pat","defer","recall","redpacket","transfer","sticker","steal_sticker","image","avatar","signature"]);if(!source.startsWith("{")||!source.endsWith("}"))return false;const data=JSON.parse(source);if(!Array.isArray(data.messages)||!Array.isArray(data.actions)||(!data.messages.length&&!data.actions.length))return false;if(!data.messages.every(x=>x&&typeof x.text==="string"&&typeof x.translation==="string"&&typeof x.tone==="string"))return false;if(!data.actions.every(x=>x&&types.has(String(x.type||x.kind).toLowerCase())))return false;if(profile.translationEnabled){for(const row of [...data.messages,...data.actions.filter(x=>String(x.type||x.kind).toLowerCase()==="voice")])if(looksForeign(row.text)&&!String(row.translation||"").trim())return false}else if([...data.messages,...data.actions].some(x=>String(x.translation||"").trim()))return false;return true}catch{return false}}
function looksForeign(value){const text=String(value||"").trim(),cjk=(text.match(/[\u3400-\u9fff]/g)||[]).length;if(/[\u3040-\u30ff\uac00-\ud7af\u0400-\u04ff\u0600-\u06ff]/.test(text))return true;return /[A-Za-z]{2}/.test(text)&&cjk<2}
function formatDuration(value){const seconds=Math.max(0,Math.round(Number(value)||0));return`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`}
function estimateVoiceDuration(text){return Math.max(2,Math.min(60,Math.round(String(text||"").length/4.2)))}
function findActionTarget(messages,target,role){if(target&&!/^last_/.test(target)){const exact=messages.find(x=>x.id===target&&x.role===role);if(exact)return exact}return[...messages].reverse().find(x=>x.role===role&&!x.recalled)}
function rollbackWalletMessages(state,messageIds){if(!messageIds.size||!state.wallet?.ledger)return;const removed=state.wallet.ledger.filter(row=>messageIds.has(row.messageId));for(const row of removed)state.wallet.balance=Math.round((Number(state.wallet.balance)+(row.direction==="income"?-Number(row.amount):Number(row.amount)))*100)/100;state.wallet.ledger=state.wallet.ledger.filter(row=>!messageIds.has(row.messageId))}
function refreshConversationPreview(state,conversationId){const conversation=state.conversations.find(x=>x.id===conversationId),last=[...(state.messages[conversationId]||[])].reverse().find(x=>!x.recalled);if(!conversation)return;conversation.preview=last?previewFor(last):"暂无消息";conversation.time=last?.time||""}
function previewFor(message={}){return({voice:"[语音]",redpacket:"[红包]",transfer:"[转账]",image:"[图片]","text-image":"[图片]",sticker:"[表情包]",location:"[位置]",file:"[文件]","voice-call":"[语音通话]","video-call":"[视频通话]","chat-record":"[聊天记录]"})[message.type]||message.text||"新消息"}
function readableAiError(error){const text=String(error?.message||error||"AI 请求失败");if(/Failed to fetch|NetworkError|Load failed/i.test(text))return"AI 请求未送达：请检查 Base URL、网络或接口是否允许网页跨域访问";return text}
function unlockCallAudio(){prepareCallAudio()}
