import assert from 'node:assert/strict';
import { seedState } from './core/store.js';
import { ensureForum,forumAlias,forumActors,forumGroups,forumCreateGroup,forumJoinGroup,forumLeaveGroup,forumIsMember,forumEditGroup,forumDeleteGroup,forumPost,forumReply,forumVisible,forumToggle,forumToggleReply } from './forum-model.js';

const state=structuredClone(seedState);
ensureForum(state);
const seoul=forumActors(state,'world-seoul').map(p=>p.id);
assert(seoul.includes('char-jun'));
assert(!seoul.includes('npc-soo'));
const post=forumPost(state,{authorId:'char-jun',worldId:'world-seoul',text:'雨停了，唱片店门口还有人在等。'});
assert.equal(forumVisible(state,'world-seoul').length,1);
assert.equal(forumVisible(state,'world-tokyo').length,0);
const timeline=forumPost(state,{authorId:'user-me',worldId:'world-seoul',board:'timeline',anonymous:false,text:'刚刚路过唱片店，门口的雨停了。'});
assert.equal(timeline.board,'timeline');
assert.equal(timeline.anonymous,false);
assert.throws(()=>forumPost(state,{authorId:'npc-soo',worldId:'world-seoul',text:'跨世界内容'}),/世界不匹配/);
assert.equal(forumAlias('char-jun','world-seoul'),forumAlias('char-jun','world-seoul'));
forumReply(state,{postId:post.id,authorId:'user-me',text:'我就在附近。'});
assert.throws(()=>forumReply(state,{postId:post.id,authorId:'npc-soo',text:'我也在'}),/世界不匹配/);
forumToggle(state,post.id,'likes','user-me');
assert.deepEqual(state.forum.posts[0].likes,['user-me']);
forumToggle(state,post.id,'likes','user-me');
assert.deepEqual(state.forum.posts[0].likes,[]);
const groups=forumGroups(state,'world-seoul');
assert.equal(groups.length,6);
assert.equal(forumGroups(state,'world-tokyo').length,6);
assert.notEqual(groups[0].id,forumGroups(state,'world-tokyo')[0].id);
assert.throws(()=>forumPost(state,{authorId:'user-me',worldId:'world-seoul',groupId:groups[0].id,text:'先发帖再入组'}),/加入小组/);
forumJoinGroup(state,groups[0].id,'user-me');
assert(forumIsMember(state,groups[0].id,'user-me'));
const groupPost=forumPost(state,{authorId:'user-me',worldId:'world-seoul',groupId:groups[0].id,text:'有人也喜欢下雨后的街道吗？'});
assert.equal(groupPost.board,'group');
assert.throws(()=>forumPost(state,{authorId:'user-me',worldId:'world-tokyo',groupId:groups[0].id,text:'跨世界小组'}),/世界不匹配/);
const reply=forumReply(state,{postId:groupPost.id,authorId:'char-jun',text:'雨后唱片店外的那条路很安静。'});
const nested=forumReply(state,{postId:groupPost.id,authorId:'user-me',parentId:reply.id,text:'那我下次去走走。'});
assert.equal(nested.parentId,reply.id);
assert.throws(()=>forumReply(state,{postId:post.id,authorId:'user-me',parentId:reply.id,text:'串到另一条帖子'}),/不存在/);
forumToggleReply(state,reply.id,'user-me');assert.deepEqual(reply.likes,['user-me']);
const quoted=forumPost(state,{authorId:'user-me',worldId:'world-seoul',text:'这句我记住了。',quotePostId:groupPost.id});
assert.equal(quoted.quotePostId,groupPost.id);
forumLeaveGroup(state,groups[0].id,'user-me');assert(!forumIsMember(state,groups[0].id,'user-me'));
const custom=forumCreateGroup(state,{worldId:'world-seoul',ownerId:'user-me',name:'周三电影夜',category:'书影音',description:'每周看一部电影'});
assert(forumIsMember(state,custom.id,'user-me'));
assert.throws(()=>forumLeaveGroup(state,custom.id,'user-me'),/组长/);
forumEditGroup(state,custom.id,'user-me',{name:'电影夜航',category:'书影音',description:'每周一场',prompt:'最近喜欢的一幕'});
assert.equal(custom.name,'电影夜航');
const customPost=forumPost(state,{authorId:'user-me',worldId:'world-seoul',groupId:custom.id,text:'上周看了一场午夜电影。',challenge:true});
assert(customPost.challenge);
forumDeleteGroup(state,custom.id,'user-me');
assert.equal(customPost.board,'topic');
assert.equal(customPost.groupId,'');
assert(forumVisible(state,'world-seoul').includes(customPost));
console.log('Forum: worlds, group membership, nested replies, quotes, and reactions passed.');
