import { escapeHtml as esc,openSheet,closeSheet,showToast } from './core/ui.js';
import { ensureForum,forumAlias,forumActors,forumVisible,forumGroups,forumCreateGroup,forumJoinGroup,forumLeaveGroup,forumIsMember,forumEditGroup,forumDeleteGroup,forumPost,forumReply,forumToggle,forumToggleReply } from './forum-model.js';
import { refreshForum,replyToForumPost } from './forum-engine.js';
import { tikPost,ensureTikTok } from './tiktok-model.js';
import { xPost,ensureX } from './x-model.js';
import { postGroupMessage } from './group-model.js';
import { friendWorldGroup } from './account-system.js';

const date=t=>new Date(t).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
const short=(value,n=180)=>String(value||'').length>n?`${String(value).slice(0,n)}…`:String(value||'');
export function createForumRenderer({store,navigate}){
  let view='feed',tab='all',query='',limit=12,sort='new',groupId='',postId='',refreshing=false,containerRef=null,replyTarget='';
  const state=()=>store.getState(),db=()=>ensureForum(state()),me=()=>state().currentUserId,world=()=>state().currentWorldId||state().worlds?.[0]?.id;
  const groups=()=>forumGroups(state(),world());
  const post=id=>db().posts.find(p=>p.id===id&&!p.deleted&&p.worldId===world());
  const group=id=>groups().find(g=>g.id===id);
  function actor(id){return state().people.find(p=>p.id===id)||{name:'已注销用户',initials:'?'}}
  function socialGroup(s,kind,worldId){const app=kind==='x'?ensureX(s):ensureTikTok(s);if(s.chatGroups.some(g=>g.id===app.groupId&&g.worldId===worldId))return app.groupId;const target=s.chatGroups.find(g=>g.worldId===worldId&&g.personIds?.length)||s.chatGroups.find(g=>g.worldId===worldId);if(!target)throw Error('当前世界没有社交分组');app.groupId=target.id;return target.id}
  function label(p){return p.anonymous?forumAlias(p.authorId,p.worldId):actor(p.authorId).chatName||actor(p.authorId).name}
  function place(p){return p.groupId?group(p.groupId)?.name||'兴趣小组':p.board==='tree'?'匿名树洞':p.board==='timeline'?'此刻时间线':'话题广场'}
  function replyLabel(p,r){return p.anonymous?forumAlias(r.authorId,p.worldId):actor(r.authorId).chatName||actor(r.authorId).name}
  function visible(){let rows=forumVisible(state(),world());if(view==='group')rows=rows.filter(p=>p.groupId===groupId);else rows=rows.filter(p=>tab==='all'||tab==='saved'?(tab!=='saved'||(p.bookmarks||[]).includes(me())):tab==='mine'?p.authorId===me():p.board===tab);if(query)rows=rows.filter(p=>`${p.text} ${p.topic} ${place(p)} ${label(p)}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));if(sort==='hot')rows.sort((a,b)=>(b.likes?.length||0)*2+db().replies.filter(r=>r.postId===b.id).length-(a.likes?.length||0)*2-db().replies.filter(r=>r.postId===a.id).length||b.createdAt-a.createdAt);return rows}
  function quote(p){const origin=p.quotePostId&&post(p.quotePostId);return origin?`<button class="forum-quote" data-forum-open="${esc(origin.id)}"><small>↗ 转自 ${esc(label(origin))} · ${esc(place(origin))}</small><span>${esc(short(origin.text,135))}</span></button>`:''}
  function sourceVideo(p){return p.sourceTikTokPostId?`<button class="forum-quote" data-forum-video="${esc(p.sourceTikTokPostId)}"><small>▶ 来自映兔</small><span>打开原作品继续看 ›</span></button>`:''}
  function card(p){const count=db().replies.filter(r=>r.postId===p.id&&!r.deleted).length,liked=(p.likes||[]).includes(me()),saved=(p.bookmarks||[]).includes(me());
    return `<article class="forum-post" data-forum-open="${esc(p.id)}" tabindex="0" role="button" aria-label="查看${esc(label(p))}的帖子详情">
      <div class="forum-post-top"><span class="forum-alias-mark">${p.anonymous?'✳':'◌'}</span><div><strong>${esc(label(p))}</strong><small>${esc(place(p))} · ${date(p.createdAt)}</small></div><button class="forum-card-menu" data-forum-more="${esc(p.id)}" aria-label="更多">···</button></div>
      ${p.challenge?'<span class="forum-topic-tag">✦ 小组接力</span>':''}${p.topic?`<span class="forum-topic-tag"># ${esc(p.topic)}</span>`:''}<p>${esc(p.text)}</p>${quote(p)}${sourceVideo(p)}
      <div class="forum-post-actions"><button data-forum-like="${esc(p.id)}" class="${liked?'active':''}" aria-label="点赞">${liked?'♥':'♡'} <small>${p.likes?.length||0}</small></button>
      <button data-forum-open="${esc(p.id)}" aria-label="查看评论">☷ <small>${count}</small></button><button data-forum-share="${esc(p.id)}" aria-label="分享">↗ <small>${p.reposts?.length||0} 转发</small></button>
      <button data-forum-save="${esc(p.id)}" class="${saved?'active':''}" aria-label="收藏">${saved?'◆':'◇'}</button></div></article>`}
  function groupCard(g){const count=forumVisible(state(),world()).filter(p=>p.groupId===g.id).length,joined=forumIsMember(state(),g.id,me());return `<button class="forum-group-card" data-forum-group="${esc(g.id)}"><span class="forum-group-symbol">${esc(g.symbol||'✦')}</span><span class="forum-group-info"><small>${esc(g.category)} · ${count} 帖${joined?' · 已加入':''}</small><strong>${esc(g.name)}</strong><em>${esc(g.description)}</em></span><b>↗</b></button>`}
  function banner(){return `<header class="forum-top"><div class="forum-brand"><span class="forum-kicker">BUNNY / ECHO SQUARE</span><button data-forum-settings aria-label="论坛设置">⚙</button></div><div class="forum-title-row"><div><h1>回声广场<span>.</span></h1><p>今天有什么值得聊的？</p></div></div><div class="forum-world"><span>正在看</span><select data-forum-world aria-label="切换世界">${(state().worlds||[]).map(w=>`<option value="${esc(w.id)}" ${w.id===world()?'selected':''}>${esc(w.name)}</option>`).join('')}</select></div></header>`}
  function feed(){const rows=visible();return `<div class="forum-scroll">${banner()}<section class="forum-discover"><div class="forum-section-head"><div><small>YOUR CIRCLES</small><h2>兴趣小组</h2></div><button data-forum-new-group>＋ 创建</button></div><div class="forum-group-grid">${groups().map(groupCard).join('')}</div></section>
    <div class="forum-board-strip"><button data-forum-route="tiktok"><small>01 / VIDEO</small><strong>映兔</strong><span>看见世界 ↗</span></button><button data-forum-tab="tree"><small>02 / ANON</small><strong>匿名树洞</strong><span>说出秘密 ↗</span></button><button data-forum-tab="timeline"><small>03 / NOW</small><strong>此刻</strong><span>发生着 ↗</span></button></div>
    <section class="forum-feed"><div class="forum-feed-heading"><div><span>LIVE FROM YOUR WORLD</span><h2>大家正在聊</h2></div><button data-forum-refresh ${refreshing?'disabled':''}>${refreshing?'生成中…':'↻ 更新'}</button></div>
    <nav class="forum-tabs">${[['all','全部'],['tree','树洞'],['group','小组'],['topic','话题'],['timeline','此刻'],['mine','我的'],['saved','收藏']].map(([key,text])=>`<button data-forum-tab="${key}" class="${tab===key?'active':''}">${text}</button>`).join('')}</nav>
    <div class="forum-feed-tools"><label class="forum-search"><span>⌕</span><input data-forum-search type="search" placeholder="找小组、话题或一句话" value="${esc(query)}"></label><select data-forum-sort aria-label="帖子排序"><option value="new" ${sort==='new'?'selected':''}>最新</option><option value="hot" ${sort==='hot'?'selected':''}>热议</option></select></div>
    <div class="forum-list">${rows.slice(0,limit).map(card).join('')||empty('还没有新的回声','加入一个小组，先发起今天的话题。')}</div>${rows.length>limit?'<button class="forum-load" data-forum-more-posts>继续往下看 ↓</button>':''}</section><div class="forum-end">已看到这里 · 明天还会有新的故事</div></div><button class="forum-compose" data-forum-compose>＋ 写点什么</button>`}
  function empty(title,copy){return `<div class="forum-empty"><span class="forum-empty-symbol">◯<i>◯</i></span><strong>${title}</strong><p>${copy}</p></div>`}
  function groupPage(){const g=group(groupId);if(!g){view='feed';return feed()}const rows=visible(),joined=forumIsMember(state(),g.id,me()),memberCount=db().memberships[g.id]?.length||0,challengeCount=new Set(rows.filter(p=>p.challenge).map(p=>p.authorId)).size,participated=rows.some(p=>p.challenge&&p.authorId===me());return `<div class="forum-scroll forum-inner"><header class="forum-inner-bar"><button data-forum-back aria-label="返回广场">‹</button><span>兴趣小组 / ${esc(g.category)}</span>${g.ownerId===me()?'<button data-forum-edit-group aria-label="编辑小组">⋯</button>':'<button data-forum-share-group aria-label="分享小组">↗</button>'}</header><div class="forum-group-hero"><span class="forum-group-big">${esc(g.symbol)}</span><small>${esc(g.category)} · ${memberCount} 位成员 · ${rows.length} 个话题</small><h1>${esc(g.name)}</h1><p>${esc(g.description)}</p><button class="${joined?'joined':''}" data-forum-join="${esc(g.id)}">${joined?'✓ 已加入 · 点击退出':'＋ 加入小组'}</button></div><div class="forum-prompt"><small>小组接力 / GROUP PROMPT</small><strong>${esc(g.prompt||'今天有什么新发现？')}</strong><span>${challengeCount} 人已参与 · 不必有标准答案</span><button data-forum-compose-group="${esc(g.id)}">${joined?participated?'再写一个答案 ↗':'写下我的答案 ↗':'加入后参与 ↗'}</button></div><section class="forum-feed"><div class="forum-feed-heading"><div><span>GROUP DISCUSSIONS</span><h2>组内讨论</h2></div><select data-forum-sort aria-label="帖子排序"><option value="new" ${sort==='new'?'selected':''}>最新</option><option value="hot" ${sort==='hot'?'selected':''}>热议</option></select></div><div class="forum-list">${rows.slice(0,limit).map(card).join('')||empty('这里还很安静','成为第一个留下声音的人。')}</div>${rows.length>limit?'<button class="forum-load" data-forum-more-posts>继续往下看 ↓</button>':''}</section></div>${joined?'<button class="forum-compose" data-forum-compose>＋ 发到小组</button>':''}`}
  function replyTree(p){const rows=db().replies.filter(r=>r.postId===p.id&&!r.deleted),roots=rows.filter(r=>!r.parentId||!rows.some(x=>x.id===r.parentId));const item=(r,depth=0)=>`<article class="forum-reply ${depth?'nested':''}"><div class="forum-reply-avatar">${esc(replyLabel(p,r).slice(0,1))}</div><div class="forum-reply-body"><div><b>${esc(replyLabel(p,r))}</b><small>${date(r.createdAt)}</small></div><p>${esc(r.text)}</p><div class="forum-reply-actions"><button data-forum-reply-to="${esc(r.id)}">回复</button><button data-forum-like-reply="${esc(r.id)}" class="${(r.likes||[]).includes(me())?'active':''}">♡ ${r.likes?.length||0}</button></div>${depth<3?rows.filter(x=>x.parentId===r.id).map(x=>item(x,depth+1)).join(''):''}</div></article>`;return roots.map(r=>item(r)).join('')}

  function relatedHtml(p){const related=forumVisible(state(),world()).filter(x=>x.id!==p.id&&(p.groupId?x.groupId===p.groupId:true)).slice(0,2);const fallback=p.groupId?group(p.groupId):groups()[0];return `<section class="forum-related"><div class="forum-section-head"><div><small>KEEP EXPLORING</small><h2>顺着这条线走</h2></div></div>${related.length?related.map(x=>`<button data-forum-open="${esc(x.id)}"><small>${esc(place(x))} · ${esc(label(x))}</small><span>${esc(short(x.text,90))}</span><b>↗</b></button>`).join(''):fallback?`<button data-forum-group="${esc(fallback.id)}"><small>兴趣小组 · ${esc(fallback.category)}</small><span>${esc(fallback.prompt||fallback.description)}</span><b>↗</b></button>`:''}</section>`}
  function postPage(){const p=post(postId);if(!p){view='feed';return feed()}const count=db().replies.filter(r=>r.postId===p.id&&!r.deleted).length;return `<div class="forum-scroll forum-inner"><header class="forum-inner-bar"><button data-forum-back aria-label="返回">‹</button><span>${esc(place(p))} / 帖子</span><button data-forum-more="${esc(p.id)}">···</button></header><div class="forum-post-page"><div class="forum-post-top"><span class="forum-alias-mark">${p.anonymous?'✳':'◌'}</span><div><strong>${esc(label(p))}</strong><small>${date(p.createdAt)} · ${esc(place(p))}</small></div></div>${p.challenge?'<span class="forum-topic-tag">✦ 小组接力</span>':''}${p.topic?`<span class="forum-topic-tag"># ${esc(p.topic)}</span>`:''}<p>${esc(p.text)}</p>${quote(p)}${sourceVideo(p)}<div class="forum-post-actions"><button data-forum-like="${esc(p.id)}" class="${(p.likes||[]).includes(me())?'active':''}">♡ ${p.likes?.length||0}</button><button data-forum-save="${esc(p.id)}" class="${(p.bookmarks||[]).includes(me())?'active':''}">◇ 收藏</button><button data-forum-share="${esc(p.id)}">↗ 分享 · ${p.reposts?.length||0}</button>${p.anonymous&&p.authorId!==me()?`<button data-forum-guess="${esc(p.id)}">猜谁</button>`:''}</div></div><section class="forum-thread"><div class="forum-section-head"><div><small>CONVERSATION</small><h2>${count} 条回应</h2></div></div>${replyTree(p)||empty('等第一句回应','你的评论会开启这段对话。')}</section>${relatedHtml(p)}</div><form class="forum-reply-composer" data-forum-reply-form><button type="button" data-forum-clear-reply hidden>×</button><input name="text" maxlength="480" placeholder="回应 ${esc(label(p))}…" required><button>发送</button></form>`}
  function render(container,params={}){containerRef=container;ensureForum(state());groups();if(params.postId&&post(params.postId)){view='post';postId=params.postId}else if(params.groupId&&group(params.groupId)){view='group';groupId=params.groupId}container.className='app-view forum-app forum-v2';container.innerHTML=view==='post'?postPage():view==='group'?groupPage():feed();bind(container)}
  function rerender(keep=true){const top=containerRef?.scrollTop||0;render(containerRef);if(keep)containerRef.scrollTop=top}
  function back(){if(view==='post'&&groupId&&post(postId)?.groupId===groupId)view='group';else view='feed';postId='';replyTarget='';rerender(false)}
  function openPost(id){if(!post(id))return;postId=id;view='post';replyTarget='';rerender(false)}
  function bind(c){c.onclick=event=>{const b=event.target.closest('button,[data-forum-open]');if(!b||!c.contains(b))return;const d=b.dataset;
    if(d.forumOpen){openPost(d.forumOpen);return}if(d.forumBack!==undefined){back();return}
    if(d.forumGroup){groupId=d.forumGroup;view='group';limit=12;rerender(false);return}
    if(d.forumTab){tab=d.forumTab;view='feed';limit=12;rerender();return}
    if(d.forumRoute){navigate(d.forumRoute);return}if(d.forumVideo){const source=state().tiktok?.posts?.find(p=>p.id===d.forumVideo);if(source)store.update(s=>ensureTikTok(s).groupId=source.groupId);navigate('tiktok');return}if(d.forumSettings!==undefined){settings();return}
    if(d.forumRefresh!==undefined){void refresh();return}if(d.forumEditGroup!==undefined){editGroup();return}if(d.forumNewGroup!==undefined){newGroup();return}
    if(d.forumJoin){try{store.update(s=>forumIsMember(s,d.forumJoin,me())?forumLeaveGroup(s,d.forumJoin,me()):forumJoinGroup(s,d.forumJoin,me()));rerender();showToast(forumIsMember(state(),d.forumJoin,me())?'已加入小组':'已退出小组')}catch(error){showToast(error.message)}return}
    if(d.forumComposeGroup){if(!forumIsMember(state(),d.forumComposeGroup,me()))return showToast('先加入小组');compose(d.forumComposeGroup,'',true);return}
    if(d.forumCompose!==undefined){compose(view==='group'?groupId:'');return}
    if(d.forumLike){store.update(s=>forumToggle(s,d.forumLike,'likes',me()));rerender();return}
    if(d.forumSave){store.update(s=>forumToggle(s,d.forumSave,'bookmarks',me()));rerender();return}
    if(d.forumLikeReply){store.update(s=>forumToggleReply(s,d.forumLikeReply,me()));rerender();return}
    if(d.forumReplyTo){replyTarget=d.forumReplyTo;const target=db().replies.find(r=>r.id===replyTarget);const input=c.querySelector('.forum-reply-composer input');if(input){input.placeholder=`回复 ${replyLabel(post(postId),target)}…`;input.focus();c.querySelector('[data-forum-clear-reply]').hidden=false}return}
    if(d.forumClearReply!==undefined){replyTarget='';const input=c.querySelector('.forum-reply-composer input');input.placeholder=`回应 ${label(post(postId))}…`;b.hidden=true;return}
    if(d.forumShare){share(d.forumShare);return}if(d.forumShareGroup!==undefined){navigator.clipboard?.writeText(`回声广场 · ${group(groupId)?.name||''}`).then(()=>showToast('小组信息已复制'));return}
    if(d.forumGuess){guess(d.forumGuess);return}if(d.forumMore){postMenu(d.forumMore);return}
    if(d.forumMorePosts!==undefined){limit+=12;rerender();return}
  };const worldSelect=c.querySelector('[data-forum-world]');if(worldSelect)worldSelect.onchange=e=>{store.update(s=>s.currentWorldId=e.target.value);view='feed';tab='all';query='';groupId='';postId='';rerender(false)};const search=c.querySelector('[data-forum-search]');if(search)search.oninput=e=>{query=e.target.value;const at=e.target.selectionStart;rerender();const input=c.querySelector('[data-forum-search]');input.focus();input.setSelectionRange(at,at)};c.querySelector('[data-forum-sort]')?.addEventListener('change',e=>{sort=e.target.value;rerender()});c.querySelector('[data-forum-reply-form]')?.addEventListener('submit',e=>{e.preventDefault();const text=e.target.elements.text.value.trim();if(!text)return;try{store.update(s=>forumReply(s,{postId,authorId:me(),text,parentId:replyTarget}));replyTarget='';rerender();showToast('回应已发出');void replyToForumPost(store,postId).then(count=>{if(count&&view==='post')rerender()}).catch(()=>{})}catch(error){showToast(error.message)}});c.querySelectorAll('[data-forum-open]').forEach(el=>{if(el.tagName==='ARTICLE')el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openPost(el.dataset.forumOpen)}}})}
  async function refresh(){if(refreshing)return;refreshing=true;rerender();try{const result=await refreshForum(store,world());showToast(`新增 ${result.posts} 条帖子、${result.replies} 条回复`)}catch(error){showToast(error.message)}finally{refreshing=false;if(containerRef?.isConnected&&document.querySelector('#app-screen')?.dataset.app==='forum')rerender()}}
  function compose(selectedGroup='',quotePostId='',challenge=false){const target=selectedGroup&&group(selectedGroup),origin=quotePostId&&post(quotePostId);openSheet(`<form class="forum-form"><div class="sheet-title"><h3>${origin?'引用转发':target?'发到 '+esc(target.name):'写给这个世界'}</h3><button type="button" class="button ghost" data-sheet-close>取消</button></div><label class="field"><span>发往哪里</span><select name="destination">${[...groups().filter(g=>forumIsMember(state(),g.id,me())).map(g=>`<option value="${esc(g.id)}" ${g.id===selectedGroup?'selected':''}>小组 · ${esc(g.name)}</option>`),'<option value="tree">匿名树洞</option>','<option value="topic">话题广场</option>','<option value="timeline">此刻时间线</option>'].join('')}</select></label><label class="field"><span>发布身份</span><select name="anonymous"><option value="yes">匿名代号</option><option value="no">公开昵称</option></select></label><label class="field"><span>话题标签（可选）</span><input name="topic" maxlength="32" placeholder="例如：雨天的唱片店"></label><textarea name="text" maxlength="1600" rows="6" placeholder="一件小事，也值得认真聊聊…" required></textarea>${origin?`<div class="forum-quote"><small>引用 ${esc(label(origin))}</small><span>${esc(short(origin.text,130))}</span></div>`:''}<p class="sub">匿名帖子与评论显示稳定代号。引用匿名帖子也只显示代号。</p><button class="button">发布</button></form>`,{onReady(sheet){const form=sheet.querySelector('form');if(origin)form.elements.text.placeholder='说说你转发它的原因…';form.onsubmit=e=>{e.preventDefault();try{let row;store.update(s=>{const dest=form.elements.destination.value;row=forumPost(s,{authorId:me(),worldId:world(),groupId:dest.startsWith('forum-')?dest:'',board:dest.startsWith('forum-')?'group':dest,anonymous:form.elements.anonymous.value==='yes',topic:form.elements.topic.value,text:form.elements.text.value,quotePostId,challenge})});closeSheet();view='post';postId=row.id;groupId=row.groupId||'';rerender(false);showToast('已发布');void replyToForumPost(store,row.id).then(count=>{if(count&&view==='post')rerender()}).catch(()=>{})}catch(error){showToast(error.message)}}}})}

  function editGroup(){const g=group(groupId);if(!g||g.ownerId!==me())return;openSheet(`<form class="forum-form"><div class="sheet-title"><h3>小组管理</h3><button type="button" class="button ghost" data-sheet-close>关闭</button></div><label class="field"><span>小组名字</span><input name="name" maxlength="28" value="${esc(g.name)}" required></label><label class="field"><span>分类</span><input name="category" maxlength="16" value="${esc(g.category)}"></label><label class="field"><span>介绍</span><textarea name="description" rows="3" maxlength="280">${esc(g.description)}</textarea></label><label class="field"><span>接力题目</span><input name="prompt" maxlength="80" value="${esc(g.prompt||'')}"></label><button class="button">保存小组</button><button type="button" class="button danger-button" data-forum-delete-group>删除小组</button><p class="sub">删除后原有帖子会保留在话题广场，评论与点赞也会保留。</p></form>`,{onReady(sheet){const form=sheet.querySelector('form');form.onsubmit=e=>{e.preventDefault();try{const q=form.elements;store.update(s=>forumEditGroup(s,g.id,me(),{name:q.name.value,category:q.category.value,description:q.description.value,prompt:q.prompt.value}));closeSheet();rerender();showToast('小组资料已更新')}catch(error){showToast(error.message)}};sheet.querySelector('[data-forum-delete-group]').onclick=()=>{if(!confirm(`删除「${g.name}」？帖子会移到话题广场。`))return;try{store.update(s=>forumDeleteGroup(s,g.id,me()));closeSheet();groupId='';view='feed';rerender(false);showToast('小组已删除，原帖已保留')}catch(error){showToast(error.message)}}}})}
  function newGroup(){openSheet(`<form class="forum-form"><div class="sheet-title"><h3>创建兴趣小组</h3><button type="button" class="button ghost" data-sheet-close>取消</button></div><label class="field"><span>小组名字</span><input name="name" maxlength="28" placeholder="例如：周三看电影" required></label><label class="field"><span>兴趣分类</span><select name="category">${['日常','书影音','创作','心事','游戏','附近','其他'].map(x=>`<option>${x}</option>`).join('')}</select></label><label class="field"><span>小组介绍</span><textarea name="description" maxlength="280" rows="3" placeholder="这里适合聊什么？"></textarea></label><label class="field"><span>小组接力题目</span><input name="prompt" maxlength="80" placeholder="给新成员的第一道小问题"></label><p class="sub">小组只在当前世界显示。成员加入后可以发帖。</p><button class="button">创建小组</button></form>`,{onReady(sheet){sheet.querySelector('form').onsubmit=e=>{e.preventDefault();try{let row;const q=e.target.elements;store.update(s=>{row=forumCreateGroup(s,{worldId:world(),ownerId:me(),name:q.name.value,category:q.category.value,description:q.description.value,prompt:q.prompt.value})});closeSheet();groupId=row.id;view='group';rerender(false)}catch(error){showToast(error.message)}}}})}
  function share(id){const p=post(id);if(!p)return;const summary=`${label(p)}在回声广场：${short(p.text,180)}`,friends=(state().conversations||[]).filter(c=>c.userAccountId===me()&&state().chatGroups?.some(g=>g.id===friendWorldGroup(state(),c.personId)&&g.worldId===p.worldId)),threads=(state().groupThreads||[]).filter(g=>g.accountId===me()&&g.worldId===world()&&!g.archived);
    openSheet(`<div class="forum-share-sheet"><div class="sheet-title"><h3>让这段话继续流动</h3><button class="button ghost" data-sheet-close>关闭</button></div><p>${esc(short(p.text,120))}</p><div class="forum-share-grid"><button data-share-repost>↻<span>${(p.reposts||[]).includes(me())?'已转发':'转发到此刻'}</span></button><button data-share-quote>✎<span>引用发帖</span></button><button data-share-x>𝕏<span>发到瞬语</span></button><button data-share-tiktok>▶<span>发到映兔</span></button><button data-share-copy>⌁<span>复制文字</span></button></div><h4>分享给聊天中的人</h4><div class="forum-share-peers">${friends.map(c=>`<button data-share-chat="${esc(c.id)}">◌ ${esc(actor(c.personId).name)}</button>`).join('')}${threads.map(g=>`<button data-share-thread="${esc(g.id)}">◌ ${esc(g.name)}</button>`).join('')||'<small>当前世界暂无聊天</small>'}</div></div>`,{onReady(sheet){const close=message=>{closeSheet();showToast(message);rerender()};sheet.querySelector('[data-share-repost]').onclick=()=>{if((p.reposts||[]).includes(me()))return showToast('这条帖子已经转发过了');try{store.update(s=>{forumToggle(s,id,'reposts',me());forumPost(s,{authorId:me(),worldId:p.worldId,board:'timeline',anonymous:false,text:'转发了一条讨论。',quotePostId:id})});close('已转发到此刻')}catch(error){showToast(error.message)}};sheet.querySelector('[data-share-quote]').onclick=()=>{closeSheet();compose(p.groupId&&forumIsMember(state(),p.groupId,me())?p.groupId:'',id)};sheet.querySelector('[data-share-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(summary);close('已复制')}catch{showToast('复制失败')}};sheet.querySelector('[data-share-x]').onclick=()=>{try{store.update(s=>{xPost(s,{authorId:me(),groupId:socialGroup(s,'x',p.worldId),text:summary})});close('已发到瞬语')}catch(error){showToast(error.message)}};sheet.querySelector('[data-share-tiktok]').onclick=()=>{try{store.update(s=>{tikPost(s,{authorId:me(),groupId:socialGroup(s,'tiktok',p.worldId),kind:'story',title:'来自回声广场',caption:summary,body:'这段话想和更多人分享',coverColor:'#d9dde0'})});close('已发到映兔')}catch(error){showToast(error.message)}};sheet.querySelectorAll('[data-share-chat]').forEach(b=>b.onclick=()=>{store.update(s=>{const conv=s.conversations.find(c=>c.id===b.dataset.shareChat&&c.userAccountId===me());if(!conv)return;const text=`↗ 回声广场 · ${summary}`;(s.messages[conv.id]||=[]).push({id:crypto.randomUUID(),role:'user',type:'text',text,sourceForumPostId:id,createdAt:Date.now(),time:date(Date.now())});conv.preview=text;conv.time=date(Date.now())});close('已分享到聊天')});sheet.querySelectorAll('[data-share-thread]').forEach(b=>b.onclick=()=>{const row=postGroupMessage(store,b.dataset.shareThread,{speakerId:me(),type:'forum-post',text:summary,sourceId:id});if(row)close('已分享到群聊');else showToast('群聊已失效')})}})}
  function guess(id){const p=post(id),last=p?.guesses?.[me()];if(!p||p.authorId===me())return;if(last&&Date.now()-last.at<86400000)return showToast(last.correct?'你已经猜到了':'今天已经猜过了，明天再试试');openSheet(`<div class="forum-guess"><div class="sheet-title"><h3>猜猜是谁</h3><button class="button ghost" data-sheet-close>关闭</button></div><p>读读用词和那些小习惯。每天只能猜一次。</p><div class="group-picker">${forumActors(state(),p.worldId).map(a=>`<button data-forum-pick="${esc(a.id)}">${esc(a.name)}</button>`).join('')}</div></div>`,{onReady(sheet){sheet.querySelectorAll('[data-forum-pick]').forEach(b=>b.onclick=()=>{const correct=b.dataset.forumPick===p.authorId;store.update(s=>{const row=ensureForum(s).posts.find(x=>x.id===id);row.guesses||={};row.guesses[me()]={at:Date.now(),correct}});closeSheet();showToast(correct?`猜对了，原来是${actor(p.authorId).name}`:'还差一点，明天再猜');rerender()})}})}
  function postMenu(id){const p=post(id);if(!p)return;openSheet(`<div class="sheet-title"><h3>这条帖子</h3><button class="button ghost" data-sheet-close>关闭</button></div><button class="button secondary" data-copy-post>复制内容</button>${p.authorId===me()?'<button class="button danger-button" data-delete-post>删除帖子</button>':''}`,{onReady(sheet){sheet.querySelector('[data-copy-post]').onclick=async()=>{try{await navigator.clipboard.writeText(p.text);showToast('已复制')}catch{showToast('复制失败')}closeSheet()};sheet.querySelector('[data-delete-post]')?.addEventListener('click',()=>{store.update(s=>ensureForum(s).posts.find(x=>x.id===id).deleted=true);closeSheet();if(view==='post')back();else rerender()})}})}
  function settings(){const s=db().settings;openSheet(`<form class="forum-settings"><div class="sheet-title"><h3>社区设置</h3><button type="button" class="button ghost" data-sheet-close>关闭</button></div><p>更新会使用主 API。新内容按当前世界生成并缓存，已有帖子会保留。</p><label class="field"><span>每次生成帖子</span><input name="batchPosts" type="number" min="2" max="8" value="${Number(s.batchPosts)||4}"></label><label class="field"><span>论坛专用规则 / 世界介绍</span><textarea name="rules" rows="6" maxlength="3000" placeholder="只用于论坛内容生成">${esc(s.rules||'')}</textarea></label><button class="button">保存设置</button></form>`,{onReady(sheet){sheet.querySelector('form').onsubmit=e=>{e.preventDefault();store.update(st=>{const settings=ensureForum(st).settings;settings.batchPosts=Math.max(2,Math.min(8,Number(e.target.elements.batchPosts.value)||4));settings.rules=e.target.elements.rules.value.trim()});closeSheet();showToast('社区设置已保存')}}})}
  return render;
}
