import { escapeHtml as esc, openSheet, closeSheet, showToast } from './core/ui.js';
import { ensureForum,forumAlias,forumActors,forumVisible,forumPost,forumReply,forumToggle } from './forum-model.js';
import { refreshForum,replyToForumPost } from './forum-engine.js';

const date=t=>new Date(t).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
export function createForumRenderer({store,navigate}){
  let tab='all',query='',limit=12,refreshing=false,containerRef=null;
  const state=()=>store.getState(),db=()=>ensureForum(state()),me=()=>state().currentUserId,world=()=>state().currentWorldId||state().worlds?.[0]?.id;
  function actor(id){return state().people.find(p=>p.id===id)||{name:'已注销用户',initials:'?'}}
  function label(p){return p.anonymous?forumAlias(p.authorId,p.worldId):actor(p.authorId).chatName||actor(p.authorId).name}
  function posts(){return forumVisible(state(),world()).filter(p=>(tab==='all'||tab==='saved'&&p.bookmarks.includes(me())||p.board===tab)&&(!query||`${p.text} ${p.topic} ${label(p)}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())))}
  function card(p){const replies=db().replies.filter(r=>r.postId===p.id),liked=p.likes.includes(me()),saved=p.bookmarks.includes(me());return `<article class="forum-post" data-forum-card="${esc(p.id)}"><div class="forum-post-top"><span class="forum-alias-mark">${p.anonymous?'✳':'◌'}</span><div><strong>${esc(label(p))}</strong><small>${p.board==='tree'?'匿名树洞':'话题讨论'} · ${date(p.createdAt)}</small></div><button class="forum-card-menu" data-forum-more="${esc(p.id)}" aria-label="更多">···</button></div>${p.topic?`<span class="forum-topic-tag"># ${esc(p.topic)}</span>`:''}<p>${esc(p.text)}</p><div class="forum-post-actions"><button data-forum-like="${esc(p.id)}" class="${liked?'active':''}" aria-label="点赞">${liked?'♥':'♡'} <small>${p.likes.length||''}</small></button><button data-forum-detail="${esc(p.id)}" aria-label="评论">↗ <small>${replies.length||'回复'}</small></button><button data-forum-save="${esc(p.id)}" class="${saved?'active':''}" aria-label="收藏">${saved?'◆':'◇'}</button>${p.anonymous&&p.authorId!==me()?`<button data-forum-guess="${esc(p.id)}" aria-label="猜猜是谁">猜谁</button>`:''}</div></article>`}
  function render(container){containerRef=container;ensureForum(state());container.className='app-view forum-app';const all=posts(),worlds=state().worlds||[];container.innerHTML=`<div class="forum-scroll"><header class="forum-top"><span class="forum-kicker">BUNNY / COMMUNITY</span><div class="forum-title-row"><div><h1>附近的人，<br><em>此刻的话。</em></h1><p>有些话适合实名，有些话适合藏起来。</p></div><button data-forum-settings aria-label="论坛设置">⚙</button></div><div class="forum-world"><span>正在看</span><select data-forum-world aria-label="切换世界">${worlds.map(w=>`<option value="${esc(w.id)}" ${w.id===world()?'selected':''}>${esc(w.name)}</option>`).join('')}</select></div></header><div class="forum-board-strip"><button data-forum-route="tiktok"><small>01 / 影像</small><strong>短视频</strong><span>看见世界 ↗</span></button><button data-forum-tab="tree"><small>02 / 匿名</small><strong>树洞</strong><span>说出秘密 ↗</span></button><button data-forum-route="x-social"><small>03 / 文字</small><strong>时间线</strong><span>发生着 ↗</span></button></div><section class="forum-feed"><div class="forum-feed-heading"><div><span>THE COMMON ROOM</span><h2>广场</h2></div><button data-forum-refresh ${refreshing?'disabled':''}>${refreshing?'生成中…':'↻ 刷新'}</button></div><nav class="forum-tabs">${[['all','全部'],['tree','树洞'],['topic','话题'],['saved','收藏']].map(([key,text])=>`<button data-forum-tab="${key}" class="${tab===key?'active':''}">${text}</button>`).join('')}</nav><label class="forum-search"><span>⌕</span><input data-forum-search type="search" placeholder="找话题、句子或匿名代号" value="${esc(query)}"></label><div class="forum-list">${all.slice(0,limit).map(card).join('')||`<div class="forum-empty"><span>✳</span><strong>这里还很安静</strong><p>写下第一句话，或点刷新让这个世界的人出现。</p></div>`}</div>${all.length>limit?'<button class="forum-load" data-forum-more-posts>继续往下看 ↓</button>':''}</section><div class="forum-end">NOT EVERY STORY NEEDS A NAME · BUNNY</div></div><button class="forum-compose" data-forum-compose aria-label="写帖子">＋ 写点什么</button>`;bind(container);}
  function bind(c){c.querySelector('[data-forum-world]').onchange=e=>{store.update(s=>s.currentWorldId=e.target.value);tab='all';query='';limit=12;render(c)};c.querySelector('[data-forum-refresh]').onclick=()=>void refresh();c.querySelector('[data-forum-settings]').onclick=settings;c.querySelector('[data-forum-compose]').onclick=compose;c.querySelector('[data-forum-search]').oninput=e=>{query=e.target.value;const cursor=e.target.selectionStart;render(c);const input=c.querySelector('[data-forum-search]');input.focus();input.setSelectionRange(cursor,cursor)};c.querySelectorAll('[data-forum-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.forumRoute));c.querySelectorAll('[data-forum-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.forumTab;limit=12;render(c)});c.querySelector('[data-forum-more-posts]')?.addEventListener('click',()=>{const top=c.scrollTop;limit+=12;render(c);c.scrollTop=top});c.querySelectorAll('[data-forum-like]').forEach(b=>b.onclick=()=>{store.update(s=>forumToggle(s,b.dataset.forumLike,'likes',me()));const top=c.scrollTop;render(c);c.scrollTop=top});c.querySelectorAll('[data-forum-save]').forEach(b=>b.onclick=()=>{store.update(s=>forumToggle(s,b.dataset.forumSave,'bookmarks',me()));const top=c.scrollTop;render(c);c.scrollTop=top});c.querySelectorAll('[data-forum-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.forumDetail));c.querySelectorAll('[data-forum-guess]').forEach(b=>b.onclick=()=>guess(b.dataset.forumGuess));c.querySelectorAll('[data-forum-more]').forEach(b=>b.onclick=()=>postMenu(b.dataset.forumMore))}
  async function refresh(){if(refreshing)return;refreshing=true;render(containerRef);try{const result=await refreshForum(store,world());showToast(`新增 ${result.posts} 条帖子、${result.replies} 条回复`)}catch(error){showToast(error.message)}finally{refreshing=false;if(containerRef?.isConnected&&document.querySelector('#app-screen')?.dataset.app==='forum')render(containerRef)}}
  function compose(){openSheet(`<form class="forum-form"><div class="sheet-title"><h3>写给这个世界</h3><button type="button" class="button ghost" data-sheet-close>取消</button></div><label class="field"><span>发往哪里</span><select name="board"><option value="tree">匿名树洞</option><option value="topic">话题广场 · 公开身份</option></select></label><label class="field" data-topic-field hidden><span>话题</span><input name="topic" maxlength="32" placeholder="例如：雨天的唱片店"></label><textarea name="text" maxlength="1600" rows="7" placeholder="今天发生了什么？不用写得很完整。" required></textarea><p class="sub">树洞里会显示稳定的匿名代号；其他账号无法直接看见你的真实身份。</p><button class="button">发布</button></form>`,{onReady(sheet){const form=sheet.querySelector('form');form.elements.board.onchange=()=>sheet.querySelector('[data-topic-field]').hidden=form.elements.board.value!=='topic';form.onsubmit=e=>{e.preventDefault();try{let id;store.update(s=>{id=forumPost(s,{authorId:me(),worldId:world(),board:form.elements.board.value,topic:form.elements.topic.value,text:form.elements.text.value,anonymous:form.elements.board.value==='tree'}).id});closeSheet();tab='all';render(containerRef);showToast('已发布');void replyToForumPost(store,id).then(count=>{if(count&&containerRef?.isConnected&&document.querySelector('#app-screen')?.dataset.app==='forum')render(containerRef)}).catch(()=>{})}catch(error){showToast(error.message)}}}})}
  function detail(postId){const p=db().posts.find(x=>x.id===postId);if(!p)return;const replies=db().replies.filter(r=>r.postId===postId);openSheet(`<div class="forum-detail"><div class="sheet-title"><h3>${p.board==='tree'?'匿名树洞':'话题讨论'}</h3><button class="button ghost" data-sheet-close>关闭</button></div><small>${esc(label(p))} · ${date(p.createdAt)}</small><p>${esc(p.text)}</p><div class="forum-detail-count">${replies.length} 条回复</div><div class="forum-replies">${replies.map(r=>`<article><b>${esc(p.board==='tree'?forumAlias(r.authorId,p.worldId):actor(r.authorId).name)}</b><small>${date(r.createdAt)}</small><p>${esc(r.text)}</p></article>`).join('')||'<p>还没有回复，先说一句吧。</p>'}</div><form><textarea name="text" rows="2" maxlength="480" placeholder="写一条回复…" required></textarea><button class="button">发送回复</button></form></div>`,{onReady(sheet){sheet.querySelector('form').onsubmit=e=>{e.preventDefault();try{store.update(s=>forumReply(s,{postId,authorId:me(),text:e.target.elements.text.value}));closeSheet();render(containerRef);detail(postId);void replyToForumPost(store,postId).then(count=>{if(count){closeSheet();render(containerRef);detail(postId)}}).catch(()=>{})}catch(error){showToast(error.message)}}}})}
  function guess(postId){const p=db().posts.find(x=>x.id===postId),last=p?.guesses?.[me()];if(!p||p.authorId===me())return;if(last&&Date.now()-last.at<24*60*60*1000)return showToast(last.correct?'你已经猜到了':'今天已经猜过，明天再试试');const options=forumActors(state(),p.worldId);openSheet(`<div class="forum-guess"><div class="sheet-title"><h3>猜猜是谁</h3><button class="button ghost" data-sheet-close>关闭</button></div><p>读读用词和那些小习惯。每天只能猜一次。</p><div class="group-picker">${options.map(a=>`<button data-forum-pick="${esc(a.id)}">${esc(a.name)}</button>`).join('')}</div></div>`,{onReady(sheet){sheet.querySelectorAll('[data-forum-pick]').forEach(b=>b.onclick=()=>{const correct=b.dataset.forumPick===p.authorId;store.update(s=>{const row=ensureForum(s).posts.find(x=>x.id===postId);row.guesses||={};row.guesses[me()]={at:Date.now(),correct}});closeSheet();showToast(correct?`猜对了，原来是${actor(p.authorId).name}`:'还差一点，明天再猜');render(containerRef)})}})}
  function postMenu(postId){const p=db().posts.find(x=>x.id===postId);if(!p)return;openSheet(`<div class="sheet-title"><h3>这条帖子</h3><button class="button ghost" data-sheet-close>关闭</button></div><button class="button secondary" data-copy-post>复制内容</button>${p.authorId===me()?'<button class="button danger-button" data-delete-post>删除帖子</button>':''}`,{onReady(sheet){sheet.querySelector('[data-copy-post]').onclick=async()=>{try{await navigator.clipboard.writeText(p.text);showToast('已复制')}catch{showToast('复制失败')}closeSheet()};sheet.querySelector('[data-delete-post]')?.addEventListener('click',()=>{store.update(s=>ensureForum(s).posts.find(x=>x.id===postId).deleted=true);closeSheet();render(containerRef)})}})}
  function settings(){const s=db().settings;openSheet(`<form class="forum-settings"><div class="sheet-title"><h3>社区设置</h3><button type="button" class="button ghost" data-sheet-close>关闭</button></div><p>刷新时使用主 API；帖子与评论写入本机缓存。每个世界单独显示内容。</p><label class="field"><span>每次生成帖子</span><input name="batchPosts" type="number" min="2" max="8" value="${Number(s.batchPosts)||4}"></label><label class="field"><span>论坛专用规则 / 世界介绍</span><textarea name="rules" rows="6" maxlength="3000" placeholder="这里的规则只用于论坛内容生成">${esc(s.rules||'')}</textarea></label><button class="button">保存设置</button></form>`,{onReady(sheet){sheet.querySelector('form').onsubmit=e=>{e.preventDefault();store.update(st=>{const settings=ensureForum(st).settings;settings.batchPosts=Math.max(2,Math.min(8,Number(e.target.elements.batchPosts.value)||4));settings.rules=e.target.elements.rules.value.trim()});closeSheet();showToast('社区设置已保存')}}})}
  return render;
}
