import { sendToModel } from './integrations/ai-client.js';
import { ensureForum,forumActors,forumPost,forumReply,forumVisible } from './forum-model.js';
import { knownWorldEvents } from './world-engine.js';

function parse(raw){const match=String(raw||'').match(/\{[\s\S]*\}/);if(!match)throw Error('模型没有返回社区 JSON');try{return JSON.parse(match[0])}catch{throw Error('社区内容格式无效')}}
export async function refreshForum(store,worldId){
  const state=store.getState(),db=ensureForum(state),model=state.modelProfiles.find(p=>p.id===state.activeModelProfileId);if(!model?.apiKey||!model?.model)throw Error('请先在手机设置里配置模型与 API');
  const actors=forumActors(state,worldId),allowed=new Set(actors.map(p=>p.id));if(!allowed.size)throw Error('当前世界还没有 CHAR / NPC');
  const recent=forumVisible(state,worldId).slice(0,12).map(p=>({board:p.board,text:p.text,topic:p.topic}));
  const events=knownWorldEvents(state,state.currentUserId,worldId,8).filter(e=>e.payload?.public).map(e=>e.payload.summary||e.payload.text).filter(Boolean);
  const count=Math.min(8,Math.max(2,Number(db.settings.batchPosts)||4));
  const context={world:state.worlds.find(w=>w.id===worldId)?.name,actors:actors.map(p=>({id:p.id,name:p.name,persona:(p.persona||p.personality||p.note||'').slice(0,320)})),publicEvents:events,recent};
  const prompt=`你在写虚拟手机论坛的一次增量刷新。输出 ${count} 条帖子，合计约 ${Math.min(16,count*2)} 条评论。只使用 actors 中的 authorId；树洞可匿名，话题板用公开身份。内容可聊琐事、当地小发现、求助、兴趣、圈内小梗，像真实网友，不要每篇都抒情或结尾提问。角色会有自己的口癖与兴趣，但不要暴露尚未公开的私事、其他世界和 USER 的私人聊天。紧贴 publicEvents，避免重复 recent。帖子 20—180 字，评论 4—50 字。只输出 JSON：{"posts":[{"authorId":"角色ID","board":"tree或topic","topic":"话题标签，可空","text":"正文","replies":[{"authorId":"角色ID","text":"评论"}]}]}。附加社区规则：${String(db.settings.rules||'无').slice(0,3000)}`;
  const output=parse(await sendToModel(model,[{role:'user',text:JSON.stringify(context)}],prompt));if(!Array.isArray(output.posts))throw Error('社区返回内容缺少帖子');
  let posts=0,replies=0;store.update(s=>{const db=ensureForum(s),existing=new Set(db.posts.filter(p=>p.worldId===worldId).map(p=>p.text.trim()));for(const draft of output.posts.slice(0,count)){if(!allowed.has(draft?.authorId)||typeof draft.text!=='string'||!draft.text.trim()||existing.has(draft.text.trim()))continue;const post=forumPost(s,{authorId:draft.authorId,worldId,text:draft.text,board:draft.board,topic:draft.topic,anonymous:draft.board!=='topic'});existing.add(post.text);posts++;for(const reply of (Array.isArray(draft.replies)?draft.replies:[]).slice(0,3)){if(!allowed.has(reply?.authorId)||typeof reply.text!=='string'||!reply.text.trim())continue;forumReply(s,{postId:post.id,authorId:reply.authorId,text:reply.text});replies++}}db.lastRefreshAt[worldId]=Date.now()});return{posts,replies}
}
export async function replyToForumPost(store,postId){const state=store.getState(),post=ensureForum(state).posts.find(p=>p.id===postId),model=state.modelProfiles.find(p=>p.id===state.activeModelProfileId);if(!post||!model?.apiKey||!model?.model)return 0;const actors=forumActors(state,post.worldId),allowed=new Set(actors.map(p=>p.id)),replies=state.forum.replies.filter(r=>r.postId===postId).slice(-8).map(r=>({name:state.people.find(p=>p.id===r.authorId)?.name,text:r.text}));if(!actors.length)return 0;const prompt='为这条论坛帖子生成 0—3 条自然回复。角色可不参与；只用指定 actor ID。不要替 USER 发言，不要知道私密信息，拒绝模板化鼓励和泛泛感叹。只返回 JSON：{"replies":[{"authorId":"角色ID","text":"短回复"}]}。';const result=parse(await sendToModel(model,[{role:'user',text:JSON.stringify({post:post.text,replies,actors:actors.map(p=>({id:p.id,name:p.name,persona:(p.persona||p.personality||p.note||'').slice(0,250)}))})}],prompt));let count=0;store.update(s=>{for(const row of (Array.isArray(result.replies)?result.replies:[]).slice(0,3)){if(!allowed.has(row?.authorId)||!row.text)continue;forumReply(s,{postId,authorId:row.authorId,text:row.text});count++}});return count}
