import {generateSocialCover} from './social-media.js';
import { sendToModel } from './integrations/ai-client.js';
import { ensureForum,forumActors,forumPost,forumReply,forumVisible,forumGroups,forumJoinGroup } from './forum-model.js';
import { knownWorldEvents } from './world-engine.js';

function parse(raw){const match=String(raw||'').match(/\{[\s\S]*\}/);if(!match)throw Error('模型没有返回社区 JSON');try{return JSON.parse(match[0])}catch{throw Error('社区内容格式无效')}}
export async function refreshForum(store,worldId){
  const state=store.getState(),db=ensureForum(state),model=state.modelProfiles.find(p=>p.id===state.activeModelProfileId);if(!model?.apiKey||!model?.model)throw Error('请先在手机设置里配置模型与 API');
  const actors=forumActors(state,worldId),allowed=new Set(actors.map(p=>p.id));if(!allowed.size)throw Error('当前世界还没有 CHAR / NPC');
  const recent=forumVisible(state,worldId).slice(0,12).map(p=>({board:p.board,groupId:p.groupId||'',text:p.text,topic:p.topic}));
  const events=knownWorldEvents(state,state.currentUserId,worldId,8).filter(e=>e.payload?.public).map(e=>e.payload.summary||e.payload.text).filter(Boolean);
  const count=Math.min(8,Math.max(2,Number(db.settings.batchPosts)||4));
  const communityGroups=forumGroups(state,worldId).map(g=>({id:g.id,name:g.name,category:g.category,description:g.description,prompt:g.prompt}));
  const context={world:state.worlds.find(w=>w.id===worldId)?.name,actors:actors.map(p=>({id:p.id,name:p.name,persona:(p.persona||p.personality||p.note||'').slice(0,320)})),groups:communityGroups,publicEvents:events,recent};
  const prompt=`最多一条帖子可增加 imagePrompt 字段描述适合配图的具体画面，不需要配图则留空。你在写虚拟手机论坛的一次增量刷新。输出 ${count} 条帖子，合计约 ${Math.min(16,count*2)} 条评论。只使用 actors 中的 authorId；board 可为 tree、topic、timeline、group，groupId 仅可用 groups 里的 ID，至少 ${Math.max(1,Math.floor(count/2))} 条发在不同兴趣小组里，其中 1 条可回应小组接力题并设 challenge=true；树洞可匿名，小组成员也可以匿名，但别让所有人都匿名。时间线是论坛内部短句流，不属于 X 应用。小组帖要真正回应其兴趣主题或本周接力题，角色按自己性格选择感兴趣的小组，不要所有人都在同一个组。内容可聊琐事、当地小发现、求助、兴趣、圈内小梗，像真实网友，不要每篇都抒情或结尾提问。评论可以自然接话、纠正、分享经历，避免清一色赞美。不要暴露尚未公开的私事、其他世界和 USER 的私人聊天。紧贴 publicEvents，避免重复 recent。帖子 20—180 字，评论 4—50 字。只输出 JSON：{"posts":[{"authorId":"角色ID","board":"tree或topic或timeline或group","groupId":"小组ID，可空","anonymous":false,"challenge":false,"topic":"话题标签，可空","text":"正文","replies":[{"authorId":"角色ID","text":"评论"}]}]}。附加社区规则：${String(db.settings.rules||'无').slice(0,3000)}`;
  const output=parse(await sendToModel(model,[{role:'user',text:JSON.stringify(context)}],prompt));if(!Array.isArray(output.posts))throw Error('社区返回内容缺少帖子');
  const imageRows=[];let posts=0,replies=0;store.update(s=>{const db=ensureForum(s),existing=new Set(db.posts.filter(p=>p.worldId===worldId).map(p=>p.text.trim())),groupIds=new Set(forumGroups(s,worldId).map(g=>g.id));for(const draft of output.posts.slice(0,count)){if(!allowed.has(draft?.authorId)||typeof draft.text!=='string'||!draft.text.trim()||existing.has(draft.text.trim()))continue;const groupId=groupIds.has(draft.groupId)?draft.groupId:'';if(groupId)forumJoinGroup(s,groupId,draft.authorId);const post=forumPost(s,{authorId:draft.authorId,worldId,text:draft.text,board:groupId?'group':draft.board,groupId,topic:draft.topic,anonymous:draft.board==='tree'||Boolean(draft.anonymous),challenge:Boolean(draft.challenge)});post.imagePrompt=String(draft.imagePrompt||'').slice(0,1200);imageRows.push(post);existing.add(post.text);posts++;for(const reply of (Array.isArray(draft.replies)?draft.replies:[]).slice(0,3)){if(!allowed.has(reply?.authorId)||typeof reply.text!=='string'||!reply.text.trim())continue;forumReply(s,{postId:post.id,authorId:reply.authorId,text:reply.text});replies++}}db.lastRefreshAt[worldId]=Date.now()});await generateSocialCover(store,'forum',imageRows);return{posts,replies}
}
export async function replyToForumPost(store,postId){const state=store.getState(),post=ensureForum(state).posts.find(p=>p.id===postId),model=state.modelProfiles.find(p=>p.id===state.activeModelProfileId);if(!post||!model?.apiKey||!model?.model)return 0;const actors=forumActors(state,post.worldId),allowed=new Set(actors.map(p=>p.id)),replies=state.forum.replies.filter(r=>r.postId===postId).slice(-8).map(r=>({name:state.people.find(p=>p.id===r.authorId)?.name,text:r.text}));if(!actors.length)return 0;const group=post.groupId?forumGroups(state,post.worldId).find(g=>g.id===post.groupId):null;const prompt='为这条论坛帖子生成 0—3 条自然回复。角色可不参与；只用指定 actor ID。回应帖子具体内容和已有回复，允许不同意见、补充细节或轻微跑题。如果是兴趣小组，遵守小组主题。不要替 USER 发言，不要知道私密信息，拒绝模板化鼓励和泛泛感叹。只返回 JSON：{"replies":[{"authorId":"角色ID","text":"短回复"}]}。';const result=parse(await sendToModel(model,[{role:'user',text:JSON.stringify({post:post.text,group:group?{name:group.name,description:group.description}:null,replies,actors:actors.map(p=>({id:p.id,name:p.name,persona:(p.persona||p.personality||p.note||'').slice(0,250)}))})}],prompt));let count=0;store.update(s=>{for(const row of (Array.isArray(result.replies)?result.replies:[]).slice(0,3)){if(!allowed.has(row?.authorId)||!row.text)continue;forumReply(s,{postId,authorId:row.authorId,text:row.text});count++}});return count}
