import {escapeHtml as esc} from './core/ui.js';
export const gameCatalog=[
 {id:'island',name:'兔屿生活',tag:'慢生活 · 3D',symbol:'⌂',description:'散步、换装、照料田地，和朋友一起把小岛过成日常。',time:'随时回家',tone:'island'},
 {id:'pairs',name:'翻翻心事',tag:'记忆 · 配对',symbol:'◫',description:'翻开十二张小卡，找到藏在其中的六对相同图案。',time:'约 2 分钟',tone:'pairs'},
 {id:'line',name:'三步之间',tag:'策略 · 棋盘',symbol:'◯',description:'你执圆圈，对手执叉。三点连成一线，就赢下这一小局。',time:'约 1 分钟',tone:'line'}
];
export function gameDay(state,now=Date.now()){const timezone=state.worlds?.find(w=>w.id===state.currentWorldId)?.timezone;try{return new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(now)}catch{return new Date(now).toLocaleDateString('en-CA')}}
export function ensureGameDay(state,now=Date.now()){const key=`${state.currentWorldId}::${state.currentUserId}`,day=gameDay(state,now);state.gameRoom||={};const room=state.gameRoom[key]||={days:{},sessions:{}};room.days||={};room.sessions||={};room.days[day]||={visits:[],results:[],started:[]};return {room,today:room.days[day],day,key};}
export function lineWinner(board){for(const [a,b,c] of [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]])if(board[a]&&board[a]===board[b]&&board[a]===board[c])return board[a];return board.every(Boolean)?'draw':'';}
export function createGamesRenderer({store,navigate}){
 let root,view='list',selected='island';const state=()=>store.getState(),read=()=>ensureGameDay(state()),game=()=>gameCatalog.find(g=>g.id===selected);
 const mutate=fn=>store.update(s=>fn(ensureGameDay(s)));
 const open=id=>{selected=id;view='detail';mutate(({today})=>{if(!today.visits.includes(id))today.visits.push(id)});paint()};
 function tasks(id){const {today,day,key}=read(),results=today.results.filter(r=>r.gameId===id),home=state().bunnyIslands?.[key],events=[...(home?.actionLog||[]).filter(e=>e.actorId===state().currentUserId&&gameDay(state(),e.at)===day),...(today.islandActions||[]).map(kind=>({kind}))];return id==='island'?[
  ['来岛上走一走',events.some(e=>e.kind==='move')],['照料田地或宠物',events.some(e=>['plant','water','feed','harvest'].includes(e.kind))],['换一个今天的造型',events.some(e=>e.kind==='dress')]
 ]:[['打开今天的游戏',today.visits.includes(id)],['完成一局',results.length>0],[id==='pairs'?'20 次翻牌内完成配对':'取得胜利或平局',results.some(r=>id==='pairs'?r.moves<=20:['user','draw'].includes(r.winner))]];}
 function paint(){const {day}=read();root.className='app-view game-room';root.innerHTML=view==='list'?`<header class="game-room-header"><small>BUNNY / PLAYROOM</small><h1>玩一会儿<span>.</span></h1><p>把今天留一点给快乐。</p><span class="game-room-date">${esc(day)} · 每日更新</span></header><div class="game-library">${gameCatalog.map((g,i)=>`<button data-game="${g.id}" class="game-library-card ${g.tone}"><span class="game-art" aria-hidden="true">${g.symbol}<i></i><b>0${i+1}</b></span><span class="game-library-copy"><small>${g.tag}</small><strong>${g.name}</strong><em>${g.time}</em></span><span class="game-arrow">↗</span></button>`).join('')}</div><p class="game-room-foot">三种不同的节奏。今天想从哪一个开始？</p>`:view==='detail'?detail():play();
  root.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>open(b.dataset.game));root.querySelector('[data-games-home]')?.addEventListener('click',()=>{view='list';paint()});root.querySelector('[data-game-start]')?.addEventListener('click',start);root.querySelector('[data-game-detail]')?.addEventListener('click',()=>{view='detail';paint()});root.querySelector('[data-game-again]')?.addEventListener('click',()=>{mutate(({room})=>delete room.sessions[selected]);start()});
  root.querySelectorAll('[data-pair]').forEach(b=>b.onclick=()=>flip(+b.dataset.pair));root.querySelectorAll('[data-cell]').forEach(b=>b.onclick=()=>move(+b.dataset.cell));
  const back=document.querySelector('#back-button');if(back)back.onclick=()=>{if(view==='play'){view='detail';paint()}else if(view==='detail'){view='list';paint()}else navigate('desktop')};
 }
 function detail(){const g=game(),rows=tasks(g.id),done=rows.filter(x=>x[1]).length;return `<header class="game-detail-header"><button data-games-home aria-label="游戏列表">‹</button><span>游乐屋 / ${g.tag}</span></header><section class="game-detail-hero ${g.tone}"><span class="game-detail-art">${g.symbol}</span><small>${g.tag}</small><h1>${g.name}</h1><p>${g.description}</p></section><section class="game-tasks"><header><div><small>DAILY LITTLE THINGS</small><h2>今日小目标</h2></div><span>${done} / ${rows.length}</span></header>${rows.map(([title,done],i)=>`<div class="game-task ${done?'done':''}"><span>${done?'✓':String(i+1).padStart(2,'0')}</span><p>${title}</p><small>${done?'已完成':'待完成'}</small></div>`).join('')}<p class="game-task-note">按当前世界日期刷新。进度来自实际游戏操作。</p></section><div class="game-entry"><span>${g.time}<small>${read().day}</small></span><button data-game-start>${read().room.sessions[selected]?'继续游戏':'开始游戏'} ↗</button></div>`;}
 function start(){mutate(({room,today,day})=>{if(!today.started.includes(selected))today.started.push(selected);if(selected==='island')return;if(!room.sessions[selected]||room.sessions[selected].day!==day){if(selected==='pairs'){const cards=['☁','♡','✳','☾','♧','✦'].flatMap(x=>[x,x]);for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]]}room.sessions[selected]={day,cards,open:[],matched:[],moves:0,finished:false,id:crypto.randomUUID()};}else room.sessions[selected]={day,board:Array(9).fill(''),finished:false,id:crypto.randomUUID()};}});if(selected==='island')return navigate('bunny-island',{_parent:{name:'games',params:{gameId:'island'}}});view='play';paint();}
 function finish(session,winner){if(session.finished)return;session.finished=true;session.winner=winner;mutate(({today})=>{if(!today.results.some(r=>r.id===session.id))today.results.push({id:session.id,gameId:selected,winner,moves:session.moves||0,at:Date.now()})});}
 function play(){const session=read().room.sessions[selected];if(!session){view='detail';return detail()}const won=session.finished;return `<header class="game-detail-header"><button data-game-detail aria-label="游戏详情">‹</button><span>${game().name}</span><button data-game-again>重来</button></header><section class="mini-game"><small>${selected==='pairs'?`${session.moves} 次翻牌 · ${session.matched.length/2} / 6 对`:'你是 ○ · 对手是 ×'}</small><h2>${won?(selected==='pairs'?'全部找到啦。':session.winner==='user'?'这一局，你赢了。':session.winner==='draw'?'势均力敌。':'下一局再来。'):(selected==='pairs'?'记住刚刚的那张。':'慢慢想，轮到你。')}</h2>${selected==='pairs'?`<div class="pairs-board" data-no-swipe>${session.cards.map((c,i)=>`<button data-pair="${i}" class="${session.matched.includes(i)?'matched':session.open.includes(i)?'flipped':''}" aria-label="${session.open.includes(i)||session.matched.includes(i)?c:'翻开卡片 '+(i+1)}">${session.open.includes(i)||session.matched.includes(i)?c:'b.'}</button>`).join('')}</div>`:`<div class="line-board" data-no-swipe>${session.board.map((v,i)=>`<button data-cell="${i}" aria-label="第 ${i+1} 格" ${won||v?'disabled':''}>${v==='user'?'○':v==='opponent'?'×':''}</button>`).join('')}</div>`}<p>${selected==='pairs'?'每次翻两张，相同图案会留在桌面。':'横、竖、斜，任意三点成线即可获胜。'}</p>${won?'<button class="mini-finish" data-game-detail>查看今日进度 ↗</button>':''}</section>`;}
 function flip(i){const scope=read().key,session=read().room.sessions.pairs;if(session.finished||session.open.length===2||session.open.includes(i)||session.matched.includes(i))return;mutate(()=>{session.open.push(i);if(session.open.length===2){session.moves++;const [a,b]=session.open;if(session.cards[a]===session.cards[b]){session.matched.push(a,b);session.open=[];if(session.matched.length===12)finish(session,'user')}}});paint();if(session.open.length===2)setTimeout(()=>{if(read().key!==scope||read().room.sessions.pairs!==session)return;mutate(()=>session.open=[]);if(view==='play'&&selected==='pairs')paint()},750);}
 function move(i){const session=read().room.sessions.line;if(session.finished||session.board[i])return;mutate(()=>{session.board[i]='user';let winner=lineWinner(session.board);if(!winner){const empty=session.board.map((v,i)=>v?-1:i).filter(i=>i>=0);const winning=role=>empty.find(n=>{const board=[...session.board];board[n]=role;return lineWinner(board)===role});const pick=winning('opponent')??winning('user')??(empty.includes(4)?4:empty[Math.floor(Math.random()*empty.length)]);session.board[pick]='opponent';winner=lineWinner(session.board)}if(winner)finish(session,winner)});paint();}
 return function render(container,params={}){root=container;store.update(s=>ensureGameDay(s));if(params.gameId&&gameCatalog.some(g=>g.id===params.gameId))open(params.gameId);else{view='list';paint();}};
}
