import { escapeHtml, initialsAvatar, showToast, openSheet, closeSheet } from './core/ui.js';
import { walletDebit } from './wallet-v2.js';
import { createGroupThread, postGroupMessage, generateGroupReplies } from './group-model.js';
import { ensureWorldEngine, entityWorld } from './world-engine.js';
import { saveMediaBlob, getMediaUrl } from './media-store.js';
import { openGroupMemberSettings, groupMemberBubbleStyle } from './group-member-settings.js';
import { applyGroupAppearance, openGroupAppearance } from './group-appearance.js';
import { chatRecordCard, openChatRecordDetail } from './chat-record.js';
import { accountContext } from './account-system.js';

export function openCreateGroupSheet(store,navigate) {
  const state=ensureWorldEngine(store.getState()),worlds=[...new Map(state.chatGroups.map(group=>[group.worldId, state.worlds.find(row=>row.id===group.worldId)||{id:group.worldId,name:group.name}])).values()].filter(row=>row.id);
  openSheet(`<form class="group-create-sheet"><div class="sheet-title"><h3>创建群聊</h3><button type="button" class="button ghost" data-sheet-close>关闭</button></div><label class="field"><span>群名称</span><input name="name" maxlength="28" required placeholder="例如：周末去哪儿"></label><label class="field"><span>所属世界</span><select name="worldId">${worlds.map(row=>`<option value="${escapeHtml(row.id)}">${escapeHtml(row.name)}</option>`).join('')}</select></label><div class="group-member-picker" data-members></div><p class="sub">选择同一世界的至少两位 CHAR / NPC。入群不等于加好友；NPC 只有成为好友才会私聊你。</p><button class="button">创建群聊</button></form>`,{onReady(sheet){const form=sheet.querySelector('form'),members=sheet.querySelector('[data-members]');const draw=()=>{const worldId=form.elements.worldId.value;members.innerHTML=state.people.filter(row=>['char','npc'].includes(row.type)&&entityWorld(state,row.id)===worldId).map(row=>`<label><input type="checkbox" name="member" value="${escapeHtml(row.id)}"><span>${initialsAvatar(row,state.chatProfiles[row.id]||{})}</span><strong>${escapeHtml(row.name)}</strong><small>${row.type.toUpperCase()}</small></label>`).join('')||'<p>这个世界还没有角色，请先在联系人中新建。</p>'};form.elements.worldId.onchange=draw;draw();form.onsubmit=e=>{e.preventDefault();try{const data=new FormData(form),thread=createGroupThread(store,{name:data.get('name'),worldId:data.get('worldId'),memberIds:data.getAll('member')});closeSheet();navigate('group-chat',{id:thread.id})}catch(error){showToast(error.message)}}}});
}

export function createGroupChatRenderer({store,navigate}) {
  let generating=false,selectMode=false,selected=new Set(),selectedThreadId='';
  return function render(container,params={}) {
    const previousScroll=selectMode?container.querySelector('[data-group-stream]')?.scrollTop:null;
    const state=ensureWorldEngine(store.getState()),thread=state.groupThreads.find(row=>row.id===(params.id||state.groupThreads.find(item=>item.accountId===state.currentUserId&&!item.archived)?.id)&&row.accountId===state.currentUserId&&!row.archived);if(!thread)return navigate('chat');
    if(thread.unread)store.update(s=>{const row=s.groupThreads.find(x=>x.id===thread.id);if(row)row.unread=0});
    if(selectedThreadId!==thread.id){selectedThreadId=thread.id;selected.clear();selectMode=false}
    const members=thread.memberIds.map(id=>state.people.find(row=>row.id===id)).filter(Boolean),messages=state.groupMessages[thread.id]||[];
    container.className='app-view group-chat-view';
    container.innerHTML=`<section class="group-chat-shell"><header class="group-chat-head"><button type="button" data-group-back aria-label="返回聊天列表">‹</button><div><strong>${escapeHtml(thread.name)}</strong><small>${members.length} 人 · ${escapeHtml(state.worlds.find(row=>row.id===thread.worldId)?.name||'独立世界')}</small></div><button type="button" data-group-settings aria-label="群聊设置">•••</button></header>${thread.announcement&&thread.showAnnouncement!==false?`<div class="group-announcement">公告 · ${escapeHtml(thread.announcement)}</div>`:''}<div class="group-chat-stream" data-group-stream>${messages.map(row=>messageCard(row,state,thread,selectMode,selected)).join('')||'<div class="group-empty">群里还很安静。发一句话，看看谁会接上。</div>'}${generating?'<div class="group-typing">群里有人正在输入…</div>':''}</div><div class="group-bottom">${selectMode?`<div class="group-selection-bar"><button type="button" data-group-cancel-select>取消</button><strong>已选择 ${selected.size} 条</strong><button type="button" data-group-forward ${selected.size?'':'disabled'}>合并转发</button></div>`:''}<div class="group-tools hidden" data-group-tools>${[['sticker','☺','表情包'],['photo','▧','照片'],['location','⌖','位置'],['screen','↗','分享界面'],['call','♧','群通话'],['video-call','▦','群视频'],['redpacket','礼','群红包'],['mention','@','提醒成员']].map(([id,icon,label])=>`<button type="button" data-group-tool="${id}"><span>${icon}</span>${label}</button>`).join('')}</div><form class="group-composer" data-group-composer><button type="button" data-group-more aria-label="展开群聊功能">＋</button><textarea name="text" rows="1" maxlength="1200" placeholder="说点什么… 输入 @ 可以提到某人"></textarea><button type="submit" ${generating?'disabled':''}>发送</button></form></div></section>`;
    if(thread.interfaceCss){const style=document.createElement('style');style.textContent=String(thread.interfaceCss).replace(/<\/?style[^>]*>/gi,'').slice(0,4000);container.prepend(style)}
    applyGroupAppearance(container,thread);
    container.querySelector('[data-group-back]').onclick=()=>navigate('chat');
    container.querySelector('[data-group-settings]').onclick=()=>openGroupSettings(store,thread,()=>render(container,params),navigate);
    container.querySelectorAll('[data-group-route]').forEach(button=>button.onclick=()=>navigate(button.dataset.groupRoute));
    container.querySelectorAll('[data-group-forum-post]').forEach(button=>button.onclick=()=>navigate('forum',{postId:button.dataset.groupForumPost,_parent:{name:'group-chat',params:{id:thread.id}}}));
    container.querySelectorAll('[data-member-memory]').forEach(button=>button.onclick=()=>{const personId=button.dataset.memberMemory;closeSheet();navigate('memory-debug',{personId,memoryOwnerId:accountContext(store.getState(),personId,thread.accountId).memoryOwnerId,_parent:{name:'group-chat',params:{id:thread.id}}})});
    container.querySelectorAll('[data-chat-record]').forEach(button=>button.onclick=()=>{const message=messages.find(row=>row.id===button.dataset.chatRecord);if(message)openChatRecordDetail(message)});
    container.querySelector('[data-group-cancel-select]')?.addEventListener('click',()=>{selectMode=false;selected.clear();render(container,params)});
    container.querySelector('[data-group-forward]')?.addEventListener('click',()=>forwardGroupRecords(store,thread,messages,selected,()=>{selectMode=false;selected.clear();render(container,params)}));
    container.querySelectorAll('[data-group-select]').forEach(button=>button.onclick=()=>{const id=button.dataset.groupSelect;if(selected.has(id))selected.delete(id);else selected.add(id);render(container,params)});
    if(!selectMode)container.querySelectorAll('[data-group-message]').forEach(article=>{let timer,start;const cancel=()=>clearTimeout(timer);article.addEventListener('pointerdown',event=>{if(event.target.closest('button,a'))return;start={x:event.clientX,y:event.clientY};timer=setTimeout(()=>{navigator.vibrate?.(10);selectMode=true;selected.add(article.dataset.groupMessage);render(container,params)},480)});article.addEventListener('pointermove',event=>{if(start&&(Math.abs(event.clientX-start.x)>8||Math.abs(event.clientY-start.y)>8))cancel()});article.addEventListener('pointerup',cancel);article.addEventListener('pointercancel',cancel);article.addEventListener('contextmenu',event=>{event.preventDefault();cancel();selectMode=true;selected.add(article.dataset.groupMessage);render(container,params)})});
    container.querySelector('[data-group-more]').onclick=()=>container.querySelector('[data-group-tools]').classList.toggle('hidden');
    container.querySelectorAll('[data-group-tool]').forEach(button=>button.onclick=()=>openGroupTool(button.dataset.groupTool,store,thread,()=>render(container,params),navigate,container));
    container.querySelectorAll('[data-group-packet]').forEach(button=>button.onclick=()=>{const row=messages.find(item=>item.id===button.dataset.groupPacket);openSheet(`<div class="sheet-title"><h3>群红包 · ¥${Number(row?.amount||0).toFixed(2)}</h3><button class="button ghost" data-sheet-close>关闭</button></div><p>${escapeHtml(row?.text||'')}</p><div class="group-packet-shares">${(row?.shares||[]).map(share=>`<p>${escapeHtml(state.people.find(person=>person.id===share.personId)?.name||'成员')} <strong>¥${Number(share.amount).toFixed(2)}</strong></p>`).join('')}</div>`)});
    const form=container.querySelector('[data-group-composer]');form.onsubmit=async e=>{e.preventDefault();const text=form.elements.text.value.trim();if(!text)return;const row=postGroupMessage(store,thread.id,{speakerId:thread.accountId,text});if(!row)return;form.elements.text.value='';render(container,params);if(generating||thread.allowAiReplies===false)return;generating=true;render(container,params);try{const result=await generateGroupReplies(store,thread.id);if(!result.length)showToast('群里暂时没人接话；可检查模型配置或角色日程')}catch(error){showToast(`群聊回复暂未生成：${error.message}`)}finally{generating=false;if(container.isConnected&&store.getState().currentUserId===thread.accountId)render(container,params)}};
    const stream=container.querySelector('[data-group-stream]');requestAnimationFrame(()=>stream.scrollTop=previousScroll??stream.scrollHeight);
    stream.querySelectorAll('[data-group-media]').forEach(img=>{getMediaUrl(img.dataset.groupMedia).then(url=>{if(url&&img.isConnected)img.src=url})});
  };
}

function messageCard(row,state,thread,selectMode=false,selected=new Set()) {
  const person=state.people.find(item=>item.id===row.speakerId)||{id:row.speakerId,name:'已退出成员',initials:'?'} ,self=row.speakerId===thread.accountId,at=new Date(row.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});
  const content=row.type==='chat-record'?chatRecordCard(row):row.type==='redpacket'?`<button type="button" class="group-message-bubble redpacket" data-group-packet="${escapeHtml(row.id)}"><b>🧧 群红包 ¥${Number(row.amount).toFixed(2)}</b><span>${escapeHtml(row.text)}</span><small>${(row.shares||[]).length} 人拼手气 · 查看份额</small></button>`:row.type==='sticker'?`<div class="group-sticker">${row.stickerUrl?`<img src="${escapeHtml(row.stickerUrl)}" alt="${escapeHtml(row.text)}">`:escapeHtml(row.text)}</div>`:row.type==='photo'?`<div class="group-photo"><img data-group-media="${escapeHtml(row.mediaId||'')}" alt="${escapeHtml(row.text)}"><small>${escapeHtml(row.text)}</small></div>`:row.type==='location'?`<a class="group-message-bubble group-rich-card" href="https://www.openstreetmap.org/?mlat=${encodeURIComponent(row.lat||'')}&mlon=${encodeURIComponent(row.lon||'')}&zoom=16" target="_blank" rel="noopener noreferrer"><b>⌖ ${escapeHtml(row.text)}</b><small>${Number(row.lat||0).toFixed(4)}, ${Number(row.lon||0).toFixed(4)} · 查看地图</small></a>`:row.type==='app-link'?`<button type="button" class="group-message-bubble group-rich-card" data-group-route="${escapeHtml(row.route||'forum')}"><small>↗ 分享界面</small><b>${escapeHtml(row.text)}</b><small>打开对应 App 查看</small></button>`:row.type==='forum-post'?`<button type="button" class="group-message-bubble group-rich-card" data-group-forum-post="${escapeHtml(row.sourceId||'')}"><small>↗ 回声广场 · 帖子</small><b>${escapeHtml(row.text)}</b><small>查看讨论与回应</small></button>`:row.type==='shared-post'?`<button type="button" class="group-message-bubble group-rich-card" data-group-route="tiktok"><small>▶ TikTok 短视频</small><b>${escapeHtml(row.text)}</b><small>去 TikTok 查看</small></button>`:row.type==='group-call'?`<div class="group-message-bubble group-rich-card"><small>♧ 群通话</small><b>${escapeHtml(row.text)}</b></div>`:`<div class="group-message-bubble" style="${escapeHtml(groupMemberBubbleStyle(thread,row.speakerId))}">${escapeHtml(row.text)}</div>`;
  return `<article class="group-message ${self?'mine':''}" data-member="${escapeHtml(row.speakerId)}" data-group-message="${escapeHtml(row.id)}">${selectMode?`<button type="button" class="group-select-hit ${selected.has(row.id)?'active':''}" data-group-select="${escapeHtml(row.id)}" aria-label="${selected.has(row.id)?'取消选择':'选择'}消息">${selected.has(row.id)?'✓':''}</button>`:''}${self?'':`<button type="button" class="group-message-avatar" data-member-memory="${escapeHtml(person.id)}" aria-label="查看${escapeHtml(person.name)}的记忆">${initialsAvatar(person,{...(state.chatProfiles[person.id]||{}),avatarUrl:thread.memberProfiles?.[person.id]?.avatarUrl||state.chatProfiles?.[person.id]?.avatarUrl||person.avatarUrl||''})}</button>`}<div class="group-message-main"><small>${self?escapeHtml(thread.memberProfiles?.[row.speakerId]?.nickname||thread.nicknames[row.speakerId]||person?.chatName||person?.name||'成员'):`<button type="button" class="group-member-memory-link" data-member-memory="${escapeHtml(person.id)}">${escapeHtml(thread.memberProfiles?.[row.speakerId]?.nickname||thread.nicknames[row.speakerId]||person?.chatName||person?.name||'成员')}</button>`} · ${at}</small>${content}</div></article>`;
}

function forwardGroupRecords(store,thread,messages,selected,done){
  if(!selected.size)return;const state=store.getState(),singles=state.conversations.filter(row=>row.userAccountId===state.currentUserId&&!row.hiddenFromList),groups=state.groupThreads.filter(row=>row.accountId===state.currentUserId&&!row.archived&&row.id!==thread.id);
  openSheet(`<div class="sheet-title"><h3>转发群聊天记录</h3><button type="button" class="button ghost" data-sheet-close>取消</button></div><p class="sub">已选择 ${selected.size} 条，发送后对方可以点开查看完整记录。</p><div class="forward-targets">${singles.map(row=>`<label><input type="radio" name="groupForwardTarget" value="single:${escapeHtml(row.id)}"><span>${escapeHtml(state.people.find(person=>person.id===row.personId)?.name||'联系人')}</span></label>`).join('')}${groups.map(row=>`<label><input type="radio" name="groupForwardTarget" value="group:${escapeHtml(row.id)}"><span>${escapeHtml(row.name)} · 群聊</span></label>`).join('')}</div><button type="button" class="button" data-send-group-record>发送聊天记录</button>`,{onReady(sheet){sheet.querySelector('[data-send-group-record]').onclick=()=>{const target=sheet.querySelector('input[name=groupForwardTarget]:checked');if(!target)return showToast('请选择接收会话');const bundle=messages.filter(row=>selected.has(row.id)).map(row=>({role:row.speakerId===thread.accountId?'user':'char',sender:thread.memberProfiles?.[row.speakerId]?.nickname||thread.nicknames?.[row.speakerId]||state.people.find(person=>person.id===row.speakerId)?.name||'成员',text:row.text,type:row.type,time:new Date(row.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})})),title=`${thread.name}的聊天记录`;if(target.value.startsWith('group:')){const id=target.value.slice(6),row=postGroupMessage(store,id,{speakerId:state.currentUserId,text:title,type:'chat-record'});if(!row)return showToast('群聊已失效');store.update(s=>{s.groupMessages[id].find(item=>item.id===row.id).bundle=bundle})}else{const id=target.value.slice(7);store.update(s=>{s.messages[id]||=[];s.messages[id].push({id:crypto.randomUUID(),role:'user',type:'chat-record',text:title,bundle,time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})})})}closeSheet();done();showToast('聊天记录已转发')}}});
}

function openGroupTool(tool,store,thread,done,navigate,container){
  const send=(text,type,extra={})=>{const row=postGroupMessage(store,thread.id,{speakerId:thread.accountId,text,type,sourceId:extra.sourceId||''});if(!row)return;store.update(s=>Object.assign(s.groupMessages[thread.id].find(x=>x.id===row.id),extra));closeSheet();done()};
  if(tool==='redpacket')return openGroupRedpacket(store,thread,done);
  if(tool==='mention'){const people=thread.memberIds.filter(id=>id!==thread.accountId).map(id=>store.getState().people.find(p=>p.id===id)).filter(Boolean);return openSheet(`<div class="sheet-title"><h3>提醒谁</h3><button class="button ghost" data-sheet-close>关闭</button></div><div class="group-picker">${people.map(p=>`<button data-group-mention="${escapeHtml(p.name)}">@${escapeHtml(p.name)}</button>`).join('')}</div>`,{onReady(sheet){sheet.querySelectorAll('[data-group-mention]').forEach(b=>b.onclick=()=>{closeSheet();const input=container.querySelector('[data-group-composer] textarea');input.value+=`@${b.dataset.groupMention} `;input.focus()})}})}
  if(tool==='sticker'){const s=store.getState(),rows=[...(s.stickerLibraries?.global||[]),...(s.stickerLibraries?.user||[]),...thread.memberIds.flatMap(id=>s.stickerLibraries?.characters?.[id]||[])].filter(x=>x?.url).slice(0,80);return openSheet(`<div class="sheet-title"><h3>群表情</h3><button class="button ghost" data-sheet-close>关闭</button></div><div class="group-sticker-picker">${rows.map((x,i)=>`<button data-sticker="${i}"><img src="${escapeHtml(x.url)}" alt="${escapeHtml(x.name||'表情')}"><small>${escapeHtml(x.name||'表情')}</small></button>`).join('')||'<p>可先在聊天设置里上传表情包。</p>'}</div>`,{onReady(sheet){sheet.querySelectorAll('[data-sticker]').forEach(b=>b.onclick=()=>{const x=rows[Number(b.dataset.sticker)];send(`[表情] ${x.name||'表情'}`,'sticker',{stickerUrl:x.url})})}})}
  if(tool==='photo'){const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;if(file.size>12*1024*1024)return showToast('请选择 12MB 以内的图片');try{const saved=await saveMediaBlob(file);send(`照片 · ${file.name}`,'photo',{mediaId:saved.mediaId})}catch(error){showToast(error.message)}};input.click();return}
  if(tool==='location')return openSheet(`<form class="group-location-form"><div class="sheet-title"><h3>分享位置</h3><button type="button" class="button ghost" data-sheet-close>关闭</button></div><label class="field"><span>地点名称</span><input name="name" maxlength="60" placeholder="咖啡馆 / 公园 / 当前地点" required></label><div class="group-coordinates"><label class="field"><span>纬度</span><input name="lat" type="number" step="any" min="-90" max="90" required></label><label class="field"><span>经度</span><input name="lon" type="number" step="any" min="-180" max="180" required></label></div><button type="button" class="button secondary" data-group-geo>使用当前定位</button><button class="button">发送位置</button></form>`,{onReady(sheet){const form=sheet.querySelector('form');sheet.querySelector('[data-group-geo]').onclick=()=>{if(!navigator.geolocation)return showToast('设备不支持定位');navigator.geolocation.getCurrentPosition(p=>{form.elements.lat.value=p.coords.latitude.toFixed(6);form.elements.lon.value=p.coords.longitude.toFixed(6);if(!form.elements.name.value)form.elements.name.value='我在这里'},()=>showToast('未获得定位权限'),{timeout:8000})};form.onsubmit=e=>{e.preventDefault();send(form.elements.name.value.trim(),'location',{lat:Number(form.elements.lat.value),lon:Number(form.elements.lon.value)})}}});
  if(tool==='screen')return openSheet(`<div class="sheet-title"><h3>分享到群里</h3><button class="button ghost" data-sheet-close>关闭</button></div><div class="group-picker">${[['tiktok','映兔 · 正在刷的短视频'],['x-social','瞬语 · 文字时间线'],['forum','回声广场 · 树洞与话题'],['moments','日常圈 · 好友动态']].map(([route,label])=>`<button data-group-app="${route}">${label}</button>`).join('')}</div>`,{onReady(sheet){sheet.querySelectorAll('[data-group-app]').forEach(b=>b.onclick=()=>send(b.textContent.trim(),'app-link',{route:b.dataset.groupApp}))}});
  if(tool==='call'||tool==='video-call')return navigate('group-call',{id:thread.id,mode:tool==='video-call'?'video':'voice'});
}

function openGroupSettings(store,thread,done,navigate) {
  const state=store.getState(),members=thread.memberIds.map(id=>state.people.find(row=>row.id===id)).filter(Boolean),candidates=state.people.filter(row=>['char','npc'].includes(row.type)&&entityWorld(state,row.id)===thread.worldId&&!thread.memberIds.includes(row.id));
  openSheet(`<form class="group-settings-sheet"><div class="sheet-title"><h3>群聊设置</h3><button type="button" class="button ghost" data-sheet-close>关闭</button></div>
  <details open><summary>群资料与公告</summary><label class="field"><span>群名称</span><input name="name" maxlength="28" value="${escapeHtml(thread.name)}"></label><label class="field"><span>我在群里的昵称</span><input name="myNickname" maxlength="24" value="${escapeHtml(thread.nicknames?.[thread.accountId]||'')}"></label><label class="field"><span>群公告</span><textarea name="announcement" rows="3" maxlength="240">${escapeHtml(thread.announcement||'')}</textarea></label></details>
  <details><summary>成员 · ${members.length} 人</summary><div class="group-settings-members">${members.map(row=>`<label><span>${escapeHtml(row.name)}</span>${row.id===thread.accountId?`<button type="button" data-edit-member="${escapeHtml(row.id)}">编辑</button><small>你</small>`:`<button type="button" data-edit-member="${escapeHtml(row.id)}">编辑</button><button type="button" data-remove-member="${escapeHtml(row.id)}">移出</button>`}</label>`).join('')}</div><label class="field"><span>邀请同世界角色</span><select name="invite"><option value="">暂不邀请</option>${candidates.map(row=>`<option value="${escapeHtml(row.id)}">${escapeHtml(row.name)} · ${row.type.toUpperCase()}</option>`).join('')}</select></label></details>
  <details><summary>异地与群聊样式</summary><label class="setting-row"><span>群成员与我异地</span><input type="checkbox" name="longDistance" ${thread.longDistance?'checked':''}></label><div data-group-distance ${thread.longDistance?'':'hidden'}><label class="field"><span>我所在的城市</span><input name="userCity" value="${escapeHtml(thread.userCity||'')}"></label><label class="field"><span>真实地点原型</span><input name="userCityPrototype" value="${escapeHtml(thread.userCityPrototype||'')}"></label></div><label class="field"><span>群聊界面 CSS</span><textarea name="interfaceCss" rows="4" placeholder=".group-chat-shell { background: #e7eff2; }">${escapeHtml(thread.interfaceCss||'')}</textarea></label></details><details><summary>会话与通知</summary><label class="setting-row"><span>置顶群聊</span><input type="checkbox" name="pinned" ${thread.pinned?'checked':''}></label><label class="setting-row"><span>消息免打扰</span><input type="checkbox" name="muted" ${thread.muted?'checked':''}></label><label class="setting-row"><span>在聊天顶部显示公告</span><input type="checkbox" name="showAnnouncement" ${thread.showAnnouncement===false?'':'checked'}></label><label class="setting-row"><span>发送消息后生成角色回复</span><input type="checkbox" name="allowAiReplies" ${thread.allowAiReplies===false?'':'checked'}></label></details>
  <button type="button" class="button secondary" data-group-appearance>聊天背景 · 气泡样式 · 自定义美化</button><button type="button" class="button secondary" data-group-voice-call>发起语音通话</button><button type="button" class="button secondary" data-group-video-call>发起视频通话</button><button class="button">保存设置</button><button type="button" class="button secondary" data-clear-group>清空本机群聊天记录</button><button type="button" class="button secondary" data-leave-group>退出群聊</button></form>`,{onReady(sheet){const form=sheet.querySelector('form');sheet.querySelector('[data-group-appearance]').onclick=()=>{closeSheet();openGroupAppearance(store,thread,done)};form.elements.longDistance.onchange=()=>sheet.querySelector('[data-group-distance]').hidden=!form.elements.longDistance.checked;sheet.querySelectorAll('[data-edit-member]').forEach(button=>button.onclick=()=>{closeSheet();openGroupMemberSettings(store,thread.id,button.dataset.editMember,done,navigate)});sheet.querySelectorAll('[data-remove-member]').forEach(button=>button.onclick=()=>{store.update(s=>{const row=s.groupThreads.find(x=>x.id===thread.id);row.memberIds=row.memberIds.filter(id=>id!==button.dataset.removeMember)});closeSheet();done();showToast('成员已移出')});form.onsubmit=e=>{e.preventDefault();store.update(s=>{const row=s.groupThreads.find(x=>x.id===thread.id);row.name=form.elements.name.value.trim()||row.name;row.nicknames[thread.accountId]=form.elements.myNickname.value.trim();row.announcement=form.elements.announcement.value.trim();row.muted=form.elements.muted.checked;row.pinned=form.elements.pinned.checked;row.showAnnouncement=form.elements.showAnnouncement.checked;row.allowAiReplies=form.elements.allowAiReplies.checked;row.longDistance=form.elements.longDistance.checked;row.userCity=form.elements.userCity.value.trim();row.userCityPrototype=form.elements.userCityPrototype.value.trim();row.interfaceCss=form.elements.interfaceCss.value.slice(0,4000);if(form.elements.invite.value&&!row.memberIds.includes(form.elements.invite.value))row.memberIds.push(form.elements.invite.value)});closeSheet();done();showToast('群聊设置已保存')};sheet.querySelector('[data-group-voice-call]').onclick=()=>{closeSheet();navigate('group-call',{id:thread.id,mode:'voice'})};sheet.querySelector('[data-group-video-call]').onclick=()=>{closeSheet();navigate('group-call',{id:thread.id,mode:'video'})};sheet.querySelector('[data-clear-group]').onclick=()=>{if(!confirm('清空这台设备上的群聊天记录？'))return;store.update(s=>s.groupMessages[thread.id]=[]);closeSheet();done();showToast('本机记录已清空')};sheet.querySelector('[data-leave-group]').onclick=()=>{store.update(s=>{s.groupThreads=s.groupThreads.filter(x=>x.id!==thread.id);delete s.groupMessages[thread.id]});closeSheet();navigate('chat')}}});
  document.querySelectorAll('#modal-root [data-remove-member]').forEach(remove=>{const id=remove.dataset.removeMember,muted=thread.mutedMemberIds?.includes(id);remove.insertAdjacentHTML('beforebegin',`<button type="button" data-mute-member="${escapeHtml(id)}">${muted?'解除禁言':'禁言'}</button>`);const button=remove.previousElementSibling;button.onclick=()=>{store.update(s=>{const row=s.groupThreads.find(x=>x.id===thread.id);row.mutedMemberIds||=[];row.mutedMemberIds=row.mutedMemberIds.includes(id)?row.mutedMemberIds.filter(x=>x!==id):[...row.mutedMemberIds,id]});const blocked=store.getState().groupThreads.find(x=>x.id===thread.id)?.mutedMemberIds?.includes(id);button.textContent=blocked?'解除禁言':'禁言';showToast(blocked?'该成员已禁言':'已解除禁言')}});
}

function openGroupRedpacket(store,thread,done) {
  openSheet(`<form class="group-redpacket-sheet"><div class="sheet-title"><h3>发群红包</h3><button type="button" class="button ghost" data-sheet-close>关闭</button></div><p>余额会立即扣除。份额按确定的随机种子分给其他成员。</p><label class="field"><span>总金额</span><input name="amount" type="number" min="0.01" max="200" step="0.01" required placeholder="20.00"></label><label class="field"><span>祝福语</span><input name="note" maxlength="40" value="大家一起开心"></label><button class="button">发送红包</button></form>`,{onReady(sheet){sheet.querySelector('form').onsubmit=e=>{e.preventDefault();const form=e.currentTarget,amount=Math.round(Number(form.elements.amount.value)*100)/100,current=store.getState(),live=current.groupThreads.find(row=>row.id===thread.id&&row.accountId===current.currentUserId&&!row.archived),recipientIds=live?.memberIds.filter(id=>id!==thread.accountId)||[];if(!live||!recipientIds.length)return showToast('群聊已结束或没有可领取的成员');if(!Number.isFinite(amount)||amount<.01||amount>200)return showToast('请输入 0.01—200 元');if(amount*100<recipientIds.length)return showToast('金额至少要让每人分到一分钱');const messageId=crypto.randomUUID();if(!walletDebit(store,{amount,kind:'redpacket',title:`${thread.name} 群红包`,conversationId:thread.id,messageId,note:form.elements.note.value}))return showToast('余额不足');const row=postGroupMessage(store,thread.id,{speakerId:thread.accountId,text:form.elements.note.value||'恭喜发财',type:'redpacket',amount,messageId});const shares=splitAmount(amount,recipientIds,messageId);store.update(s=>{const target=s.groupMessages[thread.id].find(item=>item.id===row.id);target.shares=shares});closeSheet();done();showToast('群红包已发送')}}});
}

export function splitAmount(amount,ids,seed) {
  const cents=Math.round(amount*100),weights=ids.map((_,i)=>1+((seed.charCodeAt(i%seed.length)||17)*(i+3)%13)),sum=weights.reduce((a,b)=>a+b,0);let remaining=cents;
  return ids.map((id,i)=>{const share=i===ids.length-1?remaining:Math.max(1,Math.min(remaining-(ids.length-i-1),Math.floor(cents*weights[i]/sum)));remaining-=share;return {personId:id,amount:share/100}});
}
