import { escapeHtml, initialsAvatar, showToast, openSheet, closeSheet } from './core/ui.js';
import { walletDebit } from './wallet-v2.js';
import { createGroupThread, postGroupMessage, generateGroupReplies } from './group-model.js';
import { ensureWorldEngine, entityWorld } from './world-engine.js';

export function openCreateGroupSheet(store,navigate) {
  const state=ensureWorldEngine(store.getState()),worlds=[...new Map(state.chatGroups.map(group=>[group.worldId, state.worlds.find(row=>row.id===group.worldId)||{id:group.worldId,name:group.name}])).values()].filter(row=>row.id);
  openSheet(`<form class="group-create-sheet"><div class="sheet-title"><h3>创建群聊</h3><button type="button" class="button ghost" data-sheet-close>关闭</button></div><label class="field"><span>群名称</span><input name="name" maxlength="28" required placeholder="例如：周末去哪儿"></label><label class="field"><span>所属世界</span><select name="worldId">${worlds.map(row=>`<option value="${escapeHtml(row.id)}">${escapeHtml(row.name)}</option>`).join('')}</select></label><div class="group-member-picker" data-members></div><p class="sub">选择同一世界的至少两位 CHAR / NPC。入群不等于加好友；NPC 只有成为好友才会私聊你。</p><button class="button">创建群聊</button></form>`,{onReady(sheet){const form=sheet.querySelector('form'),members=sheet.querySelector('[data-members]');const draw=()=>{const worldId=form.elements.worldId.value;members.innerHTML=state.people.filter(row=>['char','npc'].includes(row.type)&&entityWorld(state,row.id)===worldId).map(row=>`<label><input type="checkbox" name="member" value="${escapeHtml(row.id)}"><span>${initialsAvatar(row,state.chatProfiles[row.id]||{})}</span><strong>${escapeHtml(row.name)}</strong><small>${row.type.toUpperCase()}</small></label>`).join('')||'<p>这个世界还没有角色，请先在联系人中新建。</p>'};form.elements.worldId.onchange=draw;draw();form.onsubmit=e=>{e.preventDefault();try{const data=new FormData(form),thread=createGroupThread(store,{name:data.get('name'),worldId:data.get('worldId'),memberIds:data.getAll('member')});closeSheet();navigate('group-chat',{id:thread.id})}catch(error){showToast(error.message)}}}});
}

export function createGroupChatRenderer({store,navigate}) {
  let generating=false;
  return function render(container,params={}) {
    const state=ensureWorldEngine(store.getState()),thread=state.groupThreads.find(row=>row.id===(params.id||state.groupThreads.find(item=>item.accountId===state.currentUserId&&!item.archived)?.id)&&row.accountId===state.currentUserId&&!row.archived);if(!thread)return navigate('chat');
    if(thread.unread)store.update(s=>{const row=s.groupThreads.find(x=>x.id===thread.id);if(row)row.unread=0});
    const members=thread.memberIds.map(id=>state.people.find(row=>row.id===id)).filter(Boolean),messages=state.groupMessages[thread.id]||[];
    container.className='app-view group-chat-view';
    container.innerHTML=`<section class="group-chat-shell"><header class="group-chat-head"><button type="button" data-group-back aria-label="返回聊天列表">‹</button><div><strong>${escapeHtml(thread.name)}</strong><small>${members.length} 人 · ${escapeHtml(state.worlds.find(row=>row.id===thread.worldId)?.name||'独立世界')}</small></div><button type="button" data-group-settings aria-label="群聊设置">•••</button></header>${thread.announcement?`<div class="group-announcement">公告 · ${escapeHtml(thread.announcement)}</div>`:''}<div class="group-chat-stream" data-group-stream>${messages.map(row=>messageCard(row,state,thread)).join('')||'<div class="group-empty">群里还很安静。发一句话，看看谁会接上。</div>'}${generating?'<div class="group-typing">群里有人正在输入…</div>':''}</div><form class="group-composer" data-group-composer><button type="button" data-group-redpacket aria-label="发群红包">礼</button><textarea name="text" rows="1" maxlength="1200" placeholder="说点什么… 输入 @ 可以提到某人"></textarea><button type="submit" ${generating?'disabled':''}>发送</button></form></section>`;
    container.querySelector('[data-group-back]').onclick=()=>navigate('chat');
    container.querySelector('[data-group-settings]').onclick=()=>openGroupSettings(store,thread,()=>render(container,params),navigate);
    container.querySelector('[data-group-redpacket]').onclick=()=>openGroupRedpacket(store,thread,()=>render(container,params));
    container.querySelectorAll('[data-group-packet]').forEach(button=>button.onclick=()=>{const row=messages.find(item=>item.id===button.dataset.groupPacket);openSheet(`<div class="sheet-title"><h3>群红包 · ¥${Number(row?.amount||0).toFixed(2)}</h3><button class="button ghost" data-sheet-close>关闭</button></div><p>${escapeHtml(row?.text||'')}</p><div class="group-packet-shares">${(row?.shares||[]).map(share=>`<p>${escapeHtml(state.people.find(person=>person.id===share.personId)?.name||'成员')} <strong>¥${Number(share.amount).toFixed(2)}</strong></p>`).join('')}</div>`)});
    const form=container.querySelector('[data-group-composer]');form.onsubmit=async e=>{e.preventDefault();const text=form.elements.text.value.trim();if(!text)return;const row=postGroupMessage(store,thread.id,{speakerId:thread.accountId,text});if(!row)return;form.elements.text.value='';render(container,params);if(generating)return;generating=true;render(container,params);try{const result=await generateGroupReplies(store,thread.id);if(!result.length)showToast('群里暂时没人接话；可检查模型配置或角色日程')}catch(error){showToast(`群聊回复暂未生成：${error.message}`)}finally{generating=false;if(container.isConnected&&store.getState().currentUserId===thread.accountId)render(container,params)}};
    const stream=container.querySelector('[data-group-stream]');requestAnimationFrame(()=>stream.scrollTop=stream.scrollHeight);
  };
}

function messageCard(row,state,thread) {
  const person=state.people.find(item=>item.id===row.speakerId)||{id:row.speakerId,name:'已退出成员',initials:'?'} ,self=row.speakerId===thread.accountId,at=new Date(row.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});
  return `<article class="group-message ${self?'mine':''}">${self?'':`<span class="group-message-avatar">${initialsAvatar(person,state.chatProfiles[person.id]||{})}</span>`}<div class="group-message-main"><small>${escapeHtml(thread.nicknames[row.speakerId]||person?.chatName||person?.name||'成员')} · ${at}</small>${row.type==='redpacket'?`<button type="button" class="group-message-bubble redpacket" data-group-packet="${escapeHtml(row.id)}"><b>🧧 群红包 ¥${Number(row.amount).toFixed(2)}</b><span>${escapeHtml(row.text)}</span><small>${(row.shares||[]).length} 人拼手气 · 查看份额</small></button>`:`<div class="group-message-bubble">${escapeHtml(row.text)}</div>`}</div></article>`;
}

function openGroupSettings(store,thread,done,navigate) {
  const state=store.getState(),members=thread.memberIds.map(id=>state.people.find(row=>row.id===id)).filter(Boolean),candidates=state.people.filter(row=>['char','npc'].includes(row.type)&&entityWorld(state,row.id)===thread.worldId&&!thread.memberIds.includes(row.id));
  openSheet(`<form class="group-settings-sheet"><div class="sheet-title"><h3>群聊设置</h3><button type="button" class="button ghost" data-sheet-close>关闭</button></div><label class="field"><span>群名称</span><input name="name" maxlength="28" value="${escapeHtml(thread.name)}"></label><label class="field"><span>我在群里的昵称</span><input name="myNickname" maxlength="24" value="${escapeHtml(thread.nicknames?.[thread.accountId]||'')}"></label><label class="field"><span>群公告</span><textarea name="announcement" rows="3" maxlength="240">${escapeHtml(thread.announcement||'')}</textarea></label><div class="group-settings-members"><strong>成员</strong>${members.map(row=>`<label><span>${escapeHtml(row.name)}</span>${row.id===thread.accountId?'<small>你</small>':`<button type="button" data-remove-member="${escapeHtml(row.id)}">移出</button>`}</label>`).join('')}</div><label class="field"><span>邀请同世界角色</span><select name="invite"><option value="">暂不邀请</option>${candidates.map(row=>`<option value="${escapeHtml(row.id)}">${escapeHtml(row.name)} · ${row.type.toUpperCase()}</option>`).join('')}</select></label><label class="setting-row"><span>消息免打扰</span><input type="checkbox" name="muted" ${thread.muted?'checked':''}></label><button class="button">保存</button><button type="button" class="button secondary" data-leave-group>退出群聊</button></form>`,{onReady(sheet){const form=sheet.querySelector('form');sheet.querySelectorAll('[data-remove-member]').forEach(button=>button.onclick=()=>{store.update(s=>{const row=s.groupThreads.find(x=>x.id===thread.id);row.memberIds=row.memberIds.filter(id=>id!==button.dataset.removeMember)});closeSheet();done();showToast('成员已移出')});form.onsubmit=e=>{e.preventDefault();store.update(s=>{const row=s.groupThreads.find(x=>x.id===thread.id);row.name=form.elements.name.value.trim()||row.name;row.nicknames[thread.accountId]=form.elements.myNickname.value.trim();row.announcement=form.elements.announcement.value.trim();row.muted=form.elements.muted.checked;if(form.elements.invite.value&&!row.memberIds.includes(form.elements.invite.value))row.memberIds.push(form.elements.invite.value)});closeSheet();done();showToast('群聊设置已保存')};sheet.querySelector('[data-leave-group]').onclick=()=>{store.update(s=>{s.groupThreads=s.groupThreads.filter(x=>x.id!==thread.id);delete s.groupMessages[thread.id]});closeSheet();navigate('chat')}}});
}

function openGroupRedpacket(store,thread,done) {
  openSheet(`<form class="group-redpacket-sheet"><div class="sheet-title"><h3>发群红包</h3><button type="button" class="button ghost" data-sheet-close>关闭</button></div><p>余额会立即扣除。份额按确定的随机种子分给其他成员。</p><label class="field"><span>总金额</span><input name="amount" type="number" min="0.01" max="200" step="0.01" required placeholder="20.00"></label><label class="field"><span>祝福语</span><input name="note" maxlength="40" value="大家一起开心"></label><button class="button">发送红包</button></form>`,{onReady(sheet){sheet.querySelector('form').onsubmit=e=>{e.preventDefault();const form=e.currentTarget,amount=Math.round(Number(form.elements.amount.value)*100)/100,current=store.getState(),live=current.groupThreads.find(row=>row.id===thread.id&&row.accountId===current.currentUserId&&!row.archived),recipientIds=live?.memberIds.filter(id=>id!==thread.accountId)||[];if(!live||!recipientIds.length)return showToast('群聊已结束或没有可领取的成员');if(!Number.isFinite(amount)||amount<.01||amount>200)return showToast('请输入 0.01—200 元');if(amount*100<recipientIds.length)return showToast('金额至少要让每人分到一分钱');const messageId=crypto.randomUUID();if(!walletDebit(store,{amount,kind:'redpacket',title:`${thread.name} 群红包`,conversationId:thread.id,messageId,note:form.elements.note.value}))return showToast('余额不足');const row=postGroupMessage(store,thread.id,{speakerId:thread.accountId,text:form.elements.note.value||'恭喜发财',type:'redpacket',amount,messageId});const shares=splitAmount(amount,recipientIds,messageId);store.update(s=>{const target=s.groupMessages[thread.id].find(item=>item.id===row.id);target.shares=shares});closeSheet();done();showToast('群红包已发送')}}});
}

export function splitAmount(amount,ids,seed) {
  const cents=Math.round(amount*100),weights=ids.map((_,i)=>1+((seed.charCodeAt(i%seed.length)||17)*(i+3)%13)),sum=weights.reduce((a,b)=>a+b,0);let remaining=cents;
  return ids.map((id,i)=>{const share=i===ids.length-1?remaining:Math.max(1,Math.min(remaining-(ids.length-i-1),Math.floor(cents*weights[i]/sum)));remaining-=share;return {personId:id,amount:share/100}});
}
