import { escapeHtml, initialsAvatar, showToast, openSheet, closeSheet } from './core/ui.js';
import { walletDebit } from './wallet-v2.js';
import { createGroupThread, postGroupMessage, generateGroupReplies } from './group-model.js';
import { ensureWorldEngine, entityWorld } from './world-engine.js';
import { saveMediaBlob, getMediaUrl } from './media-store.js';
import { sendToModel } from './integrations/ai-client.js';

export function openCreateGroupSheet(store,navigate) {
  const state=ensureWorldEngine(store.getState()),worlds=[...new Map(state.chatGroups.map(group=>[group.worldId, state.worlds.find(row=>row.id===group.worldId)||{id:group.worldId,name:group.name}])).values()].filter(row=>row.id);
  openSheet(`<form class="group-create-sheet"><div class="sheet-title"><h3>创建群聊</h3><button type="button" class="button ghost" data-sheet-close>关闭</button></div><label class="field"><span>群名称</span><input name="name" maxlength="28" required placeholder="例如：周末去哪儿"></label><label class="field"><span>所属世界</span><select name="worldId">${worlds.map(row=>`<option value="${escapeHtml(row.id)}">${escapeHtml(row.name)}</option>`).join('')}</select></label><div class="group-member-picker" data-members></div><p class="sub">选择同一世界的至少两位 CHAR / NPC。入群不等于加好友；NPC 只有成为好友才会私聊你。</p><button class="button">创建群聊</button></form>`,{onReady(sheet){const form=sheet.querySelector('form'),members=sheet.querySelector('[data-members]');const draw=()=>{const worldId=form.elements.worldId.value;members.innerHTML=state.people.filter(row=>['char','npc'].includes(row.type)&&entityWorld(state,row.id)===worldId).map(row=>`<label><input type="checkbox" name="member" value="${escapeHtml(row.id)}"><span>${initialsAvatar(row,state.chatProfiles[row.id]||{})}</span><strong>${escapeHtml(row.name)}</strong><small>${row.type.toUpperCase()}</small></label>`).join('')||'<p>这个世界还没有角色，请先在联系人中新建。</p>'};form.elements.worldId.onchange=draw;draw();form.onsubmit=e=>{e.preventDefault();try{const data=new FormData(form),thread=createGroupThread(store,{name:data.get('name'),worldId:data.get('worldId'),memberIds:data.getAll('member')});closeSheet();navigate('group-chat',{id:thread.id})}catch(error){showToast(error.message)}}}});
}

export function createGroupChatRenderer({store,navigate}) {
  let generating=false;
  return function render(container,params={}) {
    const state=ensureWorldEngine(store.getState()),thread=state.groupThreads.find(row=>row.id===(params.id||state.groupThreads.find(item=>item.accountId===state.currentUserId&&!item.archived)?.id)&&row.accountId===state.currentUserId&&!row.archived);if(!thread)return navigate('chat');
    if(thread.unread)store.update(s=>{const row=s.groupThreads.find(x=>x.id===thread.id);if(row)row.unread=0});
    const members=thread.memberIds.map(id=>state.people.find(row=>row.id===id)).filter(Boolean),messages=state.groupMessages[thread.id]||[];
    container.className='app-view group-chat-view';
    container.innerHTML=`<section class="group-chat-shell"><header class="group-chat-head"><button type="button" data-group-back aria-label="返回聊天列表">‹</button><div><strong>${escapeHtml(thread.name)}</strong><small>${members.length} 人 · ${escapeHtml(state.worlds.find(row=>row.id===thread.worldId)?.name||'独立世界')}</small></div><button type="button" data-group-settings aria-label="群聊设置">•••</button></header>${thread.announcement&&thread.showAnnouncement!==false?`<div class="group-announcement">公告 · ${escapeHtml(thread.announcement)}</div>`:''}<div class="group-chat-stream" data-group-stream>${messages.map(row=>messageCard(row,state,thread)).join('')||'<div class="group-empty">群里还很安静。发一句话，看看谁会接上。</div>'}${generating?'<div class="group-typing">群里有人正在输入…</div>':''}</div><div class="group-bottom"><div class="group-tools hidden" data-group-tools>${[['sticker','☺','表情包'],['photo','▧','照片'],['location','⌖','位置'],['screen','↗','分享界面'],['call','♧','群通话'],['redpacket','礼','群红包'],['mention','@','提醒成员']].map(([id,icon,label])=>`<button type="button" data-group-tool="${id}"><span>${icon}</span>${label}</button>`).join('')}</div><form class="group-composer" data-group-composer><button type="button" data-group-more aria-label="展开群聊功能">＋</button><textarea name="text" rows="1" maxlength="1200" placeholder="说点什么… 输入 @ 可以提到某人"></textarea><button type="submit" ${generating?'disabled':''}>发送</button></form></div></section>`;
    container.querySelector('[data-group-back]').onclick=()=>navigate('chat');
    container.querySelector('[data-group-settings]').onclick=()=>openGroupSettings(store,thread,()=>render(container,params),navigate);
    container.querySelectorAll('[data-group-route]').forEach(button=>button.onclick=()=>navigate(button.dataset.groupRoute));
    container.querySelector('[data-group-more]').onclick=()=>container.querySelector('[data-group-tools]').classList.toggle('hidden');
    container.querySelectorAll('[data-group-tool]').forEach(button=>button.onclick=()=>openGroupTool(button.dataset.groupTool,store,thread,()=>render(container,params),navigate,container));
    container.querySelectorAll('[data-group-packet]').forEach(button=>button.onclick=()=>{const row=messages.find(item=>item.id===button.dataset.groupPacket);openSheet(`<div class="sheet-title"><h3>群红包 · ¥${Number(row?.amount||0).toFixed(2)}</h3><button class="button ghost" data-sheet-close>关闭</button></div><p>${escapeHtml(row?.text||'')}</p><div class="group-packet-shares">${(row?.shares||[]).map(share=>`<p>${escapeHtml(state.people.find(person=>person.id===share.personId)?.name||'成员')} <strong>¥${Number(share.amount).toFixed(2)}</strong></p>`).join('')}</div>`)});
    const form=container.querySelector('[data-group-composer]');form.onsubmit=async e=>{e.preventDefault();const text=form.elements.text.value.trim();if(!text)return;const row=postGroupMessage(store,thread.id,{speakerId:thread.accountId,text});if(!row)return;form.elements.text.value='';render(container,params);if(generating||thread.allowAiReplies===false)return;generating=true;render(container,params);try{const result=await generateGroupReplies(store,thread.id);if(!result.length)showToast('群里暂时没人接话；可检查模型配置或角色日程')}catch(error){showToast(`群聊回复暂未生成：${error.message}`)}finally{generating=false;if(container.isConnected&&store.getState().currentUserId===thread.accountId)render(container,params)}};
    const stream=container.querySelector('[data-group-stream]');requestAnimationFrame(()=>stream.scrollTop=stream.scrollHeight);
    stream.querySelectorAll('[data-group-media]').forEach(img=>{getMediaUrl(img.dataset.groupMedia).then(url=>{if(url&&img.isConnected)img.src=url})});
  };
}

function messageCard(row,state,thread) {
  const person=state.people.find(item=>item.id===row.speakerId)||{id:row.speakerId,name:'已退出成员',initials:'?'} ,self=row.speakerId===thread.accountId,at=new Date(row.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});
  const content=row.type==='redpacket'?`<button type="button" class="group-message-bubble redpacket" data-group-packet="${escapeHtml(row.id)}"><b>🧧 群红包 ¥${Number(row.amount).toFixed(2)}</b><span>${escapeHtml(row.text)}</span><small>${(row.shares||[]).length} 人拼手气 · 查看份额</small></button>`:row.type==='sticker'?`<div class="group-sticker">${row.stickerUrl?`<img src="${escapeHtml(row.stickerUrl)}" alt="${escapeHtml(row.text)}">`:escapeHtml(row.text)}</div>`:row.type==='photo'?`<div class="group-photo"><img data-group-media="${escapeHtml(row.mediaId||'')}" alt="${escapeHtml(row.text)}"><small>${escapeHtml(row.text)}</small></div>`:row.type==='location'?`<a class="group-message-bubble group-rich-card" href="https://www.openstreetmap.org/?mlat=${encodeURIComponent(row.lat||'')}&mlon=${encodeURIComponent(row.lon||'')}&zoom=16" target="_blank" rel="noopener noreferrer"><b>⌖ ${escapeHtml(row.text)}</b><small>${Number(row.lat||0).toFixed(4)}, ${Number(row.lon||0).toFixed(4)} · 查看地图</small></a>`:row.type==='app-link'?`<button type="button" class="group-message-bubble group-rich-card" data-group-route="${escapeHtml(row.route||'forum')}"><small>↗ 分享界面</small><b>${escapeHtml(row.text)}</b><small>打开对应 App 查看</small></button>`:row.type==='shared-post'?`<button type="button" class="group-message-bubble group-rich-card" data-group-route="tiktok"><small>▶ TikTok 短视频</small><b>${escapeHtml(row.text)}</b><small>去 TikTok 查看</small></button>`:row.type==='group-call'?`<div class="group-message-bubble group-rich-card"><small>♧ 群通话</small><b>${escapeHtml(row.text)}</b></div>`:`<div class="group-message-bubble">${escapeHtml(row.text)}</div>`;
  return `<article class="group-message ${self?'mine':''}">${self?'':`<span class="group-message-avatar">${initialsAvatar(person,state.chatProfiles[person.id]||{})}</span>`}<div class="group-message-main"><small>${escapeHtml(thread.nicknames[row.speakerId]||person?.chatName||person?.name||'成员')} · ${at}</small>${content}</div></article>`;
}

function openGroupTool(tool,store,thread,done,navigate,container){
  const send=(text,type,extra={})=>{const row=postGroupMessage(store,thread.id,{speakerId:thread.accountId,text,type,sourceId:extra.sourceId||''});if(!row)return;store.update(s=>Object.assign(s.groupMessages[thread.id].find(x=>x.id===row.id),extra));closeSheet();done()};
  if(tool==='redpacket')return openGroupRedpacket(store,thread,done);
  if(tool==='mention'){const people=thread.memberIds.filter(id=>id!==thread.accountId).map(id=>store.getState().people.find(p=>p.id===id)).filter(Boolean);return openSheet(`<div class="sheet-title"><h3>提醒谁</h3><button class="button ghost" data-sheet-close>关闭</button></div><div class="group-picker">${people.map(p=>`<button data-group-mention="${escapeHtml(p.name)}">@${escapeHtml(p.name)}</button>`).join('')}</div>`,{onReady(sheet){sheet.querySelectorAll('[data-group-mention]').forEach(b=>b.onclick=()=>{closeSheet();const input=container.querySelector('[data-group-composer] textarea');input.value+=`@${b.dataset.groupMention} `;input.focus()})}})}
  if(tool==='sticker'){const s=store.getState(),rows=[...(s.stickerLibraries?.global||[]),...(s.stickerLibraries?.user||[]),...thread.memberIds.flatMap(id=>s.stickerLibraries?.characters?.[id]||[])].filter(x=>x?.url).slice(0,80);return openSheet(`<div class="sheet-title"><h3>群表情</h3><button class="button ghost" data-sheet-close>关闭</button></div><div class="group-sticker-picker">${rows.map((x,i)=>`<button data-sticker="${i}"><img src="${escapeHtml(x.url)}" alt="${escapeHtml(x.name||'表情')}"><small>${escapeHtml(x.name||'表情')}</small></button>`).join('')||'<p>可先在聊天设置里上传表情包。</p>'}</div>`,{onReady(sheet){sheet.querySelectorAll('[data-sticker]').forEach(b=>b.onclick=()=>{const x=rows[Number(b.dataset.sticker)];send(`[表情] ${x.name||'表情'}`,'sticker',{stickerUrl:x.url})})}})}
  if(tool==='photo'){const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;if(file.size>12*1024*1024)return showToast('请选择 12MB 以内的图片');try{const saved=await saveMediaBlob(file);send(`照片 · ${file.name}`,'photo',{mediaId:saved.mediaId})}catch(error){showToast(error.message)}};input.click();return}
  if(tool==='location')return openSheet(`<form class="group-location-form"><div class="sheet-title"><h3>分享位置</h3><button type="button" class="button ghost" data-sheet-close>关闭</button></div><label class="field"><span>地点名称</span><input name="name" maxlength="60" placeholder="咖啡馆 / 公园 / 当前地点" required></label><div class="group-coordinates"><label class="field"><span>纬度</span><input name="lat" type="number" step="any" min="-90" max="90" required></label><label class="field"><span>经度</span><input name="lon" type="number" step="any" min="-180" max="180" required></label></div><button type="button" class="button secondary" data-group-geo>使用当前定位</button><button class="button">发送位置</button></form>`,{onReady(sheet){const form=sheet.querySelector('form');sheet.querySelector('[data-group-geo]').onclick=()=>{if(!navigator.geolocation)return showToast('设备不支持定位');navigator.geolocation.getCurrentPosition(p=>{form.elements.lat.value=p.coords.latitude.toFixed(6);form.elements.lon.value=p.coords.longitude.toFixed(6);if(!form.elements.name.value)form.elements.name.value='我在这里'},()=>showToast('未获得定位权限'),{timeout:8000})};form.onsubmit=e=>{e.preventDefault();send(form.elements.name.value.trim(),'location',{lat:Number(form.elements.lat.value),lon:Number(form.elements.lon.value)})}}});
  if(tool==='screen')return openSheet(`<div class="sheet-title"><h3>分享到群里</h3><button class="button ghost" data-sheet-close>关闭</button></div><div class="group-picker">${[['tiktok','TikTok · 正在刷的短视频'],['x-social','X · 文字时间线'],['forum','论坛 · 树洞与话题'],['moments','朋友圈 · 好友动态']].map(([route,label])=>`<button data-group-app="${route}">${label}</button>`).join('')}</div>`,{onReady(sheet){sheet.querySelectorAll('[data-group-app]').forEach(b=>b.onclick=()=>send(b.textContent.trim(),'app-link',{route:b.dataset.groupApp}))}});
  if(tool==='call')return openGroupCall(store,thread,done);
}

function openGroupCall(store,thread,done){
  let stream=null,started=Date.now(),timer,busy=false;
  const members=thread.memberIds.map(id=>store.getState().people.find(p=>p.id===id)).filter(Boolean),log=[];
  const cleanup=()=>{clearInterval(timer);stream?.getTracks().forEach(t=>t.stop());globalThis.speechSynthesis?.cancel()};
  const finish=()=>{if(!document.querySelector('[data-group-call]'))return;cleanup();const seconds=Math.max(1,Math.round((Date.now()-started)/1000)),row=postGroupMessage(store,thread.id,{speakerId:thread.accountId,text:`群通话 · ${Math.floor(seconds/60)}分${seconds%60}秒`,type:'group-call'});if(row)store.update(s=>{s.groupMessages[thread.id].find(x=>x.id===row.id).transcript=log.slice(-30)});closeSheet();done()};
  openSheet(`<div class="group-call-room" data-group-call><small>GROUP CALL / ${escapeHtml(thread.name)}</small><h3>群通话</h3><p>角色通过已配置的模型接话；语音由本机朗读。麦克风和摄像头只在本机打开。</p><div class="group-call-members">${members.map(p=>`<span>${initialsAvatar(p,store.getState().chatProfiles[p.id]||{})}<small>${escapeHtml(p.name)}</small></span>`).join('')}</div><time data-call-time>00:00</time><div class="group-call-controls"><button data-call-mic>打开麦克风</button><button data-call-camera>打开摄像头</button><button data-call-end>结束通话</button></div><video data-call-preview autoplay muted playsinline></video><div class="group-call-log" data-call-log></div><form data-call-say><input name="text" maxlength="200" placeholder="在通话里说一句…" required><button>说话</button></form><label class="group-call-voice"><input type="checkbox" data-call-voice checked> 朗读角色回应</label></div>`,{onReady(sheet){
    timer=setInterval(()=>{const sec=Math.floor((Date.now()-started)/1000),time=sheet.querySelector('[data-call-time]');if(time)time.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;else cleanup()},1000);
    sheet.querySelector('[data-call-end]').onclick=finish;
    sheet.querySelector('[data-call-mic]').onclick=async e=>{try{if(stream?.getAudioTracks().length){stream.getAudioTracks().forEach(t=>t.enabled=!t.enabled);e.target.textContent=stream.getAudioTracks()[0].enabled?'关闭麦克风':'打开麦克风'}else{const audio=await navigator.mediaDevices.getUserMedia({audio:true});stream=new MediaStream([...(stream?.getTracks()||[]),...audio.getAudioTracks()]);e.target.textContent='关闭麦克风'}}catch{showToast('未获得麦克风权限')}};
    sheet.querySelector('[data-call-camera]').onclick=async e=>{try{if(stream?.getVideoTracks().length){stream.getVideoTracks().forEach(t=>t.stop());stream=stream.getAudioTracks().length?new MediaStream(stream.getAudioTracks()):null;sheet.querySelector('video').srcObject=null;e.target.textContent='打开摄像头'}else{const video=await navigator.mediaDevices.getUserMedia({video:true});stream=new MediaStream([...(stream?.getTracks()||[]),...video.getVideoTracks()]);sheet.querySelector('video').srcObject=stream;e.target.textContent='关闭摄像头'}}catch{showToast('未获得摄像头权限')}};
    sheet.querySelector('[data-call-say]').onsubmit=async e=>{e.preventDefault();if(busy)return;const form=e.currentTarget,text=form.elements.text.value.trim();if(!text)return;form.elements.text.value='';log.push({speakerId:thread.accountId,text});draw();const state=store.getState(),model=state.modelProfiles.find(p=>p.id===state.activeModelProfileId),allowed=members.filter(p=>p.id!==thread.accountId);if(!model?.apiKey||!model?.model)return showToast('请先配置模型 API');busy=true;try{const prompt='模拟真实多人群通话，最多两位在场角色自然接话；只使用给定角色 ID，不替 USER 说话，不知道私密信息。只返回 JSON：{"messages":[{"speakerId":"角色ID","text":"口语短句"}]}。';const raw=await sendToModel(model,[{role:'user',text:JSON.stringify({group:thread.name,members:allowed.map(p=>({id:p.id,name:p.name,persona:p.persona||p.personality||p.note})),recent:log.slice(-8),groupRecent:(state.groupMessages[thread.id]||[]).slice(-6).map(r=>r.text)})}],prompt),data=JSON.parse(String(raw).match(/\{[\s\S]*\}/)?.[0]||'{}');for(const line of (Array.isArray(data.messages)?data.messages:[]).slice(0,3)){if(!allowed.some(p=>p.id===line.speakerId)||!line.text)continue;log.push({speakerId:line.speakerId,text:String(line.text).slice(0,160)});draw();if(sheet.querySelector('[data-call-voice]')?.checked&&globalThis.speechSynthesis){const utterance=new SpeechSynthesisUtterance(line.text);utterance.lang='zh-CN';speechSynthesis.speak(utterance)}}}catch(error){showToast(`通话回应失败：${error.message}`)}finally{busy=false}};
    function draw(){const box=sheet.querySelector('[data-call-log]');box.innerHTML=log.slice(-12).map(row=>`<p><b>${escapeHtml(members.find(p=>p.id===row.speakerId)?.name||'成员')}</b> ${escapeHtml(row.text)}</p>`).join('');box.scrollTop=box.scrollHeight}
  }});
}

function openGroupSettings(store,thread,done,navigate) {
  const state=store.getState(),members=thread.memberIds.map(id=>state.people.find(row=>row.id===id)).filter(Boolean),candidates=state.people.filter(row=>['char','npc'].includes(row.type)&&entityWorld(state,row.id)===thread.worldId&&!thread.memberIds.includes(row.id));
  openSheet(`<form class="group-settings-sheet"><div class="sheet-title"><h3>群聊设置</h3><button type="button" class="button ghost" data-sheet-close>关闭</button></div>
  <details open><summary>群资料与公告</summary><label class="field"><span>群名称</span><input name="name" maxlength="28" value="${escapeHtml(thread.name)}"></label><label class="field"><span>我在群里的昵称</span><input name="myNickname" maxlength="24" value="${escapeHtml(thread.nicknames?.[thread.accountId]||'')}"></label><label class="field"><span>群公告</span><textarea name="announcement" rows="3" maxlength="240">${escapeHtml(thread.announcement||'')}</textarea></label></details>
  <details><summary>成员 · ${members.length} 人</summary><div class="group-settings-members">${members.map(row=>`<label><span>${escapeHtml(row.name)}</span>${row.id===thread.accountId?'<small>你</small>':`<button type="button" data-remove-member="${escapeHtml(row.id)}">移出</button>`}</label>`).join('')}</div><label class="field"><span>邀请同世界角色</span><select name="invite"><option value="">暂不邀请</option>${candidates.map(row=>`<option value="${escapeHtml(row.id)}">${escapeHtml(row.name)} · ${row.type.toUpperCase()}</option>`).join('')}</select></label></details>
  <details><summary>会话与通知</summary><label class="setting-row"><span>置顶群聊</span><input type="checkbox" name="pinned" ${thread.pinned?'checked':''}></label><label class="setting-row"><span>消息免打扰</span><input type="checkbox" name="muted" ${thread.muted?'checked':''}></label><label class="setting-row"><span>在聊天顶部显示公告</span><input type="checkbox" name="showAnnouncement" ${thread.showAnnouncement===false?'':'checked'}></label><label class="setting-row"><span>发送消息后生成角色回复</span><input type="checkbox" name="allowAiReplies" ${thread.allowAiReplies===false?'':'checked'}></label></details>
  <button class="button">保存设置</button><button type="button" class="button secondary" data-clear-group>清空本机群聊天记录</button><button type="button" class="button secondary" data-leave-group>退出群聊</button></form>`,{onReady(sheet){const form=sheet.querySelector('form');sheet.querySelectorAll('[data-remove-member]').forEach(button=>button.onclick=()=>{store.update(s=>{const row=s.groupThreads.find(x=>x.id===thread.id);row.memberIds=row.memberIds.filter(id=>id!==button.dataset.removeMember)});closeSheet();done();showToast('成员已移出')});form.onsubmit=e=>{e.preventDefault();store.update(s=>{const row=s.groupThreads.find(x=>x.id===thread.id);row.name=form.elements.name.value.trim()||row.name;row.nicknames[thread.accountId]=form.elements.myNickname.value.trim();row.announcement=form.elements.announcement.value.trim();row.muted=form.elements.muted.checked;row.pinned=form.elements.pinned.checked;row.showAnnouncement=form.elements.showAnnouncement.checked;row.allowAiReplies=form.elements.allowAiReplies.checked;if(form.elements.invite.value&&!row.memberIds.includes(form.elements.invite.value))row.memberIds.push(form.elements.invite.value)});closeSheet();done();showToast('群聊设置已保存')};sheet.querySelector('[data-clear-group]').onclick=()=>{if(!confirm('清空这台设备上的群聊天记录？'))return;store.update(s=>s.groupMessages[thread.id]=[]);closeSheet();done();showToast('本机记录已清空')};sheet.querySelector('[data-leave-group]').onclick=()=>{store.update(s=>{s.groupThreads=s.groupThreads.filter(x=>x.id!==thread.id);delete s.groupMessages[thread.id]});closeSheet();navigate('chat')}}});
  document.querySelectorAll('#modal-root [data-remove-member]').forEach(remove=>{const id=remove.dataset.removeMember,muted=thread.mutedMemberIds?.includes(id);remove.insertAdjacentHTML('beforebegin',`<button type="button" data-mute-member="${escapeHtml(id)}">${muted?'解除禁言':'禁言'}</button>`);const button=remove.previousElementSibling;button.onclick=()=>{store.update(s=>{const row=s.groupThreads.find(x=>x.id===thread.id);row.mutedMemberIds||=[];row.mutedMemberIds=row.mutedMemberIds.includes(id)?row.mutedMemberIds.filter(x=>x!==id):[...row.mutedMemberIds,id]});const blocked=store.getState().groupThreads.find(x=>x.id===thread.id)?.mutedMemberIds?.includes(id);button.textContent=blocked?'解除禁言':'禁言';showToast(blocked?'该成员已禁言':'已解除禁言')}});
}

function openGroupRedpacket(store,thread,done) {
  openSheet(`<form class="group-redpacket-sheet"><div class="sheet-title"><h3>发群红包</h3><button type="button" class="button ghost" data-sheet-close>关闭</button></div><p>余额会立即扣除。份额按确定的随机种子分给其他成员。</p><label class="field"><span>总金额</span><input name="amount" type="number" min="0.01" max="200" step="0.01" required placeholder="20.00"></label><label class="field"><span>祝福语</span><input name="note" maxlength="40" value="大家一起开心"></label><button class="button">发送红包</button></form>`,{onReady(sheet){sheet.querySelector('form').onsubmit=e=>{e.preventDefault();const form=e.currentTarget,amount=Math.round(Number(form.elements.amount.value)*100)/100,current=store.getState(),live=current.groupThreads.find(row=>row.id===thread.id&&row.accountId===current.currentUserId&&!row.archived),recipientIds=live?.memberIds.filter(id=>id!==thread.accountId)||[];if(!live||!recipientIds.length)return showToast('群聊已结束或没有可领取的成员');if(!Number.isFinite(amount)||amount<.01||amount>200)return showToast('请输入 0.01—200 元');if(amount*100<recipientIds.length)return showToast('金额至少要让每人分到一分钱');const messageId=crypto.randomUUID();if(!walletDebit(store,{amount,kind:'redpacket',title:`${thread.name} 群红包`,conversationId:thread.id,messageId,note:form.elements.note.value}))return showToast('余额不足');const row=postGroupMessage(store,thread.id,{speakerId:thread.accountId,text:form.elements.note.value||'恭喜发财',type:'redpacket',amount,messageId});const shares=splitAmount(amount,recipientIds,messageId);store.update(s=>{const target=s.groupMessages[thread.id].find(item=>item.id===row.id);target.shares=shares});closeSheet();done();showToast('群红包已发送')}}});
}

export function splitAmount(amount,ids,seed) {
  const cents=Math.round(amount*100),weights=ids.map((_,i)=>1+((seed.charCodeAt(i%seed.length)||17)*(i+3)%13)),sum=weights.reduce((a,b)=>a+b,0);let remaining=cents;
  return ids.map((id,i)=>{const share=i===ids.length-1?remaining:Math.max(1,Math.min(remaining-(ids.length-i-1),Math.floor(cents*weights[i]/sum)));remaining-=share;return {personId:id,amount:share/100}});
}
