import { escapeHtml, initialsAvatar, showToast } from './core/ui.js';
import { sendToModel } from './integrations/ai-client.js';
import { generateImage } from './image-client.js';
import { saveMediaBlob, getMediaUrl } from './media-store.js';
import { postGroupMessage } from './group-model.js';
import { compileWorldbook } from './apps/prompt-library.js';

export function createGroupCallRenderer({store,navigate}) {
  let active=null;
  return (container,params={})=>{
    active?.cleanup();
    const state=store.getState(),thread=state.groupThreads.find(row=>row.id===params.id&&row.accountId===state.currentUserId);
    if(!thread)return navigate('chat');
    const members=thread.memberIds.map(id=>state.people.find(row=>row.id===id)).filter(Boolean).slice(0,9);
    const session={id:thread.id,started:Date.now(),stream:null,timer:null,closed:false,busy:false,log:[],cleanup(){if(this.closed)return;clearInterval(this.timer);this.stream?.getTracks().forEach(track=>track.stop());globalThis.speechSynthesis?.cancel();this.closed=true;const sec=Math.max(1,Math.round((Date.now()-this.started)/1000)),row=postGroupMessage(store,thread.id,{speakerId:thread.accountId,text:`群通话 · ${Math.floor(sec/60)}分${sec%60}秒`,type:'group-call'});if(row)store.update(s=>{const message=s.groupMessages[thread.id]?.find(x=>x.id===row.id);if(message)message.transcript=this.log.slice(-40)})}};
    active=session;
    const mode=params.mode==='video'?'video':'voice';
    container.className='app-view group-call-view';
    container.innerHTML=`<section class="group-call-stage ${mode}" data-group-call><header><small>正在与 ${escapeHtml(thread.name)} 通话</small><time data-call-time>00:00</time></header><div class="group-call-grid">${members.map(person=>{const profile=thread.memberProfiles?.[person.id]||{},name=profile.nickname||thread.nicknames?.[person.id]||person.name;return `<article class="group-call-tile" data-speaker="${escapeHtml(person.id)}"><div class="group-call-portrait">${initialsAvatar(person,{avatarUrl:profile.avatarUrl||state.chatProfiles?.[person.id]?.avatarUrl||person.avatarUrl||''})}${person.id===thread.accountId?'<video data-call-preview autoplay muted playsinline></video>':''}<img data-call-image="${escapeHtml(person.id)}" alt="" hidden></div><span>${escapeHtml(name)}</span><i aria-hidden="true"></i></article>`}).join('')}${Array.from({length:Math.max(0,9-members.length)},()=>'<article class="group-call-tile empty"><span>等待加入</span></article>').join('')}</div><div class="group-call-caption" data-call-caption>在通话里说一句话，大家会自然接话。</div><div class="group-call-transcript" data-call-log></div><form data-call-say><input name="text" maxlength="240" placeholder="在通话里说一句…" aria-label="通话内容" required><button>发送</button></form><nav class="group-call-toolbar"><button data-call-mic type="button"><span>♩</span>麦克风</button><button data-call-camera type="button"><span>▣</span>摄像头</button><button data-call-mode type="button"><span>▦</span>${mode==='video'?'语音':'视频'}</button><button data-call-generate type="button"><span>✦</span>生图</button><button data-call-end type="button" class="end"><span>⌕</span>挂断</button></nav></section>`;
    const current=()=>active===session&&!session.closed&&container.isConnected&&document.querySelector('#app-screen')?.dataset.app==='group-call';
    container.querySelectorAll('.group-call-tile[data-speaker]').forEach(tile=>tile.onclick=()=>{container.querySelectorAll('.group-call-tile').forEach(x=>x.classList.remove('selected'));tile.classList.add('selected')});
    const caption=container.querySelector('[data-call-caption]');
    const speak=(speakerId,line)=>{if(!current())return;session.log.push({speakerId,text:line});const person=members.find(p=>p.id===speakerId),name=thread.memberProfiles?.[speakerId]?.nickname||person?.name||'成员';caption.textContent=`${name}：${line}`;container.querySelectorAll('[data-speaker]').forEach(tile=>tile.classList.toggle('speaking',tile.dataset.speaker===speakerId));const box=container.querySelector('[data-call-log]');box.innerHTML=session.log.slice(-4).map(item=>`<p><b>${escapeHtml(thread.memberProfiles?.[item.speakerId]?.nickname||members.find(p=>p.id===item.speakerId)?.name||'成员')}</b> ${escapeHtml(item.text)}</p>`).join('');box.scrollTop=box.scrollHeight};
    const setStream=()=>{const video=container.querySelector('[data-call-preview]');if(video){video.srcObject=session.stream;video.hidden=!session.stream?.getVideoTracks().some(t=>t.readyState==='live')}};
    const end=()=>{if(!current())return;session.cleanup();navigate('group-chat',{id:thread.id})};
    session.timer=setInterval(()=>{if(!current())return session.cleanup();const sec=Math.floor((Date.now()-session.started)/1000);container.querySelector('[data-call-time]').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`},1000);
    container.querySelector('[data-call-end]').onclick=end;
    container.querySelector('[data-call-mode]').onclick=()=>{container.querySelector('[data-call-mode]').lastChild.textContent=container.querySelector('.group-call-stage').classList.toggle('video')?'语音':'视频'};
    container.querySelector('[data-call-mic]').onclick=async e=>{try{if(session.stream?.getAudioTracks().length){const track=session.stream.getAudioTracks()[0];track.enabled=!track.enabled;e.currentTarget.classList.toggle('on',track.enabled)}else{const audio=await navigator.mediaDevices.getUserMedia({audio:true});if(!current()){audio.getTracks().forEach(t=>t.stop());return}session.stream=new MediaStream([...(session.stream?.getTracks()||[]),...audio.getTracks()]);e.currentTarget.classList.add('on')}}catch{showToast('麦克风未获得权限')}};
    container.querySelector('[data-call-camera]').onclick=async e=>{try{const tracks=session.stream?.getVideoTracks()||[];if(tracks.length){tracks.forEach(t=>t.stop());session.stream=new MediaStream(session.stream.getAudioTracks());e.currentTarget.classList.remove('on')}else{const camera=await navigator.mediaDevices.getUserMedia({video:true});if(!current()){camera.getTracks().forEach(t=>t.stop());return}session.stream=new MediaStream([...(session.stream?.getTracks()||[]),...camera.getTracks()]);container.querySelector('.group-call-stage').classList.add('video');e.currentTarget.classList.add('on')}setStream()}catch{showToast('摄像头未获得权限')}};
    container.querySelector('[data-call-say]').onsubmit=async e=>{e.preventDefault();if(session.busy)return;const input=e.currentTarget.elements.text,text=input.value.trim();if(!text)return;input.value='';speak(thread.accountId,text);const live=store.getState(),model=live.modelProfiles.find(p=>p.id===live.activeModelProfileId);if(!model?.apiKey||!model?.model)return showToast('请先配置模型 API');session.busy=true;try{const roster=members.filter(p=>p.id!==thread.accountId);const system='模拟真实多人群通话，最多两位在场角色自然接话。只使用给定角色 ID；不能替用户说话；回复具体、简短、口语化，不轮流报到，不透露不在场的人才知道的事。只返回 JSON：{"messages":[{"speakerId":"角色ID","text":"一句话"}]}。';const raw=await sendToModel(model,[{role:'user',text:JSON.stringify({group:thread.name,members:roster.map(p=>({id:p.id,name:thread.memberProfiles?.[p.id]?.nickname||p.name,persona:p.persona||p.personality||p.note,city:thread.memberProfiles?.[p.id]?.city||p.city,worldbooks:(live.worldbooks||[]).filter(book=>(thread.memberProfiles?.[p.id]?.worldbookIds||live.chatProfiles?.[p.id]?.worldbookIds||[]).includes(book.id)).map(book=>compileWorldbook(book,text)).filter(Boolean)})),recent:session.log.slice(-8),groupRecent:(live.groupMessages[thread.id]||[]).slice(-8).map(x=>x.text)})}],system);const data=JSON.parse(String(raw).match(/\{[\s\S]*\}/)?.[0]||'{}');for(const line of (Array.isArray(data.messages)?data.messages:[]).slice(0,3)){if(!current()||!roster.some(p=>p.id===line.speakerId)||!line.text)continue;const body=String(line.text).slice(0,180);speak(line.speakerId,body);await new Promise(resolve=>{const wait=Math.min(4500,700+body.length*110),timer=setTimeout(resolve,wait);if(globalThis.speechSynthesis){const utterance=new SpeechSynthesisUtterance(body);utterance.lang='zh-CN';utterance.onend=utterance.onerror=()=>{clearTimeout(timer);resolve()};speechSynthesis.speak(utterance)}})}}catch(error){showToast(`通话回应失败：${error.message}`)}finally{session.busy=false}};
    container.querySelector('[data-call-generate]').onclick=async()=>{const people=members.filter(p=>p.id!==thread.accountId);const chosen=people.find(p=>p.id===container.querySelector('.group-call-tile.selected')?.dataset.speaker)||people.find(p=>p.id===container.querySelector('.group-call-tile.speaking')?.dataset.speaker)||people[0];if(!chosen)return;const live=store.getState(),config=live.mediaApis?.image;if(!config?.enabled)return showToast('请先在模型与 API 中开启生图');caption.textContent=`正在为 ${chosen.name} 生成通话画面…`;try{const profile=live.chatProfiles?.[chosen.id]||{},prompt=`手机视频通话中的人物半身画面，自然光，写实。人物：${chosen.name}。设定：${chosen.persona||chosen.personality||chosen.note||''}。所在城市：${thread.memberProfiles?.[chosen.id]?.city||chosen.city||''}。没有文字与水印。`;const src=await generateImage(config,{prompt,referenceImage:profile.imageReferenceFace||''});const response=await fetch(src);if(!response.ok)throw Error('图片未能保存');const media=await saveMediaBlob(await response.blob());store.update(s=>{const row=s.groupThreads.find(x=>x.id===thread.id);(row.memberProfiles||={})[chosen.id]||={};row.memberProfiles[chosen.id].callImageMediaId=media.mediaId});if(current()){const image=container.querySelector(`[data-call-image="${CSS.escape(chosen.id)}"]`);image.src=media.src;image.hidden=false;caption.textContent=`${chosen.name} 的画面已生成`}}catch(error){showToast(`生图失败：${error.message}`)}};
    for(const person of members){const mediaId=thread.memberProfiles?.[person.id]?.callImageMediaId;if(mediaId)getMediaUrl(mediaId).then(url=>{if(!current()||!url)return;const image=container.querySelector(`[data-call-image="${CSS.escape(person.id)}"]`);if(image){image.src=url;image.hidden=false}})}
  };
}
