import { escapeHtml as esc, showToast } from './core/ui.js';
import { ensureLife,islandWeather,cropsCatalog,cropProgress,fishCatalog,itemLabel,lifeAction } from './island-life.js';

export function createLifePanel(container,{read,mutate,onEvent}){
  let panel=null,tab='garden',timer=null;
  const perform=(action,args={})=>{try{let result;mutate(home=>{result=lifeAction(home,action,args)});onEvent?.(result);showToast(result.summary);draw();}catch(e){showToast(e.message)}};
  function open(next='garden'){tab=next;if(!panel){panel=document.createElement('section');panel.className='island-life-panel';panel.setAttribute('role','dialog');panel.setAttribute('aria-label','小岛生活');container.append(panel);}draw();}
  function draw(){if(!panel?.isConnected)return;const home=read(),life=ensureLife(home),weather=islandWeather(home);panel.innerHTML=`<header><div><small>ISLAND LIFE</small><h2>日常</h2></div><span>${life.coins} 岛币</span><button data-close aria-label="关闭生活面板">×</button></header><nav>${[['garden','田地'],['pets','宠物'],['fish','钓鱼'],['shop','商店'],['bag','背包']].map(([id,label])=>`<button data-tab="${id}" aria-selected="${id===tab}">${label}</button>`).join('')}</nav><div class="island-life-content">${content(home,life,weather)}</div>`;
    panel.querySelector('[data-close]').onclick=()=>{panel.remove();panel=null;clearInterval(timer)};
    panel.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;draw()});
    panel.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>perform(b.dataset.action,{type:b.dataset.type,item:b.dataset.item,id:b.dataset.id,qty:b.dataset.qty||1}));
    panel.querySelector('form')?.addEventListener('submit',e=>{e.preventDefault();perform('adopt',{species:e.target.elements.species.value,name:e.target.elements.name.value})});
    clearInterval(timer);if(tab==='fish'){tickFish();timer=setInterval(()=>{if(!panel?.isConnected){clearInterval(timer);return;}tickFish()},160);}
  }
  function content(home,life,w){
    const weather=`<div class="island-calendar"><strong>${w.kind} · ${w.temperature}°</strong><span>${w.season} / ${w.day}${w.festival?` · ${w.festival}`:''}</span></div>`;
    if(tab==='garden')return weather+`<div class="life-section-title"><h3>我的六块田</h3><button data-action="till">翻地</button></div><div class="life-plots">${Array.from({length:6},(_,i)=>{const x=2+i%3,z=5+Math.floor(i/3),crop=home.crops.find(c=>c.x===x&&c.z===z),progress=crop?cropProgress(home,crop):0;return `<article><small>0${i+1}</small><strong>${crop?esc(crop.kind||'草莓'):life.tilled.includes(`${x},${z}`)?'待播种':'未翻地'}</strong>${crop?`<progress max="1" value="${progress}"></progress><span>${progress>=1?'可以收获':`${Math.round(progress*100)}% · ${crop.wateredAt?'已浇水':'可浇水'}`}</span>`:'<span>一格小小的期待</span>'}</article>`}).join('')}</div><div class="life-actions"><button data-action="water">浇一块田</button><button data-action="harvest">收获成熟作物</button></div><h3>选择种子</h3>${Object.entries(cropsCatalog).map(([id,c])=>`<div class="life-row"><div><strong>${c.name}</strong><small>${Math.round(c.hours*60)} 分钟 · 种子 ${life.inventory['seed:'+id]||0}</small></div><button data-action="plant" data-type="${id}">播种</button></div>`).join('')}<p class="life-hint">雨天自然加速，浇水再加速；已浇水的作物收获更多。离线也会生长。</p>`;
    if(tab==='pets')return `<h3>一起住的小朋友</h3>${life.pets.map(p=>`<article class="pet-care"><div><strong>${esc(p.name)}</strong><small>${{cat:'猫咪',dog:'小狗',rabbit:'兔子'}[p.species]} · 亲密 ${Math.round(p.affection)}</small></div>${[['hunger','饱腹'],['mood','心情'],['health','健康']].map(([k,n])=>`<label>${n}<progress max="100" value="${p[k]}"></progress><span>${Math.round(p[k])}</span></label>`).join('')}<div class="life-actions"><button data-action="feed" data-id="${p.id}">喂食 · 1 份口粮</button><button data-action="play" data-id="${p.id}">陪它玩</button></div></article>`).join('')||'<p class="life-hint">给一个小朋友留个位置。它会出现在岛上，离线期间也有自己的作息。</p>'}${life.pets.length<2?'<form class="life-adopt"><h3>领养 · 60 岛币</h3><select name="species" aria-label="宠物种类"><option value="cat">猫咪</option><option value="dog">小狗</option><option value="rabbit">兔子</option></select><input name="name" maxlength="16" placeholder="给它起个名字" required><button>欢迎回家</button></form>':''}`;
    if(tab==='fish')return weather+`<div class="fishing-scene"><div class="fishing-ring"></div><strong data-fish-status></strong><p>浮标下沉后，在 2.5 秒内收竿。</p><button data-fish-button></button><small>鱼饵 ${life.inventory.bait||0} · 雨天和夜晚可能遇到不同的鱼</small></div><h3>钓获记录</h3>${Object.entries(fishCatalog).map(([id,f])=>`<div class="life-row"><strong>${f.name}</strong><span>${life.inventory['fish:'+id]||0} 条</span></div>`).join('')}`;
    if(tab==='shop')return weather+`${w.festival?`<div class="life-festival"><h3>${w.festival}</h3><p>今天收购价提高 20%，还有一份小礼物。</p><button data-action="festival">领取节日礼物</button></div>`:''}<h3>小岛补给</h3>${[...Object.entries(cropsCatalog).map(([id,c])=>['seed:'+id,c.seed]),['bait',4],['food',7]].map(([id,price])=>`<div class="life-row"><div><strong>${itemLabel(id)}</strong><small>${price} 岛币 / 份</small></div><button data-action="buy" data-item="${id}">买一份</button></div>`).join('')}<p class="life-hint">岛币仅用于小游戏，与手机钱包分开。出售作物或鱼可以补充岛币。</p>`;
    return `<h3>随身背包</h3>${Object.entries(life.inventory).filter(([,n])=>n>0).map(([id,n])=>`<div class="life-row"><div><strong>${itemLabel(id)}</strong><small>× ${n}</small></div>${/^(crop|fish):/.test(id)?`<button data-action="sell" data-item="${id}" data-qty="${n}">全部出售</button>`:'<span>补给</span>'}</div>`).join('')||'<p>背包空空的。</p>'}<h3>最近收支</h3>${life.ledger.slice(-8).reverse().map(row=>`<div class="life-row"><small>${esc(row.label)}</small><span>${row.amount>0?'+':''}${row.amount}</span></div>`).join('')||'<p class="life-hint">初始赠送 180 岛币，去种下第一颗种子吧。</p>'}`;
  }
  function tickFish(){const f=read().life?.fishing,now=Date.now(),status=panel.querySelector('[data-fish-status]'),b=panel.querySelector('[data-fish-button]');if(!b)return;const bite=f&&now>=f.biteAt&&now<=f.expiresAt;status.textContent=!f?'在水边等一会儿':bite?'上钩了，现在收竿！':now>f.expiresAt?'鱼游走了':'浮标轻轻晃动…';panel.querySelector('.fishing-ring').classList.toggle('bite',!!bite);b.textContent=f?'收竿':'抛竿 · 1 枚鱼饵';b.onclick=()=>perform(f?'reel':'cast');}
  return {open,dispose(){clearInterval(timer);panel?.remove()}};
}

export function floatIslandDialogue(container,{saved={},persist}){
  const panel=container.querySelector('[data-island-dialogue]'),form=container.querySelector('[data-island-form]'),title=panel.querySelector('span');
  panel.classList.add('island-chat-window');const header=document.createElement('header');header.className='island-window-handle';header.append(title);header.insertAdjacentHTML('beforeend','<button data-window-min aria-label="折叠对话">−</button><button data-window-max aria-label="放大或恢复对话">□</button><button data-window-close aria-label="关闭对话">×</button>');panel.prepend(header);panel.append(form);panel.insertAdjacentHTML('beforeend','<button class="island-resize-handle" aria-label="拖动调整对话框大小">◢</button>');
  let geometry={x:saved.x??18,y:saved.y??140,w:saved.w??280,h:saved.h??200},minimized=!!saved.minimized,hidden=saved.hidden??true;
  const bounds=()=>container.querySelector('.island-scene').getBoundingClientRect();
  function apply(){const r=bounds();geometry.w=Math.max(220,Math.min(geometry.w,r.width-24));geometry.h=Math.max(150,Math.min(geometry.h,r.height-120));geometry.x=Math.max(8,Math.min(geometry.x,r.width-geometry.w-8));geometry.y=Math.max(65,Math.min(geometry.y,r.height-(minimized?44:geometry.h)-80));Object.assign(panel.style,{left:geometry.x+'px',top:geometry.y+'px',width:geometry.w+'px',height:(minimized?44:geometry.h)+'px'});panel.classList.toggle('minimized',minimized);panel.hidden=hidden;}
  const save=()=>persist({...geometry,minimized,hidden});
  function attach(handle,resize){let start=null;handle.onpointerdown=e=>{if(!resize&&e.target.closest('button'))return;e.preventDefault();e.stopPropagation();start={px:e.clientX,py:e.clientY,...geometry};handle.setPointerCapture(e.pointerId)};handle.onpointermove=e=>{if(!start)return;e.preventDefault();e.stopPropagation();if(resize){geometry.w=start.w+e.clientX-start.px;geometry.h=start.h+e.clientY-start.py}else{geometry.x=start.gx+e.clientX-start.px;geometry.y=start.gy+e.clientY-start.py}apply()};
    const down=handle.onpointerdown;handle.onpointerdown=e=>{down(e);if(start){start.gx=geometry.x;start.gy=geometry.y;}};
    handle.onpointerup=handle.onpointercancel=e=>{if(start){start=null;save();e.stopPropagation()}};
  }
  attach(header,false);attach(panel.querySelector('.island-resize-handle'),true);
  let restoredSize=null;header.querySelector('[data-window-max]').onclick=()=>{if(restoredSize){geometry={...restoredSize};restoredSize=null}else{restoredSize={...geometry};const r=bounds();geometry={x:12,y:80,w:r.width-24,h:r.height-190}}minimized=false;apply();save()};
  header.querySelector('[data-window-min]').onclick=()=>{minimized=!minimized;apply();save()};header.querySelector('[data-window-close]').onclick=()=>{hidden=true;apply();save()};
  const observer=new ResizeObserver(()=>{if(!panel.isConnected){observer.disconnect();return;}apply()});observer.observe(container);apply();
  return {open(){hidden=false;minimized=false;apply();save();form.querySelector('input')?.focus()},dispose(){observer.disconnect()}};
}
