import {ensureGameDay} from './games-hub.js';
import { ensureLife, islandWeather, cropProgress, cropsCatalog } from './island-life.js';
import { createLifePanel, floatIslandDialogue } from './island-panels.js';
import { normalizeLook, wardrobeChoices } from './island-wardrobe.js';
import { openIslandHome } from './island-home.js';
import { escapeHtml, showToast } from './core/ui.js';
import { avatarDefaults, openAvatarStudio } from './island-avatar.js';
import { createIsland3D } from './island-3d.js';
import { sendToModel } from './integrations/ai-client.js';
import { addMemoryEntry, retrieveMemoryContext } from './memory-engine.js';
import { accountContext } from './account-system.js';
import { appendWorldEvent, entityWorld } from './world-engine.js';
import { compileWorldbook } from './apps/prompt-library.js';

const plots=Array.from({length:6},(_,i)=>({x:2+i%3,z:5+Math.floor(i/3)}));
function key(state){return `${state.currentWorldId||'default'}::${state.currentUserId||'user'}`}
function island(store){const state=store.getState(),id=key(state);if(!state.bunnyIslands?.[id])store.update(s=>{s.bunnyIslands||={};s.bunnyIslands[id]={schemaVersion:1,worldId:s.currentWorldId||'default',accountId:s.currentUserId,avatar:{x:4,z:4,skin:'#f3c7a4',hair:'#6c4b39',shirt:'#8db3cb'},crops:[],harvests:0,actionLog:[]}});return store.getState().bunnyIslands[id]}
function visitorFor(state){return state.people.find(person=>['char','npc'].includes(person.type)&&entityWorld(state,person.id)===(state.currentWorldId||'default'))}

export function createGamesRenderer({navigate,store}){return container=>{const home=store?island(store):null;container.className='app-view bunny-games-view';container.innerHTML=`<header class="playroom-header"><small>BUNNY / PLAYROOM</small><h1>游乐屋<span>.</span></h1><p>留一点时间给自己。</p></header><button class="playroom-feature" data-open-island><div class="playroom-cover" aria-hidden="true"><svg viewBox="0 0 320 220"><defs><linearGradient id="playroom-cover-shade" x2="0" y2="1"><stop stop-color="#fff"/><stop offset="1" stop-color="#c9cbcd"/></linearGradient></defs><ellipse cx="163" cy="183" rx="101" ry="15" fill="#d8dadc"/><path d="M50 148Q68 94 158 105T270 145L267 170Q157 219 53 170Z" fill="url(#playroom-cover-shade)" stroke="#fff"/><ellipse cx="160" cy="143" rx="110" ry="40" fill="#f3f4f5" stroke="#fff"/><path d="M140 116v42h52v-42l-26-21Z" fill="#fff" stroke="#c5c8ca"/><path d="M134 116l32-27 33 27" stroke="#575d62" stroke-width="8" fill="none" stroke-linejoin="round"/><path d="M161 157v-20h12v20" fill="#b6bcc0"/><path d="M97 143v-34m127 36v-25" stroke="#999fa3" stroke-width="6"/><circle cx="97" cy="94" r="26" fill="#c4cac9"/><circle cx="224" cy="110" r="20" fill="#d5d9d7"/><circle cx="121" cy="151" r="5" fill="#bcc2c5"/></svg><span class="playroom-live">你的世界 · 随时继续</span></div><div class="playroom-feature-copy"><div><small>01 / 小岛生活</small><h2>兔屿</h2><p>散步、换装，还有一点日常。</p></div><span class="playroom-enter" aria-label="进入游戏">↗</span></div></button><div class="playroom-summary"><div><strong>${home?.crops?.length||0}<small> / 6</small></strong><span>正在生长的田地</span></div><div><strong>${home?.life?.pets?.length||0}</strong><span>岛上的小朋友</span></div><div><strong>${home?.harvests||0}</strong><span>收获过的田地</span></div></div><section class="playroom-guide"><h3>今天从哪里开始</h3><button data-open-wardrobe><span>01</span><div><strong>换一套喜欢的衣服</strong><small>发型、搭配与小配饰</small></div><b>↗</b></button><button data-open-life><span>02</span><div><strong>照顾小岛的日常</strong><small>种植、宠物、钓鱼与补给</small></div><b>↗</b></button></section>`;container.querySelector('[data-open-island]').onclick=()=>navigate('bunny-island');container.querySelector('[data-open-wardrobe]').onclick=()=>{navigate('bunny-island');requestAnimationFrame(()=>document.querySelector('[data-island-dress]')?.click())};container.querySelector('[data-open-life]').onclick=()=>{navigate('bunny-island');requestAnimationFrame(()=>document.querySelector('[data-island-plant]')?.click())}}}

export function createIslandRenderer({store,navigate}){
  let scene3d=null,lifePanel=null,chatWindow=null,responding=false,lastAutoAt=0;
  return function render(container){scene3d?.dispose();lifePanel?.dispose();chatWindow?.dispose();const saved=island(store),state=store.getState(),visitor=visitorFor(state),model=state.modelProfiles?.find(row=>row.id===state.activeModelProfileId),ready=Boolean(model?.apiKey&&model?.model),user=state.people.find(person=>person.id===state.currentUserId);if(visitor&&!saved.visitorLooks?.[visitor.id])store.update(s=>{const home=s.bunnyIslands[key(s)];home.visitorLooks||={};const persona=[visitor.persona,visitor.personality,visitor.note].filter(Boolean).join(' ');home.visitorLooks[visitor.id]={...avatarDefaults,gender:/^(male|男|男性)$/.test(visitor.gender||'')?'male':'female',hairStyle:/短发/.test(persona)?'crop':/长发/.test(persona)?'long':'bob',hair:/白发|银发/.test(persona)?'#eee3d0':/金发/.test(persona)?'#eac783':'#6c4b39',outfit:/连衣裙/.test(persona)?'dress':/运动|卫衣/.test(persona)?'hoodie':'sweater',shirt:'#bca1d2'};});store.update(s=>ensureLife(s.bunnyIslands[key(s)]));const weather=islandWeather(saved);container.className='app-view bunny-island-view';
    container.innerHTML=`<section class="island-scene"><canvas data-island-canvas aria-label="可旋转的三维小岛。轻点地面移动，拖动旋转。"></canvas><div class="island-sky"><small>ISLAND / ${weather.season}</small><h1>兔屿生活<span class="island-title-dot">.</span></h1><span>${escapeHtml(user?.name||'我')} 的小岛 · ${saved.crops.length}/6 块田</span></div><button class="island-home-entry" data-island-home>⌂ 回家</button><div class="island-weather">${weather.kind} <span>${weather.temperature}° · ${weather.festival||weather.day}</span></div><div class="island-dialogue" data-island-dialogue><span>${escapeHtml(visitor?.name||'岛上还没有朋友')}</span><p>${visitor?'TA 在岛上。点「对话」，或者先种点什么。':'在联系人创建角色后，TA 可以来这里做客。'}</p></div><div class="island-controls"><div class="island-tools"><button type="button" data-island-plant><svg viewBox="0 0 24 24"><path d="M12 20V10M12 14C3 14 4 5 4 5s8-1 8 9Zm0-4c0-7 8-7 8-7s1 8-8 7Z"/></svg> <span>生活</span></button><button type="button" data-island-harvest><svg viewBox="0 0 24 24"><rect x="5" y="7" width="14" height="14" rx="4"/><path d="M8 7V5a4 4 0 0 1 8 0v2M8 14h8"/></svg> <span>背包</span></button><button type="button" data-island-dress><svg viewBox="0 0 24 24"><path d="m8 4-5 4 3 5 2-2v10h8V11l2 2 3-5-5-4a4 4 0 0 1-8 0Z"/></svg> <span>衣橱</span></button><button type="button" data-island-talk ${visitor?'':'disabled'}><svg viewBox="0 0 24 24"><path d="M21 11a9 9 0 0 1-9 9H4l1-4a9 9 0 1 1 16-5Z"/><path d="M8 10h8m-8 4h5"/></svg> <span>对话</span></button></div><button type="button" class="island-char-look" data-char-look ${visitor?'':'hidden'}>让朋友自己挑一套衣服</button><form data-island-form><input name="speech" maxlength="160" placeholder="对${escapeHtml(visitor?.name||'岛上的朋友')}说点什么" ${visitor?'':'disabled'}><button type="submit" ${visitor?'':'disabled'}>发送</button></form><small class="island-tip">轻点地面移动 · 拖动旋转 · 滚轮缩放${ready?'':' · 配置文字 API 后可现场对话'}</small></div></section>`;
    const canvas=container.querySelector('[data-island-canvas]');try{scene3d=createIsland3D(canvas,{scene:()=>{const current=island(store);return{avatar:current.avatar,crops:current.crops.map(c=>({...c,progress:cropProgress(current,c),color:cropsCatalog[c.type]?.color})),pets:current.life?.pets||[],tilled:current.life?.tilled||[],weather:islandWeather(current),visitor:visitor?{x:5.55,z:4.25,...current.visitorLooks?.[visitor.id]}:null}},onMove:(x,z)=>move(x,z)})}catch(error){canvas.replaceWith(Object.assign(document.createElement('p'),{className:'island-webgl-error',textContent:`此设备暂时无法显示 3D 场景：${error.message}`}))}if(!scene3d&&canvas.isConnected)canvas.replaceWith(Object.assign(document.createElement('p'),{className:'island-webgl-error',textContent:'浏览器未启用 WebGL。请在支持 WebGL 的浏览器中打开。'}));
    lifePanel=createLifePanel(container,{read:()=>island(store),mutate:fn=>store.update(s=>fn(s.bunnyIslands[key(s)])),onEvent:event=>{recordAction(event.action,event.summary);updateCount();if(['plant','harvest','feed','reel'].includes(event.action))void maybeRespond(event.summary)}});
    chatWindow=floatIslandDialogue(container,{saved:saved.ui?.dialogue,persist:value=>store.update(s=>{const home=s.bunnyIslands[key(s)];home.ui||={};home.ui.dialogue=value})});
    container.querySelector('[data-island-plant]').onclick=()=>lifePanel.open('garden');
    container.querySelector('[data-island-harvest]').onclick=()=>lifePanel.open('bag');
    container.querySelector('[data-char-look]').onclick=async event=>{if(!ready)return showToast('先在设置中配置文字 API');const requestHomeKey=key(store.getState()),button=event.currentTarget;button.disabled=true;button.textContent='TA 正在挑选…';try{const raw=await sendToModel(model,[{role:'user',text:JSON.stringify({name:visitor.name,persona:visitor.persona||visitor.personality||visitor.note||'',current:island(store).visitorLooks?.[visitor.id],place:'在朋友的兔屿小岛做客',availableOutfits:wardrobeChoices(island(store).visitorLooks?.[visitor.id]?.gender,'outfit').filter(([id])=>id!=='none')})}],'请作为这个角色为今天在小岛上的活动选择自己的衣服，保留自己的外貌，不改变身份。只回复 JSON：{"outfit":"availableOutfits 中的一个有效 ID","shirt":"#六位十六进制颜色","reason":"15至40字第一人称随口解释，具体自然，不要通用寒暄"}。');const choice=JSON.parse(String(raw).match(/\{[\s\S]*\}/)?.[0]||'{}');if(!wardrobeChoices(island(store).visitorLooks?.[visitor.id]?.gender,'outfit').some(([id])=>id===choice.outfit&&id!=='none')||!/^#[0-9a-f]{6}$/i.test(choice.shirt))throw Error('返回的服饰格式不正确');if(key(store.getState())!==requestHomeKey)return;store.update(s=>Object.assign(s.bunnyIslands[requestHomeKey].visitorLooks[visitor.id],normalizeLook(s.bunnyIslands[requestHomeKey].visitorLooks[visitor.id]),{outfit:choice.outfit,shirt:choice.shirt,wardrobeVersion:2}));const line=String(choice.reason||'今天想穿这一套。').slice(0,80);container.querySelector('[data-island-dialogue] p').textContent=line;recordAction('char-dress',`${visitor.name}换了衣服，说：${line}`,{},true,visitor.id)}catch(error){showToast(`换装未完成：${error.message}`)}finally{button.disabled=false;button.textContent='让朋友自己挑一套衣服'}};
    container.querySelector('[data-island-home]').onclick=()=>openIslandHome(container,{avatar:island(store).avatar,home:island(store).home,onSave:home=>store.update(s=>{s.bunnyIslands[key(s)].home=home})});container.querySelector('[data-island-dress]').onclick=()=>openDress();container.querySelector('[data-island-talk]').onclick=()=>{chatWindow.open()};container.querySelector('[data-island-form]').onsubmit=e=>{e.preventDefault();const input=e.target.elements.speech,text=input.value.trim();if(!text)return;input.value='';recordAction('speak',`对 ${visitor.name} 说：${text}`);void respond(text,false)};
    function updateCount(){const label=container.querySelector('.island-sky>span');if(label)label.textContent=`${user?.name||'我'} 的小岛 · ${island(store).crops.length}/6 块田`}
    function move(x,z){const home=island(store);if(home.avatar.x===x&&home.avatar.z===z)return;store.update(s=>{const avatar=s.bunnyIslands[key(s)].avatar;avatar.x=x;avatar.z=z});recordAction('move',`走到了小岛坐标 ${x},${z}`,{x,z},false)}
    function recordAction(kind,summary,target={},remember=true,actorId=state.currentUserId){const id=crypto.randomUUID(),at=Date.now(),witnessIds=[state.currentUserId,...(visitor?[visitor.id]:[])],event={id,kind,summary,at,actorId,target,witnessIds};store.update(s=>{const home=s.bunnyIslands[key(s)];home.actionLog=[...home.actionLog,event].slice(-80);if(actorId===s.currentUserId){const {today}=ensureGameDay(s,at);today.islandActions||=[];if(!today.islandActions.includes(kind))today.islandActions.push(kind)}});if(kind!=='move')appendWorldEvent(store,{id:`island:${id}`,worldId:state.currentWorldId||'default',actorIds:[actorId],witnessIds,kind:`island-${kind}`,payload:{summary,location:'兔屿生活',public:false},source:'bunny-island'});if(remember&&visitor){const ownerId=accountContext(store.getState(),visitor.id,state.currentUserId).memoryOwnerId;void addMemoryEntry(ownerId,{kind:'episodic',category:'daily_event',layer:'temporary',text:`我在${user?.name||'USER'}的小岛上亲眼看见：${summary}`,importance:2,confidence:1,visibility:'witness',sourceIds:[id],worldId:state.currentWorldId||'default',accountId:state.currentUserId,source:'bunny-island'}).catch(()=>{})}return event}
    async function maybeRespond(kind){if(!visitor||Date.now()-lastAutoAt<18_000)return;lastAutoAt=Date.now();await respond(`我刚才${kind}。`,true)}
    async function respond(text,automatic){if(!visitor||responding)return;const panel=container.querySelector('[data-island-dialogue]');if(!panel)return;if(!ready){panel.querySelector('span').textContent='现场聊天';panel.querySelector('p').textContent='先到设置中配置文字 API，岛上的角色才会根据你做的事回应。';return}responding=true;panel.querySelector('span').textContent=visitor.name+' · 正在想';panel.querySelector('p').textContent='…';try{const live=store.getState(),home=island(store),history=home.actionLog.slice(-6).filter(row=>row.witnessIds.includes(visitor.id)).map(row=>({kind:row.kind,summary:row.summary,at:row.at})),ownerId=accountContext(live,visitor.id,live.currentUserId).memoryOwnerId,privateMemory=await retrieveMemoryContext(live,ownerId,text),profile=live.chatProfiles?.[visitor.id]||{},books=(live.worldbooks||[]).filter(book=>(profile.worldbookIds||[]).includes(book.id)).map(book=>compileWorldbook(book,text)).filter(Boolean),prompt={place:'USER 的兔屿小岛',you:{name:visitor.name,persona:visitor.persona||visitor.personality||visitor.note||'',relation:profile.relationship||''},userSaid:text,visibleActions:history,crops:home.crops.map(row=>({kind:row.kind,ageMinutes:Math.floor((Date.now()-row.plantedAt)/60000)})),memory:privateMemory.promptBlock,worldbooks:books,scene:'USER 和你都在小岛上，其他人不在场'};const raw=await sendToModel(model,[{role:'user',text:JSON.stringify(prompt)}],'你正在兔屿生活的小岛上扮演这个角色本人。只知道亲眼看见的动作、你自己的记忆、绑定的世界书和用户刚说的话；允许有自己的喜好、心情、日程和不完美的短句。不要替用户做动作或说话，不要说自己是 AI，不要套用「很高兴」「让我们一起」等通用寒暄。只回复 JSON：{"speech":"一句具体自然的现场回应，2—80字","emotion":"当前情绪"}。');const parsed=JSON.parse(String(raw).match(/\{[\s\S]*\}/)?.[0]||'{}'),speech=String(parsed.speech||'').trim().slice(0,120);if(!speech)throw Error('模型未返回现场台词');if(!panel.isConnected)return;panel.querySelector('span').textContent=`${visitor.name}${parsed.emotion?` · ${String(parsed.emotion).slice(0,12)}`:''}`;panel.querySelector('p').textContent=speech;recordAction('char-speak',`${visitor.name}说：${speech}`,{},false,visitor.id)}catch(error){if(panel.isConnected){panel.querySelector('span').textContent='现场聊天暂时断开';panel.querySelector('p').textContent=automatic?'你的动作已保存，稍后可点「对话」重试。':`未生成回复：${error.message}`}}finally{responding=false}}
    function openDress(){openAvatarStudio(container,island(store).avatar,look=>{store.update(s=>{const avatar=s.bunnyIslands[key(s)].avatar;s.bunnyIslands[key(s)].avatar={...look,x:avatar.x,z:avatar.z}});recordAction('dress','换上了新的小岛造型',{},true);showToast('新造型已保存');})}
  }
}
