import { escapeHtml, showToast } from './core/ui.js';
import { createIsland3D } from './island-3d.js';
import { sendToModel } from './integrations/ai-client.js';
import { addMemoryEntry, retrieveMemoryContext } from './memory-engine.js';
import { accountContext } from './account-system.js';
import { appendWorldEvent, entityWorld } from './world-engine.js';
import { compileWorldbook } from './apps/prompt-library.js';

const plots=Array.from({length:6},(_,i)=>({x:2+i%3,z:5+Math.floor(i/3)}));
function key(state){return `${state.currentWorldId||'default'}::${state.currentUserId||'user'}`}
function island(store){const state=store.getState(),id=key(state);if(!state.bunnyIslands?.[id])store.update(s=>{s.bunnyIslands||={};s.bunnyIslands[id]={schemaVersion:1,worldId:s.currentWorldId||'default',accountId:s.currentUserId,avatar:{x:4,z:4,skin:'#f3c7a4',hair:'#6c4b39',shirt:'#8db3cb'},crops:[],harvests:0,actionLog:[]}});return store.getState().bunnyIslands[id]}
function visitorFor(state){return state.people.find(person=>['char','npc'].includes(person.type)&&entityWorld(state,person.id)===(state.currentWorldId||'default'))||state.people.find(person=>person.type==='char')}

export function createGamesRenderer({navigate}){return container=>{container.className='app-view bunny-games-view';container.innerHTML=`<section class="bunny-games-hero"><span>THE PLAYROOM</span><h1>游乐屋</h1><p>故事在手机以外，也在一座会慢慢长大的小岛上。</p><button type="button" data-open-island>进入兔屿生活 <b>↗</b></button></section><section class="bunny-games-preview"><div>🏡</div><div><strong>兔屿生活 · 第一章</strong><small>走走看看 · 播种 · 与岛上的朋友说话</small></div></section><p class="bunny-games-foot">长按聊天列表可以置顶或删除会话；岛上发生的事会成为在场角色的共同经历。</p>`;container.querySelector('[data-open-island]').onclick=()=>navigate('bunny-island')}}

export function createIslandRenderer({store,navigate}){
  let scene3d=null,responding=false,lastAutoAt=0;
  return function render(container){scene3d?.dispose();const saved=island(store),state=store.getState(),visitor=visitorFor(state),model=state.modelProfiles?.find(row=>row.id===state.activeModelProfileId),ready=Boolean(model?.apiKey&&model?.model),user=state.people.find(person=>person.id===state.currentUserId);container.className='app-view bunny-island-view';
    container.innerHTML=`<section class="island-scene"><canvas data-island-canvas aria-label="可旋转的三维小岛。轻点地面移动，拖动旋转。"></canvas><div class="island-sky"><small>BUNNY ISLAND · ${new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric'})}</small><h1>兔屿生活</h1><span>${escapeHtml(user?.name||'我')} 的小岛 · ${saved.crops.length}/6 块田</span></div><div class="island-weather">☀ <span>今天适合慢慢来</span></div><div class="island-dialogue" data-island-dialogue><span>${escapeHtml(visitor?.name||'岛上还没有朋友')}</span><p>${visitor?'TA 在岛上。点「说句话」，或者先种点什么。':'在联系人创建角色后，TA 可以来这里做客。'}</p></div><div class="island-controls"><div class="island-tools"><button type="button" data-island-plant>🌱 <span>播种</span></button><button type="button" data-island-harvest>🧺 <span>收获</span></button><button type="button" data-island-dress>🎨 <span>装扮</span></button><button type="button" data-island-talk ${visitor?'':'disabled'}>💬 <span>说句话</span></button></div><form data-island-form><input name="speech" maxlength="160" placeholder="对${escapeHtml(visitor?.name||'岛上的朋友')}说点什么" ${visitor?'':'disabled'}><button type="submit" ${visitor?'':'disabled'}>发送</button></form><small class="island-tip">轻点地面移动 · 拖动旋转 · 滚轮缩放${ready?'':' · 配置文字 API 后可现场对话'}</small></div></section>`;
    const canvas=container.querySelector('[data-island-canvas]');try{scene3d=createIsland3D(canvas,{scene:()=>{const current=island(store);return{avatar:current.avatar,crops:current.crops,visitor:visitor?{x:5.55,z:4.25}:null}},onMove:(x,z)=>move(x,z)})}catch(error){canvas.replaceWith(Object.assign(document.createElement('p'),{className:'island-webgl-error',textContent:`此设备暂时无法显示 3D 场景：${error.message}`}))}if(!scene3d&&canvas.isConnected)canvas.replaceWith(Object.assign(document.createElement('p'),{className:'island-webgl-error',textContent:'浏览器未启用 WebGL。请在支持 WebGL 的浏览器中打开。'}));
    container.querySelector('[data-island-plant]').onclick=()=>{const used=new Set(island(store).crops.map(row=>`${row.x},${row.z}`)),plot=plots.find(row=>!used.has(`${row.x},${row.z}`));if(!plot)return showToast('六块田都种上了，成熟后可以收获');store.update(s=>s.bunnyIslands[key(s)].crops.push({...plot,kind:'草莓',plantedAt:Date.now()}));recordAction('plant',`在小岛的 ${plot.x},${plot.z} 种下一株草莓`,plot);updateCount();showToast('草莓已种下，会随真实时间生长');void maybeRespond('plant')};
    container.querySelector('[data-island-harvest]').onclick=()=>{const crop=island(store).crops.find(row=>Date.now()-row.plantedAt>=2*60*60*1000);if(!crop)return showToast('还没有成熟的草莓，大约需要 2 小时');store.update(s=>{const home=s.bunnyIslands[key(s)];home.crops=home.crops.filter(row=>row!==crop&&!(row.x===crop.x&&row.z===crop.z));home.harvests++});recordAction('harvest','收获了一株草莓',crop);updateCount();showToast('草莓收进篮子里了');void maybeRespond('harvest')};
    container.querySelector('[data-island-dress]').onclick=()=>openDress();container.querySelector('[data-island-talk]').onclick=()=>{const input=container.querySelector('[data-island-form] input');input.focus();showToast(`可以直接和 ${visitor.name} 说话`)};container.querySelector('[data-island-form]').onsubmit=e=>{e.preventDefault();const input=e.target.elements.speech,text=input.value.trim();if(!text)return;input.value='';recordAction('speak',`对 ${visitor.name} 说：${text}`);void respond(text,false)};
    function updateCount(){const label=container.querySelector('.island-sky span');if(label)label.textContent=`${user?.name||'我'} 的小岛 · ${island(store).crops.length}/6 块田`}
    function move(x,z){const home=island(store);if(home.avatar.x===x&&home.avatar.z===z)return;store.update(s=>{const avatar=s.bunnyIslands[key(s)].avatar;avatar.x=x;avatar.z=z});recordAction('move',`走到了小岛坐标 ${x},${z}`,{x,z},false)}
    function recordAction(kind,summary,target={},remember=true,actorId=state.currentUserId){const id=crypto.randomUUID(),at=Date.now(),witnessIds=[state.currentUserId,...(visitor?[visitor.id]:[])],event={id,kind,summary,at,actorId,target,witnessIds};store.update(s=>{const home=s.bunnyIslands[key(s)];home.actionLog=[...home.actionLog,event].slice(-80)});if(kind!=='move')appendWorldEvent(store,{id:`island:${id}`,worldId:state.currentWorldId||'default',actorIds:[actorId],witnessIds,kind:`island-${kind}`,payload:{summary,location:'兔屿生活',public:false},source:'bunny-island'});if(remember&&visitor){const ownerId=accountContext(store.getState(),visitor.id,state.currentUserId).memoryOwnerId;void addMemoryEntry(ownerId,{kind:'episodic',category:'daily_event',layer:'temporary',text:`我在${user?.name||'USER'}的小岛上亲眼看见：${summary}`,importance:2,confidence:1,visibility:'witness',sourceIds:[id],worldId:state.currentWorldId||'default',accountId:state.currentUserId,source:'bunny-island'}).catch(()=>{})}return event}
    async function maybeRespond(kind){if(!visitor||Date.now()-lastAutoAt<18_000)return;lastAutoAt=Date.now();await respond(kind==='plant'?'我刚才种了草莓。':'我收获了一株草莓。',true)}
    async function respond(text,automatic){if(!visitor||responding)return;const panel=container.querySelector('[data-island-dialogue]');if(!panel)return;if(!ready){panel.querySelector('span').textContent='现场聊天';panel.querySelector('p').textContent='先到设置中配置文字 API，岛上的角色才会根据你做的事回应。';return}responding=true;panel.querySelector('span').textContent=visitor.name+' · 正在想';panel.querySelector('p').textContent='…';try{const live=store.getState(),home=island(store),history=home.actionLog.slice(-6).filter(row=>row.witnessIds.includes(visitor.id)).map(row=>({kind:row.kind,summary:row.summary,at:row.at})),ownerId=accountContext(live,visitor.id,live.currentUserId).memoryOwnerId,privateMemory=await retrieveMemoryContext(live,ownerId,text),profile=live.chatProfiles?.[visitor.id]||{},books=(live.worldbooks||[]).filter(book=>(profile.worldbookIds||[]).includes(book.id)).map(book=>compileWorldbook(book,text)).filter(Boolean),prompt={place:'USER 的兔屿小岛',you:{name:visitor.name,persona:visitor.persona||visitor.personality||visitor.note||'',relation:profile.relationship||''},userSaid:text,visibleActions:history,crops:home.crops.map(row=>({kind:row.kind,ageMinutes:Math.floor((Date.now()-row.plantedAt)/60000)})),memory:privateMemory.promptBlock,worldbooks:books,scene:'USER 和你都在小岛上，其他人不在场'};const raw=await sendToModel(model,[{role:'user',text:JSON.stringify(prompt)}],'你正在兔屿生活的小岛上扮演这个角色本人。只知道亲眼看见的动作、你自己的记忆、绑定的世界书和用户刚说的话；允许有自己的喜好、心情、日程和不完美的短句。不要替用户做动作或说话，不要说自己是 AI，不要套用「很高兴」「让我们一起」等通用寒暄。只回复 JSON：{"speech":"一句具体自然的现场回应，2—80字","emotion":"当前情绪"}。');const parsed=JSON.parse(String(raw).match(/\{[\s\S]*\}/)?.[0]||'{}'),speech=String(parsed.speech||'').trim().slice(0,120);if(!speech)throw Error('模型未返回现场台词');if(!panel.isConnected)return;panel.querySelector('span').textContent=`${visitor.name}${parsed.emotion?` · ${String(parsed.emotion).slice(0,12)}`:''}`;panel.querySelector('p').textContent=speech;recordAction('char-speak',`${visitor.name}说：${speech}`,{},false,visitor.id)}catch(error){if(panel.isConnected){panel.querySelector('span').textContent='现场聊天暂时断开';panel.querySelector('p').textContent=automatic?'你的动作已保存，稍后可点「说句话」重试。':`未生成回复：${error.message}`}}finally{responding=false}}
    function openDress(){const picker=document.createElement('div');picker.className='island-dress-panel';picker.innerHTML=`<header><strong>今天穿什么？</strong><button type="button" data-dress-close>完成</button></header>${[['skin','肤色',['#f3c7a4','#d7a879','#a8765e','#7b5548']],['hair','发色',['#6c4b39','#312c32','#c78a62','#eac783']],['shirt','上衣',['#e39d87','#9aadd8','#a4c89c','#e8c278']]].map(([part,label,colors])=>`<section><small>${label}</small><div>${colors.map(color=>`<button type="button" data-dress-part="${part}" data-dress-color="${color}" style="background:${color}" aria-label="${label} ${color}"></button>`).join('')}</div></section>`).join('')}`;container.querySelector('.island-scene').append(picker);picker.querySelector('[data-dress-close]').onclick=()=>picker.remove();picker.querySelectorAll('[data-dress-part]').forEach(button=>button.onclick=()=>{store.update(s=>s.bunnyIslands[key(s)].avatar[button.dataset.dressPart]=button.dataset.dressColor);recordAction('dress',`换了${button.dataset.dressPart==='hair'?'发色':button.dataset.dressPart==='skin'?'肤色':'上衣'}`,{},false);showToast('造型已保存')})}
  }
}
