import assert from 'node:assert/strict';
import { ensureLife,lifeAction,cropProgress,islandWeather,HOUR } from './island-life.js';
const at=Date.parse('2026-10-01T09:00:00Z'),make=()=>({worldId:'world-a',accountId:'user-a',crops:[],harvests:0});
const home=make();ensureLife(home,at);lifeAction(home,'till',{},at);lifeAction(home,'plant',{type:'lettuce'},at);assert.equal(home.life.inventory['seed:lettuce'],3);lifeAction(home,'water',{},at+1000);const restored=JSON.parse(JSON.stringify(home));assert.equal(cropProgress(home,home.crops[0],at+HOUR),cropProgress(restored,restored.crops[0],at+HOUR));lifeAction(restored,'harvest',{},at+HOUR);assert.equal(restored.life.inventory['crop:lettuce'],3);assert.throws(()=>lifeAction(restored,'harvest',{},at+HOUR));lifeAction(restored,'sell',{item:'crop:lettuce',qty:3},at+HOUR);assert.equal(restored.life.coins,216);assert.equal(restored.life.inventory['crop:lettuce'],0);assert.throws(()=>lifeAction(restored,'sell',{item:'crop:lettuce',qty:3},at+HOUR));
lifeAction(home,'adopt',{species:'cat',name:'团团'},at);const id=home.life.pets[0].id;lifeAction(home,'feed',{id},at);assert.equal(home.life.inventory.food,4);lifeAction(home,'play',{id},at);assert.throws(()=>lifeAction(home,'play',{id},at+1000));ensureLife(home,at+100*HOUR);assert.equal(home.life.pets[0].hunger,15);const mood=home.life.pets[0].mood;ensureLife(home,at+100*HOUR);assert.equal(home.life.pets[0].mood,mood);
const fishing=make();ensureLife(fishing,at);lifeAction(fishing,'cast',{},at);const f=JSON.parse(JSON.stringify(fishing)),bite=f.life.fishing.biteAt;lifeAction(f,'reel',{},bite);assert.equal(Object.entries(f.life.inventory).filter(([id])=>id.startsWith('fish:')).length,1);assert.throws(()=>lifeAction(f,'reel',{},bite));lifeAction(fishing,'reel',{},at+1);assert.equal(Object.keys(fishing.life.inventory).filter(id=>id.startsWith('fish:')).length,0);assert.equal(fishing.life.inventory.bait,4);
lifeAction(home,'festival',{},at+100*HOUR-100*HOUR);assert.throws(()=>lifeAction(home,'festival',{},at));assert.equal(islandWeather(home,at).festival,'秋日集市');assert.deepEqual(islandWeather(home,at),islandWeather(JSON.parse(JSON.stringify(home)),at));
const other=make();other.worldId='world-b';other.accountId='user-b';ensureLife(other,at);assert.equal(other.life.coins,180);assert.equal(other.life.pets.length,0);assert.equal(other.life.claims.length,0);assert.throws(()=>lifeAction(other,'buy',{item:'seed:bad'},at));assert.equal(other.life.coins,180);
console.log('PASS: growth and rain determinism, harvest/sell exactly once, pet care/cooldown, 72h cap, saved fishing/timing, one daily gift, isolated homes');

const offline=make();ensureLife(offline,at);lifeAction(offline,'adopt',{species:'dog',name:'点点'},at);const online=JSON.parse(JSON.stringify(offline));ensureLife(offline,at+48*HOUR);for(let i=1;i<=48;i++)ensureLife(online,at+i*HOUR);for(const stat of ['hunger','mood','health'])assert(Math.abs(online.life.pets[0][stat]-offline.life.pets[0][stat])<1e-8,stat+' offline integration');console.log('PASS: pet offline integration matches hourly updates');
