// Small self-contained WebGL scene: all objects are real 3D meshes, with no network dependency.
export function createIsland3D(canvas,{scene,onMove}){
  const gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl)return null;
  const shader=(type,source)=>{const value=gl.createShader(type);gl.shaderSource(value,source);gl.compileShader(value);if(!gl.getShaderParameter(value,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(value));return value};
  const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,`attribute vec3 aPosition;attribute vec3 aColor;uniform float uYaw;uniform float uElevation;uniform float uAspect;uniform float uZoom;uniform vec3 uCenter;varying vec3 vColor;void main(){vec3 p=aPosition-uCenter;float c=cos(uYaw),s=sin(uYaw),e=cos(uElevation),f=sin(uElevation);float x=p.x*c-p.z*s;float z=p.x*s+p.z*c;float y=p.y*e-z*f;float depth=p.y*f+z*e;gl_Position=vec4(x*uZoom/uAspect,y*uZoom,-depth*.035,1.);vColor=aColor;}`));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,`precision mediump float;varying vec3 vColor;void main(){gl_FragColor=vec4(vColor,1.);}`));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));
  const buffer=gl.createBuffer(),position=gl.getAttribLocation(program,'aPosition'),color=gl.getAttribLocation(program,'aColor'),uniforms=Object.fromEntries(['uYaw','uElevation','uAspect','uZoom','uCenter'].map(key=>[key,gl.getUniformLocation(program,key)]));let yaw=.72,zoom=.105,drag=null,frame=0;
  const faces=[[[0,4,6,2],1],[[1,3,7,5],.78],[[0,1,5,4],.86],[[2,6,7,3],.72],[[4,5,7,6],1.13],[[0,2,3,1],.67]];
  function box(data,x,y,z,w,h,d,hex){const rgb=parseColor(hex),corners=[[-1,-1,-1],[1,-1,-1],[-1,-1,1],[1,-1,1],[-1,1,-1],[1,1,-1],[-1,1,1],[1,1,1]];for(const [ids,shade] of faces){for(const index of [0,1,2,0,2,3]){const p=corners[ids[index]];data.push(x+p[0]*w/2,y+p[1]*h/2,z+p[2]*d/2,...rgb.map(v=>Math.min(1,v*shade)))}}}
  function character(data,x,z,look,step=0){const shirt=look.shirt||'#e39d87',hair=look.hair||'#6c4b39',skin=look.skin||'#f3c7a4';box(data,x-.13,.62,z,.17,.43,.2,'#eef4ed');box(data,x+.13,.62,z,.17,.43,.2,'#eef4ed');box(data,x,1.02,z,.48,.52,.3,shirt);box(data,x,1.48,z,.49,.47,.43,skin);box(data,x,1.77,z-.04,.53,.22,.5,hair);box(data,x-.12,1.52,z+.225,.055,.055,.02,'#2e292b');box(data,x+.12,1.52,z+.225,.055,.055,.02,'#2e292b');if(step)box(data,x,1.31,z+.25,.14,.06,.03,'#b96c6e')}
  function render(){if(!canvas.isConnected)return;const width=Math.max(1,Math.round(canvas.clientWidth*devicePixelRatio)),height=Math.max(1,Math.round(canvas.clientHeight*devicePixelRatio));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;gl.viewport(0,0,width,height)}const state=scene(),verts=[];box(verts,4.5,-.72,4.5,13,.42,13,'#74c4d9');box(verts,4.5,-.45,4.5,10.4,.25,10.4,'#f4d7a6');for(let x=0;x<9;x++)for(let z=0;z<9;z++)box(verts,x,.02,z,.97,.32,.97,(x+z)%4===0?'#9ccf82':'#a8d88b');
    // House, roof, dock, paths and foliage are deliberately simple low-poly pieces.
    for(let x=4;x<=7;x++)box(verts,x,.21,3,.9,.035,.9,'#e8cea4');box(verts,6.8,.81,2.1,2.35,1.25,2.05,'#f9e9ca');box(verts,6.8,1.56,2.1,2.7,.32,2.3,'#b87f84');box(verts,6.8,.58,3.17,.55,.8,.06,'#8e6c62');box(verts,5.96,1.04,3.17,.47,.4,.06,'#a8d8de');box(verts,1.25,.8,1.1,.36,1.4,.36,'#9a755c');box(verts,1.25,1.7,1.1,1.35,1.25,1.35,'#5f9d72');box(verts,7.8,.73,6.6,.35,1.27,.35,'#9a755c');box(verts,7.8,1.5,6.6,1.25,1.2,1.25,'#70a97a');box(verts,2,.34,7.6,.6,.3,.6,'#e8a8b1');box(verts,1.9,.61,7.6,.12,.3,.12,'#609779');
    for(let x=2;x<=4;x++)for(let z=5;z<=6;z++){box(verts,x,.22,z,.76,.09,.76,'#9a755f');const crop=state.crops?.find(row=>row.x===x&&row.z===z);if(crop){const age=(Date.now()-crop.plantedAt)/(60*60*1000),size=Math.min(.63,.18+Math.max(0,age)*.22);box(verts,x,.35+size/2,z,.1,size,.1,'#438c5e');box(verts,x-.12,.42+size/2,z,.23,.09,.18,'#74b97a');box(verts,x+.12,.42+size/2,z,.23,.09,.18,'#74b97a');if(age>2)box(verts,x,.49+size,z,.19,.2,.19,'#f28a8f')}}
    character(verts,state.avatar.x,state.avatar.z,state.avatar);if(state.visitor)character(verts,state.visitor.x,state.visitor.z,{skin:'#f2d3b7',shirt:'#c1a2d9',hair:'#685666'},1);
    gl.clearColor(.56,.79,.88,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.useProgram(program);gl.uniform1f(uniforms.uYaw,yaw);gl.uniform1f(uniforms.uElevation,.62);gl.uniform1f(uniforms.uAspect,width/height);gl.uniform1f(uniforms.uZoom,zoom);gl.uniform3f(uniforms.uCenter,4.5,.45,4.5);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(position);gl.enableVertexAttribArray(color);gl.vertexAttribPointer(position,3,gl.FLOAT,false,24,0);gl.vertexAttribPointer(color,3,gl.FLOAT,false,24,12);gl.drawArrays(gl.TRIANGLES,0,verts.length/6);frame=requestAnimationFrame(render)}
  canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,yaw,moved:false};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x;if(Math.abs(dx)>7||Math.abs(e.clientY-drag.y)>7)drag.moved=true;if(drag.moved)yaw=drag.yaw+dx*.008};canvas.onpointerup=e=>{if(!drag)return;const moved=drag.moved;drag=null;if(moved)return;const rect=canvas.getBoundingClientRect(),sx=(e.clientX-rect.left)/rect.width,sy=(e.clientY-rect.top)/rect.height,aspect=rect.width/rect.height,xx=(sx*2-1)*aspect/zoom,zz=-(1-2*sy)/(.62*zoom),x=Math.round(4.5+xx*Math.cos(yaw)+zz*Math.sin(yaw)),z=Math.round(4.5-xx*Math.sin(yaw)+zz*Math.cos(yaw));if(x>=0&&x<=8&&z>=0&&z<=8)onMove(x,z)};canvas.onwheel=e=>{e.preventDefault();zoom=Math.min(.16,Math.max(.075,zoom-e.deltaY*.0001))};render();return{dispose(){cancelAnimationFrame(frame);canvas.onpointerdown=canvas.onpointermove=canvas.onpointerup=canvas.onwheel=null}};
}
function parseColor(hex){const clean=String(hex||'#ffffff').replace('#','');const value=/^[0-9a-f]{6}$/i.test(clean)?clean:'ffffff';return [0,2,4].map(i=>parseInt(value.slice(i,i+2),16)/255)}
