import { escapeHtml, showToast, openSheet, closeSheet } from "./core/ui.js";
import { memoryProfile, listMemoryEntries, clearCharacterMemory, retrieveMemoryContext } from "./memory-engine.js";

const META={user_detail:["关于 USER 的小事","USER","✦"],shared_plan:["我们的计划","PLAN","↗"],impression:["心中的 USER","IMPRESSION","◌"],important_event:["重要事件","IMPORTANT","◆"],daily_event:["相处日常","EVERYDAY","·"],todo:["待办事项","TO DO","✓"],promise:["彼此的承诺","PROMISE","∞"],relationship:["关系与相处","RELATIONSHIP","♥"],self_awareness:["CHAR 对自己的认知","SELF","◎"],preference:["偏好与习惯","PREFERENCE","＋"],boundary:["边界与雷区","BOUNDARY","—"]};

export function createMemoryDebugRenderer({store,navigate}){
  return async function render(container,params={}){
    const state=store.getState(),personId=params.personId||state.people.find(x=>x.type==="char")?.id,memoryOwnerId=params.memoryOwnerId||personId,person=state.people.find(x=>x.id===personId);if(!person)return navigate("contacts");
    const profile=memoryProfile(state,memoryOwnerId),entries=await listMemoryEntries(memoryOwnerId),dynamic=profile.dynamicState,layers=countLayers(entries);
    container.className="app-view memory-debug-view memory-vault";
    container.innerHTML=`<section class="memory-vault-hero"><div><span>PRIVATE MEMORY VAULT</span><h2>${escapeHtml(person.name)} 的记忆</h2><p>${escapeHtml(profile.lastSummary||"记忆会随着相处逐渐形成，不会机械复述给任何人听。")}</p></div><div class="memory-orbit"><b>${entries.length}</b><small>MEMORIES</small></div></section><section class="memory-pulse"><article><span>关系阶段</span><strong>${escapeHtml(dynamic.relationshipStage.stage)}</strong><small>${escapeHtml(dynamic.relationshipStage.interactionPattern)}</small></article>${meter("信任",dynamic.charImpressionOfUser.trustLevel)}${meter("好感",dynamic.charImpressionOfUser.affectionLevel)}${meter("距离",100-Number(dynamic.relationshipStage.emotionalDistance||0))}</section><section class="memory-layer-strip"><div><b>${layers.permanent}</b><span>永久记忆</span><small>身份、边界、重大事件</small></div><div><b>${layers.retrieval}</b><span>检索记忆</span><small>相关话题出现时想起</small></div><div><b>${layers.temporary}</b><span>临时记忆</span><small>近期情绪与短期安排</small></div></section><section class="memory-core-card"><header><span>CORE MEMORY</span><small>${profile.lastUpdatedAt?new Date(profile.lastUpdatedAt).toLocaleString("zh-CN"):"尚未总结"}</small></header><p>${escapeHtml(profile.coreMemory)}</p></section><div class="memory-category-grid">${Object.keys(META).map(key=>categoryCard(key,entries)).join("")}</div><section class="memory-inner-grid">${innerCard("CHAR 此刻的自己",dynamic.charSelfState.currentMood,[dynamic.charSelfState.selfUnderstanding,...dynamic.charSelfState.recentThoughts])}${innerCard("心中的 USER",dynamic.charImpressionOfUser.recentMood,[...(dynamic.charImpressionOfUser.traits||[]),...(dynamic.charImpressionOfUser.smallDetails||[])])}${innerCard("两个人之间",dynamic.relationshipFeeling.currentFeeling,[dynamic.relationshipFeeling.attachmentStyle,...(dynamic.relationshipFeeling.expectations||[])])}</section><details class="memory-debug-panel"><summary>开发者调试与实际 Prompt</summary><div class="row"><button class="button secondary" data-test-retrieval>测试检索</button><button class="button secondary" data-clear-memory>清空记忆</button></div><pre>${escapeHtml(profile.lastPrompt||"在聊天设置开启测试模式并对话一次后，这里会显示实际请求。")}</pre></details>`;
    container.querySelector("[data-test-retrieval]").onclick=()=>openSheet(`<div class="sheet-title"><h3>测试记忆检索</h3><button class="button ghost" data-sheet-close>关闭</button></div><label class="field"><span>模拟 USER 消息</span><textarea data-query rows="4" placeholder="例如：你还记得我们说过周末去哪里吗？"></textarea></label><button class="button" data-run>查看本轮会想起什么</button><pre class="retrieval-result" data-result></pre>`,{onReady(sheet){sheet.querySelector("[data-run]").onclick=async()=>{const result=await retrieveMemoryContext(store.getState(),memoryOwnerId,sheet.querySelector("[data-query]").value);sheet.querySelector("[data-result]").textContent=result.selected.map(x=>`[${layerName(x.layer)} / ${categoryName(x.category)}] ${x.text||x.event}`).join("\n")||"没有命中记忆"}}});
    container.querySelector("[data-clear-memory]").onclick=()=>openSheet(`<div class="confirm-dialog"><h3>清空 ${escapeHtml(person.name)} 的记忆？</h3><p>人物设定会保留，当前账号对应的永久、检索、临时记忆和动态关系状态都会重置。</p><div class="row"><button class="button secondary" data-sheet-close>取消</button><button class="button" data-confirm>清空</button></div></div>`,{onReady(sheet){sheet.querySelector("[data-confirm]").onclick=async()=>{await clearCharacterMemory(memoryOwnerId);store.update(s=>{delete s.memoryProfiles?.[memoryOwnerId]});closeSheet();showToast("记忆库已清空");render(container,params)}}});
  }
}

function meter(label,value){const number=Math.max(0,Math.min(100,Number(value)||0));return`<article class="memory-meter"><span>${label}</span><strong>${number}</strong><i><b style="width:${number}%"></b></i></article>`}
function categoryCard(key,entries){const [title,en,icon]=META[key],rows=entries.filter(x=>(x.category||legacyCategory(x))===key).sort((a,b)=>(b.importance||0)-(a.importance||0)||b.timestamp-a.timestamp);return`<article class="memory-category-card ${rows.length?"has-memory":"empty-memory"}"><header><i>${icon}</i><div><span>${en}</span><strong>${title}</strong></div><b>${rows.length}</b></header><div>${rows.slice(0,5).map(x=>`<p><span class="memory-layer-dot ${x.layer||"retrieval"}"></span>${escapeHtml(x.text||x.event||"")}<small>${layerName(x.layer)}${x.dueDate?` · ${escapeHtml(x.dueDate)}`:""}</small></p>`).join("")||"<small>还没有形成这一类记忆</small>"}</div></article>`}
function innerCard(title,lead,items){const rows=(items||[]).filter(Boolean).slice(0,5);return`<article><span>${title}</span><strong>${escapeHtml(lead||"仍在变化")}</strong><div>${rows.map(x=>`<small>${escapeHtml(x)}</small>`).join("")||"<small>尚未形成清晰认知</small>"}</div></article>`}
function countLayers(entries){return entries.reduce((out,x)=>{out[x.layer||"retrieval"]=(out[x.layer||"retrieval"]||0)+1;return out},{permanent:0,retrieval:0,temporary:0})}
function layerName(value){return({permanent:"永久",retrieval:"检索",temporary:"临时"})[value]||"检索"}
function categoryName(value){return META[value]?.[0]||"相处日常"}
function legacyCategory(x){if(x.kind==="episodic")return"important_event";if(x.kind==="keyword")return"user_detail";return"daily_event"}
