import { sendToModel } from "./integrations/ai-client.js";

const DB_NAME="bunny-bunny-memory",STORE="entries",DIM=192,running=new Set(),TEMP_TTL=7*24*60*60*1000;
const CATEGORIES=["user_detail","shared_plan","impression","important_event","daily_event","todo","promise","relationship","self_awareness","preference","boundary"];
export const DEFAULT_MEMORY_PROFILE={
  coreMemory:"还没有形成需要常驻的共同记忆。",
  dynamicState:{
    charImpressionOfUser:{traits:[],smallDetails:[],likes:[],dislikes:[],concerns:[],trustLevel:20,affectionLevel:10,recentMood:"仍在认识彼此"},
    charSelfState:{currentMood:"平静",selfUnderstanding:"保持原本的自我认知",recentThoughts:[],unresolvedFeelings:[]},
    relationshipStage:{stage:"初识",emotionalDistance:80,interactionPattern:"仍在摸索相处节奏",milestones:[],tensionPoints:[],sharedRituals:[]},
    relationshipFeeling:{currentFeeling:"好奇",attachmentStyle:"依照人物设定自然发展",expectations:[],worries:[]}
  },
  summaryEveryN:8,grandEveryM:40,lastRegularTurn:0,lastGrandTurn:0,lastUpdatedAt:"",memoryDebugEnabled:false,lastPrompt:"",lastRetrieval:null,
  regularPrompt:"只提炼真正会影响之后相处的细节：USER 的小事、共同计划、承诺、待办、关系变化和有情绪重量的事件。普通寒暄只进入临时记忆。",
  grandPrompt:"重新审视长期相处形成的印象、关系阶段、CHAR 对自己的认知与两人的相处模式。变化必须缓慢、真实，并始终服从原始人设。"
};

export function memoryProfile(state,personId){return{...DEFAULT_MEMORY_PROFILE,...(state.memoryProfiles?.[personId]||{}),dynamicState:deepMerge(DEFAULT_MEMORY_PROFILE.dynamicState,state.memoryProfiles?.[personId]?.dynamicState||{})}}

export async function retrieveMemoryContext(state,personId,input){
  const profile=memoryProfile(state,personId),all=await getEntries(personId),now=Date.now(),expired=all.filter(x=>x.layer==="temporary"&&x.expiresAt&&x.expiresAt<now);expired.forEach(x=>removeEntry(x.id).catch(()=>{}));
  const entries=all.filter(x=>!expired.includes(x)),query=String(input||"").trim(),lower=query.toLowerCase(),vector=embed(query);
  const keyword=entries.filter(x=>(x.keywords||[]).some(key=>lower.includes(String(key).toLowerCase()))).sort((a,b)=>(b.priority||b.importance||0)-(a.priority||a.importance||0)).slice(0,5);
  const permanent=entries.filter(x=>x.layer==="permanent").sort((a,b)=>(b.importance||0)-(a.importance||0)||b.timestamp-a.timestamp).slice(0,6);
  const semantic=entries.filter(x=>["memory","longTerm"].includes(x.kind)&&Array.isArray(x.vector)&&x.layer!=="temporary").map(x=>({...x,score:cosine(vector,x.vector)})).filter(x=>x.score>.1).sort((a,b)=>b.score-a.score||(b.importance||0)-(a.importance||0)).slice(0,6);
  const temporary=entries.filter(x=>x.layer==="temporary").map(x=>({...x,score:cosine(vector,x.vector||embed(x.text||""))})).filter(x=>x.score>.06||now-x.timestamp<24*60*60*1000).sort((a,b)=>b.score-a.score||b.timestamp-a.timestamp).slice(0,4);
  const today=new Date(),monthDay=`${String(today.getMonth()+1).padStart(2,"0")}-${String(today.getDate()).padStart(2,"0")}`,episodic=entries.filter(x=>(x.kind==="episodic"||x.category==="important_event")&&(x.isAnniversary||String(x.date||"").slice(5)===monthDay)).slice(0,4);
  const selected=uniqueById([...permanent,...keyword,...episodic,...semantic,...temporary]).slice(0,16),groups=groupForPrompt(selected);
  const promptBlock=`【不可违背的共同核心记忆】\n${profile.coreMemory}\n【CHAR 此刻的内在状态与关系感受】\n${JSON.stringify(profile.dynamicState)}\n【本轮自然联想到的记忆】\n${groups||"本轮没有需要刻意想起的旧事。"}\n把这些内容当作一个真实的人自然记得的往事、印象和未完成事项：只在相关时影响态度、措辞和决定，不要逐条复述，不要主动报数值，不要像读取档案，也不要为了提到记忆而改变话题。原始人物设定永远高于关系状态；状态只能改变熟悉程度和当下反应，不能把角色改造成另一种性格。`;
  return{promptBlock,selected,keyword,episodic,permanent,temporary,semantic:semantic.map(x=>({id:x.id,text:x.text,category:x.category,score:Number(x.score.toFixed(4))}))};
}

export function savePromptDebug(store,personId,payload){const state=store.getState();if(!memoryProfile(state,personId).memoryDebugEnabled)return;const transcript=(payload.messages||[]).map((message,index)=>`${index+1}. ${String(message.role||"user").toUpperCase()} [${message.type||"text"}] ${message.text||message.description||message.type||""}`).join("\n"),actual=`【SYSTEM PROMPT】\n${payload.systemPrompt||""}\n\n【MESSAGES】\n${transcript}`;store.update(s=>{s.memoryProfiles=s.memoryProfiles||{};s.memoryProfiles[personId]={...memoryProfile(s,personId),lastPrompt:actual.slice(-100000),lastRetrieval:payload.retrieval||null,lastPromptAt:new Date().toISOString()}})}

export function scheduleMemoryMaintenance({store,personId,model,messages}){const state=store.getState(),profile=memoryProfile(state,personId),turns=(messages||[]).filter(x=>x.role==="user"&&!x.recalled).length,n=Math.max(2,Number(profile.summaryEveryN)||8),m=Math.max(n,Number(profile.grandEveryM)||40),grand=turns-profile.lastGrandTurn>=m,regular=turns-profile.lastRegularTurn>=n;if((!regular&&!grand)||running.has(personId)||!model?.apiKey||!model.model)return;running.add(personId);queueMicrotask(async()=>{try{await maintain(store,personId,model,grand?"grand":"regular")}catch(error){console.warn("Bunny memory update failed",error)}finally{running.delete(personId)}})}

export async function addMemoryEntry(personId,entry){const layer=entry.layer||layerFor(entry.category,entry.importance),row={id:entry.id||crypto.randomUUID(),personId,kind:entry.kind||"memory",category:entry.category||"daily_event",layer,timestamp:entry.timestamp||Date.now(),importance:3,status:"active",...entry};if(["memory","longTerm"].includes(row.kind))row.vector=embed(row.text||row.event||"");if(layer==="temporary"&&!row.expiresAt)row.expiresAt=Date.now()+TEMP_TTL;await putEntries([row]);return row}
export async function listMemoryEntries(personId){const rows=await getEntries(personId),now=Date.now(),expired=rows.filter(x=>x.layer==="temporary"&&x.expiresAt&&x.expiresAt<now);await Promise.all(expired.map(x=>removeEntry(x.id)));return rows.filter(x=>!expired.includes(x))}
export async function clearCharacterMemory(personId){const rows=await getEntries(personId);await Promise.all(rows.map(x=>removeEntry(x.id)))}

async function maintain(store,personId,model,mode){
  const state=store.getState(),profile=memoryProfile(state,personId),person=state.people.find(x=>x.id===personId),user=state.people.find(x=>x.id===state.currentUserId),conv=state.conversations.find(x=>x.personId===personId),messages=state.messages[conv?.id]||[],turns=messages.filter(x=>x.role==="user"&&!x.recalled).length,limit=mode==="grand"?Math.max(40,Number(profile.grandEveryM)||40)*2:Math.max(8,Number(profile.summaryEveryN)||8)*2,recent=messages.slice(-limit).map(x=>`${x.role==="char"?person.name:user.name}：${x.recalled?"[已撤回]":x.text||x.description||`[${x.type}]`}`).join("\n"),custom=mode==="grand"?profile.grandPrompt:profile.regularPrompt;
  const prompt=`你在后台维护 ${person.name} 与 ${user.name} 的私人记忆和关系状态。原始人物设定：${person.personality||person.persona||person.note||""}\nUSER 档案：${user.personality||user.note||""}\n现有核心记忆：${profile.coreMemory}\n现有动态状态：${JSON.stringify(profile.dynamicState)}\n这是${mode==="grand"?"长期大总结":"阶段整理"}。${custom}\n最近对话：\n${recent}\n请像真人在心里整理近况：区分 USER 小事、共同计划、心中印象、重要事件、普通日常、待办、承诺、关系变化、自我认知、偏好与边界。永久层只放身份事实、明确边界、重大承诺/事件和稳定关系认知；检索层放以后可能因话题想起的内容；临时层放近期情绪、短期安排和普通日常。不要因为一次情绪就改写性格或关系。只返回严格 JSON：{"coreMemory":"高度压缩、需要每轮常驻的稳定共同记忆","memories":[{"category":"${CATEGORIES.join(" 或 ")}","layer":"permanent或retrieval或temporary","text":"自然简洁的第三人称事实","keywords":["精确触发词"],"importance":1,"date":"YYYY-MM-DD或空","dueDate":"YYYY-MM-DD或空","status":"active或done","emotionalWeight":1,"isAnniversary":false}],"dynamicState":{"charImpressionOfUser":{"traits":[],"smallDetails":[],"likes":[],"dislikes":[],"concerns":[],"trustLevel":0,"affectionLevel":0,"recentMood":""},"charSelfState":{"currentMood":"","selfUnderstanding":"","recentThoughts":[],"unresolvedFeelings":[]},"relationshipStage":{"stage":"","emotionalDistance":0,"interactionPattern":"","milestones":[],"tensionPoints":[],"sharedRituals":[]},"relationshipFeeling":{"currentFeeling":"","attachmentStyle":"","expectations":[],"worries":[]}},"summary":"本次变化摘要"}。所有字段必须存在；数值 0-100 且只能渐进变化。`;
  const result=parseJson(await sendToModel(model,[{role:"user",text:prompt}],""));if(!result)throw Error("记忆总结没有返回有效 JSON");
  const existing=await getEntries(personId),seen=new Set(existing.map(x=>normalize(x.text||x.event))),rows=[];for(const item of result.memories||[]){if(!item.text||!CATEGORIES.includes(item.category)||seen.has(normalize(item.text)))continue;seen.add(normalize(item.text));const layer=["permanent","retrieval","temporary"].includes(item.layer)?item.layer:layerFor(item.category,item.importance),timestamp=Date.now();rows.push({id:crypto.randomUUID(),personId,kind:"memory",category:item.category,layer,text:String(item.text).slice(0,600),keywords:(item.keywords||[]).map(String).slice(0,10),importance:clamp(item.importance,1,5),date:item.date||"",dueDate:item.dueDate||"",status:item.status||"active",emotionalWeight:clamp(item.emotionalWeight,1,5),isAnniversary:Boolean(item.isAnniversary),timestamp,expiresAt:layer==="temporary"?timestamp+TEMP_TTL:0,vector:embed(item.text)})}await putEntries(rows);
  store.update(s=>{s.memoryProfiles=s.memoryProfiles||{};const old=memoryProfile(s,personId),dynamic=boundedDynamic(old.dynamicState,result.dynamicState||{});s.memoryProfiles[personId]={...old,coreMemory:String(result.coreMemory||old.coreMemory).slice(0,6000),dynamicState:dynamic,lastRegularTurn:turns,lastGrandTurn:mode==="grand"?turns:old.lastGrandTurn,lastUpdatedAt:new Date().toISOString(),lastSummary:String(result.summary||"").slice(0,1500)}})
}

function groupForPrompt(entries){const order=[["user_detail","关于 USER 的小事"],["preference","偏好与习惯"],["shared_plan","我们的计划"],["todo","待办事项"],["promise","彼此的承诺"],["important_event","重要事件"],["daily_event","相处日常"],["impression","心中的 USER"],["relationship","关系与相处模式"],["self_awareness","CHAR 对自己的认知"],["boundary","边界与雷区"]];return order.map(([key,label])=>{const rows=entries.filter(x=>(x.category||legacyCategory(x))===key);return rows.length?`【${label}】\n${rows.map(x=>`- ${x.text||x.event}`).join("\n")}`:""}).filter(Boolean).join("\n")}
function legacyCategory(x){if(x.kind==="episodic")return"important_event";if(x.kind==="keyword")return"user_detail";return"daily_event"}
function layerFor(category,importance){if(["promise","boundary","important_event"].includes(category)&&Number(importance)>=4)return"permanent";if(["daily_event"].includes(category)&&Number(importance)<=2)return"temporary";return"retrieval"}
function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE)){const object=db.createObjectStore(STORE,{keyPath:"id"});object.createIndex("personId","personId");object.createIndex("kind","kind")}};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function getEntries(personId){if(!globalThis.indexedDB)return[];const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readonly"),request=tx.objectStore(STORE).index("personId").getAll(personId);request.onsuccess=()=>resolve(request.result||[]);request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close()})}
async function putEntries(rows){if(!rows.length||!globalThis.indexedDB)return;const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite"),object=tx.objectStore(STORE);rows.forEach(x=>object.put(x));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}
async function removeEntry(id){if(!globalThis.indexedDB)return;const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}
export function embed(text){const values=new Float32Array(DIM),tokens=tokenize(text);for(const token of tokens){let h=2166136261;for(const c of token){h^=c.codePointAt(0);h=Math.imul(h,16777619)}const index=(h>>>0)%DIM,sign=(h&1)?1:-1;values[index]+=sign*(1+Math.min(token.length,8)/8)}const norm=Math.sqrt(values.reduce((sum,x)=>sum+x*x,0))||1;return Array.from(values,x=>x/norm)}
export function cosine(a,b){let sum=0,aa=0,bb=0;for(let i=0;i<Math.min(a.length,b.length);i++){sum+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i]}return aa&&bb?sum/Math.sqrt(aa*bb):0}
function tokenize(value){const text=String(value||"").toLowerCase().normalize("NFKC"),parts=text.match(/[a-z0-9_]+|[\u3400-\u9fff]/g)||[],out=[...parts];for(let i=0;i<parts.length-1;i++)out.push(parts[i]+parts[i+1]);return out}
function parseJson(text){try{const match=String(text||"").match(/\{[\s\S]*\}/);return match?JSON.parse(match[0]):null}catch{return null}}
function boundedDynamic(old,next){const merged=deepMerge(old,next);for(const key of ["trustLevel","affectionLevel"]){const before=Number(old?.charImpressionOfUser?.[key]||0),wanted=Number(merged.charImpressionOfUser?.[key]||before);merged.charImpressionOfUser[key]=Math.max(0,Math.min(100,before+Math.max(-7,Math.min(7,wanted-before))))}const before=Number(old?.relationshipStage?.emotionalDistance??80),wanted=Number(merged.relationshipStage?.emotionalDistance??before);merged.relationshipStage.emotionalDistance=Math.max(0,Math.min(100,before+Math.max(-7,Math.min(7,wanted-before))));return merged}
function deepMerge(a,b){const out={...a};for(const [key,value] of Object.entries(b||{}))out[key]=value&&typeof value==="object"&&!Array.isArray(value)?deepMerge(a?.[key]||{},value):value;return out}
function uniqueById(items){const seen=new Set();return items.filter(x=>!seen.has(x.id)&&seen.add(x.id))}
function clamp(value,min,max){return Math.max(min,Math.min(max,Number(value)||min))}
function normalize(value){return String(value||"").replace(/\s+/g,"").toLowerCase().slice(0,240)}
