import { escapeHtml, showToast, openSheet, closeSheet } from "./core/ui.js";
import { memoryProfile, listMemoryEntries, clearCharacterMemory, retrieveMemoryContext, updateMemoryEntry } from "./memory-engine.js";

const META={user_detail:["关于 USER 的小事","USER","✦"],shared_plan:["我们的计划","PLAN","↗"],impression:["心中的 USER","IMPRESSION","◌"],important_event:["重要事件","IMPORTANT","◆"],daily_event:["相处日常","EVERYDAY","·"],todo:["待办事项","TO DO","✓"],promise:["彼此的承诺","PROMISE","∞"],relationship:["关系与相处","RELATIONSHIP","♥"],self_awareness:["CHAR 对自己的认知","SELF","◎"],preference:["偏好与习惯","PREFERENCE","＋"],boundary:["边界与雷区","BOUNDARY","—"]};

export function createMemoryDebugRenderer({store,navigate}){
  return async function render(container,params={}){
    const state=store.getState(),personId=params.personId||state.people.find(x=>x.type==="char")?.id,memoryOwnerId=params.memoryOwnerId||personId,person=state.people.find(x=>x.id===personId);if(!person)return navigate("contacts");
    const profile=memoryProfile(state,memoryOwnerId),entries=await listMemoryEntries(memoryOwnerId),dynamic=profile.dynamicState,layers=countLayers(entries);
    container.className="app-view memory-debug-view memory-vault";
    container.innerHTML=`<section class="memory-vault-hero"><div><span>PRIVATE MEMORY VAULT</span><h2>${escapeHtml(person.name)} 的记忆</h2><p>${escapeHtml(profile.lastSummary||"记忆会随着相处逐渐形成，不会机械复述给任何人听。")}</p></div><div class="memory-orbit"><b>${entries.length}</b><small>MEMORIES</small></div></section><section class="memory-pulse"><article><span>关系阶段</span><strong>${escapeHtml(dynamic.relationshipStage.stage)}</strong><small>${escapeHtml(dynamic.relationshipStage.interactionPattern)}</small></article>${meter("信任",dynamic.charImpressionOfUser.trustLevel)}${meter("好感",dynamic.charImpressionOfUser.affectionLevel)}${meter("距离",100-Number(dynamic.relationshipStage.emotionalDistance||0))}</section><section class="memory-layer-strip"><div><b>${layers.permanent}</b><span>永久记忆</span><small>身份、边界、重大事件</small></div><div><b>${layers.retrieval}</b><span>检索记忆</span><small>相关话题出现时想起</small></div><div><b>${layers.temporary}</b><span>临时记忆</span><small>近期情绪与短期安排</small></div></section><section class="memory-core-card"><header><span>CORE MEMORY</span><small>${profile.lastUpdatedAt?new Date(profile.lastUpdatedAt).toLocaleString("zh-CN"):"尚未总结"}</small></header><p>${escapeHtml(profile.coreMemory)}</p></section><div class="memory-category-grid">${Object.keys(META).map(key=>categoryCard(key,entries)).join("")}</div><section class="memory-inner-grid">${innerCard("CHAR 此刻的自己",dynamic.charSelfState.currentMood,[dynamic.charSelfState.selfUnderstanding,...dynamic.charSelfState.recentThoughts])}${innerCard("心中的 USER",dynamic.charImpressionOfUser.recentMood,[...(dynamic.charImpressionOfUser.traits||[]),...(dynamic.charImpressionOfUser.smallDetails||[])])}${innerCard("两个人之间",dynamic.relationshipFeeling.currentFeeling,[dynamic.relationshipFeeling.attachmentStyle,...(dynamic.relationshipFeeling.expectations||[])])}</section><details class="memory-debug-panel"><summary>开发者调试与实际 Prompt</summary><div class="row"><button class="button secondary" data-test-retrieval>测试检索</button><button class="button secondary" data-clear-memory>清空记忆</button></div><pre>${escapeHtml(profile.lastPrompt||"在聊天设置开启测试模式并对话一次后，这里会显示实际请求。")}</pre></details>`;
    container.querySelector("[data-test-retrieval]").onclick=()=>openSheet(`<div class="sheet-title"><h3>测试记忆检索</h3><button class="button ghost" data-sheet-close>关闭</button></div><label class="field"><span>模拟 USER 消息</span><textarea data-query rows="4" placeholder="例如：你还记得我们说过周末去哪里吗？"></textarea></label><button class="button" data-run>查看本轮会想起什么</button><pre class="retrieval-result" data-result></pre>`,{onReady(sheet){sheet.querySelector("[data-run]").onclick=async()=>{const result=await retrieveMemoryContext(store.getState(),memoryOwnerId,sheet.querySelector("[data-query]").value);sheet.querySelector("[data-result]").textContent=result.selected.map(x=>`[${layerName(x.layer)} / ${categoryName(x.category)}] ${x.text||x.event}`).join("\n")||"没有命中记忆"}}});
    container.querySelector("[data-clear-memory]").onclick=()=>openSheet(`<div class="confirm-dialog"><h3>清空 ${escapeHtml(person.name)} 的记忆？</h3><p>人物设定会保留，当前账号对应的永久、检索、临时记忆和动态关系状态都会重置。</p><div class="row"><button class="button secondary" data-sheet-close>取消</button><button class="button" data-confirm>清空</button></div></div>`,{onReady(sheet){sheet.querySelector("[data-confirm]").onclick=async()=>{await clearCharacterMemory(memoryOwnerId);store.update(s=>{delete s.memoryProfiles?.[memoryOwnerId]});closeSheet();showToast("记忆库已清空");render(container,params)}}});
    const modules=[...container.querySelectorAll('.memory-pulse>article')].map((el,i)=>[el,'dynamic',i]);
    modules.push(...[...container.querySelectorAll('.memory-layer-strip>div')].map((el,i)=>[el,'layer',['permanent','retrieval','temporary'][i]]));
    modules.push([container.querySelector('.memory-core-card'),'core','core']);
    modules.push(...[...container.querySelectorAll('.memory-category-card')].map((el,i)=>[el,'category',Object.keys(META)[i]]));
    modules.push(...[...container.querySelectorAll('.memory-inner-grid>article')].map((el,i)=>[el,'inner',i]));
    for(const [el,kind,key] of modules){if(!el)continue;el.classList.add('memory-openable');el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-label',`查看${kind==='category'?categoryName(key):kind==='layer'?layerName(key)+'记忆':'记忆模块'}详情`);el.onclick=()=>openModule(kind,key);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openModule(kind,key)}}}
    function openModule(kind,key){
      if(kind==='category')return openEntries(categoryName(key),entries.filter(row=>(row.category||legacyCategory(row))===key));
      if(kind==='layer')return openEntries(`${layerName(key)}记忆`,entries.filter(row=>row.layer===key));
      if(kind==='core')return openSheet(`<div class="sheet-title"><h3>核心记忆</h3><button class="button ghost" data-sheet-close>关闭</button></div><p class="memory-detail-text">${escapeHtml(profile.coreMemory)}</p><small>由有来源的长期记忆组成；角色不会逐句复述。</small>`);
      const value=kind==='dynamic'?[dynamic.relationshipStage,dynamic.charImpressionOfUser.trustLevel,dynamic.charImpressionOfUser.affectionLevel,dynamic.relationshipStage.emotionalDistance][key]:[dynamic.charSelfState,dynamic.charImpressionOfUser,dynamic.relationshipFeeling][key];
      const title=kind==='dynamic'?['关系阶段','信任','好感','距离'][key]:['CHAR 此刻的自己','心中的 USER','两个人之间'][key];
      openSheet(`<div class="sheet-title"><h3>${title}</h3><button class="button ghost" data-sheet-close>关闭</button></div><div class="memory-detail-fields">${detailFields(value)}</div><p class="sub">这些是随相处缓慢变化的主观状态，不会替代人物原始性格。</p>`);
    }
    function openEntries(title,rows){openSheet(`<div class="sheet-title"><h3>${escapeHtml(title)} · ${rows.length}</h3><button class="button ghost" data-sheet-close>关闭</button></div><div class="memory-entry-list">${rows.sort((a,b)=>(b.pinned?1:0)-(a.pinned?1:0)||(b.timestamp||0)-(a.timestamp||0)).map(row=>`<button type="button" data-memory-entry="${escapeHtml(row.id)}"><b>${row.pinned?'📌 ':''}${escapeHtml(row.text||row.event||'')}</b><small>${escapeHtml(layerName(row.layer))} · ${new Date(row.timestamp||Date.now()).toLocaleDateString('zh-CN')} · ${escapeHtml(row.status||'active')}</small></button>`).join('')||'<p>这一栏暂时没有记忆。</p>'}</div>`,{onReady(sheet){sheet.querySelectorAll('[data-memory-entry]').forEach(button=>button.onclick=()=>openEntry(rows.find(row=>row.id===button.dataset.memoryEntry)))}})}
    function openEntry(row){if(!row)return;const sources=(row.sourceIds||[]).map(id=>[...Object.values(state.messages||{}).flat(),...Object.values(state.groupMessages||{}).flat()].find(item=>item.id===id)).filter(Boolean);openSheet(`<div class="sheet-title"><h3>记忆详情</h3><button class="button ghost" data-sheet-close>关闭</button></div><form class="memory-entry-detail"><label class="field"><span>记忆内容</span><textarea name="text" rows="5">${escapeHtml(row.text||row.event||'')}</textarea></label><dl><div><dt>层级</dt><dd>${escapeHtml(layerName(row.layer))}</dd></div><div><dt>重要度</dt><dd>${Number(row.importance||3)}/5</dd></div><div><dt>可信度</dt><dd>${Math.round(Number(row.confidence??1)*100)}%</dd></div><div><dt>状态</dt><dd>${escapeHtml(row.status||'active')}</dd></div></dl><h4>来源</h4><div class="memory-sources">${sources.map(item=>`<p>${escapeHtml(item.text||item.description||'媒体消息')}</p>`).join('')||'<p>旧版记忆没有保存原消息引用。</p>'}</div><div class="row"><button type="button" class="button secondary" data-memory-pin>${row.pinned?'取消置顶':'置顶'}</button><button type="button" class="button secondary" data-memory-hide>${row.status==='hidden'?'恢复':'隐藏'}</button></div><div class="row"><button class="button">保存纠正</button><button type="button" class="button secondary" data-memory-delete>删除</button></div></form>`,{onReady(sheet){const update=async change=>{await updateMemoryEntry(memoryOwnerId,row.id,change);closeSheet();render(container,params);showToast('记忆已更新')};sheet.querySelector('form').onsubmit=e=>{e.preventDefault();void update({text:e.target.elements.text.value})};sheet.querySelector('[data-memory-pin]').onclick=()=>void update({pinned:!row.pinned});sheet.querySelector('[data-memory-hide]').onclick=()=>void update({status:row.status==='hidden'?'active':'hidden'});sheet.querySelector('[data-memory-delete]').onclick=()=>void update({status:'deleted'})}})}
  }
}

function meter(label,value){const number=Math.max(0,Math.min(100,Number(value)||0));return`<article class="memory-meter"><span>${label}</span><strong>${number}</strong><i><b style="width:${number}%"></b></i></article>`}
function categoryCard(key,entries){const [title,en,icon]=META[key],rows=entries.filter(x=>(x.category||legacyCategory(x))===key).sort((a,b)=>(b.importance||0)-(a.importance||0)||b.timestamp-a.timestamp);return`<article class="memory-category-card ${rows.length?"has-memory":"empty-memory"}"><header><i>${icon}</i><div><span>${en}</span><strong>${title}</strong></div><b>${rows.length}</b></header><div>${rows.slice(0,5).map(x=>`<p><span class="memory-layer-dot ${x.layer||"retrieval"}"></span>${escapeHtml(x.text||x.event||"")}<small>${layerName(x.layer)}${x.dueDate?` · ${escapeHtml(x.dueDate)}`:""}</small></p>`).join("")||"<small>还没有形成这一类记忆</small>"}</div></article>`}
function innerCard(title,lead,items){const rows=(items||[]).filter(Boolean).slice(0,5);return`<article><span>${title}</span><strong>${escapeHtml(lead||"仍在变化")}</strong><div>${rows.map(x=>`<small>${escapeHtml(x)}</small>`).join("")||"<small>尚未形成清晰认知</small>"}</div></article>`}
function countLayers(entries){return entries.reduce((out,x)=>{out[x.layer||"retrieval"]=(out[x.layer||"retrieval"]||0)+1;return out},{permanent:0,retrieval:0,temporary:0})}
function layerName(value){return({permanent:"永久",retrieval:"检索",temporary:"临时"})[value]||"检索"}
function categoryName(value){return META[value]?.[0]||"相处日常"}
function legacyCategory(x){if(x.kind==="episodic")return"important_event";if(x.kind==="keyword")return"user_detail";return"daily_event"}
function detailFields(value){const labels={stage:'关系阶段',interactionPattern:'相处模式',milestones:'里程碑',tensionPoints:'未解开的事',sharedRituals:'共同习惯',emotionalDistance:'情感距离',traits:'性格印象',smallDetails:'记住的小事',likes:'喜欢',dislikes:'不喜欢',concerns:'在意',trustLevel:'信任',affectionLevel:'好感',recentMood:'最近心情',currentMood:'当下心情',selfUnderstanding:'自我认识',recentThoughts:'最近念头',unresolvedFeelings:'没说出口的感受',currentFeeling:'当前感觉',attachmentStyle:'亲密方式',expectations:'期待',worries:'担忧'};if(value===null||typeof value!=='object')return`<p>${escapeHtml(String(value??'尚未形成'))}</p>`;return Object.entries(value).map(([key,item])=>`<article><strong>${labels[key]||escapeHtml(key)}</strong><p>${escapeHtml(Array.isArray(item)?item.join('、')||'暂无':String(item??'暂无'))}</p></article>`).join('')}
