import { sendToModel } from './integrations/ai-client.js';

// The day's blocks are decided by code and stored once. The model may enrich
// their descriptions, but cannot silently move times or override user rules.
const TEMPLATES={
  worker:[['00:00','07:00','睡眠','休息','sleep',false],['07:00','09:00','起床和通勤','路上','commute',true],['09:00','12:00','工作','忙碌中','busy',false],['12:00','13:30','午休','午休','free',true],['13:30','18:00','工作','忙碌中','busy',false],['18:00','23:00','自己的时间','下班了','free',true],['23:00','24:00','准备睡觉','准备休息','rest',true]],
  student:[['00:00','07:30','睡眠','休息','sleep',false],['07:30','09:00','早餐和路上','路上','commute',true],['09:00','12:00','上课','上课中','busy',false],['12:00','13:30','午饭','午休','free',true],['13:30','17:30','上课或自习','在学校','busy',false],['17:30','23:30','自由时间','有空','free',true],['23:30','24:00','准备休息','准备休息','rest',true]],
  night:[['00:00','03:00','夜间活动','还没睡','free',true],['03:00','11:00','睡眠','休息','sleep',false],['11:00','14:00','起床和午餐','刚睡醒','free',true],['14:00','19:00','工作或学习','忙碌中','busy',false],['19:00','24:00','夜间自由时间','有空','free',true]]
};
const inflight=new Map();
export const ROUTINE_CHOICES=[['worker','上班族'],['student','学生'],['night','夜猫子']];
const minute=value=>{const [h,m]=String(value).split(':').map(Number);return h*60+(m||0)};
const clampMinute=value=>Math.max(0,Math.min(1440,minute(value)));
const pad=value=>String(value).padStart(2,'0');
const clock=value=>`${pad(Math.floor(value/60))}:${pad(value%60)}`;
function parts(date,timezone){const values=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:timezone||'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23',weekday:'short'}).formatToParts(date).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return {day:`${values.year}-${values.month}-${values.day}`,weekday:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(values.weekday),minute:Number(values.hour)*60+Number(values.minute)}}
export function ensureScheduleState(state){state.schedulePlans||={};state.scheduleDays||={};return state}
export function scheduleClock(state,personId,now=new Date()){const person=state.people.find(x=>x.id===personId),world=state.worlds.find(x=>x.id===person?.worldId||x.id===state.currentWorldId);const timezone=world?.timezone||'Asia/Shanghai';try{return {...parts(now,timezone),timezone}}catch{return {...parts(now,'Asia/Shanghai'),timezone:'Asia/Shanghai'}}}
function templateFor(person,plan){if(TEMPLATES[plan?.routine])return plan.routine;return /学生|大学|高中|初中|学校|上课/.test(`${person?.occupation||''} ${person?.persona||''}`)?'student':/夜猫|深夜|夜班/.test(`${person?.personality||''} ${person?.occupation||''}`)?'night':'worker'}
function sanitizeEvent(event,date){if(!event||event.date&&event.date!==date)return null;const start=clampMinute(event.start||'00:00'),end=clampMinute(event.end||'00:00');if(end<=start)return null;return {start:clock(start),end:clock(end),title:String(event.title||'临时安排').slice(0,80),place:String(event.place||'').slice(0,60),status:String(event.status||'有安排').slice(0,28),mood:String(event.mood||'平常').slice(0,28),availability:event.availability==='free'?'free':event.availability==='rest'?'rest':'busy',canReply:event.canReply===true,source:event.source||'user'} }
function overlay(blocks,event){const start=minute(event.start),end=minute(event.end),next=[];for(const block of blocks){const left=minute(block.start),right=minute(block.end);if(right<=start||left>=end){next.push(block);continue}if(left<start)next.push({...block,end:clock(start)});if(right>end)next.push({...block,start:clock(end)})}next.push(event);return next.sort((a,b)=>minute(a.start)-minute(b.start))}
export function ensureDailySchedule(store,personId,now=new Date()){const state=ensureScheduleState(store.getState()),person=state.people.find(x=>x.id===personId);if(!person)return null;const {day,weekday,timezone}=scheduleClock(state,personId,now),key=`${personId}:${day}`;if(state.scheduleDays[key])return state.scheduleDays[key];const plan=state.schedulePlans[personId]||{},routine=templateFor(person,plan);let blocks=TEMPLATES[routine].map(([start,end,title,status,availability,canReply])=>({start,end,title,place:person.city||'',status,mood:'平常',availability,canReply,source:'template'}));for(const rule of plan.fixed||[])if(rule.weekdays?.includes(weekday)){const event=sanitizeEvent(rule,day);if(event)blocks=overlay(blocks,{...event,source:'fixed'})}for(const rule of plan.temporary||[])if(rule.date===day){const event=sanitizeEvent(rule,day);if(event)blocks=overlay(blocks,{...event,source:rule.source||'user'})}const value={date:day,timezone,routine,blocks,createdAt:Date.now(),modelAttempted:false};store.update(s=>{ensureScheduleState(s);s.scheduleDays[key]||=value;const keys=Object.keys(s.scheduleDays).filter(k=>k.startsWith(`${personId}:`)).sort();for(const stale of keys.slice(0,-14))delete s.scheduleDays[stale]});return store.getState().scheduleDays[key]}
export function currentSchedule(store,personId,now=new Date()){const schedule=ensureDailySchedule(store,personId,now);if(!schedule)return null;const t=scheduleClock(store.getState(),personId,now).minute;return schedule.blocks.find(x=>minute(x.start)<=t&&t<minute(x.end))||schedule.blocks.at(-1)}
export function nextReplyAt(store,personId,now=new Date()){
  if(currentSchedule(store,personId,now)?.canReply!==false)return now;
  // Probe absolute time, so midnight and timezone transitions use the same
  // schedule resolver as all other device and world decisions.
  for(let step=1;step<=192;step++){
    const probe=new Date(now.getTime()+step*15*60_000);
    if(currentSchedule(store,personId,probe)?.canReply)return probe;
  }
  return new Date(now.getTime()+48*60*60_000);
}
export function schedulePrompt(store,personId){const schedule=ensureDailySchedule(store,personId),current=currentSchedule(store,personId);if(!schedule||!current)return '';return `【今日已确定的日程 / ${schedule.date} ${schedule.timezone}】\n当前 ${current.start}—${current.end}：${current.title}；地点 ${current.place||'未公开'}；状态 ${current.status}；心情 ${current.mood}；${current.canReply?'可以间歇回复':'此刻不方便即时回复'}。\n今日其余日程：${schedule.blocks.map(x=>`${x.start}–${x.end} ${x.title}${x.place?` @${x.place}`:''}`).join('；')}。日程是同一天聊天、通话、动态和主动联系的唯一时间来源；表达要自然，不向 USER 泄露完整日程。`}
export function publicScheduleStatus(store,personId){const current=currentSchedule(store,personId);return current?.status||'最近在线'}
export function saveSchedulePlan(store,personId,plan){store.update(s=>{ensureScheduleState(s);s.schedulePlans[personId]={routine:TEMPLATES[plan.routine]?plan.routine:'worker',fixed:(plan.fixed||[]).slice(0,30),temporary:(plan.temporary||[]).slice(-80)};const today=scheduleClock(s,personId).day;delete s.scheduleDays[`${personId}:${today}`]})}
export function recordScheduleCommitment(store,personId,text,now=new Date()){
  const value=String(text||'').trim(),dateToken=value.match(/明天|后天|今天|今晚|下周[一二三四五六日天]|\d{1,2}月\d{1,2}日/);
  if(!dateToken||/[？?]/.test(value)||!/(?:面试|约|见|考试|开会|聚|看|去|出差|旅行|演出|吃饭|工作|加班|上课|提醒)/.test(value))return false;
  const timeToken=value.slice(dateToken.index,dateToken.index+28).match(/(上午|下午|晚上|早上|凌晨)?\s*(\d{1,2})(?:[:点时](\d{1,2}))?/),state=store.getState(),local=scheduleClock(state,personId,now),base=new Date(`${local.day}T12:00:00Z`),when=dateToken[0];
  if(when==='明天')base.setUTCDate(base.getUTCDate()+1);else if(when==='后天')base.setUTCDate(base.getUTCDate()+2);
  else if(when.startsWith('下周')){const target='一二三四五六日天'.indexOf(when.at(-1));base.setUTCDate(base.getUTCDate()+7+((target+1-base.getUTCDay()+7)%7))}
  else if(/月/.test(when)){const [,m,d]=when.match(/(\d+)月(\d+)日/);base.setUTCMonth(Number(m)-1,Number(d))}
  const time=timeToken?.[2]||(/面试|考试/.test(value)?'10':/晚饭|吃饭|晚上/.test(value)?'19':'12');let hour=Number(time);if(timeToken&&/下午|晚上/.test(timeToken[1]||'')&&hour<12)hour+=12;
  const start=pad(Math.min(23,hour))+':'+pad(Math.min(59,Number(timeToken?.[3]||0))),end=clock(Math.min(1440,minute(start)+60)),date=base.toISOString().slice(0,10);
  const event={id:`chat-${date}-${start}-${value.slice(0,12)}`,date,start,end,title:value.slice(0,80),status:'有约定',place:'',mood:'期待',availability:'busy',canReply:false,source:'chat'};
  store.update(s=>{ensureScheduleState(s);const plan=s.schedulePlans[personId]||{routine:templateFor(s.people.find(x=>x.id===personId),{}),fixed:[],temporary:[]};plan.temporary||=[];if(!plan.temporary.some(x=>x.id===event.id))plan.temporary.push(event);s.schedulePlans[personId]=plan;delete s.scheduleDays[`${personId}:${date}`]});return true
}

export async function enrichDailySchedule(store,personId){const day=ensureDailySchedule(store,personId);if(!day)return;const key=`${personId}:${day.date}`;if(day.modelAttempted||inflight.has(key))return inflight.get(key);const state=store.getState(),model=state.modelProfiles.find(x=>x.id===state.activeModelProfileId);if(!model?.apiKey||!model?.model)return;store.update(s=>{s.scheduleDays[key].modelAttempted=true});const promise=(async()=>{const person=state.people.find(x=>x.id===personId),world=state.chatGroups.find(x=>x.id===person?.groupId);const prompt=`只为 ${person.name} 的 ${day.date} 日程补充符合人物的小细节。人物：${JSON.stringify({age:person.age,occupation:person.occupation,personality:person.personality,persona:person.persona,city:person.city})}；世界观：${world?.description||world?.summary||''}；既定时间段：${JSON.stringify(day.blocks)}。不许改变时间、地点及用户固定/临时规则，不产生与工作或睡眠冲突的事件。按相同顺序返回严格 JSON：{"details":[{"title":"简短活动","status":"用户可见的简短状态","mood":"内在心情","place":"地点或空"}]}。仅描述，不增加或删减时间段。`;try{const raw=await sendToModel(model,[{role:'user',text:prompt}],'你只负责为确定性的日程填充人物化细节，不能做决定。'),data=JSON.parse(String(raw).match(/\{[\s\S]*\}/)?.[0]||'{}');if(!Array.isArray(data.details)||data.details.length!==day.blocks.length)return;store.update(s=>{const target=s.scheduleDays[key];if(!target||target.blocks.length!==data.details.length)return;target.blocks.forEach((block,i)=>{if(block.source!=='template')return;const detail=data.details[i];for(const field of ['title','status','mood','place'])if(typeof detail[field]==='string'&&detail[field].trim())block[field]=detail[field].trim().slice(0,65)})})}catch{}finally{inflight.delete(key)}})();inflight.set(key,promise);return promise}
