import {escapeHtml as esc,showToast} from './core/ui.js';
import {saveMediaBlob,getMediaUrl} from './media-store.js';
import {generateImage} from './image-client.js';
export function mediaList(items=[]){return items.filter(x=>x&&(x.mediaId||/^(https?:\/\/|data:image\/(?:png|jpeg|webp|gif);base64,)/i.test(x.url||''))).slice(0,4).map(x=>({mediaId:x.mediaId||'',url:x.url||'',sticker:!!x.sticker}));}
export async function generateSocialCover(store,channel,rows){
 const config=store.getState().mediaApis?.image;if(!config?.enabled||!config.channels?.[channel])return;
 const row=rows.find(p=>p.imagePrompt&&!p.media&&!p.images?.length);if(!row)return;
 try{const src=await generateImage(config,{prompt:row.imagePrompt});let media;if(/^https?:/.test(src))media={url:src};else{const saved=await saveMediaBlob(await(await fetch(src)).blob());media={mediaId:saved.mediaId};if(src.startsWith('blob:'))URL.revokeObjectURL(src)}store.update(()=>{if(row.deleted)return;if(channel==='tiktok'){row.media={...media,kind:'photo'};row.kind='photo'}else row.images=[media];row.imageGenerationStatus='ready'});}catch(error){store.update(()=>{row.imageGenerationStatus='failed';row.imageGenerationError=error.message});showToast('文字已生成，配图失败：'+error.message)}
}
export function socialImages(items=[]){return items.length?`<div class="social-images">${mediaList(items).map(m=>`<button type="button" class="${m.sticker?'is-sticker':''}" data-social-zoom><img ${m.mediaId?`data-social-media="${esc(m.mediaId)}"`:`src="${esc(m.url)}"`} alt="${m.sticker?'表情包':'配图'}" loading="lazy"></button>`).join('')}</div>`:'';}
export function hydrateSocial(root){root.querySelectorAll('[data-social-media]').forEach(async img=>{img.src=await getMediaUrl(img.dataset.socialMedia)});root.querySelectorAll('[data-social-zoom]').forEach(b=>b.onclick=e=>{e.stopPropagation();const src=b.querySelector('img').src;if(!src)return;const dialog=document.createElement('dialog');dialog.className='social-lightbox';dialog.innerHTML='<button aria-label="关闭大图">×</button><img alt="图片详情">';dialog.querySelector('img').src=src;dialog.onclick=()=>{dialog.close();dialog.remove()};document.body.append(dialog);dialog.showModal()});}
export function mountMediaComposer(form,store,channel,{max=4}={}){
  const items=[];let busy=false;const box=document.createElement('div');box.className='social-composer-tools';
  box.innerHTML=`<div class="social-attachments"></div><div class="social-tool-row"><button type="button" data-tool="emoji" aria-label="插入表情">☺</button><button type="button" data-tool="sticker">表情包</button><label>图片<input type="file" accept="image/*" multiple hidden></label><button type="button" data-tool="url">链接</button><button type="button" data-tool="generate">✧ 生图</button></div><div class="social-tool-panel" hidden></div><small class="social-media-status" aria-live="polite"></small>`;form.append(box);
  const panel=box.querySelector('.social-tool-panel'),status=box.querySelector('small'),input=form.querySelector('[name=text],[name=caption]');
  const draw=()=>{box.querySelector('.social-attachments').innerHTML=items.map((m,i)=>`<div>${socialImages([m])}<button type="button" data-remove="${i}" aria-label="移除图片">×</button></div>`).join('');hydrateSocial(box);box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{items.splice(+b.dataset.remove,1);draw()})};
  const add=m=>{if(items.length>=max)throw Error(`最多添加 ${max} 张图片`);items.push(m);draw()};
  const run=async fn=>{if(busy)return;busy=true;status.textContent='正在处理…';try{await fn();status.textContent='已添加，可直接发布'}catch(e){status.textContent=e.message;showToast(e.message)}finally{busy=false}};
  box.querySelector('input[type=file]').onchange=e=>void run(async()=>{for(const file of e.target.files){if(!file.type.startsWith('image/')||file.size>12*1024*1024)throw Error('请选择 12MB 以内的图片');if(items.length>=max)break;const m=await saveMediaBlob(file);add({mediaId:m.mediaId})}e.target.value=''});
  box.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{panel.hidden=false;const type=b.dataset.tool;
    if(type==='emoji'){panel.innerHTML=['❤️','😂','🥹','😭','🥰','😎','👍','✨','🐰','🫶','🤍','😮'].map(x=>`<button type="button">${x}</button>`).join('');panel.querySelectorAll('button').forEach(btn=>btn.onclick=()=>{if(input){input.setRangeText(btn.textContent,input.selectionStart??input.value.length,input.selectionEnd??input.value.length,'end');input.dispatchEvent(new Event('input'));input.focus()}});return;}
    if(type==='sticker'){const libs=store.getState().stickerLibraries||{},list=[...(libs.global||[]),...(libs.user||[])].filter(x=>x.mediaId||/^(https?:\/\/|data:image\/(?:png|jpeg|webp|gif);base64,)/i.test(x.url||x.src||''));panel.innerHTML=list.length?list.map((m,i)=>`<button type="button" data-sticker="${i}">${m.mediaId?`<img data-social-media="${esc(m.mediaId)}" alt="表情包">`:`<img src="${esc(m.url||m.src)}" alt="表情包">`}</button>`).join(''):'<p>还没有表情包。用“图片”上传后即可发送，也可在聊天中收藏表情包。</p>';hydrateSocial(panel);panel.querySelectorAll('[data-sticker]').forEach(btn=>btn.onclick=()=>{try{const m=list[+btn.dataset.sticker];add({...m,url:m.url||m.src,sticker:true})}catch(e){showToast(e.message)}});return;}
    panel.innerHTML=`<input type="${type==='url'?'url':'text'}" placeholder="${type==='url'?'https://… 图片直链':'描述想要的画面'}"><button type="button">${type==='url'?'添加':'生成图片'}</button>`;
    panel.querySelector('button').onclick=()=>void run(async()=>{const value=panel.querySelector('input').value.trim();if(!value)throw Error('请先填写内容');if(type==='url'){if(!/^https?:\/\//i.test(value))throw Error('需要 HTTP(S) 图片直链');add({url:value})}else{const config=store.getState().mediaApis?.image;if(!config?.channels?.[channel])throw Error('请在本应用设置中开启生图');const src=await generateImage(config,{prompt:value});if(/^https?:/.test(src))add({url:src});else{const response=await fetch(src),m=await saveMediaBlob(await response.blob());add({mediaId:m.mediaId});if(src.startsWith('blob:'))URL.revokeObjectURL(src)}}panel.hidden=true});
  });
  return {get:()=>mediaList(items),busy:()=>busy};
}
export function mountImageSetting(root,store,channel){if(!root||root.querySelector(`[data-image-channel="${channel}"]`))return;const c=store.getState().mediaApis.image,section=document.createElement('section');section.className='social-image-setting';section.innerHTML=`<label><span>本平台图片生成</span><input data-image-channel="${channel}" type="checkbox" ${c.channels?.[channel]?'checked':''}></label><p>独立控制本平台的“✧ 生图”。使用小兔设置中的生图 API；关闭后仍可上传图片。</p>`;root.append(section);section.querySelector('input').onchange=e=>{store.update(s=>{s.mediaApis.image.channels||={};s.mediaApis.image.channels[channel]=e.target.checked});if(e.target.checked&&!c.enabled)showToast('本平台已开启，还需在模型与 API 中配置并开启全局生图')};}
