import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';

let uuid=0;
const context=vm.createContext({Date,JSON,Math,Set,Map,setTimeout:callback=>callback(),crypto:{randomUUID:()=>`id-${++uuid}`}});
const synthetic=(values)=>new vm.SyntheticModule(Object.keys(values),function(){for(const [key,value] of Object.entries(values))this.setExport(key,value)},{context});
const schedule=synthetic({currentSchedule:()=>({canReply:true})});
const accounts=synthetic({accountFriends:(state,id)=>state.accountFriends[id]||[],accountContext:(_state,id,accountId)=>({memoryOwnerId:`world::${id}::${accountId}`})});
const ai=synthetic({sendToModel:async()=>JSON.stringify({messages:[{speakerId:'char',text:'刚才你说的唱片，我还记着。'},{speakerId:'npc',text:'我也想听那张。'}]})});
const memory=synthetic({addMemoryEntry:async()=>({})});
const world=new vm.SourceTextModule(readFileSync(new URL('./world-engine.js',import.meta.url),'utf8'),{context});
await world.link(()=>schedule);await world.evaluate();
const group=new vm.SourceTextModule(readFileSync(new URL('./group-model.js',import.meta.url),'utf8'),{context});
await group.link(spec=>spec.includes('ai-client')?ai:spec.includes('account-system')?accounts:spec.includes('memory-engine')?memory:spec.includes('schedule-engine')?schedule:world);await group.evaluate();

const state={currentWorldId:'world',currentUserId:'user',worlds:[{id:'world'}],people:[{id:'user',type:'user',name:'我'},{id:'char',type:'char',name:'阿岚',groupId:'same'},{id:'npc',type:'npc',name:'小鱼',groupId:'same'},{id:'outsider',type:'npc',name:'外人',groupId:'other'}],chatGroups:[{id:'same',worldId:'world',personIds:['char','npc']},{id:'other',worldId:'other',personIds:['outsider']}],accountFriends:{user:['char']},conversations:[{id:'private-char',personId:'char',userAccountId:'user'},{id:'private-npc',personId:'npc',userAccountId:'user'}],messages:{'private-char':[],'private-npc':[]},modelProfiles:[{id:'model',apiKey:'test',model:'mock'}],activeModelProfileId:'model'};
const store={getState:()=>state,update(fn){fn(state)}};
assert.throws(()=>group.namespace.createGroupThread(store,{name:'错误',memberIds:['char','outsider']}),/同一个世界/);
const thread=group.namespace.createGroupThread(store,{name:'唱片群',memberIds:['char','npc']});
assert.equal(thread.memberIds.length,3);
assert.equal(group.namespace.postGroupMessage(store,thread.id,{speakerId:'outsider',text:'偷看'}),null);
const userMessage=group.namespace.postGroupMessage(store,thread.id,{speakerId:'user',text:'这张唱片有人听过吗？'});
assert.equal(state.worldLog.filter(row=>row.id===`group-message:${userMessage.id}`).length,1);
const packet=group.namespace.postGroupMessage(store,thread.id,{speakerId:'user',text:'周末见',type:'redpacket',amount:6,messageId:'wallet-packet-1'});
assert.equal(packet.id,'wallet-packet-1');
group.namespace.postGroupMessage(store,thread.id,{speakerId:'user',text:'周末见',type:'redpacket',amount:6,messageId:'wallet-packet-1'});
assert.equal(state.groupMessages[thread.id].filter(row=>row.id==='wallet-packet-1').length,1,'wallet receipt and group message share an idempotent ID');
const replies=await group.namespace.generateGroupReplies(store,thread.id);
assert.equal(replies.length,2);
assert(state.groupMessages[thread.id].every(row=>thread.memberIds.includes(row.speakerId)));
assert.equal(state.deliveryJobs.length,1);
assert.equal(state.deliveryJobs[0].senderId,'char','unfriended NPC cannot start private follow-up');
assert.equal(world.namespace.knownWorldEvents(state,'outsider','world').length,0,'outsider cannot read group facts');
const key=world.namespace.relationKey('world','user','char'),before=state.relationEdges[key].affinity;
world.namespace.changeRelationship(store,{a:'user',b:'char',worldId:'world',deltaAffinity:99,reasonEventId:'manual-1'});
assert.equal(state.relationEdges[key].affinity,Math.min(100,before+4));
world.namespace.changeRelationship(store,{a:'user',b:'char',worldId:'world',deltaAffinity:99,reasonEventId:'manual-1'});
assert.equal(state.relationEdges[key].affinity,Math.min(100,before+4),'duplicate reason does not double-apply');
world.namespace.tickWorld(store,Date.now());const count=state.worldLog.length;world.namespace.tickWorld(store,Date.now());assert.equal(state.worldLog.length,count,'offline tick is idempotent');
console.log('World and group: membership, account friend gate, witnessed facts, relationship bounds, tick deduplication passed.');
