import { escapeHtml as esc, openSheet, closeSheet, showToast } from './core/ui.js';
import { ensureX, xVisible, xPost, xToggle, xReputation } from './x-model.js';
import { switchAccount, friendWorldGroup } from './account-system.js';
import { saveMediaBlob, getMediaUrl } from './media-store.js';
const glyph={home:'M3 11 12 3l9 8v10h-6v-7H9v7H3Z',search:'M21 21l-6-6M17 10A7 7 0 1 1 3 10a7 7 0 0 1 14 0',bell:'M5 17h14l-2-4V9a5 5 0 0 0-10 0v4ZM10 21h4',mail:'M3 5h18v14H3ZM3 6l9 7 9-7',user:'M4 21c0-8 16-8 16 0M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',reply:'M3 4h18v13H9l-5 4v-4H3Z',repost:'m4 8 3-3 3 3M7 5v12h8m5-1-3 3-3-3m3 3V7h-5',like:'M12 21 3 12C-2 5 7 0 12 6c5-6 14-1 9 6Z',save:'M6 3h12v19l-6-5-6 5Z',share:'M12 16V2m-4 4 4-4 4 4M4 12v9h16v-9',sun:'M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0',plus:'M12 3v18M3 12h18',back:'m14 4-8 8 8 8',image:'M3 4h18v16H3ZM3 16l6-6 5 5 3-3 4 4',chart:'M4 21V11m5 10V5m6 16v-8m5 8V2'};
const icon=k=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${glyph[k]||glyph.home}"/></svg>`;
const date=t=>new Date(t).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
const safeUrl=s=>/^(https?:\/\/|blob:|data:image\/)/i.test(s||'')?s:'';
export function createXRenderer({store,navigate}){
 let page='home',detailId='',profileId='',peerId='',query='',tab='for-you',history=[],containerRef=null;
 const state=()=>store.getState(),x=()=>ensureX(state()),me=()=>state().activeUserAccountId,profile=id=>x().profiles[id]||{name:'已删除的账号',handle:'unknown'};
 const avatar=id=>{const p=profile(id);return `<span class="x-avatar">${safeUrl(p.avatar)?`<img src="${esc(p.avatar)}" alt="">`:esc(p.name.slice(0,1))}</span>`};
 const visible=()=>x().posts.filter(p=>xVisible(state(),p));
 function go(next,extra={}){history.push({page,detailId,profileId,peerId,query});page=next;if(extra.id)detailId=extra.id;if(extra.person)profileId=extra.person;if(extra.peer)peerId=extra.peer;render(containerRef)}
 function back(){if(page==='dm'){page='inbox';render(containerRef)}else if(page==='detail'){page='home';render(containerRef)}else if(page==='profile'&&profileId&&profileId!==me()){page='explore';render(containerRef)}else navigate('desktop')}
 function render(container){containerRef=container;ensureX(state());const user=me(),data=x();container.className='app-view x-app';container.dataset.xTheme=data.theme;document.querySelector('#back-button').onclick=back;document.querySelector('#header-title').textContent='X';
 container.innerHTML=`<header class="x-header"><button data-x-account aria-label="切换账号">${avatar(user)}</button><button class="x-wordmark" data-x-nav="home" aria-label="首页">𝕏</button><button data-x-theme aria-label="切换日间夜间">${icon('sun')}</button></header><div class="x-context"><select data-x-world aria-label="世界观">${(state().chatGroups||[{id:'group-default',name:'默认世界观'}]).map(g=>`<option value="${g.id}" ${data.groupId===g.id?'selected':''}>${esc(g.name)}</option>`).join('')}</select><button data-x-nav="saved">书签</button></div><main class="x-scroll">${page==='home'?home():page==='explore'?explore():page==='detail'?detail():page==='profile'?profilePage(profileId||user):page==='inbox'?inbox():page==='dm'?dm():page==='notifications'?notifications():saved()}</main>${['home','profile','explore','saved'].includes(page)?`<button class="x-compose-fab" data-x-compose aria-label="发布贴文">${icon('plus')}</button>`:''}<nav class="x-nav">${[['home','home','首页'],['explore','search','搜索'],['notifications','bell','通知'],['inbox','mail','私信'],['profile','user','我']].map(([p,i,label])=>`<button data-x-nav="${p}" class="${page===p?'active':''}" aria-label="${label}">${icon(i)}</button>`).join('')}</nav>`;
 bind(container);hydrate(container);
 }
 function empty(text){return `<div class="x-empty"><b>𝕏</b><p>${esc(text)}</p><button class="x-pill" data-x-compose>写第一条贴文</button></div>`}
 function home(){const posts=visible().filter(p=>!p.parentId&&(tab!=='following'||(x().follows[me()]||[]).includes(p.authorId)||p.authorId===me())).sort((a,b)=>b.createdAt-a.createdAt);return `<div class="x-tabs"><button data-x-tab="for-you" class="${tab==='for-you'?'active':''}">为你推荐</button><button data-x-tab="following" class="${tab==='following'?'active':''}">正在关注</button></div>${posts.map(p=>post(p)).join('')||empty('还没有贴文。写下今天，或去搜索页发现角色。')}`}
 function post(p,full=false){const a=profile(p.authorId),quote=p.quoteId?visible().find(q=>q.id===p.quoteId):null;return `<article class="x-post ${full?'x-post-full':''}" data-post="${p.id}"><header><button data-x-profile="${p.authorId}">${avatar(p.authorId)}</button><div><button class="x-name" data-x-profile="${p.authorId}">${esc(a.name)}${a.celebrity?'<span class="x-badge">✓</span>':''}</button><span>@${esc(a.handle)}${full?'':' · '+date(p.createdAt)}</span></div><button class="x-more" data-x-more="${p.id}" aria-label="贴文菜单">•••</button></header><div class="x-post-body" data-x-detail="${p.id}"><p>${esc(p.text)}</p>${p.images?.length?`<div class="x-images count-${p.images.length}">${p.images.map((m,i)=>`<button data-x-image="${p.id}:${i}">${m.mediaId?`<img data-x-media="${m.mediaId}" alt="贴文图片">`:`<img src="${esc(safeUrl(m.url))}" alt="贴文图片">`}</button>`).join('')}</div>`:''}${quote?`<button class="x-quote" data-x-detail="${quote.id}"><b>${esc(profile(quote.authorId).name)}</b><p>${esc(quote.text)}</p></button>`:p.quoteId?'<small>引用内容不可见或已删除</small>':''}</div>${full?`<div class="x-post-meta">${date(p.createdAt)} · <b>${p.views?.length||0}</b> 次查看</div>`:''}<footer>${[['reply','reply',visible().filter(q=>q.parentId===p.id).length],['repost','reposts',p.reposts.length],['like','likes',p.likes.length],['save','bookmarks',p.bookmarks.includes(me())?1:0],['share','share','']].map(([i,action,count])=>`<button data-x-action="${action}" data-id="${p.id}" class="${Array.isArray(p[action])&&p[action].includes(me())?'selected':''}" aria-label="${{reply:'评论',reposts:'转发',likes:'点赞',bookmarks:'收藏',share:'分享'}[action]}">${icon(i)}<span>${count||''}</span></button>`).join('')}</footer></article>`}
 function detail(){const p=visible().find(p=>p.id===detailId);if(!p)return empty('这条贴文已删除或不在当前可见范围。');if(!p.views.includes(me()))store.update(s=>s.xSocial.posts.find(q=>q.id===p.id).views.push(me()));return `<div class="x-title"><button data-x-back aria-label="返回">${icon('back')}</button><h2>贴文</h2></div>${post(p,true)}<div class="x-reply-title"><span>回复</span><button data-x-compose-reply="${p.id}">写回复</button></div><div class="x-thread">${visible().filter(q=>q.parentId===p.id).map(q=>post(q)).join('')}</div>`}
 function explore(){const counts=new Map();for(const p of visible())for(const tag of p.text.match(/#[\p{L}\p{N}_]+/gu)||[])counts.set(tag,(counts.get(tag)||0)+1);const found=visible().filter(p=>p.text.toLowerCase().includes(query.toLowerCase()));const people=state().people.filter(p=>p.type==='user'||friendWorldGroup(state(),p.id)===x().groupId).filter(p=>`${profile(p.id).name} ${profile(p.id).handle}`.toLowerCase().includes(query.toLowerCase()));return `<form class="x-search"><label>${icon('search')}<input name="q" aria-label="搜索 X" placeholder="搜索人物、贴文和话题" value="${esc(query)}"></label></form>${query?`<h3 class="x-section-title">人物</h3>${people.map(p=>personRow(p.id)).join('')}<h3 class="x-section-title">贴文</h3>${found.map(p=>post(p)).join('')}`:`<h2 class="x-section-title">正在发生</h2>${[...counts].sort((a,b)=>b[1]-a[1]).slice(0,15).map(([tag,n],i)=>`<button class="x-trend" data-x-trend="${esc(tag)}"><small>${i+1} · 当前世界观趋势</small><strong>${esc(tag)}</strong><small>${n} 条贴文</small></button>`).join('')||'<p class="x-note">发布带 #话题 的贴文后，这里会按实际数量形成热搜。</p>'}<h3 class="x-section-title">发现角色</h3>${people.map(p=>personRow(p.id)).join('')}`}`}
 function personRow(id){return `<div class="x-person-row"><button data-x-profile="${id}">${avatar(id)}<span><b>${esc(profile(id).name)}</b><small>@${esc(profile(id).handle)}</small></span></button>${id!==me()?`<button class="x-pill" data-x-follow="${id}">${(x().follows[me()]||[]).includes(id)?'正在关注':'关注'}</button>`:''}</div>`}
 function profilePage(id){const p=profile(id),stats=xReputation(state(),id),followers=Object.values(x().follows).filter(ids=>ids.includes(id)).length;return `<div class="x-profile-cover" style="${safeUrl(p.banner)?`background-image:url('${esc(p.banner)}')`:''}"></div><section class="x-profile-info"><div class="x-profile-top">${avatar(id)}${id===me()?'<button class="x-pill outline" data-x-edit-profile>编辑个人资料</button>':`<button class="x-pill" data-x-follow="${id}">${(x().follows[me()]||[]).includes(id)?'正在关注':'关注'}</button><button class="x-icon" data-x-dm="${id}" aria-label="发私信">${icon('mail')}</button>`}</div><h2>${esc(p.name)}${p.celebrity?' <span class="x-badge">✓</span>':''}</h2><small>@${esc(p.handle)}</small><p>${esc(p.bio)}</p><div class="x-profile-stats"><span><b>${(x().follows[id]||[]).length}</b> 正在关注</span><span><b>${followers}</b> 关注者</span></div>${p.celebrity?`<div class="x-reputation">本地声量 · ${stats.reach} 位读者 / ${stats.likes} 赞 / ${stats.reposts} 转发</div>`:''}</section><div class="x-tabs"><button class="active">贴文</button></div>${visible().filter(q=>(q.authorId===id&&!q.parentId)||q.reposts.includes(id)).sort((a,b)=>b.createdAt-a.createdAt).map(q=>(q.authorId!==id?'<div class="x-repost-label">↻ 转发</div>':'')+post(q)).join('')}`}
 function inbox(){const ids=[...new Set(x().dm.filter(m=>m.from===me()||m.to===me()).map(m=>m.from===me()?m.to:m.from))];return `<div class="x-title"><h2>私信</h2><button class="x-pill" data-x-new-dm>新私信</button></div>${ids.map(id=>`<button class="x-dm-row" data-x-dm="${id}">${avatar(id)}<span><b>${esc(profile(id).name)}</b><p>${esc(x().dm.filter(m=>(m.from===id&&m.to===me())||(m.to===id&&m.from===me())).at(-1)?.text||'')}</p></span></button>`).join('')||'<p class="x-note">私信按账号独立保存。</p>'}`}
 function dm(){return `<div class="x-title"><button data-x-back aria-label="返回">${icon('back')}</button><h2>${esc(profile(peerId).name)}</h2></div><div class="x-dm-stream">${x().dm.filter(m=>(m.from===me()&&m.to===peerId)||(m.from===peerId&&m.to===me())).map(m=>`<div class="x-dm-message ${m.from===me()?'mine':''}"><p>${esc(m.text)}</p><small>${date(m.createdAt)}</small></div>`).join('')}</div><form class="x-dm-form"><input name="text" aria-label="私信内容" placeholder="开始一条私信" maxlength="4000" required><button class="x-pill">发送</button></form>`}
 function notifications(){return `<h2 class="x-section-title">通知</h2>${x().events.filter(e=>e.authorId===me()&&e.actorId!==me()&&e.groupId===x().groupId&&visible().some(p=>p.id===e.postId)).reverse().map(e=>`<button class="x-notice" data-x-detail="${e.postId}">${avatar(e.actorId)}<span>${esc(profile(e.actorId).name)} ${esc(({likes:'赞了你的贴文',reposts:'转发了你的贴文',reply:'回复了你'})[e.kind]||'与你互动')}</span></button>`).join('')||'<p class="x-note">有新的互动时会出现在这里。</p>'}`}
 function saved(){return `<h2 class="x-section-title">书签</h2>${visible().filter(p=>p.bookmarks.includes(me())).map(p=>post(p)).join('')||'<p class="x-note">收藏只对当前账号可见。</p>'}`}
 async function hydrate(root){for(const img of root.querySelectorAll('[data-x-media]')){const url=await getMediaUrl(img.dataset.xMedia);if(img.isConnected&&url)img.src=url}}
 function bind(c){c.querySelector('[data-x-theme]').onclick=()=>{store.update(s=>s.xSocial.theme=x().theme==='dark'?'light':'dark');render(c)};c.querySelector('[data-x-world]').onchange=e=>{store.update(s=>s.xSocial.groupId=e.target.value);page='home';history=[];render(c)};c.querySelector('[data-x-account]').onclick=accountPicker;
 c.querySelectorAll('[data-x-nav]').forEach(b=>b.onclick=()=>{profileId=me();go(b.dataset.xNav)});c.querySelectorAll('[data-x-back]').forEach(b=>b.onclick=back);c.querySelectorAll('[data-x-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.xTab;render(c)});c.querySelectorAll('[data-x-profile]').forEach(b=>b.onclick=()=>go('profile',{person:b.dataset.xProfile}));c.querySelectorAll('[data-x-detail]').forEach(b=>b.onclick=e=>{if(e.target.closest('[data-x-image]'))return;e.stopPropagation();go('detail',{id:b.dataset.xDetail})});c.querySelectorAll('[data-x-compose]').forEach(b=>b.onclick=()=>compose());c.querySelectorAll('[data-x-compose-reply]').forEach(b=>b.onclick=()=>compose({parentId:b.dataset.xComposeReply}));
 c.querySelectorAll('[data-x-action]').forEach(b=>b.onclick=()=>{const action=b.dataset.xAction,id=b.dataset.id;if(action==='reply')return compose({parentId:id});if(action==='reposts')return openSheet(`<div class="x-sheet-actions"><button class="button" data-retweet>转发 / 取消转发</button><button class="button secondary" data-quote>引用转发</button><button class="button ghost" data-sheet-close>取消</button></div>`,{onReady(sheet){sheet.querySelector('[data-retweet]').onclick=()=>{store.update(s=>xToggle(s,id,'reposts',me()));closeSheet();render(c)};sheet.querySelector('[data-quote]').onclick=()=>{closeSheet();compose({quoteId:id})}}});if(action==='share'){const p=visible().find(p=>p.id===id);return openSheet(`<h3>分享内容</h3><textarea readonly rows="6">${esc(profile(p.authorId).name+'：'+p.text)}</textarea><p class="x-note">这是本机虚拟贴文，可复制内容分享。</p><button class="button" data-sheet-close>完成</button>`)}store.update(s=>xToggle(s,id,action,me()));render(c)});
 c.querySelectorAll('[data-x-follow]').forEach(b=>b.onclick=()=>{const id=b.dataset.xFollow;store.update(s=>{const a=(s.xSocial.follows[me()]||=[]),i=a.indexOf(id);if(i>=0)a.splice(i,1);else a.push(id)});render(c)});
 c.querySelectorAll('[data-x-dm]').forEach(b=>b.onclick=()=>go('dm',{peer:b.dataset.xDm}));c.querySelector('[data-x-new-dm]')?.addEventListener('click',()=>openSheet(`<h3>新私信</h3>${state().people.filter(p=>p.id!==me()&&(p.type==='user'||friendWorldGroup(state(),p.id)===x().groupId)).map(p=>`<button class="button secondary" data-peer="${p.id}">${esc(profile(p.id).name)}</button>`).join('')}`,{onReady(sheet){sheet.querySelectorAll('[data-peer]').forEach(b=>b.onclick=()=>{closeSheet();go('dm',{peer:b.dataset.peer})})}}));
 c.querySelector('.x-dm-form')?.addEventListener('submit',e=>{e.preventDefault();const text=e.target.elements.text.value.trim();if(!text)return;store.update(s=>s.xSocial.dm.push({id:crypto.randomUUID(),from:me(),to:peerId,text,createdAt:Date.now()}));render(c)});
 c.querySelector('.x-search')?.addEventListener('submit',e=>{e.preventDefault();query=e.target.elements.q.value.trim();render(c)});c.querySelectorAll('[data-x-trend]').forEach(b=>b.onclick=()=>{query=b.dataset.xTrend;render(c)});c.querySelector('[data-x-edit-profile]')?.addEventListener('click',editProfile);
 c.querySelectorAll('[data-x-more]').forEach(b=>b.onclick=()=>{const p=visible().find(p=>p.id===b.dataset.xMore);openSheet(`<div class="x-sheet-actions">${p.authorId===me()?'<button class="button" data-delete-post>删除贴文</button>':'<button class="button" data-mute-author>不看此账号</button>'}<button class="button secondary" data-sheet-close>取消</button></div>`,{onReady(sheet){sheet.querySelector('[data-delete-post]')?.addEventListener('click',()=>{store.update(s=>s.xSocial.posts.find(q=>q.id===p.id).deleted=true);closeSheet();render(c)});sheet.querySelector('[data-mute-author]')?.addEventListener('click',()=>{store.update(s=>(s.xSocial.muted[me()]||=[]).push(p.authorId));closeSheet();render(c)})}})});
 c.querySelectorAll('[data-x-image]').forEach(b=>b.onclick=async e=>{e.stopPropagation();const [id,i]=b.dataset.xImage.split(':'),m=visible().find(p=>p.id===id)?.images[i];if(!m)return;const url=m.mediaId?await getMediaUrl(m.mediaId):m.url;openSheet(`<img class="x-full-image" src="${esc(safeUrl(url))}" alt="贴文图片"><button class="button" data-sheet-close>关闭</button>`)});
 }
 function accountPicker(){openSheet(`<h3>选择发帖账号</h3>${state().people.filter(p=>p.type==='user').map(p=>`<button class="button secondary" data-account="${p.id}">${esc(profile(p.id).name)} ${p.id===me()?'✓':''}</button>`).join('')}<p class="x-note">大小号分别拥有关注、书签、私信和资料。角色仅在明确披露后知道关联。</p>`,{onReady(sheet){sheet.querySelectorAll('[data-account]').forEach(b=>b.onclick=()=>{store.update(s=>switchAccount(s,b.dataset.account));history=[];page='home';closeSheet();render(containerRef)})}})}
 function compose({parentId='',quoteId=''}={}){const account=me(),draftKey=`${account}:${parentId}:${quoteId}`;let media=[];openSheet(`<form class="x-compose"><div class="sheet-title"><button type="button" class="button ghost" data-sheet-close>取消</button><button class="x-pill" data-publish>发布</button></div><h3>${parentId?'回复':quoteId?'引用转发':'有什么新鲜事？'}</h3><textarea name="text" rows="6" maxlength="4000" placeholder="说点什么…">${esc(x().drafts[draftKey]||'')}</textarea><select name="audience" aria-label="谁可以看"><option value="public">当前世界观公开</option><option value="followers">仅关注者</option></select><div class="x-attachments" data-attachments></div><div class="sheet-split-actions"><label class="x-icon">${icon('image')}<input type="file" accept="image/*" multiple hidden data-x-files></label><button type="button" class="button secondary" data-image-url>图床图片</button><small data-count>0 / 4000</small></div></form>`,{onReady(sheet){const form=sheet.querySelector('form'),text=form.elements.text;let busy=false;const redraw=()=>{sheet.querySelector('[data-attachments]').innerHTML=media.map((m,i)=>`<button type="button" data-remove-image="${i}">图片 ${i+1} ×</button>`).join('');sheet.querySelectorAll('[data-remove-image]').forEach(b=>b.onclick=()=>{media.splice(Number(b.dataset.removeImage),1);redraw()})};text.oninput=()=>{sheet.querySelector('[data-count]').textContent=text.value.length+' / 4000';store.update(s=>s.xSocial.drafts[draftKey]=text.value)};sheet.querySelector('[data-x-files]').onchange=async e=>{busy=true;form.querySelector('[data-publish]').disabled=true;try{for(const file of [...e.target.files].slice(0,4-media.length)){if(file.size>12*1024*1024)throw Error('请选择 12MB 以内的图片');const m=await saveMediaBlob(file);media.push({mediaId:m.mediaId})}redraw()}catch(error){showToast(error.message)}finally{busy=false;form.querySelector('[data-publish]').disabled=false}};sheet.querySelector('[data-image-url]').onclick=()=>{const line=document.createElement('input');line.type='url';line.placeholder='https://… 图片直链';line.className='x-image-url';form.querySelector('[data-attachments]').appendChild(line);line.onchange=()=>{if(/^https?:\/\//i.test(line.value)&&media.length<4){media.push({url:line.value.trim()});redraw()}};line.focus()};form.onsubmit=e=>{e.preventDefault();if(busy)return;try{let p;store.update(s=>{p=xPost(s,{authorId:account,text:text.value,images:media,parentId,quoteId,audience:form.elements.audience.value});delete s.xSocial.drafts[draftKey]});closeSheet();go('detail',{id:parentId||p.id})}catch(error){showToast(error.message)}}}})}
 function editProfile(){const p=profile(me());openSheet(`<form class="x-profile-form"><h3>编辑个人资料</h3>${[['name','名字'],['handle','用户名'],['bio','简介'],['avatar','头像 URL'],['banner','背景图 URL']].map(([k,label])=>`<label class="field"><span>${label}</span><input name="${k}" value="${esc(p[k]||'')}" maxlength="${k==='bio'?300:2000}"></label>`).join('')}<label class="setting-row">名人身份（角色设定）<input name="celebrity" type="checkbox" ${p.celebrity?'checked':''}></label><div class="sheet-split-actions"><button class="button secondary" type="button" data-sheet-close>取消</button><button class="button">保存</button></div></form>`,{onReady(sheet){sheet.querySelector('form').onsubmit=e=>{e.preventDefault();const f=e.target;store.update(s=>Object.assign(s.xSocial.profiles[me()],{name:f.elements.name.value.trim()||p.name,handle:f.elements.handle.value.replace(/[^a-zA-Z0-9_]/g,'').slice(0,30)||p.handle,bio:f.elements.bio.value,avatar:safeUrl(f.elements.avatar.value),banner:safeUrl(f.elements.banner.value),celebrity:f.elements.celebrity.checked}));closeSheet();render(containerRef)}}})}
 return render;
}
