import { ensureAccountState, friendWorldGroup } from './account-system.js';
export function ensureX(s){ensureAccountState(s);s.xSocial||={version:1,theme:'dark',posts:[],profiles:{},follows:{},dm:[],events:[],drafts:{},muted:{},groupId:''};const x=s.xSocial;x.groupId||=friendWorldGroup(s,s.people.find(p=>p.type==='char')?.id);for(const p of s.people){x.profiles[p.id]||={id:p.id,name:p.chatName||p.name,handle:(p.id.replace(/[^a-zA-Z0-9_]/g,'_')),bio:p.signature||'',avatar:p.avatarUrl||s.chatProfiles?.[p.id]?.avatarUrl||'',banner:'',celebrity:false}}return x}
export function xVisible(s,post,viewer=s.activeUserAccountId){const x=ensureX(s),person=s.people.find(p=>p.id===viewer);return !!person&&!post.deleted&&post.groupId===x.groupId&&(person.type==='user'||friendWorldGroup(s,viewer)===post.groupId)&&!(x.muted[viewer]||[]).includes(post.authorId)&&(post.audience!=='followers'||post.authorId===viewer||(x.follows[viewer]||[]).includes(post.authorId))}
export function xEvent(s,kind,post,actor){const x=ensureX(s);x.events.push({id:crypto.randomUUID(),kind,postId:post.id,actorId:actor,authorId:kind==='reply'?(x.posts.find(p=>p.id===post.parentId)?.authorId||post.authorId):post.authorId,groupId:post.groupId,createdAt:Date.now(),visibility:post.audience||'public'});x.events=x.events.slice(-1000)}
export function xPost(s,{authorId,text,images=[],parentId='',quoteId='',audience='public'}){const x=ensureX(s);if(!s.people.some(p=>p.id===authorId))throw Error('账号不存在');if(s.people.find(p=>p.id===authorId)?.type!=='user'&&friendWorldGroup(s,authorId)!==x.groupId)throw Error('不能跨世界观发帖');if(quoteId&&!x.posts.some(p=>p.id===quoteId&&xVisible(s,p,authorId)))throw Error('引用内容不可见');if(!text.trim()&&!images.length)throw Error('写点内容或添加图片');const parent=parentId?x.posts.find(p=>p.id===parentId&&xVisible(s,p,authorId)):null;if(parentId&&!parent)throw Error('无法回复这条贴文');const p={id:crypto.randomUUID(),authorId,text:text.trim().slice(0,4000),images:images.slice(0,4),parentId,quoteId,audience:parent?.audience||audience,groupId:parent?.groupId||x.groupId,createdAt:Date.now(),likes:[],reposts:[],bookmarks:[],views:[]};x.posts.push(p);xEvent(s,parentId?'reply':'post',p,authorId);return p}
export function xToggle(s,id,key,actor){const p=ensureX(s).posts.find(p=>p.id===id);if(!p||!xVisible(s,p,actor)||!['likes','reposts','bookmarks'].includes(key))return;p[key]||=[];const i=p[key].indexOf(actor);if(i>=0)p[key].splice(i,1);else p[key].push(actor);if(key!=='bookmarks')xEvent(s,key,p,actor)}
// Only public facts and explicitly disclosed identities are passed across the future AI boundary.
export function buildXRoleContext(s,actorId,accountId=s.activeUserAccountId){const x=ensureX(s),actor=s.people.find(p=>p.id===actorId),relation=s.accountRelations?.[accountId],known=relation?.type==='alt'&&!!relation.disclosedTo?.[actorId];return{actor:{id:actorId,name:actor?.name,persona:actor?.personality||actor?.persona,occupation:actor?.occupation},viewerAccount:{id:accountId,name:x.profiles[accountId]?.name,...(known?{knownMainAccount:relation.relatedTo}:{})},visiblePosts:x.posts.filter(p=>xVisible(s,p,actorId)).slice(-30).map(p=>({id:p.id,authorId:p.authorId,text:p.text,parentId:p.parentId})),rules:['严格扮演当前角色，发帖不是私聊，不公开私密记忆。','仅能回应 visiblePosts 内的帖子；不得跨世界观互动。','账号未明确披露时，不推断现实身份或关联主账号。','不要把网友猜测写成事实；回复短、自然、符合年龄与职业。','输出 JSON：{"actions":[{"type":"post|reply|like|repost","postId":"可见贴文ID","text":"公开内容"}]}。']}}
export function xReputation(s,id){const posts=ensureX(s).posts.filter(p=>p.authorId===id&&!p.deleted&&p.groupId===s.xSocial.groupId),readers=new Set(posts.flatMap(p=>p.views||[]));return{posts:posts.filter(p=>!p.parentId).length,likes:posts.reduce((n,p)=>n+(p.likes?.length||0),0),reposts:posts.reduce((n,p)=>n+(p.reposts?.length||0),0),reach:readers.size}}
