import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { webcrypto } from 'node:crypto';
import vm from 'node:vm';
const path=file=>existsSync(file)?file:new URL('../bunny-bunny-netlify/js/'+(file==='desktop-drag.js'?'apps/':'')+file,import.meta.url);
const context=vm.createContext({crypto:webcrypto,Date,Set,Math});
async function module(file,link){const m=new vm.SourceTextModule(readFileSync(path(file),'utf8'),{context});await m.link(link||(()=>{}));await m.evaluate();return m}
const drag=(await module('desktop-drag.js')).namespace;
const s={desktopLayout:['a','b','c'],desktopDock:['d','e','f','g'],desktopFolders:[],desktopPlacements:{a:{page:0,row:0,col:0},b:{page:0,row:0,col:1},c:{page:0,row:1,col:0}}};
drag.placeDesktopItem(s,{token:'a',page:1,row:3,col:2});
assert.equal(s.desktopPlacements.a.page,1);assert.equal(s.desktopPlacements.b.col,1);
drag.placeDesktopItem(s,{token:'a',page:0,row:0,col:1});
assert.equal(s.desktopPlacements.b.page,1,'occupied drop swaps to origin');
drag.placeDesktopItem(s,{token:'a',page:0,row:0,col:1,dockIndex:2});
assert.deepEqual(s.desktopDock,['d','e','a','g']);assert(s.desktopLayout.includes('f'));assert(!s.desktopLayout.includes('a'));
drag.placeDesktopItem(s,{token:'a',page:2,row:2,col:2});
assert(!s.desktopDock.includes('a'));assert.equal(s.desktopPlacements.a.page,2);
drag.placeDesktopItem(s,{token:'a',page:0,row:1,col:0,folderTarget:'c'});
assert.equal(s.desktopFolders[0].items.join(','),'c,a');assert(!s.desktopLayout.includes('a'));
const accounts=await module('account-system.js');const x=(await module('x-model.js',()=>accounts)).namespace;
const state={people:[{id:'u',type:'user',name:'主号'},{id:'alt',type:'user',name:'小号'},{id:'a',type:'char',name:'A',groupId:'one'},{id:'b',type:'npc',name:'B',groupId:'two'}],chatGroups:[{id:'one'},{id:'two'}],conversations:[]};
x.ensureX(state);state.xSocial.groupId='one';state.accountRelations.alt={type:'alt',relatedTo:'u',disclosedTo:{}};
const anonymous=accounts.namespace.accountContext(state,'a','alt');
assert.equal(anonymous.memoryOwnerId,'a::alt');
assert(!anonymous.prompt.includes('主号'),'anonymous alt prompt cannot reveal the main account');
const p=x.xPost(state,{authorId:'u',text:'今天 #日常'});assert(x.xVisible(state,p,'a'));assert(!x.xVisible(state,p,'b'));
assert.throws(()=>x.xPost(state,{authorId:'b',text:'跨世界观'}));
assert.equal(x.buildXRoleContext(state,'b','alt').visiblePosts.length,0);
assert(!('knownMainAccount' in x.buildXRoleContext(state,'a','alt').viewerAccount));
state.accountRelations.alt.disclosedTo.a=true;assert.equal(x.buildXRoleContext(state,'a','alt').viewerAccount.knownMainAccount,'u');
assert.equal(accounts.namespace.accountContext(state,'a','alt').memoryOwnerId,'a::alt','disclosure does not merge private memory stores');
x.xToggle(state,p.id,'likes','a');assert.equal(p.likes.length,1);x.xToggle(state,p.id,'likes','a');assert.equal(p.likes.length,0);
const reply=x.xPost(state,{authorId:'a',text:'回复',parentId:p.id});assert.equal(state.xSocial.events.at(-1).authorId,'u');
const locked=x.xPost(state,{authorId:'u',text:'仅关注者',audience:'followers'});assert(!x.xVisible(state,locked,'a'));state.xSocial.follows.a=['u'];assert(x.xVisible(state,locked,'a'));
p.deleted=true;assert(!x.xVisible(state,p));assert.throws(()=>x.xPost(state,{authorId:'u',text:'引用',quoteId:p.id}));
console.log('PASS: cross-page positions, swaps, Dock replacement/extraction, folders; world isolation, alt disclosure, followers, replies, reactions, deleted quotes');
