import { conversationById, personById } from "../core/store.js";
import { escapeHtml, initialsAvatar, showToast, updateIsland, openSheet, closeSheet } from "../core/ui.js";
import { sendToModel } from "../integrations/ai-client.js";
import { applyChatAppearance } from "./chat-settings-v2.js";
import { ensureAccountState, accountUsers, activeAccount, accountRelation, conversationsForAccount, switchAccount } from "../account-system.js";

export function createChatRenderers({ store, navigate }) {
  let activeGroup = "all";
  let groupEditing = false;
  function list(container) {
    ensureDefaultGroup();
    container.className = "app-view chat-list-with-tabs";
    const state = ensureAccountState(store.getState()),accountConversations=conversationsForAccount(state);
    const pending=(state.friendRequests||[]).filter(x=>x.status==="pending").length;
    container.innerHTML = `
      <div class="row between"><span class="pill"><span class="dot"></span> Bunny Chat</span><div class="chat-head-actions"><button class="icon-button notification-button" data-friend-requests aria-label="好友申请">${bellIcon()}${pending?`<i>${pending}</i>`:""}</button><button class="icon-button" data-list-plus aria-label="聊天功能">＋</button></div></div>
      <div class="chat-group-strip ${groupEditing?"group-editing":""}"><button class="chat-group-chip ${activeGroup==="all"?"active":""}" data-group="all">全部</button>${state.chatGroups.map(group=>`<span class="chat-group-item"><button class="chat-group-chip ${activeGroup===group.id?"active":""}" data-group="${group.id}">${escapeHtml(group.name)} · ${group.personIds.length}</button><button class="group-delete-dot" data-delete-group="${group.id}" aria-label="删除${escapeHtml(group.name)}分组" ${group.id==="group-default"?"disabled":""}>−</button></span>`).join("")}<button class="chat-group-add" data-add-group aria-label="添加世界观">＋</button>${groupEditing?'<button class="chat-group-done" data-group-done aria-label="完成分组编辑">✓</button>':""}</div>
      <div class="world-rule">同一分组共享世界观并默认互相认识；不同分组彼此独立、互不认识。</div>
      <div class="section-title"><h3>联系人与会话</h3><span>${accountConversations.length} 个</span></div>
      <section>${accountConversations.filter(item=>activeGroup==="all"||personById(state,item.personId)?.groupId===activeGroup).map(item => {
        const person = personById(state, item.personId); const profile = state.chatProfiles[person.id];
        return `<article class="conversation row" data-conversation="${item.id}"><button class="avatar-button" data-open-conversation="${item.id}">${initialsAvatar(person, profile)}</button><div class="meta"><strong>${escapeHtml(profile.remark || person.name)}</strong><span>${escapeHtml(conversationPreview(item,state.messages[item.id]))}</span></div><div class="stack" style="justify-items:end;gap:.35rem"><span class="eyebrow">${item.time}</span>${item.unread ? `<span class="unread">${item.unread}</span>` : ""}</div></article>`;
      }).join("")}</section>
      ${chatTabs("chats")}`;

    container.querySelectorAll("[data-open-conversation]").forEach(button => button.addEventListener("click", () => navigate("conversation", { id: button.dataset.openConversation })));
    container.querySelectorAll("[data-conversation]").forEach(row => row.addEventListener("click", event => { if (!event.target.closest(".avatar-button")) navigate("conversation", { id: row.dataset.conversation }); }));
    container.querySelector("[data-list-plus]").addEventListener("click", () => openChatMenu(container));
    container.querySelector("[data-friend-requests]").onclick=()=>navigate("friend-requests");
    container.querySelectorAll("[data-group]").forEach(button=>{button.onclick=()=>{if(button.dataset.longPressed){button.dataset.longPressed="";return}if(groupEditing&&button.dataset.group!=="all")return editGroupName(button.dataset.group,container);activeGroup=button.dataset.group;list(container)};if(button.dataset.group!=="all")bindGroupLongPress(button,()=>{groupEditing=true;list(container)})});
    container.querySelectorAll("[data-delete-group]").forEach(button=>button.onclick=e=>{e.stopPropagation();if(!button.disabled)deleteGroup(button.dataset.deleteGroup,container)});
    container.querySelector("[data-add-group]").onclick=()=>addGroup(container);
    container.querySelector("[data-group-done]")?.addEventListener("click",()=>{groupEditing=false;list(container);showToast("世界观分组已保存")});
    bindChatTabs(container, navigate);
  }

  function ensureDefaultGroup(){const state=store.getState();if(state.chatGroups?.some(x=>x.id==="group-default"))return;store.update(s=>{s.chatGroups||=[];s.chatGroups.unshift({id:"group-default",name:"默认",worldId:s.currentWorldId||"",personIds:s.people.filter(p=>p.type!=="user"&&!p.groupId).map(p=>p.id)})})}
  function bindGroupLongPress(button,done){let timer,x=0,y=0;button.onpointerdown=e=>{x=e.clientX;y=e.clientY;timer=setTimeout(()=>{button.dataset.longPressed="1";navigator.vibrate?.(10);done()},480)};button.onpointermove=e=>{if(Math.abs(e.clientX-x)>8||Math.abs(e.clientY-y)>8)clearTimeout(timer)};button.onpointerup=button.onpointercancel=()=>clearTimeout(timer)}
  function editGroupName(id,container){const group=store.getState().chatGroups.find(x=>x.id===id);if(!group)return;openSheet(`<form class="group-name-editor"><div class="sheet-title"><h3>编辑世界观标签</h3><button type="button" class="button ghost" data-sheet-close>取消</button></div><label class="field"><span>标签名称</span><input name="name" maxlength="18" value="${escapeHtml(group.name)}" autofocus></label><button class="button">保存名称</button></form>`,{onReady(sheet){sheet.querySelector("form").onsubmit=e=>{e.preventDefault();const name=new FormData(e.currentTarget).get("name").trim();if(!name)return showToast("请输入分组名称");store.update(s=>s.chatGroups.find(x=>x.id===id).name=name);closeSheet();list(container)}}})}
  function addGroup(container){openSheet(`<form class="group-name-editor"><div class="sheet-title"><h3>新的世界观</h3><button type="button" class="button ghost" data-sheet-close>取消</button></div><label class="field"><span>世界观标签名称</span><input name="name" maxlength="18" placeholder="例如：首尔大学线" autofocus></label><button class="button">创建</button></form>`,{onReady(sheet){sheet.querySelector("form").onsubmit=e=>{e.preventDefault();const name=new FormData(e.currentTarget).get("name").trim();if(!name)return showToast("请输入分组名称");store.update(s=>s.chatGroups.push({id:"group-"+Date.now(),name,worldId:s.currentWorldId||"",personIds:[]}));closeSheet();list(container)}}})}
  function deleteGroup(id,container){const group=store.getState().chatGroups.find(x=>x.id===id);if(!group||id==="group-default")return;openSheet(`<div class="confirm-dialog"><div class="confirm-symbol">−</div><h3>删除“${escapeHtml(group.name)}”</h3><p>分组中的好友会自动移动到“默认”分组，聊天记录不会删除。</p><div class="row"><button class="button secondary" data-sheet-close>取消</button><button class="button danger-button" data-confirm-delete>删除</button></div></div>`,{onReady(sheet){sheet.querySelector("[data-confirm-delete]").onclick=()=>{store.update(s=>{const source=s.chatGroups.find(x=>x.id===id),target=s.chatGroups.find(x=>x.id==="group-default");for(const personId of source.personIds){if(!target.personIds.includes(personId))target.personIds.push(personId);const person=personById(s,personId);if(person)person.groupId=target.id}s.chatGroups=s.chatGroups.filter(x=>x.id!==id)});if(activeGroup===id)activeGroup="group-default";closeSheet();list(container);showToast("分组已删除，好友已移到默认分组")}}})}

  function conversation(container, params) {
    container.className = "app-view";
    const state = store.getState(); const conv = conversationById(state, params.id || "conv-jun"); const person = personById(state, conv.personId); const profile = state.chatProfiles[person.id]; const user=personById(state,state.currentUserId); const chatAppearance=state.chatAppearance;
    conv.unread = 0; applyChatAppearance(chatAppearance);
    container.innerHTML = `<section class="chat-layout" style="${chatAppearance.background?`background-image:linear-gradient(rgba(244,244,242,.72),rgba(244,244,242,.72)),url(${escapeHtml(chatAppearance.background)});background-size:cover;background-position:center`:""}">
      <div class="chat-person row between"><button class="avatar-button" data-profile-card>${initialsAvatar(person, profile)}</button><div class="meta"><strong>${escapeHtml(profile.remark || person.name)}</strong><span>${escapeHtml(person.note)}</span></div><button class="icon-button" data-chat-settings aria-label="聊天设置">•••</button></div>
      <div class="chat-stream" data-stream>${state.messages[conv.id].map((message,index,list) => messageBubble(message,index>0&&list[index-1].role===message.role,person,user,profile,chatAppearance)).join("")}</div>
      <div><div class="plus-tray hidden" data-plus-tray>${["图片","拍摄","语音","位置","红包","转账","文件","一起刷","表情包"].map((label,index)=>`<button data-extra="${label}"><span>${["▧","◉","♫","⌖","礼","¥","□","▷","☺"][index]}</span>${label}</button>`).join("")}</div>
      <form class="composer"><button type="button" class="icon-button" data-plus aria-label="更多功能">＋</button><textarea name="message" rows="1" placeholder="说点什么…" aria-label="消息"></textarea><button type="button" class="send secondary-send" data-send-only aria-label="仅发送">↑</button><button class="send ai-send" aria-label="发送给 AI">AI</button></form></div>
    </section>`;
    const form = container.querySelector("form");
    container.querySelector("[data-plus]").addEventListener("click", () => container.querySelector("[data-plus-tray]").classList.toggle("hidden"));
    container.querySelectorAll("[data-extra]").forEach(button => button.addEventListener("click", () => handleExtra(button.dataset.extra)));
    container.querySelector("[data-send-only]").addEventListener("click", () => submitMessage(false));
    form.addEventListener("submit", event => { event.preventDefault(); submitMessage(true); });
    container.querySelector("[data-chat-settings]").addEventListener("click", () => navigate("chat-settings", { personId: person.id }));
    const avatar = container.querySelector("[data-profile-card]");
    let clickTimer; avatar.addEventListener("click", () => { clearTimeout(clickTimer); clickTimer = setTimeout(() => showProfileCard(person, profile), 250); });
    avatar.addEventListener("dblclick", () => { clearTimeout(clickTimer); addSystemMessage(profile.patText || `拍了拍${person.name}`); showToast(profile.patText || "拍一拍"); });
    bindMessageMenus(container, conv, person);

    function handleExtra(type){
      const add=text=>{store.update(s=>s.messages[conv.id].push({id:crypto.randomUUID(),role:"user",text,time:timeNow()}));conversation(container,params)};
      if(type==="图片"||type==="拍摄"||type==="文件"){const input=document.createElement("input");input.type="file";input.accept=type==="文件"?"*/*":"image/*";if(type==="拍摄")input.setAttribute("capture","environment");input.onchange=e=>{const file=e.target.files[0];if(file)add(`[${type}] ${file.name}`)};input.click();return}
      if(type==="位置"){if(!navigator.geolocation)return showToast("当前浏览器不支持定位");navigator.geolocation.getCurrentPosition(pos=>add(`[位置] ${pos.coords.latitude.toFixed(4)}, ${pos.coords.longitude.toFixed(4)}`),()=>showToast("未获得定位权限"));return}
      if(type==="语音"){navigator.mediaDevices?.getUserMedia({audio:true}).then(stream=>{stream.getTracks().forEach(t=>t.stop());add("[语音] 00:03")}).catch(()=>showToast("未获得麦克风权限"));return}
      if(type==="红包"||type==="转账"){const amount=prompt(`${type}金额`,"52.00");if(amount)add(`[${type}] ¥${amount}`);return}
      if(type==="一起刷"){navigate("together");return}
      if(type==="表情包"){openSheet(`<div class="sheet-handle"></div><div class="sheet-title"><h3>表情包</h3><button class="button ghost" data-sheet-close>关闭</button></div><div class="action-grid">${store.getState().stickerLibraries.characters[person.id].map((x,i)=>`<button class="action-card" data-sticker-index="${i}">${escapeHtml(x.name)}</button>`).join("")||'<p class="callout">请先在聊天设置上传角色表情包。</p>'}</div>`,{onReady(sheet){sheet.querySelectorAll("[data-sticker-index]").forEach(b=>b.onclick=()=>{const x=store.getState().stickerLibraries.characters[person.id][Number(b.dataset.stickerIndex)];closeSheet();add(`[表情] ${x.name}`)})}})}
    }

    async function submitMessage(sendAi) {
      const input = form.elements.message; const text = input.value.trim(); if (!text) return;
      const now = timeNow(); store.update(s => { s.messages[conv.id].push({ id: crypto.randomUUID(), role: "user", text, time: now }); conv.preview = text; conv.time = now; }); input.value = ""; conversation(container, params);
      if (!sendAi) return;
      const current = store.getState(); const modelProfile = current.modelProfiles.find(item => item.id === current.activeModelProfileId);
      updateIsland(`${person.name} 正在通过 AI 回复…`, true);
      try { const preset=current.presets.find(x=>x.id===profile.presetId)||current.presets.find(x=>x.name===profile.preset); const books=current.worldbooks.filter(x=>(profile.worldbookIds||[]).includes(x.id)||x.name===profile.worldbook); const systemPrompt=[preset?.prompt,...books.map(x=>x.prompt)].filter(Boolean).join("\n\n"); const reply = await sendToModel(modelProfile, current.messages[conv.id], systemPrompt); store.update(s => s.messages[conv.id].push({ id: crypto.randomUUID(), role: "char", text: reply, time: timeNow() })); conversation(container, params); }
      catch (error) { showToast(error.message); }
      finally { updateIsland("bunny 正在陪你", false); }
    }

    function addSystemMessage(text) { store.update(s => s.messages[conv.id].push({ id: crypto.randomUUID(), role: "system", text, time: timeNow() })); conversation(container, params); }
  }

  function moments(container) {
    const state = store.getState();
    container.innerHTML = `<section class="moments-cover"><div><span>我的朋友圈</span><strong>把日常留在世界里。</strong></div><button class="button secondary" data-cover>更换背景</button></section><section class="feed">${state.moments.map(post => { const person = personById(state, post.personId); return `<article class="moment-card">${initialsAvatar(person, state.chatProfiles[person.id] || {})}<div><strong>${escapeHtml(person.name)}</strong><p>${escapeHtml(post.text)}</p><small>${post.time}</small><div class="moment-actions"><button data-like="${post.id}">♡ ${post.likes.length}</button><button data-comment="${post.id}">评论</button></div><div class="moment-social"><span>♥ ${post.likes.join("、")}</span>${post.comments.map(comment => `<p><b>${escapeHtml(comment.name)}：</b>${escapeHtml(comment.text)}</p>`).join("")}</div></div></article>`; }).join("")}</section>${chatTabs("moments")}`;
    container.querySelector("[data-cover]").addEventListener("click", () => showToast("朋友圈背景可从相册或图床链接设置"));
    container.querySelectorAll("[data-like]").forEach(button => button.addEventListener("click", () => { store.update(s => { const post=s.moments.find(p=>p.id===button.dataset.like); if(!post.likes.includes("小满"))post.likes.push("小满"); }); moments(container); }));
    container.querySelectorAll("[data-comment]").forEach(button => button.addEventListener("click", () => showToast("评论输入框将在消息组件中复用")));
    bindChatTabs(container, navigate);
  }

  function me(container) {
    const state=ensureAccountState(store.getState()),user=activeAccount(state),accounts=accountUsers(state);
    container.innerHTML=`<button class="card user-profile-entry row" data-open-user>${initialsAvatar(user,{avatarUrl:user.avatarUrl||""})}<div class="meta"><strong>${escapeHtml(user.chatName||user.name)}</strong><span>${escapeHtml(user.signature||user.note||"点击头像编辑完整 USER 名片")}</span></div><span>›</span></button><section class="card user-profile-summary"><div class="setting-row"><div><span class="label">真实名字</span><small>${escapeHtml(user.name||"未填写")}</small></div><span class="pill">${accountRelation(state,user.id).type==="alt"?"小号":"USER"}</span></div><div class="setting-row"><div><span class="label">所在地</span><small>${escapeHtml(user.location||user.city||"未填写")}</small></div></div><div class="setting-row"><div><span class="label">人物设定</span><small>${escapeHtml(user.personality||user.note||"未填写")}</small></div></div></section><div class="section-title"><h3>内容</h3><span>按当前账号保存</span></div><section class="card"><button class="setting-row profile-function" data-favorites><div><span class="label">收藏</span><small>文字、照片、语音与通话片段</small></div><span class="pill">${(state.favorites||[]).length}</span></button><button class="setting-row profile-function" data-anonymous-box><div><span class="label">匿名提问箱</span><small>来自 CHAR 与 NPC 的匿名问题</small></div><span class="pill">${(state.anonymousQuestions||[]).filter(x=>x.status!=="answered").length}</span></button></section><div class="section-title"><h3>账号身份</h3><button class="mini-add-account" data-add-account>＋ 添加账号</button></div><section class="account-switcher">${accounts.map(account=>accountCard(account,state)).join("")}</section>${chatTabs("me")}`;
    container.querySelector("[data-open-user]").onclick=()=>navigate("user-profile");
    container.querySelector("[data-favorites]").onclick=()=>navigate("favorites");
    container.querySelector("[data-anonymous-box]").onclick=()=>navigate("anonymous-box");
    container.querySelector("[data-add-account]").onclick=()=>openAccountCreator(container);
    container.querySelectorAll("[data-switch-account]").forEach(button=>button.onclick=()=>{store.update(s=>switchAccount(s,button.dataset.switchAccount));me(container);showToast("已切换账号")});
    container.querySelectorAll("[data-delete-account]").forEach(button=>button.onclick=e=>{e.stopPropagation();deleteAccount(button.dataset.deleteAccount,container)});
    bindChatTabs(container,navigate);
  }

  function openAccountCreator(container){const state=ensureAccountState(store.getState()),accounts=accountUsers(state);openSheet(`<form class="account-create-sheet"><div class="sheet-title"><div><small>NEW IDENTITY</small><h3>添加账号</h3></div><button type="button" class="button ghost" data-sheet-close>取消</button></div><label class="field"><span>账号显示名</span><input name="chatName" maxlength="30" required placeholder="例如：moon.archive"></label><label class="field"><span>真实名字 / 称呼</span><input name="name" maxlength="30" required placeholder="这个账号的人设称呼"></label><label class="field"><span>账号类型</span><select name="relationType"><option value="none">独立身份，不关联任何账号</option><option value="alt">已有账号的小号</option></select></label><label class="field" data-related hidden><span>小号归属身份</span><select name="relatedTo" disabled>${accounts.map(x=>`<option value="${x.id}">${escapeHtml(x.chatName||x.name)}</option>`).join("")}</select><small>只有小号需要选择归属，独立身份不会继承任何资料或记忆。</small></label><button class="button">创建并切换到新账号</button></form>`,{onReady(sheet){const form=sheet.querySelector("form"),related=sheet.querySelector("[data-related]"),select=form.elements.relatedTo;const sync=()=>{const alt=form.relationType.value==="alt";related.hidden=!alt;select.disabled=!alt;select.required=alt};form.relationType.onchange=sync;sync();form.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(form)),id=`user-${Date.now()}`,isAlt=d.relationType==="alt",source=isAlt?personById(store.getState(),d.relatedTo):null;store.update(s=>{s.people.push({id,type:"user",name:d.name,chatName:d.chatName,initials:d.chatName.slice(0,2).toUpperCase(),phone:"",location:isAlt?source?.location||"":"",city:isAlt?source?.city||"":"",signature:"",appearance:"",familyBackground:"",personality:isAlt?source?.personality||"":"",tmi:""});s.accountRelations[id]={type:isAlt?"alt":"none",relatedTo:isAlt?d.relatedTo:"",disclosedTo:{}};s.accountFriends[id]=[];switchAccount(s,id)});closeSheet();me(container);showToast(isAlt?"小号已创建并绑定归属身份":"独立账号已创建，不关联其他身份")}}})}
  function deleteAccount(id,container){const state=store.getState(),account=personById(state,id),accounts=accountUsers(state);if(accounts.length<=1)return showToast("至少保留一个账号");if(!confirm(`删除账号“${account?.chatName||account?.name}”及该账号的会话和朋友圈？`))return;store.update(s=>{const convIds=s.conversations.filter(x=>x.userAccountId===id).map(x=>x.id);s.conversations=s.conversations.filter(x=>x.userAccountId!==id);convIds.forEach(x=>delete s.messages[x]);s.moments=(s.moments||[]).filter(x=>x.accountId!==id&&x.personId!==id);s.people=s.people.filter(x=>x.id!==id);delete s.accountRelations[id];delete s.accountFriends[id];if(s.currentUserId===id)switchAccount(s,s.people.find(x=>x.type==="user")?.id)});me(container);showToast("账号已删除")}

  function openChatMenu(container){openSheet(`<div class="sheet-handle"></div><div class="sheet-title"><h3>发起</h3><button class="button ghost" data-sheet-close>关闭</button></div><div class="action-grid"><button class="action-card" data-action="group"><span class="action-icon">界</span>管理世界分组</button><button class="action-card" data-action="chat"><span class="action-icon">群</span>创建群聊</button><button class="action-card" data-action="friend"><span class="action-icon">＋</span>添加好友</button></div>`,{onReady(sheet){sheet.querySelector('[data-action="group"]').onclick=()=>{closeSheet();openGroupEditor(container)};sheet.querySelector('[data-action="chat"]').onclick=()=>showToast("请选择同一世界分组内的角色创建群聊");sheet.querySelector('[data-action="friend"]').onclick=()=>{closeSheet();navigate("add-friend")}}})}
  function openGroupEditor(container){const state=store.getState();openSheet(`<div class="sheet-handle"></div><div class="sheet-title"><h3>世界分组</h3><button class="button ghost" data-sheet-close>关闭</button></div><div class="group-manager">${state.chatGroups.map(g=>`<article class="group-card"><div class="row between"><div><strong>${escapeHtml(g.name)}</strong><div class="sub">同组角色默认互相认识</div></div><button class="button ghost" data-rename="${g.id}">改名</button></div><div class="group-members">${state.people.filter(p=>p.type!=="user").map(p=>`<label class="pill"><input type="checkbox" data-member="${g.id}" value="${p.id}" ${g.personIds.includes(p.id)?"checked":""}> ${escapeHtml(p.name)}</label>`).join("")}</div></article>`).join("")}</div><button class="button" data-new-group>＋ 创建分组</button>`,{onReady(sheet){sheet.querySelectorAll("[data-member]").forEach(x=>x.onchange=()=>store.update(s=>{s.chatGroups.forEach(g=>g.personIds=g.personIds.filter(id=>id!==x.value));const target=s.chatGroups.find(g=>g.id===x.dataset.member);if(x.checked)target.personIds.push(x.value);const person=personById(s,x.value);person.groupId=x.checked?target.id:""}));sheet.querySelectorAll("[data-rename]").forEach(x=>x.onclick=()=>{const name=prompt("分组名称",state.chatGroups.find(g=>g.id===x.dataset.rename).name);if(name)store.update(s=>s.chatGroups.find(g=>g.id===x.dataset.rename).name=name);closeSheet();openGroupEditor(container)});sheet.querySelector("[data-new-group]").onclick=()=>{const name=prompt("新分组名称","新的世界");if(!name)return;store.update(s=>s.chatGroups.push({id:"group-"+Date.now(),name,worldId:"",personIds:[]}));closeSheet();openGroupEditor(container)}}})}
  function showProfileCard(person, profile) { openSheet(`<div class="sheet-handle"></div><section class="profile-card">${initialsAvatar(person,profile)}<div><span class="eyebrow">BUNNY CHAT CARD</span><h3>${escapeHtml(person.name)}</h3><p>@${escapeHtml(profile.remark || person.name).toLowerCase().replace(/\s/g,"_")}</p></div></section><blockquote class="signature">“${escapeHtml(person.signature || person.note)}”</blockquote><div class="row"><button class="button" data-sheet-close>发消息</button><button class="button secondary" data-sheet-close>语音通话</button></div>`); }
  function bindMessageMenus(container,conv,person){container.querySelectorAll(".message.char .bubble").forEach(bubble=>{let timer;bubble.addEventListener("pointerdown",()=>timer=setTimeout(()=>showMessageMenu(bubble.closest(".message").dataset.messageId,conv,person),500));bubble.addEventListener("pointerup",()=>clearTimeout(timer));bubble.addEventListener("pointercancel",()=>clearTimeout(timer));});}
  function showMessageMenu(messageId,conv,person){const message=store.getState().messages[conv.id].find(item=>item.id===messageId);openSheet(`<div class="reaction-row">${["♥","😂","🥺","👍","…"].map(emoji=>`<button data-reaction="${emoji}">${emoji}</button>`).join("")}</div><div class="section-title"><h3>消息操作</h3><span>${escapeHtml(person.name)}</span></div><div class="action-grid"><button class="action-card" data-copy>复制</button><button class="action-card" data-edit>编辑</button><button class="action-card" data-select>多选</button></div>`,{onReady(sheet){sheet.querySelector("[data-copy]").addEventListener("click",async()=>{await navigator.clipboard?.writeText(message.text);showToast("已复制");closeSheet();});sheet.querySelector("[data-edit]").addEventListener("click",()=>{const next=prompt("编辑消息",message.text);if(next!==null)store.update(s=>{const m=s.messages[conv.id].find(item=>item.id===messageId);m.text=next;});closeSheet();});sheet.querySelector("[data-select]").addEventListener("click",()=>{showToast("已进入多选模式");closeSheet();});sheet.querySelectorAll("[data-reaction]").forEach(button=>button.addEventListener("click",()=>{store.update(s=>{const m=s.messages[conv.id].find(item=>item.id===messageId);m.reaction=button.dataset.reaction;});showToast("已添加 reaction");closeSheet();}));}});}
  return { list, conversation, moments, me };
}

function accountCard(account,state){const relation=accountRelation(state,account.id),active=state.activeUserAccountId===account.id,related=personById(state,relation.relatedTo);return`<article class="account-card ${active?"active":""}" data-switch-account="${account.id}">${initialsAvatar(account,{avatarUrl:account.avatarUrl||""})}<div><strong>${escapeHtml(account.chatName||account.name)}</strong><span>${relation.type==="main"?"主账号":relation.type==="alt"?`${escapeHtml(related?.chatName||related?.name||"已有账号")} 的小号`:"独立账号"}</span></div>${active?'<b>使用中</b>':`<button data-delete-account="${account.id}" aria-label="删除账号">−</button>`}</article>`}
function messageBubble(message,continuation,person,user,profile,appearance){if(message.role==="system")return `<article class="system-message">${escapeHtml(message.text)}</article>`;const owner=message.role==="user"?user:person,avatarProfile=message.role==="user"?{avatarUrl:user.avatarUrl||""}:profile,hide=message.role==="user"&&appearance.hideUserAvatar;return `<article class="message ${message.role} ${continuation?"continuation":""} ${hide?"hide-user-avatar":""}" data-message-id="${message.id}" data-message-role="${message.role}">${hide?"":`<div class="message-avatar">${initialsAvatar(owner,avatarProfile)}</div>`}<div class="bubble">${escapeHtml(message.text)}</div>${message.reaction?`<span class="message-reaction">${message.reaction}</span>`:""}<time>${message.time}</time></article>`;}
function chatTabs(active){const icon=(path)=>`<svg viewBox="0 0 24 24" aria-hidden="true">${path}</svg>`;return `<nav class="chat-tabs"><button aria-label="聊天" data-chat-tab="chat" class="${active==="chats"?"active":""}">${icon('<path d="M4 5h16v11H9l-5 4V5z"/>')}</button><button aria-label="朋友圈" data-chat-tab="moments" class="${active==="moments"?"active":""}">${icon('<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="2"/>')}</button><button aria-label="我" data-chat-tab="chat-me" class="${active==="me"?"active":""}">${icon('<circle cx="12" cy="8" r="3"/><path d="M5 20c1-5 13-5 14 0"/>')}</button></nav>`;}
function bindChatTabs(container,navigate){container.querySelectorAll("[data-chat-tab]").forEach(button=>button.addEventListener("click",()=>navigate(button.dataset.chatTab)));}
function bellIcon(){return'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 10a6 6 0 0 1 12 0v4l2 3H4l2-3v-4Z"/><path d="M10 20h4"/></svg>'}
function timeNow(){return new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit",hour12:false});}
function conversationPreview(item,messages=[]){const last=[...(messages||[])].reverse().find(x=>!x.recalled);if(!last)return item.preview||"暂无消息";return({voice:"[语音]",redpacket:"[红包]",transfer:"[转账]",image:"[图片]","text-image":"[图片]",sticker:"[表情包]",location:"[位置]",file:"[文件]","voice-call":"[语音通话]","video-call":"[视频通话]","chat-record":"[聊天记录]"})[last.type]||last.text||item.preview||"新消息"}
