import { escapeHtml, initialsAvatar, showToast, openSheet, closeSheet } from "../core/ui.js";

export function createContactsRenderer({store,navigate}){return container=>{const state=store.getState(),user=state.people.find(x=>x.id===state.currentUserId),chars=sortedChars(state.people);container.innerHTML=`
  <button class="card user-profile-entry row" data-user-profile>${initialsAvatar(user,{avatarUrl:user.avatarUrl||""})}<div class="meta"><span class="eyebrow">MY USER</span><strong>${escapeHtml(user.name)}</strong><span>${escapeHtml(user.note||"编辑自己的资料")}</span></div><span>›</span></button>
  <div class="row between"><span class="pill">${escapeHtml(state.worlds[0]?.name||"Bunny World")}</span><button class="button ghost" data-create-char>＋ 创建角色</button></div>
  <div class="section-title"><h3>全部 CHAR</h3><span>${chars.length} 位</span></div>
  <section class="contact-book">${grouped(chars).map(group=>`<div class="contact-letter">${group.letter}</div>${group.items.map(person=>contactRow(person,state)).join("")}`).join("")}</section>`;
  container.querySelector("[data-user-profile]").onclick=()=>navigate("user-profile");container.querySelector("[data-create-char]").onclick=()=>navigate("character-edit");container.querySelectorAll("[data-edit-char]").forEach(x=>x.onclick=()=>navigate("character-edit",{id:x.dataset.editChar}));container.querySelectorAll("[data-chat-settings-person]").forEach(x=>x.onclick=()=>navigate("chat-settings",{personId:x.dataset.chatSettingsPerson,conversationId:state.conversations.find(c=>c.personId===x.dataset.chatSettingsPerson)?.id||""}))}}

export function createCharacterEditorRenderer({store,navigate}){return(container,params={})=>{const state=store.getState(),existing=params.id?state.people.find(x=>x.id===params.id):null,p=existing||{name:"",initials:"",age:"",gender:"",occupation:"",personality:"",note:"",signature:"",city:"",cityPrototype:"",sortKey:"",groupId:""};let avatar=existing?state.chatProfiles[existing.id]?.avatarUrl||"":"";render();function render(){container.innerHTML=`<form class="stack profile-editor" data-character-form><section class="profile-avatar-editor"><button type="button" data-avatar-pick>${avatar?`<img src="${escapeHtml(avatar)}" alt="">`:'<span>＋</span>'}</button><strong>${existing?"编辑 CHAR":"创建 CHAR"}</strong><small>点击头像可选照片、拍摄或图床</small></section>${identityFields(p,state)}<button class="button">${existing?"保存角色资料":"创建并保存"}</button></form>`;container.querySelector("[data-avatar-pick]").onclick=()=>pickAvatar(value=>{avatar=value;render()});container.querySelector("form").onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget)),id=existing?.id||`char-${Date.now()}`,person={...(existing||{}),...data,id,type:"char",initials:data.initials||initials(data.name),online:true};store.update(s=>{if(existing)Object.assign(s.people.find(x=>x.id===id),person);else{s.people.push(person);s.chatProfiles[id]=profileSeed(person,avatar);s.stickerLibraries.characters[id]=[]}s.chatProfiles[id]={...profileSeed(person,avatar),...(s.chatProfiles[id]||{}),avatarUrl:avatar};if(data.groupId){s.chatGroups.forEach(g=>g.personIds=g.personIds.filter(x=>x!==id));const g=s.chatGroups.find(x=>x.id===data.groupId);if(g&&!g.personIds.includes(id))g.personIds.push(id)}});showToast(existing?"角色资料已保存":"角色已创建，可在聊天中添加好友");navigate("contacts")}}}}

export function createUserProfileRenderer({store,navigate}){return container=>{const state=store.getState(),user=state.people.find(x=>x.id===state.currentUserId);let avatar=user.avatarUrl||"";render();function render(){container.innerHTML=`<form class="stack profile-editor"><section class="profile-avatar-editor"><button type="button" data-avatar-pick>${avatar?`<img src="${escapeHtml(avatar)}" alt="">`:'<span>＋</span>'}</button><strong>USER 资料</strong><small>点击头像更换</small></section><section class="card stack">${field("name","姓名",user.name)}${field("chatName","昵称 / 账号",user.chatName)}<div class="row">${field("age","年龄",user.age||"","number")}${field("gender","性别",user.gender||"")}</div>${field("occupation","职业",user.occupation||"")}${field("personality","性格",user.personality||"")}${area("note","个人简介",user.note)}${field("city","城市",user.city)}${field("cityPrototype","原型城市",user.cityPrototype)}</section><button class="button">保存 USER 资料</button></form>`;container.querySelector("[data-avatar-pick]").onclick=()=>pickAvatar(value=>{avatar=value;render()});container.querySelector("form").onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));store.update(s=>Object.assign(s.people.find(x=>x.id===s.currentUserId),data,{avatarUrl:avatar}));showToast("USER 资料已保存");navigate("contacts")}}}}

export function createAddFriendRenderer({store,navigate}){return container=>{const state=store.getState(),added=new Set(state.conversations.map(x=>x.personId)),candidates=sortedChars(state.people).filter(x=>!added.has(x.id));container.innerHTML=`<p class="callout">这里显示通讯录中尚未加入聊天列表的 CHAR。添加后会立即建立可用会话。</p><div class="section-title"><h3>新的朋友</h3><span>${candidates.length} 位</span></div><section class="contact-book">${candidates.length?grouped(candidates).map(group=>`<div class="contact-letter">${group.letter}</div>${group.items.map(person=>`<article class="contact-row card row"><div class="contact-avatar">${initialsAvatar(person,state.chatProfiles[person.id]||{})}</div><div class="meta"><strong>${escapeHtml(person.name)}</strong><span>${escapeHtml(person.note||person.personality||"")}</span></div><button class="button secondary" data-add-friend="${person.id}">添加</button></article>`).join("")}`).join(""):'<div class="empty"><strong>没有待添加的联系人</strong><span>可以先到联系人应用创建新的 CHAR。</span></div>'}</section><button class="button secondary" data-create-char>创建新角色</button>`;container.querySelector("[data-create-char]").onclick=()=>navigate("character-edit");container.querySelectorAll("[data-add-friend]").forEach(button=>button.onclick=()=>{const id=button.dataset.addFriend,person=state.people.find(x=>x.id===id),convId=`conv-${id.replace(/^char-/,"")}-${Date.now()}`;store.update(s=>{s.conversations.push({id:convId,personId:id,preview:"你们已经是好友了",time:timeNow(),unread:0});s.messages[convId]=[]});showToast(`${person.name} 已添加到聊天列表`);navigate("conversation",{id:convId})})}}

function identityFields(p,state){return`<section class="card stack">${field("name","角色姓名",p.name)}<div class="row">${field("initials","头像缩写",p.initials)}${field("sortKey","排序字母",p.sortKey||p.initials?.[0]||"")}</div><div class="row">${field("age","年龄",p.age||"","number")}${field("gender","性别",p.gender||"")}</div>${field("occupation","职业",p.occupation||"")}${area("personality","性格与人设",p.personality||"")}${field("note","状态简介",p.note||"")}${field("signature","个性签名",p.signature||"")}<div class="row">${field("city","城市",p.city||"")}${field("cityPrototype","原型城市",p.cityPrototype||"")}</div><label class="field"><span>世界分组</span><select name="groupId"><option value="">暂不分组</option>${state.chatGroups.map(g=>`<option value="${g.id}" ${p.groupId===g.id?"selected":""}>${escapeHtml(g.name)}</option>`).join("")}</select></label></section>`}
function contactRow(person,state){const added=state.conversations.some(x=>x.personId===person.id);return`<article class="contact-row card row"><div class="contact-avatar">${initialsAvatar(person,state.chatProfiles[person.id]||{})}</div><div class="meta"><strong>${escapeHtml(person.name)}</strong><span>${escapeHtml(person.note||person.personality||"")}</span></div><span class="pill">${added?"好友":"未添加"}</span><button class="icon-button" data-chat-settings-person="${person.id}" aria-label="聊天设置">•••</button><button class="icon-button" data-edit-char="${person.id}" aria-label="编辑角色">✎</button></article>`}
function sortedChars(people){return people.filter(x=>x.type==="char").sort((a,b)=>sortLetter(a).localeCompare(sortLetter(b),"en")||a.name.localeCompare(b.name,"zh-CN-u-co-pinyin"))}
function grouped(items){const groups=[];for(const item of items){const letter=sortLetter(item),last=groups.at(-1);if(!last||last.letter!==letter)groups.push({letter,items:[item]});else last.items.push(item)}return groups}
function sortLetter(p){const x=String(p.sortKey||p.initials||p.name||"#").trim()[0]?.toUpperCase()||"#";return/[A-Z]/.test(x)?x:"#"}
function field(name,label,value,type="text"){return`<label class="field"><span>${label}</span><input name="${name}" type="${type}" value="${escapeHtml(value||"")}"></label>`}
function area(name,label,value){return`<label class="field"><span>${label}</span><textarea name="${name}" rows="4">${escapeHtml(value||"")}</textarea></label>`}
function initials(name){return String(name||"CHAR").replace(/\s/g,"").slice(0,2).toUpperCase()}
function profileSeed(person,avatar){return{avatarUrl:avatar,remark:person.name,voiceSpeed:1,voiceId:"",autoPlayVoice:false,llmTone:true,language:"中文",emotion:"自动",toneStyle:"自然",translationEnabled:false,visionEnabled:true,memoryDepth:24,quietHours:"23:00—08:00",proactiveCall:false,patText:`你拍了拍${person.name}`,patUserText:`${person.name}拍了拍你`}}
function pickAvatar(done){openSheet(`<div class="sheet-title"><h3>更换头像</h3><button class="button ghost" data-sheet-close>取消</button></div><div class="action-grid"><button class="action-card" data-source="album"><span class="action-icon">▧</span>选取照片</button><button class="action-card" data-source="camera"><span class="action-icon">◉</span>拍摄</button><button class="action-card" data-source="url"><span class="action-icon">⌁</span>图床 URL</button></div>`,{onReady(sheet){sheet.querySelectorAll("[data-source]").forEach(button=>button.onclick=()=>{if(button.dataset.source==="url"){const url=prompt("图片 URL");if(/^https?:\/\//.test(url||"")){closeSheet();done(url)}return}const input=document.createElement("input");input.type="file";input.accept="image/*";if(button.dataset.source==="camera")input.capture="user";input.onchange=()=>readImage(input.files?.[0]).then(value=>{closeSheet();done(value)}).catch(e=>showToast(e.message));input.click()})}})}
function readImage(file){return new Promise((resolve,reject)=>{if(!file)return reject(Error("没有选择图片"));if(file.size>6*1024*1024)return reject(Error("请选择 6MB 以内图片"));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error("头像读取失败"));r.readAsDataURL(file)})}
function timeNow(){return new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit",hour12:false})}
