import { goBack } from '../core/router.js';
import { escapeHtml, initialsAvatar, showToast, openSheet, closeSheet } from "../core/ui.js";
import { clearCharacterMemory } from "../memory-engine.js";
import { addMemoryEntry } from "../memory-engine.js";
import { ensureAccountState, activeAccount, accountRelation, accountContext, conversationsForAccount } from "../account-system.js";

const PAGE_SIZE=6;
function editWorldSummary(store,selectedId,done){
  const groups=store.getState().chatGroups||[];
  if(!groups.length)return showToast('请先在聊天列表创建世界观分组');
  let id=groups.some(g=>g.id===selectedId)?selectedId:groups[0].id;
  const drafts=new Map(groups.map(g=>[g.id,String(g.description||'')]));
  openSheet(`<form class="world-summary-editor"><header><span>WORLD NOTES</span><h3>世界观简述</h3><p>时代、地点、社会规则与共同背景。角色会自然代入，世界书可继续补充细节。</p></header><label class="field"><span>选择世界观</span><select name="group">${groups.map(g=>`<option value="${escapeHtml(g.id)}" ${g.id===id?'selected':''}>${escapeHtml(g.name)}</option>`).join('')}</select></label><label class="field"><span>简述</span><textarea name="description" rows="8" maxlength="12000" placeholder="例如：现代首尔，故事围绕一家独立唱片店展开。人物遵循现实社会规则……">${escapeHtml(drafts.get(id))}</textarea></label><small>仅发送当前角色所属分组的简述，不混入其他世界观。</small><div class="sheet-split-actions"><button type="button" class="button secondary" data-sheet-close>取消</button><button class="button">保存简述</button></div></form>`,{onReady(sheet){
    const form=sheet.querySelector('form'),area=form.elements.description;
    form.elements.group.onchange=e=>{drafts.set(id,area.value);id=e.target.value;area.value=drafts.get(id)||''};
    form.onsubmit=e=>{e.preventDefault();drafts.set(id,area.value);store.update(s=>{for(const group of s.chatGroups||[])if(drafts.has(group.id))group.description=drafts.get(group.id).trim()});closeSheet();done();showToast('世界观简述已保存，下次 AI 请求即生效')};
  }});
}
import { worldGroupForPerson } from "../world-context.js";

export function createContactsRenderer({store,navigate}){
  let roleType="char",page=0,selectedGroup="all";
  return function render(container){
    const state=store.getState(),user=state.people.find(x=>x.id===state.currentUserId),roles=state.people.filter(x=>x.type===roleType&&(selectedGroup==="all"||worldGroupForPerson(state,x.id)?.id===selectedGroup)).sort(roleSort),pages=Math.max(1,Math.ceil(roles.length/PAGE_SIZE));
    page=Math.min(page,pages-1);const visible=roles.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE);
    container.className="app-view role-archive-view";
    container.innerHTML=`<section class="role-archive">
      <header class="role-archive-head"><button class="role-user-chip" data-user-profile>${initialsAvatar(user,{avatarUrl:user.avatarUrl||""})}<span><small>MY USER</small><strong>${escapeHtml(user.chatName||user.name)}</strong></span></button><label class="role-type-picker"><select data-role-type><option value="char" ${roleType==="char"?"selected":""}>CHAR</option><option value="npc" ${roleType==="npc"?"selected":""}>配角 / NPC</option></select><span>⌄</span></label></header>
      <div class="archive-caption"><div><span>CHARACTER ARCHIVE</span><strong>${roleType==="char"?"主要角色":"支线人物"}</strong></div><div class="archive-caption-actions"><button data-relationship-map aria-label="关系手账">${archiveToolIcon("relation")}</button><button data-manage-roles aria-label="管理联系人">${archiveToolIcon("manage")}</button><button data-import-role aria-label="导入角色">${archiveToolIcon("import")}</button><button data-create-role aria-label="新建角色">${archiveToolIcon("plus")}</button></div></div>
      <div class="contact-world-row"><label><span>世界观</span><select data-contact-world aria-label="联系人世界观"><option value="all">全部世界观</option>${(state.chatGroups||[]).map(g=>`<option value="${escapeHtml(g.id)}" ${selectedGroup===g.id?"selected":""}>${escapeHtml(g.name)}</option>`).join("")}</select></label><button type="button" data-world-summary>编辑世界观简述</button></div>
      <div class="polaroid-page" data-role-page>${visible.map((person,index)=>roleCard(person,state,index)).join("")}${emptyCards(visible.length,roleType)}</div>
      <nav class="archive-pagination"><button data-page-prev ${page===0?"disabled":""}>‹</button><div>${Array.from({length:pages},(_,i)=>`<button class="${i===page?"active":""}" data-page="${i}"></button>`).join("")}</div><button data-page-next ${page===pages-1?"disabled":""}>›</button></nav>
    </section>`;
    container.querySelector("[data-contact-world]").onchange=e=>{selectedGroup=e.target.value;page=0;render(container)};
    container.querySelector("[data-world-summary]").onclick=()=>editWorldSummary(store,selectedGroup,()=>render(container));
    container.querySelector("[data-user-profile]").onclick=()=>navigate("user-profile");
    container.querySelector("[data-role-type]").onchange=e=>{roleType=e.target.value;page=0;render(container)};
    container.querySelectorAll("[data-create-role]").forEach(x=>x.onclick=()=>navigate("character-edit",{type:roleType}));
    container.querySelectorAll("[data-role-id]").forEach(x=>x.onclick=()=>navigate("character-edit",{id:x.dataset.roleId,type:roleType}));
    container.querySelector("[data-manage-roles]").onclick=()=>navigate("contact-manage",{type:roleType});
    container.querySelector("[data-relationship-map]").onclick=()=>navigate("relationship-map");
    container.querySelector("[data-import-role]").onclick=()=>importRoleFile(store,roleType,()=>render(container));
    container.querySelector("[data-page-prev]").onclick=()=>{if(page){page--;render(container)}};
    container.querySelector("[data-page-next]").onclick=()=>{if(page<pages-1){page++;render(container)}};
    container.querySelectorAll("[data-page]").forEach(x=>x.onclick=()=>{page=Number(x.dataset.page);render(container)});
    bindSwipe(container.querySelector("[data-role-page]"),dir=>{if(dir==="left"&&page<pages-1)page++;if(dir==="right"&&page)page--;render(container)});
  };
}

export function createContactManagerRenderer({store,navigate}){
  return function render(container,params={}){const state=store.getState(),type=params.type==="npc"?"npc":"char",items=state.people.filter(x=>x.type===type).sort(roleSort);container.className="app-view contact-manager-view";container.innerHTML=`<section class="contact-manager-hero"><span>CONTACT MANAGEMENT</span><h2>管理${type==="npc"?"配角 / NPC":"CHAR"}</h2><p>这里只负责整理和删除联系人。返回档案页后，点击拍立得即可编辑资料。</p></section><label class="contact-manager-filter"><span>角色类型</span><select data-manager-type><option value="char" ${type==="char"?"selected":""}>CHAR</option><option value="npc" ${type==="npc"?"selected":""}>配角 / NPC</option></select></label><section class="contact-manager-list">${items.map(person=>managerRow(person,state)).join("")||'<div class="empty"><strong>没有可管理的联系人</strong></div>'}</section>`;container.querySelector("[data-manager-type]").onchange=e=>navigate("contact-manage",{type:e.target.value});container.querySelectorAll("[data-delete-contact]").forEach(button=>button.onclick=()=>{const person=state.people.find(x=>x.id===button.dataset.deleteContact);if(person)confirmDeleteRole(person,store,()=>render(container,params))})}
}

export function createCharacterEditorRenderer({store,navigate}){
  return function render(container,params={}){
    const state=store.getState(),existing=params.id?state.people.find(x=>x.id===params.id):null,type=existing?.type==="npc"||params.type==="npc"?"npc":"char",base={...roleDefaults(type),...(existing||{}),...(params.draft||{})};if(type==="npc"&&!base.groupId)base.groupId=state.chatGroups.find(x=>x.worldId===state.currentWorldId)?.id||"group-default";
    let avatar=base.avatarUrl||state.chatProfiles[base.id]?.avatarUrl||"";
    container.className="app-view role-file-view";
    container.innerHTML=`<form class="archive-folder ${type}" data-role-form><div class="archive-folder-tab">CONFIDENTIAL // ${type.toUpperCase()}</div><section class="archive-paper">
      <header class="archive-doc-head"><div><span>BUNNY OS</span><strong>${type==="npc"?"NPC FILE":"CHARACTER FILE"}</strong></div><small>||| | |||| | |||</small></header>
      <div class="archive-profile-grid"><button type="button" class="archive-photo" data-avatar-pick>${avatar?`<img src="${escapeHtml(avatar)}" alt="">`:'<span>＋</span><small>PHOTO</small>'}</button><div class="archive-mini-grid">${box("name","01 / NAME",base.name,true)}${box("gender","02 / GENDER",base.gender)}${box("age","03 / AGE",base.age,false,"number")}${box("height","04 / HEIGHT",base.height)}${box("birthday","05 / BIRTHDAY",base.birthday)}${box("phone","06 / CONTACT",base.phone||randomPhone())}</div></div>
      ${type==="npc"?npcFields(base,state):charFields(base,state)}
      <footer class="archive-file-actions"><button type="button" class="round-file-button cancel" data-cancel>×</button>${existing?`<button type="button" class="round-file-button export-role" data-export-role aria-label="导出角色">${archiveToolIcon("export")}</button>`:"<span>保存后将作为隐藏人设发送给 AI</span>"}<button class="round-file-button save">✓</button></footer>
    </section></form>`;
    container.querySelector("[data-cancel]").onclick=goBack;
    container.querySelector("[data-avatar-pick]").onclick=()=>{const draft=roleFormData(container.querySelector("form"));pickAvatar(value=>render(container,{...params,draft:{...base,...draft,avatarUrl:value}}))};
    container.querySelector("[data-export-role]")?.addEventListener("click",()=>exportRoleChoice(existing,state.chatProfiles[existing.id]||{}));
    if(type==="npc")container.querySelector('[name="groupId"]').onchange=event=>{const draft=roleFormData(container.querySelector("form"));draft.groupId=event.target.value;render(container,{...params,draft:{...base,...draft}})};
    let submitting=false;
    container.querySelector("form").onsubmit=e=>{
      e.preventDefault();if(submitting)return;const data=roleFormData(e.currentTarget),duplicate=!existing&&store.getState().people.some(p=>p.type===type&&normalizeName(p.name)===normalizeName(data.name));if(duplicate)return duplicateRoleNotice(data.name);
      submitting=true;e.currentTarget.querySelector(".save").disabled=true;const id=existing?.id||`${type}-${Date.now()}`,person={...base,...data,id,type,avatarUrl:avatar||base.avatarUrl||"",initials:existing?.initials||initials(data.name),online:existing?.online??true};
      person.persona=data.persona||[data.personality,data.appearance,data.familyBackground,data.hobbies].filter(Boolean).join("\n");if(type==="npc"){person.boundIdentityIds=data.boundIdentityIds||[];person.boundCharId=person.boundIdentityIds.find(identityId=>state.people.find(x=>x.id===identityId)?.type==="char")||""}
      store.update(s=>{const old=s.people.find(x=>x.id===id);if(old)Object.assign(old,person);else s.people.push(person);s.chatProfiles[id]={...profileSeed(person,person.avatarUrl),...(s.chatProfiles[id]||{}),avatarUrl:person.avatarUrl};s.stickerLibraries.characters[id]||=[];s.chatGroups.forEach(g=>g.personIds=g.personIds.filter(x=>x!==id));const group=s.chatGroups.find(g=>g.id===data.groupId);if(group&&!group.personIds.includes(id))group.personIds.push(id)});
      roleSavedNotice(type,Boolean(existing),goBack);
    };
  };
}

export function createUserProfileRenderer({store}){
  return function render(container){
    let state=store.getState(),user=state.people.find(x=>x.id===state.currentUserId);
    if(!user.phone){store.update(s=>s.people.find(x=>x.id===s.currentUserId).phone=randomPhone());state=store.getState();user=state.people.find(x=>x.id===state.currentUserId)}
    container.className="app-view user-card-view";container.innerHTML=userDisplay(user);
    container.querySelector("[data-edit-user]").onclick=()=>openUserEditor(store,user,()=>render(container));
  };
}

export function createAddFriendRenderer({store,navigate}){
  return container=>{const state=ensureAccountState(store.getState()),account=activeAccount(state),added=new Set(conversationsForAccount(state).map(x=>x.personId)),items=state.people.filter(x=>(x.type==="char"||x.type==="npc")&&!added.has(x.id)).sort(roleSort);
    container.className="app-view";container.innerHTML=`<p class="callout">正在以 ${escapeHtml(account.chatName||account.name)} 添加好友。CHAR 与已保存 NPC 都可以建立独立会话。</p><section class="contact-book">${grouped(items).map(g=>`<div class="contact-letter">${g.letter}</div>${g.items.map(p=>`<article class="contact-row card row"><div>${initialsAvatar(p,state.chatProfiles[p.id]||{})}</div><div class="meta"><strong>${escapeHtml(p.name)}</strong><span>${escapeHtml(p.note||p.personality||p.persona||"")}</span></div><span class="pill">${p.type.toUpperCase()}</span><button class="button secondary" data-add="${p.id}">添加</button></article>`).join("")}`).join("")||'<div class="empty"><strong>没有待添加的联系人</strong></div>'}</section><button class="button secondary" data-new>创建新 CHAR</button>`;
    container.querySelector("[data-new]").onclick=()=>navigate("character-edit",{type:"char"});
    container.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>addForAccount(b.dataset.add));
    function addForAccount(personId){const current=ensureAccountState(store.getState()),relation=accountRelation(current),person=current.people.find(x=>x.id===personId);if(relation.type!=="alt")return finish(false);openSheet(`<div class="account-disclosure"><div class="sheet-title"><h3>让 ${escapeHtml(person.name)} 知道这是小号吗？</h3></div><p class="callout">不知道时，对方会把当前账号当成陌生人，但底层记忆仍保持连续，不会无依据认出你。</p><div class="row"><button class="button secondary" data-disclose="no">暂不告诉</button><button class="button" data-disclose="yes">告诉对方</button></div></div>`,{onReady(sheet){sheet.querySelectorAll("[data-disclose]").forEach(button=>button.onclick=()=>{closeSheet();finish(button.dataset.disclose==="yes")})}});function finish(disclosed){const id=`conv-${person.id}-${Date.now()}`,accountId=store.getState().currentUserId;store.update(s=>{ensureAccountState(s);s.conversations.push({id,personId:person.id,userAccountId:accountId,preview:"你们已经是好友了",time:timeNow(),unread:0});s.messages[id]=[];if(!s.accountFriends[accountId].includes(person.id))s.accountFriends[accountId].push(person.id);if(s.accountRelations[accountId]?.type==="alt")s.accountRelations[accountId].disclosedTo[person.id]=disclosed});const updated=ensureAccountState(store.getState()),memoryOwnerId=accountContext(updated,person.id,accountId).memoryOwnerId,text=disclosed?`USER 告诉 ${person.name}，当前账号是其已认识账号的小号。`:`一个未公开身份的新账号添加了 ${person.name}；目前在 CHAR 视角中只是陌生联系人。`;addMemoryEntry(memoryOwnerId,{kind:"memory",category:disclosed?"user_detail":"daily_event",layer:"retrieval",text,importance:disclosed?2:1,keywords:["小号","新账号"]}).catch(()=>{});showToast(`${person.name} 已添加`);navigate("conversation",{id})}}
  };
}

function roleCard(person,state,index){const p=state.chatProfiles[person.id]||{},bounds=boundPeople(person,state),src=p.avatarUrl||person.avatarUrl,rot=[-2.2,1.5,-.7,1.9,-1.4,.8][index];return`<article class="role-card" style="--card-rotate:${rot}deg"><button class="role-card-open" data-role-id="${person.id}" aria-label="编辑 ${escapeHtml(person.name)}"><span class="role-pin"></span><span class="role-photo">${src?`<img src="${escapeHtml(src)}" alt="">`:initialsAvatar(person,p)}</span><strong>${escapeHtml(person.name||"UNNAMED")}</strong><small>${person.type==="npc"?`NPC · ${escapeHtml(bounds.map(x=>x.name).join(" / ")||"未绑定")}`:escapeHtml(person.occupation||person.signature||"CHAR")}</small></button></article>`}
function managerRow(person,state){const profile=state.chatProfiles[person.id]||{},bounds=boundPeople(person,state);return`<article class="contact-manager-row">${initialsAvatar(person,{avatarUrl:profile.avatarUrl||person.avatarUrl||""})}<div><strong>${escapeHtml(person.name)}</strong><span>${person.type==="npc"?`NPC · 关联 ${escapeHtml(bounds.map(x=>x.name).join(" / ")||"未设置")}`:escapeHtml(person.occupation||person.signature||"CHAR")}</span></div><button data-delete-contact="${person.id}" aria-label="删除 ${escapeHtml(person.name)}">−</button></article>`}
function emptyCards(count,type){return Array.from({length:PAGE_SIZE-count},()=>'<span class="role-card role-card-empty"></span>').join("")}
function charFields(p,s){return`${big("appearance","07 / APPEARANCE","外形与穿搭",p.appearance)}${big("familyBackground","08 / FAMILY","家庭与成长背景",p.familyBackground)}${big("personality","09 / PERSONALITY","性格、脾气、处事方式与聊天习惯",p.personality||p.persona)}${big("hobbies","10 / HOBBIES & TMI","爱好、口癖、关系网与其他细节",p.hobbies)}<div class="archive-field-row">${field("occupation","职业 / 身份",p.occupation)}${field("signature","个性签名",p.signature)}</div><div class="archive-field-row">${field("city","所在城市",p.city)}${field("cityPrototype","原型城市",p.cityPrototype)}</div>${field("note","当前状态",p.note)}${groupSelect(p,s)}`}
function npcFields(p,s){const group=s.chatGroups.find(x=>x.id===p.groupId),worldId=group?.worldId||s.currentWorldId,boundIds=new Set([...(p.boundIdentityIds||[]),...(p.boundCharId?[p.boundCharId]:[])]),identities=s.people.filter(x=>x.type==="user"?x.id===s.currentUserId:x.type==="char"&&s.chatGroups.some(g=>g.worldId===worldId&&(g.id===x.groupId||(g.personIds||[]).includes(x.id))));return`${groupSelect(p,s)}<fieldset class="npc-bindings"><legend>07 / BOUND IDENTITIES</legend><p>可多选这个世界观中的 USER 与 CHAR；独立 NPC 也可以不绑定。</p><div>${identities.map(identity=>`<label><input type="checkbox" name="boundIdentityIds" value="${identity.id}" ${boundIds.has(identity.id)?"checked":""}>${initialsAvatar(identity,s.chatProfiles[identity.id]||{})}<span><strong>${escapeHtml(identity.chatName||identity.name)}</strong><small>${identity.type==="user"?"USER":"CHAR"}</small></span></label>`).join("")||'<small>这个世界观还没有可绑定身份</small>'}</div></fieldset>${big("persona","08 / PERSONA","人物设定：身份、关系、外形、性格、爱好、口癖、经历与 TMI",p.persona||p.personality,8)}<div class="archive-field-row">${field("city","所在城市",p.city)}${field("cityPrototype","原型城市",p.cityPrototype)}</div>${field("note","NPC 身份简述",p.note||p.occupation||"")}`}
function userDisplay(u){const avatar=u.avatarUrl?`<img src="${escapeHtml(u.avatarUrl)}" alt="">`:`<span>${escapeHtml(u.initials||initials(u.name))}</span>`;return`<article class="user-profile-clean"><header><span>MY PROFILE</span><small>${escapeHtml(u.phone||"")}</small></header><button class="user-pass-avatar" data-edit-user aria-label="编辑 USER 资料">${avatar}<i>✎</i></button><div class="user-pass-name"><h2>${escapeHtml(u.chatName||u.name)}</h2><p>${escapeHtml(u.name||"")} · ${escapeHtml(u.location||u.city||"未设置所在地")}</p></div><div class="user-profile-line"><span>身高</span><strong>${escapeHtml(u.height||"—")}</strong></div><div class="user-profile-signature">${escapeHtml(u.signature||"还没有写个性签名")}</div>${detail("外形",u.appearance)}${detail("家庭背景",u.familyBackground)}${detail("性格",u.personality)}${detail("OTHER TMI",u.tmi||u.note)}<footer><span>点击头像创建或编辑资料</span><strong>BB / USER</strong></footer></article>`}

function openUserEditor(store,source,done){const d={...source};const show=()=>openSheet(`<form class="user-edit-card user-edit-flat" data-user-form><header><span>EDIT PROFILE</span><small>保存后直接返回个人页面</small></header><button type="button" class="user-edit-avatar" data-avatar>${d.avatarUrl?`<img src="${escapeHtml(d.avatarUrl)}" alt="">`:`<span>${escapeHtml(d.initials||initials(d.name))}</span>`}<i>＋</i></button><div class="archive-field-row">${field("name","真实名字",d.name)}${field("chatName","社交软件名称",d.chatName)}</div><div class="archive-field-row">${field("height","身高",d.height)}${field("phone","电话号码",d.phone||randomPhone())}</div>${field("location","所在地",d.location||d.city)}${big("signature","SIGNATURE","个性签名",d.signature,2)}${big("appearance","APPEARANCE","外形与穿搭",d.appearance)}${big("familyBackground","FAMILY","家庭与成长背景",d.familyBackground)}${big("personality","PERSONALITY","性格、习惯与聊天方式",d.personality)}${big("tmi","OTHER TMI","其他希望 AI 记住的信息",d.tmi||d.note)}<footer class="user-edit-actions"><button type="button" class="round-file-button cancel" data-cancel>×</button><span>PRIVATE PROFILE</span><button class="round-file-button save">✓</button></footer></form>`,{onReady(sheet){const form=sheet.querySelector("form");form.querySelectorAll("[name]").forEach(x=>x.oninput=()=>d[x.name]=x.value);sheet.querySelector("[data-cancel]").onclick=closeSheet;sheet.querySelector("[data-avatar]").onclick=()=>pickAvatar(value=>{d.avatarUrl=value;show()});let saving=false;form.onsubmit=e=>{e.preventDefault();if(saving)return;saving=true;Object.assign(d,Object.fromEntries(new FormData(form)));store.update(s=>Object.assign(s.people.find(x=>x.id===s.currentUserId),d,{initials:initials(d.name),city:d.location}));closeSheet();showToast("USER 资料已保存");done()}}});show()}
function normalizeName(value){return String(value||"").trim().replace(/\s+/g,"").toLocaleLowerCase()}
function duplicateRoleNotice(name){openSheet(`<div class="sheet-handle"></div><div class="sheet-title"><div><small>无法重复创建</small><h3>${escapeHtml(name||"这个角色")} 已存在</h3></div></div><p class="callout">请返回角色展示页编辑已有档案，或换一个角色名称。</p><button class="button primary full" data-sheet-close>知道了</button>`) }
function roleSavedNotice(type,editing,done){let finished=false,timer;const finish=()=>{if(finished)return;finished=true;clearTimeout(timer);closeSheet();done()};openSheet(`<div class="creation-success"><span>✓</span><strong>${editing?"角色资料已保存":"角色创建成功"}</strong><small>${type==="npc"?"已存入 NPC 档案":"已存入 CHAR 档案"}</small><button class="button primary" data-success-done>返回角色展示</button></div>`,{onReady(sheet){sheet.querySelector("[data-success-done]").onclick=finish}});timer=setTimeout(finish,1100)}
function confirmDeleteRole(person,store,done){openSheet(`<div class="sheet-handle"></div><div class="sheet-title"><div><small>角色管理</small><h3>删除 ${escapeHtml(person.name)}？</h3></div><button class="button ghost" data-sheet-close>取消</button></div><p class="callout danger-callout">角色档案、聊天、记忆、专属表情包和相关好友申请都会一并删除。此操作无法撤销。</p><div class="sheet-split-actions"><button class="button secondary" data-delete-cancel>保留角色</button><button class="button danger" data-delete-confirm>确认删除</button></div>`,{onReady(sheet){sheet.querySelector("[data-delete-cancel]").onclick=closeSheet;sheet.querySelector("[data-delete-confirm]").onclick=()=>{clearCharacterMemory(person.id).catch(()=>{});store.update(s=>{const conversationIds=s.conversations.filter(c=>c.personId===person.id).map(c=>c.id);s.people=s.people.filter(p=>p.id!==person.id);s.conversations=s.conversations.filter(c=>c.personId!==person.id);conversationIds.forEach(id=>delete s.messages[id]);delete s.chatProfiles[person.id];delete s.memoryProfiles?.[person.id];s.anonymousQuestions=(s.anonymousQuestions||[]).filter(x=>x.sourcePersonId!==person.id);if(s.stickerLibraries?.characters)delete s.stickerLibraries.characters[person.id];s.chatGroups.forEach(g=>g.personIds=g.personIds.filter(id=>id!==person.id));s.friendRequests=(s.friendRequests||[]).filter(r=>r.personId!==person.id);s.blockedPersonIds=(s.blockedPersonIds||[]).filter(id=>id!==person.id);s.moments=(s.moments||[]).filter(m=>m.personId!==person.id);if(person.type==="char")s.people.filter(p=>p.type==="npc").forEach(p=>{p.boundCharId=p.boundCharId===person.id?"":p.boundCharId;p.boundIdentityIds=(p.boundIdentityIds||[]).filter(id=>id!==person.id)})});closeSheet();showToast(`${person.name} 已删除`);done()}}})}
function roleDefaults(type){return{type,name:"",gender:"",age:"",height:"",birthday:"",phone:randomPhone(),occupation:"",appearance:"",familyBackground:"",personality:"",hobbies:"",persona:"",note:"",signature:"",city:"",cityPrototype:"",groupId:"",boundCharId:"",boundIdentityIds:[]}}
function roleFormData(form){const data=Object.fromEntries(new FormData(form));data.boundIdentityIds=new FormData(form).getAll("boundIdentityIds");return data}
function boundPeople(person,state){return[...new Set([...(person.boundIdentityIds||[]),...(person.boundCharId?[person.boundCharId]:[])])].map(id=>state.people.find(x=>x.id===id)).filter(Boolean)}
function box(name,label,value,full=false,type="text"){return`<label class="archive-box ${full?"full":""}"><span>${label}</span><input name="${name}" type="${type}" value="${escapeHtml(value||"")}" ${name==="name"?"required":""}></label>`}
function big(name,label,placeholder,value,rows=4){return`<label class="archive-big-field"><span><b>${label}</b><small>${placeholder}</small></span><textarea name="${name}" rows="${rows}" placeholder="${escapeHtml(placeholder)}">${escapeHtml(value||"")}</textarea></label>`}
function field(name,label,value){return`<label class="field"><span>${label}</span><input name="${name}" value="${escapeHtml(value||"")}"></label>`}
function groupSelect(p,s){return`<label class="archive-select-field"><span>WORLD GROUP</span><select name="groupId"><option value="">暂不分组</option>${s.chatGroups.map(g=>`<option value="${g.id}" ${p.groupId===g.id?"selected":""}>${escapeHtml(g.name)}</option>`).join("")}</select></label>`}
function datum(label,value){return`<div><span>${label}</span><strong>${escapeHtml(value||"—")}</strong></div>`}
function detail(label,value){return`<div><span>${label}</span><p>${escapeHtml(value||"尚未填写")}</p></div>`}
function grouped(items){const groups=[];for(const item of items){const letter=sortLetter(item),last=groups.at(-1);if(!last||last.letter!==letter)groups.push({letter,items:[item]});else last.items.push(item)}return groups}
function sortLetter(p){const x=String(p.sortKey||p.initials||p.name||"#").trim()[0]?.toUpperCase()||"#";return/[A-Z]/.test(x)?x:"#"}
function roleSort(a,b){return sortLetter(a).localeCompare(sortLetter(b),"en")||String(a.name).localeCompare(String(b.name),"zh-CN-u-co-pinyin")}
function initials(name){return String(name||"USER").replace(/\s/g,"").slice(0,2).toUpperCase()}
function randomPhone(){const tail=String(Math.floor(Math.random()*1e8)).padStart(8,"0"),prefix=["35","37","38","55","58","76","86"][Math.floor(Math.random()*7)];return`1${prefix} ${tail.slice(0,4)} ${tail.slice(4)}`}
function profileSeed(p,avatar){return{avatarUrl:avatar,remark:p.name,voiceSpeed:1,voiceId:"",autoPlayVoice:false,llmTone:true,language:"中文",emotion:"自动",translationEnabled:false,visionEnabled:true,memoryDepth:24,quietHours:"23:00—08:00",proactiveCall:false,patText:`你拍了拍${p.name}`,patUserText:`${p.name}拍了拍你`}}
function bindSwipe(el,done){let x=0,y=0;el.onpointerdown=e=>{x=e.clientX;y=e.clientY};el.onpointerup=e=>{const dx=e.clientX-x,dy=e.clientY-y;if(Math.abs(dx)>46&&Math.abs(dx)>Math.abs(dy)*1.35)done(dx<0?"left":"right")}}
function pickAvatar(done){openSheet(`<div class="sheet-handle"></div><div class="sheet-title"><h3>更换头像</h3><button class="button ghost" data-sheet-close>取消</button></div><div class="avatar-source-pair"><button class="action-card" data-source="album">▧<strong>从相册选择</strong><small>自动压缩后保存</small></button><button class="action-card" data-source="url">⌁<strong>使用图床</strong><small>粘贴图片 URL</small></button></div>`,{onReady(sheet){sheet.querySelectorAll("[data-source]").forEach(b=>b.onclick=()=>{if(b.dataset.source==="url"){const url=prompt("图片 URL","https://");if(/^https?:\/\//.test(url||"")){closeSheet();done(url)}return}const input=document.createElement("input");input.type="file";input.accept="image/*";input.onchange=()=>readImage(input.files?.[0]).then(value=>{closeSheet();done(value)}).catch(e=>showToast(e.message));input.click()})}})}
async function readImage(file){if(!file)throw Error("没有选择图片");if(!file.type.startsWith("image/"))throw Error("请选择图片文件");if(file.size>15*1024*1024)throw Error("请选择 15MB 以内图片");const source=globalThis.createImageBitmap?await createImageBitmap(file):await loadHtmlImage(file),scale=Math.min(1,960/Math.max(source.width,source.height)),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d",{alpha:false});canvas.width=Math.max(1,Math.round(source.width*scale));canvas.height=Math.max(1,Math.round(source.height*scale));ctx.fillStyle="#f7f7f4";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(source,0,0,canvas.width,canvas.height);source.close?.();if(source.dataset?.objectUrl)URL.revokeObjectURL(source.dataset.objectUrl);return canvas.toDataURL("image/jpeg",.84)}
function loadHtmlImage(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.dataset.objectUrl=url;img.onload=()=>resolve(img);img.onerror=()=>{URL.revokeObjectURL(url);reject(Error("头像读取失败"))};img.src=url})}
function importRoleFile(store,fallbackType,done){const input=document.createElement("input");input.type="file";input.accept=".json,.png,application/json,image/png";input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{let raw,avatar="";if(file.name.toLowerCase().endsWith(".png")){raw=parsePngCharacter(new Uint8Array(await file.arrayBuffer()));avatar=await fileToDataUrl(file)}else raw=JSON.parse(await file.text());const source=raw.person||raw.data||raw.character||raw,role={...roleDefaults(source.type==="npc"?"npc":fallbackType),...source};role.type=role.type==="npc"?"npc":"char";role.name=role.name||raw.name||"导入角色";role.persona=role.persona||role.description||[role.personality,role.scenario,role.first_mes].filter(Boolean).join("\n");role.avatarUrl=role.avatarUrl||avatar;role.id=`${role.type}-${Date.now()}-${Math.random().toString(16).slice(2,6)}`;role.initials=initials(role.name);const profile={...profileSeed(role,role.avatarUrl),...(raw.profile||{})};store.update(s=>{let name=role.name,n=2;while(s.people.some(x=>normalizeName(x.name)===normalizeName(name)))name=`${role.name} ${n++}`;role.name=name;s.people.push(role);s.chatProfiles[role.id]=profile;s.stickerLibraries.characters[role.id]=[];const group=s.chatGroups.find(x=>x.id===role.groupId)||s.chatGroups.find(x=>x.worldId===s.currentWorldId);if(group){role.groupId=group.id;if(!group.personIds.includes(role.id))group.personIds.push(role.id)}});showToast(`${role.name} 已导入`);done()}catch(error){showToast(`导入失败：${error.message}`)}};input.click()}
function exportRoleChoice(person,profile){openSheet(`<div class="sheet-title"><div><small>CHARACTER CARD</small><h3>导出 ${escapeHtml(person.name)}</h3></div><button class="button ghost" data-sheet-close>取消</button></div><div class="role-export-choice"><button data-role-export="json">${archiveToolIcon("json")}<strong>JSON</strong></button><button data-role-export="png">${archiveToolIcon("image")}<strong>PNG 角色卡</strong></button></div>`,{onReady(sheet){sheet.querySelectorAll("[data-role-export]").forEach(button=>button.onclick=async()=>{try{const payload={format:"bunny-character-v2",version:2,person,profile};if(button.dataset.roleExport==="json")downloadFile(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),`${safeFileName(person.name)}.character.json`);else await exportRolePng(payload);closeSheet();showToast("角色卡已导出")}catch(error){showToast(error.message)}})}})}
async function exportRolePng(payload){const canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=canvas.height=768;const grad=ctx.createLinearGradient(0,0,768,768);grad.addColorStop(0,"#faf9f5");grad.addColorStop(1,"#dadbd6");ctx.fillStyle=grad;ctx.fillRect(0,0,768,768);ctx.strokeStyle="#111";ctx.lineWidth=3;ctx.strokeRect(32,32,704,704);ctx.fillStyle="#111";ctx.font='800 24px -apple-system,"PingFang SC",sans-serif';ctx.fillText("BUNNY CHARACTER ARCHIVE",64,82);let drew=false,url=payload.person.avatarUrl||payload.profile.avatarUrl;if(url){try{const image=await loadUrlImage(url);ctx.save();ctx.beginPath();ctx.roundRect(64,120,640,450,28);ctx.clip();ctx.drawImage(image,64,120,640,450);ctx.restore();drew=true}catch{}}if(!drew){ctx.fillStyle="#111";ctx.beginPath();ctx.roundRect(64,120,640,450,28);ctx.fill();ctx.fillStyle="#fff";ctx.textAlign="center";ctx.font='800 128px -apple-system,"PingFang SC",sans-serif';ctx.fillText(initials(payload.person.name),384,390);ctx.textAlign="left"}ctx.fillStyle="#111";ctx.font='800 42px -apple-system,"PingFang SC",sans-serif';ctx.fillText(payload.person.name,64,635);ctx.fillStyle="#666";ctx.font='600 22px -apple-system,"PingFang SC",sans-serif';ctx.fillText(`${payload.person.type.toUpperCase()}  /  ${payload.person.occupation||payload.person.note||"BUNNY"}`.slice(0,44),64,678);const blob=await new Promise((resolve,reject)=>canvas.toBlob(x=>x?resolve(x):reject(Error("PNG 生成失败")),"image/png")),png=new Uint8Array(await blob.arrayBuffer()),text=bytesToBase64(new TextEncoder().encode(JSON.stringify(payload))),chunk=pngTextChunk("chara",text),out=new Uint8Array(png.length+chunk.length),iend=png.length-12;out.set(png.slice(0,iend),0);out.set(chunk,iend);out.set(png.slice(iend),iend+chunk.length);downloadFile(new Blob([out],{type:"image/png"}),`${safeFileName(payload.person.name)}.character.png`)}
function parsePngCharacter(bytes){let offset=8;while(offset+12<=bytes.length){const length=readU32(bytes,offset),type=new TextDecoder().decode(bytes.slice(offset+4,offset+8)),data=bytes.slice(offset+8,offset+8+length);if(type==="tEXt"){const zero=data.indexOf(0),key=new TextDecoder().decode(data.slice(0,zero)),value=new TextDecoder().decode(data.slice(zero+1));if(["chara","bunny_character"].includes(key)){try{return JSON.parse(new TextDecoder().decode(base64ToBytes(value)))}catch{return JSON.parse(value)}}}offset+=12+length}throw Error("PNG 中没有可识别的角色卡数据")}
function pngTextChunk(keyword,value){const data=new TextEncoder().encode(`${keyword}\0${value}`),out=new Uint8Array(12+data.length);writeU32(out,0,data.length);out.set(new TextEncoder().encode("tEXt"),4);out.set(data,8);writeU32(out,8+data.length,crc32(out.slice(4,8+data.length)));return out}
function crc32(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}return(crc^0xffffffff)>>>0}
function readU32(bytes,offset){return(bytes[offset]*0x1000000+(bytes[offset+1]<<16)+(bytes[offset+2]<<8)+bytes[offset+3])>>>0}function writeU32(bytes,offset,value){bytes[offset]=(value>>>24)&255;bytes[offset+1]=(value>>>16)&255;bytes[offset+2]=(value>>>8)&255;bytes[offset+3]=value&255}
function bytesToBase64(bytes){let value="";for(let i=0;i<bytes.length;i+=8192)value+=String.fromCharCode(...bytes.slice(i,i+8192));return btoa(value)}function base64ToBytes(value){const raw=atob(value),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes}
function loadUrlImage(url){return new Promise((resolve,reject)=>{const image=new Image();image.crossOrigin="anonymous";image.onload=()=>resolve(image);image.onerror=()=>reject(Error("头像读取失败"));image.src=url})}
function fileToDataUrl(file){return readImage(file)}
function downloadFile(blob,name){const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}function safeFileName(value){return String(value||"character").replace(/[\\/:*?"<>|]/g,"-").slice(0,60)}
function archiveToolIcon(type){const d={relation:'M5 7h4v4H5V7Zm10 0h4v4h-4V7ZM10 16h4v4h-4v-4ZM9 9h6m-3 2v5',manage:'M5 6h14M5 12h14M5 18h14M8 4v4m8 2v4m-5 2v4',import:'M12 3v12m0 0-4-4m4 4 4-4M5 17v3h14v-3',export:'M12 21V9m0 0-4 4m4-4 4 4M5 7V4h14v3',plus:'M12 5v14M5 12h14',json:'M8 5H5v14h3m8-14h3v14h-3M10 9h4m-4 3h4m-4 3h4',image:'M4 5h16v14H4V5Zm2 12 5-5 3 3 2-2 2 2'}[type]||'';return`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${d}"/></svg>`}
function timeNow(){return new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit",hour12:false})}
