// Positions are explicit grid cells. Empty cells and page boundaries survive reloads.
export function placeDesktopItem(state,{token,page,row,col,dockIndex=null,folderTarget=null}){
 state.desktopPlacements||={};state.desktopDock||=[];state.desktopFolders||=[];
 const wasDock=state.desktopDock.includes(token),origin=state.desktopPlacements[token];
 if(dockIndex!==null){if(token.includes(':'))return false;const old=state.desktopDock.indexOf(token);if(old>=0)state.desktopDock.splice(old,1);else state.desktopLayout=state.desktopLayout.filter(x=>x!==token);
  if(state.desktopDock.length>=4){const displaced=state.desktopDock.splice(Math.min(dockIndex,3),1)[0];state.desktopLayout.push(displaced);state.desktopPlacements[displaced]=origin||{page,row,col}}
  state.desktopDock.splice(Math.min(dockIndex,state.desktopDock.length),0,token);delete state.desktopPlacements[token];return true;
 }
 if(wasDock)state.desktopDock=state.desktopDock.filter(x=>x!==token);
 if(folderTarget&&!token.includes(':')){
  if(folderTarget.startsWith('folder:')){const f=state.desktopFolders.find(x=>'folder:'+x.id===folderTarget);if(f&&!f.items.includes(token)){f.items.push(token);state.desktopLayout=state.desktopLayout.filter(x=>x!==token);delete state.desktopPlacements[token];return true}}
  else if(!folderTarget.includes(':')&&folderTarget!==token){const id='folder-'+Date.now(),targetPos=state.desktopPlacements[folderTarget]||{page,row,col};state.desktopFolders.push({id,name:'新建文件夹',items:[folderTarget,token]});state.desktopLayout=state.desktopLayout.filter(x=>x!==token&&x!==folderTarget);state.desktopLayout.push('folder:'+id);state.desktopPlacements['folder:'+id]=targetPos;delete state.desktopPlacements[token];delete state.desktopPlacements[folderTarget];return true}
 }
 if(!state.desktopLayout.includes(token))state.desktopLayout.push(token);
 // Swapping cells makes occupied-cell drops predictable; other items reflow if spans differ.
 const other=Object.keys(state.desktopPlacements).find(k=>k!==token&&state.desktopPlacements[k].page===page&&state.desktopPlacements[k].row===row&&state.desktopPlacements[k].col===col);
 if(other){if(origin)state.desktopPlacements[other]=origin;else delete state.desktopPlacements[other]}
 state.desktopPlacements[token]={page,row,col};state.desktopLayout=[token,...state.desktopLayout.filter(x=>x!==token)];return true;
}

export function createHomeDrag({store,getPage,getPages,getProfile,setPage,render,getContainer}){
 let active=null,ghost=null,cue=null,raf=0,edgeTimer=0,edgeDirection=0;
 const stop=()=>{cancelAnimationFrame(raf);clearTimeout(edgeTimer);ghost?.remove();cue?.remove();ghost=cue=null;document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',end);document.removeEventListener('pointercancel',cancel);document.documentElement.classList.remove('desktop-dragging');active=null;edgeDirection=0};
 function start(node,e){if(e.button&&e.button!==0||e.target.closest('.home-remove,.home-edit'))return;stop();e.preventDefault();const token=node.dataset.token||node.dataset.dockApp,rect=node.getBoundingClientRect();active={token,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false,hover:null,hoverAt:0};ghost=node.cloneNode(true);ghost.removeAttribute('id');ghost.classList.add('home-drag-ghost');ghost.querySelectorAll('button.home-remove,button.home-edit').forEach(x=>x.remove());Object.assign(ghost.style,{position:'fixed',width:rect.width+'px',height:rect.height+'px',left:'0',top:'0',margin:'0',zIndex:99999,pointerEvents:'none',opacity:'.9',transform:`translate3d(${e.clientX-rect.width/2}px,${e.clientY-rect.height/2}px,0) scale(1.05)`});document.body.appendChild(ghost);active.width=rect.width;active.height=rect.height;cue=document.createElement('div');cue.className='home-drop-cue';document.body.appendChild(cue);document.documentElement.classList.add('desktop-dragging');document.addEventListener('pointermove',move,{passive:false});document.addEventListener('pointerup',end);document.addEventListener('pointercancel',cancel)}
 function target(e){const container=getContainer(),dock=container.querySelector('.home-dock'),d=dock.getBoundingClientRect();if(e.clientY>=d.top&&e.clientY<=d.bottom&&e.clientX>=d.left&&e.clientX<=d.right)return{dockIndex:Math.max(0,Math.min(3,Math.floor((e.clientX-d.left)/d.width*4))),page:getPage(),row:0,col:0,rect:d};const grid=container.querySelector(`[data-page="${getPage()}"] .home-grid`),r=grid.getBoundingClientRect(),p=getProfile(),row=Math.max(0,Math.min(p.rows-1,Math.floor((e.clientY-r.top)/r.height*p.rows))),col=Math.max(0,Math.min(3,Math.floor((e.clientX-r.left)/r.width*4)));return{page:getPage(),row,col,rect:{left:r.left+col*r.width/4,top:r.top+row*r.height/p.rows,width:r.width/4,height:r.height/p.rows}}}
 function move(e){if(!active)return;e.preventDefault();active.x=e.clientX;active.y=e.clientY;active.moved||=Math.hypot(e.clientX-active.startX,e.clientY-active.startY)>5;if(!raf)raf=requestAnimationFrame(()=>{raf=0;if(!active)return;ghost.style.transform=`translate3d(${active.x-active.width/2}px,${active.y-active.height/2}px,0) scale(1.05)`;const t=target({clientX:active.x,clientY:active.y}),r=t.rect;Object.assign(cue.style,{left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px'});const hit=document.elementFromPoint(active.x,active.y)?.closest('[data-token]'),token=hit?.dataset.token;if(token!==active.hover){active.hover=token;active.hoverAt=performance.now()}cue.classList.toggle('folder-ready',!!token&&token!==active.token&&performance.now()-active.hoverAt>550)});
  const r=getContainer().querySelector(`[data-page="${getPage()}"] .home-grid`).getBoundingClientRect(),dir=e.clientX<r.left+36?-1:e.clientX>r.right-36?1:0;if(dir!==edgeDirection){clearTimeout(edgeTimer);edgeDirection=dir;if(dir)edgeTimer=setTimeout(()=>{const next=getPage()+dir;if(next>=0&&next<getPages().length){setPage(next);render(getContainer())}edgeDirection=0},420)}
 }
 function end(e){if(!active)return;const a=active;if(a.moved){const t=target(e),hit=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-token]'),canFolder=!!hit&&hit.dataset.token!==a.token&&hit.dataset.token===a.hover&&performance.now()-a.hoverAt>550&&!a.token.includes(':');store.update(s=>placeDesktopItem(s,{token:a.token,...t,folderTarget:t.dockIndex===undefined&&canFolder?hit.dataset.token:null}))}stop();render(getContainer())}
 function cancel(){stop();render(getContainer())}
 return {bind(node){node.onpointerdown=e=>{store.update(s=>{s.desktopPlacements||={};getPages().forEach((page,i)=>page.forEach(entry=>s.desktopPlacements[entry.token]={page:i,row:entry.row,col:entry.col}))});start(node,e)};node.onpointermove=null;node.onpointerup=null;node.onpointercancel=null;node.oncontextmenu=e=>e.preventDefault()},cancel};
}
