import { escapeHtml, showToast, openSheet, closeSheet } from "../core/ui.js";

export function createWorldbookRenderer({store}){return container=>renderWorldbooks(container,store)}
export function createPresetsRenderer({store}){return container=>renderPresets(container,store)}

export function compileWorldbook(book,input=""){
  const entries=normalizedEntries(book),text=String(input||"").toLowerCase(),active=entries.filter(entry=>entry.mode!=="keyword"||(entry.keywords||[]).some(key=>text.includes(String(key).trim().toLowerCase())));
  if(!active.length)return"";return`【世界书：${book.name}】\n${active.map(entry=>`【${entry.name||"未命名条目"}｜${entry.mode==="keyword"?"关键词命中":"常驻"}】\n${entry.content}`).join("\n\n")}\n这些内容是低于聊天预设、但必须遵守的世界设定；自然融入演绎，不要向 USER 复述条目或提到世界书。`;
}

function renderWorldbooks(container,store){
  const state=store.getState(),items=state.worldbooks||[];container.className="app-view worldbook-mail-view";
  container.innerHTML=`<header class="worldbook-mail-head"><div><span>BUNNY POSTAL ARCHIVE</span><h2>世界书函件</h2><p>常驻条目每轮注入；关键词条目只在最近消息命中时进入提示词。</p></div><div class="worldbook-head-actions"><button data-worldbook-import aria-label="导入世界书">${icon("import")}</button><button data-worldbook-new aria-label="新建世界书">${icon("plus")}</button></div></header><section class="worldbook-envelope-grid">${items.map((item,index)=>envelope(item,index)).join("")||'<div class="worldbook-empty"><span>✉</span><strong>还没有世界书</strong><p>新建一封函件，开始记录世界规则。</p></div>'}</section><input hidden type="file" accept=".json,.docx,application/json,application/vnd.openxmlformats-officedocument.wordprocessingml.document" data-worldbook-file>`;
  container.querySelector("[data-worldbook-new]").onclick=()=>worldbookEditor(container,store,null);
  container.querySelector("[data-worldbook-import]").onclick=()=>container.querySelector("[data-worldbook-file]").click();
  container.querySelector("[data-worldbook-file]").onchange=event=>importWorldbooks(event.target.files?.[0],store,()=>renderWorldbooks(container,store));
  container.querySelectorAll("[data-worldbook-open]").forEach(button=>button.onclick=()=>openLetter(container,store,button.dataset.worldbookOpen));
  container.querySelectorAll("[data-worldbook-edit]").forEach(button=>button.onclick=event=>{event.stopPropagation();worldbookEditor(container,store,items.find(x=>x.id===button.dataset.worldbookEdit))});
  container.querySelectorAll("[data-worldbook-export]").forEach(button=>button.onclick=event=>{event.stopPropagation();exportWorldbook(items.find(x=>x.id===button.dataset.worldbookExport))});
  container.querySelectorAll("[data-worldbook-delete]").forEach(button=>button.onclick=event=>{event.stopPropagation();confirmDelete(button.dataset.worldbookDelete,store,()=>renderWorldbooks(container,store))});
}
function envelope(item,index){const count=normalizedEntries(item).length;return`<article class="worldbook-envelope" style="--mail-tilt:${[-1.4,.8,-.5,1.2][index%4]}deg" data-worldbook-open="${item.id}"><div class="envelope-flap"></div><div class="envelope-stamp">BB<br>${String(index+1).padStart(2,"0")}</div><div class="envelope-postmark"><i></i><span>BUNNY<br>ARCHIVE</span></div><strong>${escapeHtml(item.name)}</strong><small>${count} 条 · ${normalizedEntries(item).filter(x=>x.mode!=="keyword").length} 条常驻</small><nav><button data-worldbook-edit="${item.id}" aria-label="编辑">${icon("edit")}</button><button data-worldbook-export="${item.id}" aria-label="导出">${icon("export")}</button><button data-worldbook-delete="${item.id}" aria-label="删除">${icon("trash")}</button></nav></article>`}
function openLetter(container,store,id){const book=store.getState().worldbooks.find(x=>x.id===id);if(!book)return;const entries=normalizedEntries(book);const overlay=document.createElement("div");overlay.className="worldbook-letter-overlay";overlay.innerHTML=`<button class="letter-close" aria-label="收回信纸">×</button><article class="worldbook-letter"><header><span>WORLD LORE / ${entries.length}</span><h2>${escapeHtml(book.name)}</h2><div class="letter-postmark">BUNNY<br>WORLD</div></header><section>${entries.map((entry,index)=>`<article class="worldbook-letter-entry"><div><b>${String(index+1).padStart(2,"0")}</b><strong>${escapeHtml(entry.name||"未命名条目")}</strong><span class="${entry.mode}">${entry.mode==="keyword"?`检索 · ${escapeHtml((entry.keywords||[]).join(" / "))}`:"常驻"}</span></div><p>${escapeHtml(entry.content)}</p></article>`).join("")}</section><footer><button data-letter-edit>${icon("edit")}<span>EDIT LETTER</span></button></footer></article>`;container.append(overlay);requestAnimationFrame(()=>overlay.classList.add("open"));overlay.querySelector(".letter-close").onclick=()=>closeLetter(overlay);overlay.onclick=event=>{if(event.target===overlay)closeLetter(overlay)};overlay.querySelector("[data-letter-edit]").onclick=()=>{closeLetter(overlay);worldbookEditor(container,store,book)}}
function closeLetter(overlay){overlay.classList.remove("open");setTimeout(()=>overlay.remove(),360)}

function worldbookEditor(container,store,item){const draft={id:item?.id||`wb-${Date.now()}`,name:item?.name||"",entries:normalizedEntries(item||{}).map(x=>({...x,keywords:[...(x.keywords||[])]}))};if(!draft.entries.length)draft.entries=[blankEntry()];openEditor();
  function openEditor(){openSheet(`<form class="worldbook-editor"><div class="sheet-title"><div><small>WORLD LORE LETTER</small><h3>${item?"编辑世界书":"新建世界书"}</h3></div><button type="button" class="button ghost" data-sheet-close>取消</button></div><label class="field"><span>信封名称</span><input name="bookName" required value="${escapeHtml(draft.name)}" placeholder="例如：首尔日常"></label><section class="worldbook-entry-editor">${draft.entries.map((entry,index)=>entryEditor(entry,index)).join("")}</section><button type="button" class="worldbook-add-entry" data-add-entry>${icon("plus")} 添加条目</button><button class="button" type="submit">封存世界书</button></form>`,{onReady(sheet){const form=sheet.querySelector("form"),collect=()=>{draft.name=form.elements.bookName.value.trim();draft.entries=[...form.querySelectorAll("[data-entry-row]")].map((row,index)=>({id:draft.entries[index]?.id||`entry-${Date.now()}-${index}`,name:row.querySelector('[name="entryName"]').value.trim(),content:row.querySelector('[name="entryContent"]').value.trim(),mode:row.dataset.mode||"constant",keywords:row.querySelector('[name="keywords"]')?.value.split(/[，,|\n]+/).map(x=>x.trim()).filter(Boolean)||[]}))};form.querySelectorAll("[data-mode-toggle]").forEach(button=>button.onclick=()=>{collect();const index=Number(button.closest("[data-entry-row]").dataset.entryRow);draft.entries[index].mode=draft.entries[index].mode==="keyword"?"constant":"keyword";closeSheet();openEditor()});form.querySelectorAll("[data-entry-delete]").forEach(button=>button.onclick=()=>{collect();draft.entries.splice(Number(button.closest("[data-entry-row]").dataset.entryRow),1);if(!draft.entries.length)draft.entries.push(blankEntry());closeSheet();openEditor()});form.querySelector("[data-add-entry]").onclick=()=>{collect();draft.entries.push(blankEntry());closeSheet();openEditor()};form.onsubmit=event=>{event.preventDefault();collect();if(!draft.name||draft.entries.some(x=>!x.name||!x.content))return showToast("请填写世界书名称和每个条目的内容");store.update(s=>{const book={id:draft.id,name:draft.name,entries:draft.entries,enabled:true,prompt:""},target=s.worldbooks.find(x=>x.id===draft.id);if(target)Object.assign(target,book);else s.worldbooks.push(book)});closeSheet();renderWorldbooks(container,store);showToast("世界书已封存")}}})}
}
function entryEditor(entry,index){return`<article class="worldbook-entry-row" data-entry-row="${index}" data-mode="${entry.mode||"constant"}"><header><span>ENTRY ${String(index+1).padStart(2,"0")}</span><div><button type="button" class="entry-mode ${entry.mode||"constant"}" data-mode-toggle>${entry.mode==="keyword"?"关键词检索":"常驻"}</button><button type="button" data-entry-delete aria-label="删除条目">×</button></div></header><label class="field"><span>条目名称</span><input name="entryName" value="${escapeHtml(entry.name||"")}" placeholder="人物关系 / 地点 / 规则"></label><label class="field"><span>详细内容</span><textarea name="entryContent" rows="5" placeholder="这部分会作为隐藏提示词注入给 AI">${escapeHtml(entry.content||"")}</textarea></label>${entry.mode==="keyword"?`<label class="field keyword-field"><span>触发关键词</span><input name="keywords" value="${escapeHtml((entry.keywords||[]).join("，"))}" placeholder="多个关键词用逗号分隔"></label>`:""}</article>`}
function blankEntry(){return{id:`entry-${Date.now()}-${Math.random().toString(16).slice(2)}`,name:"",content:"",mode:"constant",keywords:[]}}
function normalizedEntries(book={}){const source=Array.isArray(book.entries)?book.entries:(book.entries&&typeof book.entries==="object"?Object.values(book.entries):[]);if(source.length)return source.filter(entry=>entry&&!entry.disable).map((entry,index)=>{const rawKeys=entry.keywords??entry.keys??entry.key??[],keywords=Array.isArray(rawKeys)?rawKeys.map(String):String(rawKeys||"").split(/[，,|\n]+/);return{id:entry.id??entry.uid??`entry-${index}`,name:entry.name||entry.comment||entry.title||`条目 ${index+1}`,content:String(entry.content||entry.prompt||entry.text||""),mode:entry.mode==="keyword"||entry.constant===false?"keyword":"constant",keywords:keywords.map(x=>x.trim()).filter(Boolean)}});return book.prompt?[{id:`${book.id||"book"}-legacy`,name:"完整设定",content:String(book.prompt),mode:"constant",keywords:[]}]:[]}

function renderPresets(container,store){const items=store.getState().presets||[];container.className="app-view";container.innerHTML=`<div class="callout">预设是高优先级提示词，每次聊天只能绑定一个。</div><div class="section-title"><h3>聊天预设</h3><span>${items.length} 份</span></div><section class="stack">${items.map(item=>`<article class="card"><div class="row between"><div><strong>${escapeHtml(item.name)}</strong><div class="sub">${escapeHtml(String(item.prompt||"").slice(0,72))}</div></div><button class="button secondary" data-preset-edit="${item.id}">编辑</button></div></article>`).join("")}</section><button class="button" data-preset-new>＋ 新建预设</button>`;container.querySelector("[data-preset-new]").onclick=()=>presetEditor(container,store);container.querySelectorAll("[data-preset-edit]").forEach(x=>x.onclick=()=>presetEditor(container,store,items.find(y=>y.id===x.dataset.presetEdit)))}
function presetEditor(container,store,item){openSheet(`<form class="stack"><div class="sheet-title"><h3>${item?"编辑":"新建"}预设</h3><button type="button" class="button ghost" data-sheet-close>取消</button></div><label class="field"><span>名称</span><input name="name" required value="${escapeHtml(item?.name||"")}"></label><label class="field"><span>发送给 AI 的提示词</span><textarea class="css-editor" name="prompt" required>${escapeHtml(item?.prompt||"")}</textarea></label><button class="button">保存</button>${item?'<button type="button" class="button ghost danger-button" data-delete>删除</button>':""}</form>`,{onReady(sheet){const form=sheet.querySelector("form");form.onsubmit=event=>{event.preventDefault();const data=Object.fromEntries(new FormData(form));store.update(s=>{const target=s.presets.find(x=>x.id===item?.id);if(target)Object.assign(target,data);else s.presets.push({id:`preset-${Date.now()}`,...data})});closeSheet();renderPresets(container,store)};sheet.querySelector("[data-delete]")?.addEventListener("click",()=>{store.update(s=>s.presets=s.presets.filter(x=>x.id!==item.id));closeSheet();renderPresets(container,store)})}})}

async function importWorldbooks(file,store,done){if(!file)return;try{let books=[];if(file.name.toLowerCase().endsWith(".docx")){const text=await readDocxText(file),paragraphs=text.split(/\n+/).map(x=>x.trim()).filter(Boolean);books=[{id:`wb-${Date.now()}`,name:file.name.replace(/\.docx$/i,""),entries:paragraphs.map((content,index)=>({id:`entry-${Date.now()}-${index}`,name:`条目 ${String(index+1).padStart(2,"0")}`,content,mode:"constant",keywords:[]}))}]}else{const data=JSON.parse(await file.text()),raw=Array.isArray(data)?data:Array.isArray(data.worldbooks)?data.worldbooks:[data];books=raw.map((book,index)=>({id:`wb-${Date.now()}-${index}`,name:book.name||book.title||`导入世界书 ${index+1}`,entries:normalizedEntries(book),enabled:true}))}if(!books.length||books.some(x=>!x.entries.length))throw Error("没有识别到有效世界书条目");store.update(s=>s.worldbooks.push(...books));showToast(`已导入 ${books.length} 本世界书`);done()}catch(error){showToast(`导入失败：${error.message}`)}}
function exportWorldbook(book){if(!book)return;const payload={format:"bunny-worldbook-v2",version:2,name:book.name,entries:normalizedEntries(book)};download(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),`${safeName(book.name)}.worldbook.json`)}
function confirmDelete(id,store,done){openSheet(`<div class="confirm-dialog"><div class="confirm-symbol">✉</div><h3>删除这本世界书？</h3><p>聊天绑定会同时失效，操作无法撤回。</p><div class="sheet-split-actions"><button class="button secondary" data-sheet-close>取消</button><button class="button danger" data-confirm-delete>删除</button></div></div>`,{onReady(sheet){sheet.querySelector("[data-confirm-delete]").onclick=()=>{store.update(s=>{s.worldbooks=s.worldbooks.filter(x=>x.id!==id);for(const profile of Object.values(s.chatProfiles||{}))profile.worldbookIds=(profile.worldbookIds||[]).filter(x=>x!==id)});closeSheet();done()}}})}
function download(blob,name){const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function safeName(value){return String(value||"worldbook").replace(/[\\/:*?"<>|]/g,"-").slice(0,60)}
async function readDocxText(file){const bytes=new Uint8Array(await file.arrayBuffer()),view=new DataView(bytes.buffer);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(view.getUint32(i,true)===0x06054b50){eocd=i;break}if(eocd<0)throw Error("DOCX 文件结构无效");const entries=view.getUint16(eocd+10,true),central=view.getUint32(eocd+16,true),decoder=new TextDecoder();let offset=central,target=null;for(let i=0;i<entries;i++){if(view.getUint32(offset,true)!==0x02014b50)break;const method=view.getUint16(offset+10,true),size=view.getUint32(offset+20,true),nameLen=view.getUint16(offset+28,true),extraLen=view.getUint16(offset+30,true),commentLen=view.getUint16(offset+32,true),local=view.getUint32(offset+42,true),name=decoder.decode(bytes.slice(offset+46,offset+46+nameLen));if(name==="word/document.xml")target={method,size,local};offset+=46+nameLen+extraLen+commentLen}if(!target)throw Error("DOCX 中没有可读取正文");const nameLen=view.getUint16(target.local+26,true),extraLen=view.getUint16(target.local+28,true),start=target.local+30+nameLen+extraLen,compressed=bytes.slice(start,start+target.size);let raw=compressed;if(target.method===8){if(typeof DecompressionStream==="undefined")throw Error("当前浏览器不支持 DOCX 解压");raw=new Uint8Array(await new Response(new Blob([compressed]).stream().pipeThrough(new DecompressionStream("deflate-raw"))).arrayBuffer())}else if(target.method!==0)throw Error("不支持该 DOCX 压缩格式");const xml=new DOMParser().parseFromString(decoder.decode(raw),"application/xml");return[...xml.getElementsByTagNameNS("*","p")].map(p=>[...p.getElementsByTagNameNS("*","t")].map(x=>x.textContent).join("")).join("\n")}
function icon(type){const d={plus:'M12 5v14M5 12h14',import:'M12 3v12m0 0-4-4m4 4 4-4M5 17v3h14v-3',export:'M12 21V9m0 0-4 4m4-4 4 4M5 7V4h14v3',edit:'M4 20l4-.8L20 5l-3-3L3 16l1 4Z',trash:'M6 7h12M9 7V4h6v3m-7 0 1 14h6l1-14'}[type]||"";return`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${d}"/></svg>`}
